### ISSUE TITLE
一个强大的表单设计器

### ISSUE THREAD

**Issue by longa30** [xaboy/form-create#100]
github上有个设计器。但是功能没你的强大。https://github.com/GavinZhuLei/vue-form-making。

**Comment by xaboy** [comment]
怎么了..

**Comment by longa30** [comment]
希望提供一个表单设计器。或者能告诉我个思路我将那个改成您这个的表单设计器。我目前卡那款设计器选中状态下会出现复制和删除两个按钮。这不知道该用您h这实现。

**Comment by longa30** [comment]
对您这表单还没理解。还不知道使用。目前我只用的简单的json生成表单

**Comment by xaboy** [comment]
多看看文档和 demo 吧
有开发表单设计器的计划,那个设计器我没用过,我也没什么思路

**Comment by longa30** [comment]
文档中很多都不理解。Input 输入框
$formCreate.maker.input('商品名称','goods_name').props({
        placeholder:'请输入商品名称'
    }).validate([
        { required: true, message: '请输入商品名称', trigger: 'blur' }
])
比如这段代码。$formCreate 是<form-create v-model="fApi" :rule="rule" :option="option"></form-create>他把。
我理解的意思是生成单个组件必须引用<form-create 。能否单独生成组件。

**Comment by xaboy** [comment]
必须引入 form-create 才能生成

**Comment by longa30** [comment]
那我要如何将子组件嵌入到别的组件里呢？比如input外面包裹一层div

**Comment by xaboy** [comment]
可以通过自定义组件嵌套内置组件实现

**Comment by longa30** [comment]
好的，谢谢！
