### ISSUE TITLE
Frame 组件可以定义自定义表单。最好配置是否开启Frame 模式

### ISSUE THREAD

**Issue by longa30** [xaboy/form-create#101]
希望Frame 组件可以定义自定义表单。

**Comment by xaboy** [comment]
没太明白..
frame 组件里面嵌套的是一个页面
页面里面可以写任何东西,包括表单

**Comment by longa30** [comment]
frame 直接弹出表单。对开发者会更简化。我还个问题。就是我后台请求的json。select 远程搜索没有执行那个方法。

**Comment by longa30** [comment]
![image](https://user-images.githubusercontent.com/17867961/60580872-6e34ad00-9db8-11e9-8c5a-0594c5c4abb0.png)
后台的json。然后在methods中定义一个remoteFilter_category方法。却没有执行。

**Comment by xaboy** [comment]
直接弹出表单的话,可以考虑写自定义组件,
回调不支持设置字符串

**Comment by longa30** [comment]
那在后台请求的json不能执行回调了？能否改进下。

**Comment by xaboy** [comment]
可以提前用 js 写好生成规则,然后通过$f.toJson()转换为 json,交给后台保存

**Comment by longa30** [comment]
我是用php自动生成json.让vue生成表单。是根据mysql的table表单生成json。前两天跟你提的表单生成器根据您的思路。对我有困难。所以改用这方案了。

**Comment by xaboy** [comment]
props 只能传函数,这个我也没没法

**Comment by longa30** [comment]
this.$parent。可以使用    this.$parent['addEventClick']()来执行父组件中的方法。

**Comment by longa30** [comment]
this.$parent\['addEventClick'\]()
