### ISSUE TITLE
laravel-nova后台框架使用form-create注意事项

### ISSUE THREAD

**Issue by curder** [xaboy/form-create#102]
首先，十分感谢作者提供这个脚手架工具来解决后台表单的处理。

- "@form-create/element-ui": "^0.0.4"

- "element-ui": "2.10.1"

我当前使用的是 Laravel 的后台管理面板[Nova](https://nova.laravel.com/)开发，Nova是使用Vue组件驱动的。

## 情况一

![image](https://user-images.githubusercontent.com/8327004/60854812-2092c700-a234-11e9-9475-1d37c0e9e569.png)

使用以上方式注册，控制台得到如下错误：
![image](https://user-images.githubusercontent.com/8327004/60854777-022ccb80-a234-11e9-95f7-d50f59b92c30.png)

并且从元素渲染上也没有将组件渲染成正确的dom节点：
![image](https://user-images.githubusercontent.com/8327004/60854995-ae6eb200-a234-11e9-9bae-ce8cd6951325.png)

> 从上面的情况可以看出，element-ui 组件没有挂载上，于是有了情况二的尝试。

## 情况二

![image](https://user-images.githubusercontent.com/8327004/60854900-5a63cd80-a234-11e9-8595-2f7d0037aecc.png)

使用上面的方式注册组件后，控制台得到如下错误：

![image](https://user-images.githubusercontent.com/8327004/60854979-98f98800-a234-11e9-9601-ccb44faf8b80.png)

> 此时页面元素有被正确渲染。我不清楚是不是我单独的引入一个Vue与原系统Nova的Vue冲突了导致的上面的报错。

我通过查找google等发现很多 developers 都遇到类似的报错提示：

- [[Bug Report] $attrs is readonly $listeners is readonly](https://github.com/ElemeFE/element/issues/7690)

- [[Bug Report] "$attrs is readonly" and "$listeners is readonly" console messages.](https://github.com/vuetifyjs/vuetify/issues/4068)

临时解决方案是：

修改项目`webpack.mix.js`，添加 resolve 配置，如下：

```
mix.webpackConfig({
    externals: {},
    resolve: {
        alias: {
            vue$: "vue/dist/vue.min.js"
        }
    }
});
```

这个问题折腾了我两天左右的时间，希望对遇到类似问题的developer有帮助，谢谢🙏

Happy coding!

**Comment by xaboy** [comment]
谢谢你的分享👍👍👍

**Comment by curder** [comment]
Thanks.🤓
