### ISSUE TITLE
表单对日期选择器的validate验证无法生效

### ISSUE THREAD

**Issue by Joseph244** [xaboy/form-create#103]
"dependencies": {
    "@form-create/iview": "0.0.5",

iviewUI

    "iview": "^3.2.2",

1.表单对的TimePicker   和  DatePicker  的validate验证无法生效
2.props:{
type: datetime
}也并不会出现日期时间可选，还是只有日期
3.自定义表单
`validate: [
									 {
											type: "string",
 trigger: 'change'，
											validator: (rule, value, callback) => {
												console.log(value);
												debugger
												return callback(new Error("时间不能为空"));
											}
										}
								]`
validator的时间选择器已经选择了时间，可value一直是空字符串，麻烦看下

**Comment by xaboy** [comment]
TimePicker 和 DatePicker组件验证时把type 应该是 `date`,多选的话是`array`

**Comment by xaboy** [comment]
2.我这边测试没有问题
3.第三个可能是你的自定义组件有问题,没有更新 value

**Comment by Joseph244** [comment]
我把自己的表单JSON结构复制到您的jsrun中试了就可以，但是在本地就无法验证表单，重置按钮也不生效，是什么原因呢？
我在watch中看到看到rule下面的值也已经有了我选择的值，但是就是表单验证还是提示我选择日期；
是不是我的vue版本【"vue": "^2.5.10",】和iview【  "iview": "^3.2.2",】导致的？

**Comment by xaboy** [comment]
可以发下复现的规则或者可以复现的 jsrun 地址吗
