### ISSUE TITLE
请问province_city_area在element-ui使用时报未定义

### ISSUE THREAD

**Issue by sicunzhao** [xaboy/form-create#105]
"form-create": "^1.6.6",

   element-ui

 "element-ui": "1.4.0",

 'province_city_area' is not defined，
请问在不支持 <script src=""></script>这种方式引入时，应该如何使用 

在对应的页面写对应的规则中加入如下代码
 {
          type: 'cascader',
          title: '所在区域',
          field: 'address',
          value: ['陕西省', '西安市', '新城区'],
          props: {
            // 可选项的数据源，格式参照示例说明
            data: province_city_area,
            // 选择后展示的函数，用于自定义显示格式
            renderFormat: label => label.join(' / '),
            // 是否禁用选择器
            disabled: false,
            // 是否支持清除
            clearable: true,
            // 输入框占位符
            placeholder: '请选择',
            // 次级菜单展开方式，可选值为 click 或 hover
            trigger: 'click',
            // 当此项为 true 时，点选每级菜单选项值都会发生变化，具体见上面的示例
            changeOnSelect: false,
            // 输入框大小，可选值为large和small或者不填
            size: undefined,
            // 动态获取数据，数据源需标识 loading
            loadData: () => {},
            // 是否支持搜索
            filterable: false,
            // 当搜索列表为空时显示的内容
            notFoundText: '无匹配数据',
            // 是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果
            transfer: false,
          },
          validate: [],

        },

main.js 中加入了如下代码
// ElementUI
import formCreate from 'form-create/element'
// 三级联动数据,不用可以不引入
import 'form-create/district/province_city_area.js'

**Comment by xaboy** [comment]
试试这个
```
npm i @form-create/data
import province_city_area from "@form-create/data/dist/province_city_area"
```

**Comment by sicunzhao** [comment]
> 试试这个
> 
> ```
> npm i @form-create/data
> import province_city_area from "@form-create/data/dist/province_city_area"
> ```

还是报未定义,
使用 [Element UI 中国省市区级联数据](https://github.com/Plortinus/element-china-area-data),可以，但是和当前需要的数据格式不对用不了

**Comment by xaboy** [comment]
这样没问题吧
```js
import province_city_area from "@form-create/data/dist/province_city_area"
```
```js
{
type: 'cascader',
title: '所在区域',
field: 'address',
value: ['陕西省', '西安市', '新城区'],
props: {
  // 可选项的数据源，格式参照示例说明
  data: province_city_area,
  // 选择后展示的函数，用于自定义显示格式
  renderFormat: label => label.join(' / '),
  // 是否禁用选择器
  disabled: false,
  // 是否支持清除
  clearable: true,
  // 输入框占位符
  placeholder: '请选择',
  // 次级菜单展开方式，可选值为 click 或 hover
  trigger: 'click',
  }
}
```
