### ISSUE TITLE
element-ui上传图片，不显示，控制台报错

### ISSUE THREAD

**Issue by sicunzhao** [xaboy/form-create#106]
1.6.6

element-ui

1.4.0

使用json生成的上传框，上传成功之后，不显示上传图片，控制台报，
Cannot read property 'map' of undefined
这个错误

{
          type: 'Upload',
          field: 'pic',
          title: '轮播图',
          value: [],
          // input值
          props: {
            'type': 'select',
            // 上传控件的类型，可选值为 select（点击选择），drag（支持拖拽）
            'uploadType': 'image',
            // 上传文件类型，可选值为 image（图片上传），file（文件上传）
            'action': config.uploadURL,
            // 上传的地址，必填
            'headers': {},
            // 设置上传的请求头部
            'multiple': true,
            // 是否支持多选文件
            'data': {},
            // 上传时附带的额外参数
            'name': 'upfile',
            // 上传的文件字段名
            'withCredentials': false,
            // 支持发送 cookie 凭证信息
            'accept': '',
            // 接受上传的文件类型
            'format': [],
            // 支持的文件类型，与 accept 不同的是，format 是识别文件的后缀名，accept 为 input 标签原生的 accept 属性，会在选择文件时过滤，可以两者结合使用
            'maxSize': undefined,
            // 文件大小限制，单位 kb
            'maxLength': 4,
            // 是否显示已上传文件列表
            'showUploadList': true,
            // 上传文件最大数
            'beforeUpload': () => {},
            // 上传文件之前的钩子，参数为上传的文件，若返回 false 或者 Promise 则停止上传
            'onProgress': () => {},
            // 文件上传时的钩子，返回字段为 event, file, fileList
            'onSuccess': function (event, file, fileList) {
             // event.url 为上传成功后返回的图片路径
              return event.url
            },
            // 文件上传成功时的钩子，返回字段为 response, file, fileList, 使用$f.uploadPush(field,filePath) 将上传后的路径添加到value中
            'onError': () => {},
            // 文件上传失败时的钩子，返回字段为 error, file, fileList
            'onPreview': () => {},
            // 点击已上传的文件链接时的钩子，返回字段为 file， 可以通过 file.response 拿到服务端返回数据
            'onRemove': () => {},
            // 文件列表移除文件时的钩子，返回字段为 file, fileList
            'onFormatError': () => {},
            // 文件格式验证失败时的钩子，返回字段为 file, fileList
            'onExceededSize': () => {},
            // 文件超出指定大小限制时的钩子，返回字段为 file, fileList
            // 操作按钮的图标 ,设置为false将不显示
            handleIcon: 'ios-eye-outline',
            // 点击操作按钮事件
            //  onHandle:(src)=>{},
            // 是否可删除,设置为false是不显示删除按钮
            allowRemove: true
          },
          validate: [{
            required: true,
            type: 'array',
            min: 3,
            message: '请上传3张图片',
            trigger: 'change'
          }]
        },

**Comment by sicunzhao** [comment]
具体的报错信息如下
vue.runtime.esm.js?59ee:587 [Vue warn]: Error in render: "TypeError: Cannot read property 'map' of undefined"

found in

---> <FormCreate>
       <Index> at D:\project\src\containers\activityForm\index.vue
         <App> at D:\project\src\App.vue
           <Root>
warn @ vue.runtime.esm.js?59ee:587
logError @ vue.runtime.esm.js?59ee:1733
globalHandleError @ vue.runtime.esm.js?59ee:1728
handleError @ vue.runtime.esm.js?59ee:1717
Vue._render @ vue.runtime.esm.js?59ee:4542
updateComponent @ vue.runtime.esm.js?59ee:2784
get @ vue.runtime.esm.js?59ee:3138
run @ vue.runtime.esm.js?59ee:3215
flushSchedulerQueue @ vue.runtime.esm.js?59ee:2977
(anonymous) @ vue.runtime.esm.js?59ee:1833
flushCallbacks @ vue.runtime.esm.js?59ee:1754
Promise.then (async)
microTimerFunc @ vue.runtime.esm.js?59ee:1802
nextTick @ vue.runtime.esm.js?59ee:1846
queueWatcher @ vue.runtime.esm.js?59ee:3064
update @ vue.runtime.esm.js?59ee:3205
notify @ vue.runtime.esm.js?59ee:693
reactiveSetter @ vue.runtime.esm.js?59ee:1010
set @ vue.runtime.esm.js?59ee:1032
_changeFormData @ form-create.elm.min.js?7c7c:7
value @ form-create.elm.min.js?7c7c:7
value @ form-create.elm.min.js?7c7c:7
(anonymous) @ form-create.elm.min.js?7c7c:7
handleSuccess @ element-ui.common.js?3578:21557
onSuccess @ element-ui.common.js?3578:22068
onload @ element-ui.common.js?3578:22209
load (async)
upload @ element-ui.common.js?3578:22204
post @ element-ui.common.js?3578:22076
upload @ element-ui.common.js?3578:22031
(anonymous) @ element-ui.common.js?3578:22007
uploadFiles @ element-ui.common.js?3578:22005
handleChange @ element-ui.common.js?3578:21991
invoker @ vue.runtime.esm.js?59ee:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js?59ee:1822
vue.runtime.esm.js?59ee:1737 TypeError: Cannot read property 'map' of undefined
    at t.value (form-create.elm.min.js?7c7c:7)
    at t.value (form-create.elm.min.js?7c7c:7)
    at t.value (form-create.elm.min.js?7c7c:7)
    at e.value (form-create.elm.min.js?7c7c:7)
    at eval (form-create.elm.min.js?7c7c:7)
    at Array.map (<anonymous>)
    at e.value (form-create.elm.min.js?7c7c:7)
    at e.value (form-create.elm.min.js?7c7c:7)
    at Proxy.render (form-create.elm.min.js?7c7c:7)
    at VueComponent.Vue._render (vue.runtime.esm.js?59ee:4540)

**Comment by xaboy** [comment]
更新一下 elementUI 版本试试

**Comment by sicunzhao** [comment]
可能是其他的组件配置影响了，把其他的注释掉就好了，解决了，谢谢

**Comment by lxdora** [comment]
'onSuccess': function (event, file, fileList) {
// event.url 为上传成功后返回的图片路径
return event.url
},
成功后直接返回地址页面上能显示图片吗？
