### ISSUE TITLE
Iview 最新版本下面事件绑定无效

### ISSUE THREAD

**Issue by Andyczc** [xaboy/form-create#107]
@form-create/iview 0.0.5

iview 

最新

`rule:[

            formCreate.maker.rate('推荐级别1', 'rate1', 2)
              .props({
              "count": 10,
              "allowHalf": false
            })
              .validate([{
              required: true,
              type: 'number',
              min: 3,
              message: '请大于3颗星',
              trigger: 'change'
            }]).event({
                  change:function(){
                    console.log(111)
                  }
              }),

            {
              type:"input",
              field:'asd',
              title:"评分 (参数方式)",
              on:{
                change(e){
                  console.log(e)
                }
              }
            },
              maker.create('input','test','textTitle').props({
                  disable:true
                }).event({
                  change:function(){
                    console.log(111)
                  }
              }),
              maker.radio('是否包邮', 'is_postage', 0).options([
                  {value: 0, label: "不包邮", disabled: false},
                  {value: 1, label: "包邮", disabled: false},
                  {value: 2, label: "未知", disabled: true},
              ]).col({span: 8}).emit(['change']).emitPrefix('is-postage'),
              {
                type:"slider",
                field:"slider",
                title:"滑块 (emit 方式)",
                value:1,
                emit:['change'],
                on: {
                    change:function(){
                      console.log(111)
                    }
                }
              }
          ]`

formCreate.maker创建的控件能正常触发change事件
使用on或者event对象形式则不能绑定事件

正常触发绑定事件

**Comment by xaboy** [comment]
事件名称不再自动添加`on-`前缀,改为`on-click`就好了

**Comment by Andyczc** [comment]
@xaboy 有具体代码吗

**Comment by Andyczc** [comment]
`{
                type:"slider",
                field:"slider",
                title:"滑块 (emit 方式)",
                value:1,
                emit:['change'],
                on: {
                    'on-change':function(){
                      console.log(111)
                    }
                }
              },`

好了  试出来了
