### ISSUE TITLE
如何在组件中获取 $f ？ 如何使用 model 填充表单实现更新功能？

### ISSUE THREAD

**Issue by frinder6** [xaboy/form-create#108]
"element-ui": "2.10.0",
    "form-create": "^1.6.6",
    "vue": "^2.6.10",

 "element-ui": "2.10.0",

 "element-ui": "2.10.0",

看文档可通过 $f = vm.fApi获取，但我在子组件中获取不到 vm 的（前端菜鸟或是不知道怎么获取），可能通过什么方式获取呢？代码如下：

<template>
  <el-dialog class="supdate-from" :title="title" :visible.sync="show">
    <form-create
      :option="option"
      v-model="fApi"
      :rule="formItems"
    ></form-create>
  </el-dialog>
</template>

<script>
export default {
  props: [
    "title", // 标题
    "formItems", // 表单项
    "formModel" // 填充实体
  ],
  data() {
    return {
      fApi: {},
      show: false
    };
  },
  computed: {
    option() {
      const $this = this;
      return {
        resetBtn: true,
        onSubmit: function(formData) {
          console.log(formData);
        },
        onReload($f) {
          $f.setValue($this.formModel);
        }
      };
    }
  },
  watch: {
    formModel(v) {
      // 如何在此处获取 $f ???
      // $f.setValue(v);
      console.log(1, v);
    }
  }
};

是否可以支持父组件传入 model 直接渲染 form 表单呢？这样对于更新来说就会很方便！！！

**Comment by xaboy** [comment]
```html
<div id="app1">
    //通过 v-model 获取$f
    <form-create v-model="fApi" :rule="rule" :option="option"></form-create>
</div>
```
```js
export default {
  data () {
    return {
     //实例对象
     fApi:{},
     //表单生成规则
     rule:[
       {
          type:'input',
          field:'goods_name',
          title:'商品名称'
        },
        {
          type:'datePicker',
          field:'created_at',
          title:'创建时间'
        }
     ],
     //组件参数配置
     option:{
       //表单提交事件
       onSubmit:function (formData) {
         alert(JSON.stringify(formData));
       }
     }
    };
  }
};
```
可以参考文档:[http://form-create.com/v2/guide/start.html](http://form-create.com/v2/guide/start.html)

**Comment by frinder6** [comment]
试过了，之前用的方式不对，感谢~~~
