### ISSUE TITLE
Vue 版本不支持 compile

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#109]
1.6.6

2.8.2

在项目中应用rule type="template"生成动态表单总是提示使用的 Vue 版本不支持 compile，VUE是最新版本

**Comment by xaboy** [comment]
![image](https://user-images.githubusercontent.com/21242408/61340083-60306300-a873-11e9-97d1-fc574ef2f192.png)
选中的两个 vue 版本支持`template`

**Comment by Lysom** [comment]
多谢了啊，抱歉, vue.config.js中webpack没有配置好，十分感谢你的解答

**Comment by junjiem** [comment]
@xaboy 请问vue3-cli中没有vue.config.js如何修改呢？
