### ISSUE TITLE
这个是假issues

### ISSUE THREAD

**Issue by fooller** [xaboy/form-create#11]

**Comment by fooller** [comment]
还有就是 教程中 引入的那些东西，我应该都不用引入吧，因为我是vue项目npm了你的form-create

**Comment by fooller** [comment]
我打印了this对象 并没有$formCreate 
怎么注册formCreate呢😂

**Comment by fooller** [comment]
请问：
$r和$f都是什么啊 在哪里定义的呢

**Comment by fooller** [comment]
我不定义会报错

**Comment by xaboy** [comment]
使用前要`Vue.use(formCreate)`;

**Comment by xaboy** [comment]
然后在vue内部,比如
```
mounted:function(){
   //rule 是表单规则
   //options是全局配置
   //$r是api方法的对象
    $r = this.$formCreate(rule,options);
}

```

**Comment by xaboy** [comment]
`$formCreate.make`指的是 vue内部的`this.$formCreate.make` 或者 `window.formCreate.make`
文档中没有说清楚不好意思

**Comment by fooller** [comment]
你说的这些刚才我依然解决了
import formCreat from 'form-create'
import iView from 'iview';
import 'iview/dist/styles/iview.css';
Vue.use(iView);
Vue.use(formCreat)
我是这么搞的

现在有些问题还需要请教一下
$f和$r我现在理解为实例
 this.$formCreate(this.$formCreate.maker,this.options);
我只需要写入这一句话，按理说所以的标签都会显示在我的页面上，对吧？
但是目前只显示一个button提交，其他均不显示，
难倒我挂载错了？
还有个奇怪的现象就是，不管我挂在到哪个id上，甚至不挂载为null都只显示一个button，
求，答疑解惑

**Comment by fooller** [comment]
我的代码如下
`let root = document.getElementById('demo'),that = this;
    this.options.el = root
    let $f = this.$formCreate(this.$formCreate.maker,this.options);`

**Comment by fooller** [comment]
options是复制你的一点没变，然后放进了data里 只是通过this.options.el来改变需要挂载的id

**Comment by fooller** [comment]
我打印了this.$formCreate.maker
说明这个是所有页面元素的规则，按理说会显示所有的
还有就是 $f 和 $r我这边this里边获取不到 你说的api方法，难倒我们不需要定义吗？
这样    $r = this.$formCreate(rule,options);
还是这样$r = this.$formCreate(rule,options);
虽然我在main.js里使用了Vue.use

**Comment by xaboy** [comment]
`this.$formCreate.maker`是表单生成器,你需要用他生成你的表单,你看下README后面有介绍

**Comment by xaboy** [comment]
表单成功生成出来了吗?

**Comment by fooller** [comment]
我的写法如下
`
let root = document.getElementById('demo'),that = this;
    this.options.el = root
    let rule = this.$formCreate.maker.input("商品名称","goods_name","iphone 7").props({
        clearable:true,
        placeholder: "请输入商品名称"
    }).validate([
        { required: true, message: '请输入goods_name', trigger: 'blur' },
    ])
    let $f = this.$formCreate(rule,this.options);
`

**Comment by fooller** [comment]
显示不出来

**Comment by xaboy** [comment]
正确写法
```
this.$formCreate([
this.$formCreate.maker.input("商品名称","goods_name","iphone 7").props({
clearable:true,
placeholder: "请输入商品名称"
}).validate([
{ required: true, message: '请输入goods_name', trigger: 'blur' },
])
],{
el:document.getElementById('demo')
})
```
[可以参考一下这里](https://github.com/xaboy/form-create/blob/master/mock.js)

**Comment by fooller** [comment]
hi, bro i need you, i will study your product deeply

**Comment by fooller** [comment]
ok,  it has worked

**Comment by fooller** [comment]
如果想展示全部
需要单独引入一下
import 'form-create/mock.js'
然后在mounted里写入
this.$formCreate(window.mock,{
    el:document.getElementById('demo')
    })
就ok了 当然了有个地方报错，估计还需要引入三级联动的什么东西，我再看看，这个主要是写个后来者看的

**Comment by xaboy** [comment]
mock只是个示例,你可以根据自己的需求生成表单
```
<!-- 省市区三级联动json数据 -->
<script src="/district/province_city_area.js"></script>
```

**Comment by xaboy** [comment]
ok
