### ISSUE TITLE
使用rules生成动态表单时， 给input添加children，type为template为何会引发栈溢出的问题

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#110]

**Comment by xaboy** [comment]
可以发一下复现的规则吗

**Comment by Lysom** [comment]
![image](https://user-images.githubusercontent.com/37890043/61358745-94287a00-a8ad-11e9-9cdc-5e04cabe7e6d.png)
![image](https://user-images.githubusercontent.com/37890043/61358766-a60a1d00-a8ad-11e9-8c4d-ac10cd9cb526.png)

**Comment by Lysom** [comment]
抱歉 children打错了，但是问题依然存在

**Comment by xaboy** [comment]
这个可能是 bug

**Comment by Lysom** [comment]
好的

**Comment by xaboy** [comment]
应该是 children 中有 template 组件造成的
我再检查一下,下个版本修复

**Comment by Lysom** [comment]
那太好了，感谢
