### ISSUE TITLE
单独引入form-create无法识别，不是在mian引入

### ISSUE THREAD

**Issue by baozai6795** [xaboy/form-create#111]
### 用了vue 和elementui

代码import这里是个有没有错

![image](https://user-images.githubusercontent.com/53046357/61457832-bf899280-a99b-11e9-8a6e-21900eeff91a.png)

### 路径
![image](https://user-images.githubusercontent.com/53046357/61458025-450d4280-a99c-11e9-8c18-c1e4b015df78.png)

### 报错
![image](https://user-images.githubusercontent.com/53046357/61516988-bf8ba000-aa38-11e9-8fc9-54a7c2d525bf.png)

### 代码：

	        <template>
		         <div id="app1">
				<formCreate ref="fc" v-model="fApi" :rule="rule" :option="option"></formCreate>
		       </div>
		</template>
		<script>
		   import ElementUI from '../../../node_modules/element-ui'
		   import '../../../node_modules/element-ui/lib/theme-chalk/index.css'
			//import ElementUI from 'element-ui'
		   import formCreate from "form-create/element"
		  // import formCreate from '../../../node_modules/form-create/element'
		  // import { maker } from '../../../node_modules/form-create/element'
		  // import formCreate from 'form-create'
		  import { maker } from 'form-create'
		 export default {
			data () {
			  return {
			   //表单实例对象 $f
			   fApi:{},
			   //表单生成规则
			   rule:[
				 {
					type:'input',
					field:'goods_name',
					title:'商品名称'
				  },
				  {
					type:'datePicker',
					field:'created_at',
					title:'创建时间'
				  }
			   ]
			  };
			},
			methods:{
				onSubmit(formData){
					//TODO 提交表单
				}
			}
		  };
		</script>

**Comment by xaboy** [comment]
导入的路径不对吧

```js
import formCreate from "form-create/element"
```

**Comment by baozai6795** [comment]
> 导入的路径不对吧
> 
> ```js
>  从“ form-create / element ”导入formCreate  
> ```
![image](https://user-images.githubusercontent.com/53046357/61514402-9c5df200-aa32-11e9-8a31-430eb2f7dea1.png)
跑去 iview了

**Comment by baozai6795** [comment]
<template>
  <div id="app1">
     <formCreate ref="fc" v-model="fApi" :rule="rule" :option="option"></formCreate>
    
  
</div>
</template>
<script>

import ElementUI from '../../../node_modules/element-ui'
import '../../../node_modules/element-ui/lib/theme-chalk/index.css'


//import ElementUI from 'element-ui'
import formCreate from "form-create/element"
// import formCreate from '../../../node_modules/form-create/element'
// import { maker } from '../../../node_modules/form-create/element'
// import formCreate from 'form-create'
import { maker } from 'form-create'



export default {
  data () {
    return {
     //表单实例对象 $f
     fApi:{},
     //表单生成规则
     rule:[
       {
          type:'input',
          field:'goods_name',
          title:'商品名称'
        },
        {
          type:'datePicker',
          field:'created_at',
          title:'创建时间'
        }
     ]
    };
  },
  methods:{
      onSubmit(formData){
          //TODO 提交表单
      }
  }
};


</script>
