### ISSUE TITLE
formCreate无法调用

### ISSUE THREAD

**Issue by baozai6795** [xaboy/form-create#113]
### vue +  element-ui 

**formCreate无法调用**
![image](https://user-images.githubusercontent.com/53046357/61519482-9a019500-aa3e-11e9-9ebe-3c9532121a7f.png)

![image](https://user-images.githubusercontent.com/53046357/61519559-c4535280-aa3e-11e9-8a84-36098044b81e.png)

 **  代码：**

            <template>
		  <div id="app1">
		   <formCreate ref="fc" v-model="fApi" :rule="rule" :option="option"> 
                  </formCreate>
		  </div>
           </template>
		<script>
		import 'element-ui/lib/theme-chalk/index.css';
		import formCreate from 'form-create/element';
		export default {
		   name:'Form',
		  data () {
			return {
			 //表单实例对象 $f
			 fApi:{},
			 //表单生成规则
			 rule:[
			   {
				  type:'input',
				  field:'goods_name',
				  title:'商品名称'
				},
				{
				  type:'datePicker',
				  field:'created_at',
				  title:'创建时间'
				}
			 ],
			 option:{}
			};
		  },
		  methods:{
			  onSubmit(formData){
				  //TODO 提交表单
			  }
		  },
		  components:{formCreate}
		};
		</script>

**Comment by xaboy** [comment]
1.x
```js
components:{
    formCreate:formCreate.component('form-create')
}
```
v2 
```js
components:{
    formCreate:formCreate.$form()
}
```

**Comment by baozai6795** [comment]
> 1.x中
> 
> ```js
> 组件： {
>     formCreate ：formCreate。组件（' form-create '）
> }
> ```
> 
> V2
> 
> ```js
> 组件： {
>     formCreate ：formCreate。$ form（）
> }
> ```

可以了，用第一种方法，谢谢
