### ISSUE TITLE
是否能够针对表单生成功能新增一个可视化的表单设计功能？

### ISSUE THREAD

**Issue by ww33331000** [xaboy/form-create#114]
现在整个组件看下来的功能大体上就是根据一段规则json来生成组件，是否可以添加一个自定义规划组件排版、添加组件、设置对应组件属性参数以及可以删除组件的功能？毕竟可以将这种操作结果的组件保存到数据库中，然后在指定的页面进行渲染。达到由用户进行编辑表单并发布的功能

**Comment by xaboy** [comment]
目前没有计划

**Comment by xaboy** [comment]
@ww33331000 
form-create 可视化表单设计器已发布 https://github.com/xaboy/form-create-designer
