### ISSUE TITLE
用updateRule更新 validate为[] 时不生效

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#116]
最新

element-ui

2.8.2

更新验证规则时 用updateRule 去掉验证规则 设置validate: [] 时 不生效

在deepExtend方法内 validate为[]并没有处理

**Comment by xaboy** [comment]
下个版本可以给 updateRule 方法增加第三个参数,控制是深拷贝还是直接覆盖

**Comment by xaboy** [comment]
8e334ed

**Comment by xaboy** [comment]
1.0.1版本已优化
