### ISSUE TITLE
用json生成的DatePicker的validate验证问题

### ISSUE THREAD

**Issue by oniongreen** [xaboy/form-create#118]
"@form-create/iview": "1.0.0"

用以下json生成的日期选择框，但是选择日期后也会一直报没有输入值
{
            'type': 'DatePicker',
            'field': 'ETA',
            'title': 'ETA',
            'name': 'ETA',
            'value': null,
            'className': null,
            'validate': [
              {
                'required': true,
                'type': 'date',
                'message': '请输入ETA',
                'trigger': 'change'
              }
            ],
            'props': {},

**Comment by xaboy** [comment]
感谢你的反馈.这个是 bug,下个版本会修复

**Comment by xaboy** [comment]
1.0.2已修复

**Comment by oniongreen** [comment]
谢谢！------------------ 原始邮件 ------------------
发件人: "xaboy"<notifications@github.com>
发送时间: 2019年8月11日(星期天) 晚上6:08
收件人: "xaboy/form-create"<form-create@noreply.github.com>;
抄送: "oniongreen"<308837835@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xaboy/form-create] 用json生成的DatePicker的validate验证问题 (#118)



1.0.2已修复
 
&mdash;
