### ISSUE TITLE
如何用v-if根据条件显示控件？是否可以用模板定位控件的位置？如何让控件的标题支持多语言？

### ISSUE THREAD

**Issue by jacdy** [xaboy/form-create#120]
一、如何用v-if根据条件显示控件？
二、是否可以用模板定位控件的位置？
比如我一行显示了四个控件，如果只是隐藏了这一行的某个控件后，下一行的控件会跑到上行中，这样界面全乱了。

三、如何让控件的标题支持多语言？

四、如何不用formData ，而让控件绑定其它对象的值？

**Comment by xaboy** [comment]
1. 可以用$f.hidden() 方法隐藏指定组件
2. 这个可以通过自定义布局实现 [自定义布局示例2](http://form-create.com/v2/guide/layout.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80)
3. form-create 内置的文字都可以通过配置修改,生成组件内置的文字需要组件支持多语言
4. 不支持绑定其他对象(可以通过$f.bind()获取绑定的对象),只能绑定 `rule.value`. 可以直接修改 rule.value 或者 `$f.setValue` 等方法修改

**Comment by jacdy** [comment]
@xaboy 谢谢！我看了自定义布局的说明，是通过 col.span来指定的，这样就会有我说的问题：一行显示了四个控件，如果只是隐藏了这一行的某个控件后，下一行的控件会跑到上行中，这样界面全乱了呢。如果能支持模板定位就好了,这样：
```html
<form-create><el-row><el-col :span="8" id="comp1">comp1 组件生成在这里</el-col></el-row></form-create>
```
方便告诉我改源码哪个文件可以把生成的控件最终 mount(‘#comp1’)  这样吗？ 万分感谢！

**Comment by xaboy** [comment]
你可以参考一下自定义布局示例二,隐藏某一个组件后,下一行不会上了的.
修改不了源码,源码是通过生成规则来渲染的 不支持这样
