### ISSUE TITLE
hidden方法无法隐藏

### ISSUE THREAD

**Issue by hkaikai** [xaboy/form-create#121]
@form-create 1.0.1

iview

3.4.2

afApi.hidden(true, field) 无法隐藏对应field

**Comment by xaboy** [comment]
发一下生成规则我看看,有没有报错?

**Comment by hkaikai** [comment]
http://jsrun.pro/SVbKp/edit

根据官方实例改地：http://jsrun.pro/NQhKp/edit

**Comment by xaboy** [comment]
示例里面用的版本是 `1.x`,`hidden`的用法是v2的

1.x hidden方法的用法是 hidden(field, true);

**Comment by hkaikai** [comment]
可以了，谢谢
但是vm.fApi.setValue("goods_name","fdsfdsfd");没起作用，能帮我看看嘛

**Comment by xaboy** [comment]
浏览器报错了 提示 `vm is not defined`
改成这样就好了
```js
mounted: function(fApi){  	
    fApi.setValue("goods_name","fdsfdsfd");
}
```

**Comment by hkaikai** [comment]
![微信截图_20190808112637](https://user-images.githubusercontent.com/19343340/62673085-9cb53180-b9cf-11e9-9e85-596c5a13c9be.png)
我iview样式是按需加载的，在form create后面加载的，hidden样式被覆盖了应该是

**Comment by xaboy** [comment]
好的 我下个版本优化一下

**Comment by xaboy** [comment]
1.0.2已修复
