### ISSUE TITLE
validate方法可否把错误参数也带上

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#122]

**Comment by xaboy** [comment]
这个控制不了,验证直接调的是 ui 框架的方法

**Comment by Lysom** [comment]
element ui 框架 是带有未通过校验字段的参数的  （ 是否校验成功和未通过校验的字段）

**Comment by xaboy** [comment]
`validateFields` 只返回了个`bool`
`valiadteField` 返回了错误信息

**Comment by Lysom** [comment]
好的
