### ISSUE TITLE
json生成select组件开启多选（multiple: true）则表单验证会一直不通过

### ISSUE THREAD

**Issue by jianjunx** [xaboy/form-create#123]
"@form-create/iview": "0.0.5"

iview

3.x

json生成select组件如果开启多选（multiple: true）则表单验证会一直不通过，去掉多选正常

```json
{
      type: "select",
      field: "cate_id2",
      title: "产品分类2",
      value: ['104'],
      options: [{
        "value": "104",
        "label": "生态蔬菜",
        "disabled": false
      },
      {
        "value": "105",
        "label": "新鲜水果",
        "disabled": false
      },
      ],
      props: {
        "placement": "bottom",
        "multiple": true
      },
    validate:[
        { required: true, message: '请输入goods_name', trigger: 'change' },
    ]
    }
```

复现： 在 https://jsrun.pro/FehKp/edit 使用如下json
```json
new Vue({
  el: "#app",
  data: {
    rule: [formCreate.maker.select("产品分类1", "cate_id1", ["104", "105"]).options([{
      "value": "104",
      "label": "生态蔬菜",
      "disabled": false
    },
    {
      "value": "105",
      "label": "新鲜水果",
      "disabled": false
    },
    ]).props({
      multiple: true
    }), {
      type: "select",
      field: "cate_id2",
      title: "产品分类2",
      value: ['104'],
      options: [{
        "value": "104",
        "label": "生态蔬菜",
        "disabled": false
      },
      {
        "value": "105",
        "label": "新鲜水果",
        "disabled": false
      },
      ],
      props: {
        "placement": "bottom",
        "multiple": true
      },
    validate:[
        { required: true, message: '请输入goods_name', trigger: 'change' },
    ]
    }]
  }
})
```

**Comment by xaboy** [comment]
当`multiple`为`true`时,`value`的类型为`Array`.所以要在验证规则中定义`type:'array'`

[验证规则](http://www.form-create.com/v2/guide/other/validation-rules.html)

**Comment by 804434940** [comment]
`[
                {
                    type: "select",
                    field: "cate_id",
                    title: "产品分类",
                    value: ["103","104"],
                    options: [
                        {"value": "103", "label": "生态蔬菜", "disabled": false},
                        {"value": "104", "label": "新鲜水果", "disabled": false},
                    ],
                    props: {
                        "placement": "bottom",

                        multiple: true
                    },
                    validate: [{ required: true, message: 'please input!', type: 'array' }]
                }
                ]`
这样添加了type:'array' 但是多选效果没有
![image](https://user-images.githubusercontent.com/51938617/102864963-0375a680-4470-11eb-9de2-930d2fa5a924.png)
