### ISSUE TITLE
自定义表单组件 /  Custom form component

### ISSUE THREAD

**Issue by xaboy** [xaboy/form-create#124]
如果您有适合 form-create 的表单组件，非常感谢您的支持，希望可以在这里留下您的组件信息。您的回复将成为作者的信心来源。
回复格式示例如下：

组件：vue2-editor
链接：https://github.com/davidroyer/vue2-editor

---------

If you have a form component for form-create, thank you very much for your support and hope to leave your component information here. Your response will be the source of confidence for the author.
An example of a reply format is as follows:

Component: vue2-editor
Link: https://github.com/davidroyer/vue2-editor

**Comment by AllenLing121** [comment]
你好，我用form-create和element-ui的json方式来渲染表单，为什么我的组件没办吧绑定事件呢，代码如下：
<template>
    <div>
        <div id="form-create"></div>
    </div>
</template>

<script>
    export default {
        name: "NewOrderList",
        data() {
            return {
                aa:"",
                orderForm: {},
                fApi:{},
                options: [
                    {"value":1,label:1},
                    {"value":2,label:2}
                ],
                rule: [
                    {
                        type: "select",
                        field: "test",
                        title: "产品分类",
                        value: '',
                        props: {
                            "multiple": false,
                            //是否支持多选
                            "clearable": false,
                            //是否可以清空选项，只在单选时有效
                            "filterable": true,
                            //	是否支持搜索
                            "size": "default",
                            //选择框大小，可选值为large、small、default或者不填
                            "placeholder": "请选择",
                            //选择框默认文字
                            "not-found-text": "无匹配数据",
                            //当下拉列表为空时显示的内容
                            "placement": "bottom",
                            //弹窗的展开方向，可选值为 bottom 和 top
                            "disabled": false,
                            //是否禁用
                        },
                        options: [
                            {
                            "value": "104",
                            "label": "生态蔬菜",
                            "disabled": false
                            },
                            {
                                "value": "105",
                                "label": "新鲜水果",
                                "disabled": false
                            },
                        ],
                        event:{
                            change:function(){
                                alert(212)
                            }
                        },

                    },
                ]
            };
        },
        methods:{
            change: function(...arg) {
                console.log(arg);
            },
            changeTest: function(...arg) {
                //console.log(arg);
            }
        },
        mounted: function () {
            //表单插入的节点
            const root = document.getElementById('form-create');

            //$f为表单api
            const $f = this.$formCreate.create(
                //表单生成规则
                this.rule,
                //组件参数配置
                {
                    el: root,
                    //显示表单重置按钮
                    resetBtn: false,
                    //表单提交事件
                    onSubmit: function (formData) {
                        //按钮进入提交状态
                        //console.log(formData)
                    }
                });
            console.log($f.el('test'));
            console.log(this.$refs.abc);
        }
    }
</script>
上面下拉的change事件一直棒定不上。能麻烦您为我解答下吗，非常感谢！！

**Comment by xaboy** [comment]
event 改成 on 就可以 @AllenLing121

**Comment by AllenLing121** [comment]
@xaboy 非常感谢，可以了，这个问题我搞了一天。

**Comment by a2748284941** [comment]
能加一個 mint-ui 移動端框架嗎

**Comment by a2748284941** [comment]
组件：mint-ui
链接：http://mint-ui.github.io/#!/zh-cn

**Comment by artskin** [comment]
组件：vue-treeselect
https://github.com/riophae/vue-treeselect

**Comment by chenshuichao** [comment]
组件：table
链接：https://element-plus.org
表单，提交的时候，有时候，有一个子表格，子表格，是可编辑的grid。
像订单就是这个样子，订单明细就是一个table，而订单头，就是普通的input组件。

**Comment by chenshuichao** [comment]
开票系统，开票信息就是，普通的input，商品明细，就是table。具体可以参考增值税发票。

**Comment by zhuangchong** [comment]
组件：vue-treeselect
https://github.com/riophae/vue-treeselect

**Comment by PrintCreate** [comment]
子表单可以支持一下吗?主子表
