### ISSUE TITLE
多次v-if后表单内控件绑定的事件失效

### ISSUE THREAD

**Issue by Nuoky** [xaboy/form-create#125]
#### 版本号 / version
@form-create/iview 1.0.1

#### 使用的 UI 框架 
iview

#### UI 框架的版本
3.4.2

#### 问题描述
背景：JSON形式载入rule
过程：在使用v-if=false卸载父节点后，再让 v-if=true且载入相同的rule，会出现绑定的事件失效无法正常触发事件绑定的方法内的代码。目前只能通过this.rule = cloneDeep(rule)这种方式来避免。

#### 复现步骤
https://jsfiddle.net/Nuoky/Ltuxdmkp/

#### 期望的结果
重新加载相同rule配置文件后，可以正常触发Select绑定的change事件

**Comment by xaboy** [comment]
感谢你的反馈, 这个是 bug. 
我在检查一下,下个版本修复

**Comment by Nuoky** [comment]
补充下，若使用lodash的cloneDeep(rule)或JSON.parse(JSON.stringify(rule))来暂时解决问题是不完整的，在rule内有自定义组件（new Vue()的方式）时会出错

**Comment by xaboy** [comment]
好的,下个版本可以让 vm 支持通过函数生成
```js
vm: function(){
    return new Vue;
}

**Comment by xaboy** [comment]
1.0.3版本已经修复和支持
