### ISSUE TITLE
form-create 的 div root放在el-dialog的时候显示不正常，未显示在弹出框内部

### ISSUE THREAD

**Issue by meathross** [xaboy/form-create#126]
"@form-create/element-ui": "0.0.5"

element-ui 

"element-ui": "2.10.1"

form-create 的 div root放在el-dialog的时候显示不正常，未显示在弹出框内部。使用JSON的方式创建。
![image](https://user-images.githubusercontent.com/14865604/63238435-1a532a00-c279-11e9-9d2a-fbe79b88ada9.png)
![image](https://user-images.githubusercontent.com/14865604/63238442-22ab6500-c279-11e9-8399-a740e24249a1.png)
![image](https://user-images.githubusercontent.com/14865604/63238474-453d7e00-c279-11e9-8527-2bbc7f97336a.png)
自动注入的代码，没有放在对应的div下。
![image](https://user-images.githubusercontent.com/14865604/63238502-6bfbb480-c279-11e9-82d2-2bae7f50259f.png)

**Comment by xaboy** [comment]
@meathross  确认一下`document.getElementById('form-create')`有没有获取到

**Comment by meathross** [comment]
确实没有获取到，打扰了。

**Comment by meathross** [comment]
把创建form的方法放在el-dialog的opened事件方法就可以了。
