### ISSUE TITLE
titile是否可以支持传入渲染函数或JSX

### ISSUE THREAD

**Issue by Nuoky** [xaboy/form-create#127]
#### 建议
titile是否可以支持传入渲染函数或JSX？

#### 期望的结果
```
{
        type: 'input',
        title: <p>URL<span>desc</span><p>,
        field: 'url'
}
```

**Comment by xaboy** [comment]
应该可以支持,请问一下这个使用场景是什么?

**Comment by Nuoky** [comment]
@xaboy 感谢回复~
使用场景：
经常会在表单label上加上些填写说明，这些说明较长如果直接写在placeholder里会不方便阅读；所以一般会在label后加上个“？”号Icon，hover时弹出Tooltip或Poptip展示说明

**Comment by xaboy** [comment]
@Nuoky 这个内置有,可以通过设置 [info](http://form-create.com/v2/guide/rule.html#info) 实现

**Comment by Nuoky** [comment]
好的，谢谢！

**Comment by minzhenyu** [comment]
我也有这个需求，但是有不同点，我这边需要转换markdown 格式，带有格式，所以会直接转成html,info现在应该没有v-html的效果吧  @xaboy

**Comment by minzhenyu** [comment]
我也有这个需求，但是有不同点，我这边需要转换markdown 格式，带有格式，所以会直接转成html,info现在应该没有v-html的效果吧  @xaboy
