### ISSUE TITLE
[enhancement]对于loading状态的使用期望

### ISSUE THREAD

**Issue by shadow-mike** [xaboy/form-create#128]
谢谢作者开发的form-create库，一定程度上帮助了我提高表单开发效率。
然后在使用的过程中，有了更多小的想法。

比如，
使用json形式生成表单，
以下是json局部数据，

```
option: {
    injectEvent: true, // 注入form实例
    onSubmit: async (formData, $f) => {
        // $f.submitBtnProps({ loading: true });
        const result = await this.updateTitle(formData); // 异步行为
        // $f.submitBtnProps({ loading: false });
        this.$message.success('修改成功！');
        this.closeDialog();
    },
    submitBtn: {
        loading: this.getLoading('moduleName/updateTitle'), // vuex维护的loading状态
    },
}
```
有时候异步行为的错误可能在内部就被拦截处理，不会被抛至到当前上下文环境，导致submitBtn loading无法手动置为false。
期望能不用手动维护loading状态。能够响应式配置loading状态。

**Comment by xaboy** [comment]
错误在内部就被拦截这个问题我检查一下,可能是验证的时候被拦截了.
`loading`状态还是需要根据需求手动维护,`form-create` 内部也不知道`loading`的状态

**Comment by shadow-mike** [comment]
> 错误在内部就被拦截这个问题我检查一下,可能是验证的时候被拦截了.
> `loading`状态还是需要根据需求手动维护,`form-create` 内部也不知道`loading`的状态

不不。我说的错误不是form validate的问题，指的是一种情况：异步请求时可能回来的HTTP STATUS不是200。这个时候走了error回调，不会继续向下执行`$f.submitBtnProps({ loading: false });`。因为我的this.updateTitle(formData)内部已经catch并处理了异步的错误（并没打算继续再把error throw出来）。这种情况就不知道该如何把submit按钮的loading给关掉。

我这边是用vuex维护了所有的请求loading状态。'moduleName/updateTitle'是一个含有异步请求的action的名字。触发异步时this.getLoading('moduleName/updateTitle')返回的是true，异步结束后this.getLoading('moduleName/updateTitle')返回false。我理想的期望是，在用json配置了submitBtn的loading后，this.getLoading('moduleName/updateTitle')状态值的变化能继续被submitBtn监听到……

我就只是提一个小想法而已。

**Comment by xaboy** [comment]
这样就可以了吧
```js
try{
    const result = await this.updateTitle(formData);
}catch(e){}
```

2. vuex 这里的绑定 loading 状态的写法不太对吧
```js
{
    data(){
        return {
            //...
            options: {
                submitBtn: {
                    loading: this.loading
                }
                //...
            }
        }
    },
    computed: mapGetters(["loading"]),
}
```
