### ISSUE TITLE
type template在深层嵌套中没有被包含在el-form-item中

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#129]
1.0.3

element-ui

rules生成动态表单 type [template在深层嵌套中没有被包含在el-form-item中](url)

{
        type: "div",
        children: [
          {
            type: "div",
            children: [
              {
                type: "div",
                children: [
                  {
                    type: "div",
                    children: [
                      {
                        type: "template",
                        template: "<el-input />",
                        field: "11",
                        validate: [
                          {
                            required: true,
                            message: "11",
                            trigger: "blur"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }

期望可以嵌套在el-form-item中

**Comment by Lysom** [comment]
{
                        type: "template",
                        template: "<el-input />",
                        field: "11",
                        validate: [
                          {
                            required: true,
                            message: "11",
                            trigger: "blur"
                          }
                        ]
                      }

**Comment by Lysom** [comment]
{
                        type: "template",
                        template: "\<el-input /\>",
                        field: "11",
                        validate: [
                          {
                            required: true,
                            message: "11",
                            trigger: "blur"
                          }
                        ]
                      }

**Comment by xaboy** [comment]
目前只要最外层的组件和内置组件会默认包裹在 `FormItem`中,其他组件不会
这块我再看一下,能不能优化一下

**Comment by Lysom** [comment]
如果多层嵌套的是div或者其他元素 是可以包裹在 FormItem 中

**Comment by xaboy** [comment]
通过配置生成规则`native`可以控制是否需要被嵌套,等于`true`时不会嵌套
