### ISSUE TITLE
代码注释问题

### ISSUE THREAD

**Issue by liyuchuan86** [xaboy/form-create#13]
请问能把源码中的注释添加一下吗？想扩展下，但没有注释很多代码看起比较痛苦

**Comment by liyuchuan86** [comment]
额，我是想扩展更多的控件，比如表格，比如下拉树等，并且为添加更多的属性，然后在加上可视化的表单设计

**Comment by xaboy** [comment]
扩展起来确实要注意的地方比较多.我先写注释,有什么不清楚的地方可以问我

**Comment by liyuchuan86** [comment]
非常感谢！

**Comment by xaboy** [comment]
[组件开发文档](https://github.com/xaboy/form-create-extended),你看下有没有什么不清楚的地方,我文档写的比较菜...

**Comment by liyuchuan86** [comment]
非常感谢，我先看下，不懂的在请教

**Comment by liyuchuan86** [comment]
看了文档稍微理解一点了，但还是不清楚该怎么做，比如我要给某个控件添加v-show 属性，rule 里面没有，options里面也不能配置，请指点下

**Comment by xaboy** [comment]
[可以参考一下这里](https://cn.vuejs.org/v2/guide/render-function.html)
`v-show`直接在vNode数据对象里增加`props:{show:value}` 就可以,注意这个value必须是`vm.$data`中的属性

**Comment by xaboy** [comment]
调试时崩溃我没遇到过..

**Comment by liyuchuan86** [comment]
rule里面的field 不是控件的ID么？ vm.$data 里面的值必须和field对应上吧

**Comment by xaboy** [comment]
表单的键值对保存在`vm.$data.formData`里,控件的id是什么?

**Comment by xaboy** [comment]
你的回复没有邮件提醒了不知道为什么

**Comment by ganxieni** [comment]
我很奇怪你们的聊天我收到了邮件提示

**Comment by ganxieni** [comment]
我很奇怪你们的聊天我收到了邮件提示

**Comment by ganxieni** [comment]
我很奇怪你们的聊天我收到了邮件提示

**Comment by liyuchuan86** [comment]
其实我是想问rule里面的field 是不是应该和vm.$data.formData 里面值对应上
![image](https://user-images.githubusercontent.com/32632734/41402217-4dc9edde-6ff4-11e8-968d-a98d3c2c8364.png)
![image](https://user-images.githubusercontent.com/32632734/41402231-5764a12c-6ff4-11e8-8d98-afe278bca894.png)

**Comment by xaboy** [comment]
`show:'vm.$data.postage == 1'`这种写法是错的,还有就是现在应该不支持v-show,应该我初始化的时候把参数的深度拷贝了

**Comment by xaboy** [comment]
我以为你说的是组件开发时候的v-show

**Comment by liyuchuan86** [comment]
那现在是只能在事件里面处理联动是么？ 还有我在页面上定义的data怎么才能和field对应上呢？不对应上的话 修改了 生成的控件值变了data并没有改变

**Comment by xaboy** [comment]
正常使用的话可以可以再change事件中获取值,或者`$f.getField(field)`手动获取

**Comment by liyuchuan86** [comment]
写组件的方式，我的想法是整个页面的配置，包括布局，控件全部都是json方式输出到前端，再由前端来输出到客户端

**Comment by xaboy** [comment]
用json生成一直都支持的
