### ISSUE TITLE
多层嵌套中 el-select选择失效 数据更改 DOM没有更新

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#130]
1.0.3

element-ui

在table多级嵌套中 select v-model数据更改  选项并没有更新

{
        type: "table",
        children: [
          {
            type: "tr",
            children: [
              {
                type: "td",
                children: [
                  {
                    type: "template",
                    template: `\<el-select v-model="sel"\>
\<el-option label="1" value="1"\>\</el-option\>,
\<el-option label="2" value="2"\>\</el-option\>
\<\/el-select\>`,
                    vm: new Vue({
                      data() {
                        return {
                          sel: ""
                        };
                      }
                    })
                  }
                ]
              }
            ]
          }
        ]
      }

**Comment by Lysom** [comment]
在template中是这种情况  type: 'el-select'正常

**Comment by xaboy** [comment]
template需要定义 field,并且实现 v-model 才可以
