### ISSUE TITLE
动态加载规则后无法获取到表单的双向绑定对象

### ISSUE THREAD

**Issue by NHZEX** [xaboy/form-create#133]
form-create v1.0.3
iview v3.4.2

### 问题描述
组件模式下，动态设置`rule`，无法正常使用`bind()`，`fields()`等方法。

### 复现步骤
初始`rule`为空数组，然后异步从服务器加载规则，表单渲染成功后，执行`bind()`方法无法获取双向数据绑定的表单键值对，执行`fields()`方法获取的也是空值。
ps：静态设置`rule`是能正常工作的。

**Comment by xaboy** [comment]
我检查一下

**Comment by NHZEX** [comment]
> 我检查一下

是异步的问题，我在`onReload`事件中可以获取到了，但又有一个问题，`onReload`事件被触发多次。

![image](https://user-images.githubusercontent.com/14545600/64470628-2136d380-d179-11e9-80bf-13e2882cdb1e.png)

`rule`赋值后接着获取是空，收到事件后获取正常，但事件被触发三次。
