### ISSUE TITLE
dateObject.getTime is not a function

### ISSUE THREAD

**Issue by qudawei** [xaboy/form-create#134]
1.0.3

      iview

3.4.1

    在有时间回显的页面，修改了页面规则自动渲染后，点击提交报错，这个时间我手动转换了，但是取出来还是字符串格式。但是如果手动再选一次时间，就不会报错。有人遇到这类问题吗？或者可以使用什么方法触发时间选择？
![image](https://user-images.githubusercontent.com/18113748/64582061-035ab000-d3bf-11e9-9613-60f6bc35bead.png)

在有时间的页面，在rule深拷贝一个表格，点击提交按钮不报错。

**Comment by xaboy** [comment]
应该是时间组件的 value 不正确,可以贴一下生成规则吗

**Comment by qudawei** [comment]
这个value一直都是字符串格式有问题，不过通过在validator里面设置通过解决了。
