### ISSUE TITLE
组件设置属性hidden为true不生效

### ISSUE THREAD

**Issue by TerryChenUI** [xaboy/form-create#136]
"@form-create/element-ui": "^1.0.3",

element-ui

2.12.0

设置hidden属性，该组件不会隐藏
{
      type: 'input',
      field: 'keyword',
      title: '关键字',
      props: {
        type: 'text',
        placeholder: '请输入订单编号、企业ID/名称',
        hidden: true // 设置不生效
      }
 },

使用api的方式也不能隐藏
fApi.hidden('keyword', true)

**Comment by TerryChenUI** [comment]
使用setValue的实例方法是可以的，求解答
fApi.setValue({
  keyword: '123'
})

**Comment by lizhi2013** [comment]
好像都没人答复？

**Comment by xaboy** [comment]
v2不支持hidden属性,需要自己实现.这个后面版本可以考虑增加

**Comment by xaboy** [comment]
1.0.5版本已支持
