### ISSUE TITLE
怎么创建子表单？实现增减子表单数据？给个案例！

### ISSUE THREAD

**Issue by newyearsoft** [xaboy/form-create#139]
怎么创建子表单？实现增减子表单数据？给个案例！

报销单号：
报销人：               申请报销部门： 
报销日期：           所属项目： 
类型 | 日期 | 备注 | 金额（子表单）
                                           +
                                           -
                         合计

在官网上设计个案例出来，给大家参考！

**Comment by 2943785277** [comment]
我们最近也在做这个功能

**Comment by StickChen** [comment]
希望支持嵌套对象，组件数组，甚至是动态Map

**Comment by xaboy** [comment]
已支持组件嵌套,组件数组
