### ISSUE TITLE
// 我在在引进 import { maker } from '@form-create/iview'   这个的时候这个一直是灰色的,然后在vue 脚手架的搭建下,生成表单一直不成功,望指点

### ISSUE THREAD

**Issue by jiangCheng006** [xaboy/form-create#141]

**Comment by jiangCheng006** [comment]
import Vue from 'vue'
import App from './App.vue'
import VueRouter from 'vue-router'
import ViewUI from 'view-design';
import 'view-design/dist/styles/iview.css';
import formCreate from '@form-create/iview'
//获取生成器
import { maker } from '@form-create/iview'    就是这里

Vue.use(ViewUI);
Vue.use(formCreate)
Vue.use(VueRouter)
Vue.config.productionTip = false

**Comment by xaboy** [comment]
需要先安装 form-create
```js
npm i @form-create/iview
```

**Comment by jiangCheng006** [comment]
您好，我已经安装了，是在导入maker的时候是灰色的，而且导入上面那个form-creaate的时候提示我并没有这个文件，但是我在package.json和node_modules里面都能找到这个文件，为什么看您的有的不需要导入maker有的却要呢------------------ 原始邮件 ------------------
发件人: "xaboy"<notifications@github.com>
发送时间: 2019年10月13日(星期天) 中午11:15
收件人: "xaboy/form-create"<form-create@noreply.github.com>;
抄送: "jiangcheng"<847727214@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xaboy/form-create] // 我在在引进 import { maker } from '@form-create/iview'   这个的时候这个一直是灰色的,然后在vue 脚手架的搭建下,生成表单一直不成功,望指点 (#141)



需要先安装 form-create
 npm i @form-create/iview
 
&mdash;

**Comment by xaboy** [comment]
你重新安装一下`form-create`试试,maker 可以不导入
```
const maker = formCreate.maker
```
