### ISSUE TITLE
通过json渲染表单组件，DatePicker组件value有值，但组件不显示

### ISSUE THREAD

**Issue by xiaomogutou** [xaboy/form-create#142]
1.6.6

element-ui 

2.11.1

通过json渲染表单组件，DatePicker组件value有值，但是未显示

下面是DatePicker组件的json
 
{
            "type": "DatePicker",
            "field": "payIndividuaTaxDate",
            "title": "缴纳个税时间：",
            "value": ["2019-02","2020-10"],
            "col": {
                "offset": 2,
                "span": 10,
                "labelWidth": 180
            },
            "props": {
                "type": "monthrange",
                "placeholder": "请选择"
            },
            "validate": [
                {
                    "type": "array",
                    "required": true,
                    "message": "请输入缴纳个税时间",
                    "trigger": "change"
                }
            ]
        },

希望组件可以自动带出值

**Comment by xaboy** [comment]
升级到 v2 版本试试

```
npm i @form-create/element-ui
```

**Comment by xiaomogutou** [comment]
已经升级到v2， 问题已解决，谢谢~！

**Comment by xiaomogutou** [comment]
请问v2版本中的labelWidth只能全局设置整个表单的吗？可以单独设置表单中的子元素form-item吗

**Comment by xaboy** [comment]
组件的 col 规则里可以配置labelWidth
