### ISSUE TITLE
element-ui图片上传成功但是回显失败

### ISSUE THREAD

**Issue by stardu** [xaboy/form-create#143]
element-ui

element-ui图片上传成功但是回显失败是什么原因？

**Comment by xaboy** [comment]
需要在 success 事件里设置图片路径

**Comment by stardu** [comment]
file.url = res.data;这样设置图片路径不可以么？res.data是我上传图片成功后台返回的图片路径。我这样设置控制台会报警告<transition-group> children must be keyed: <li>
