### ISSUE TITLE
多个控件时，仅第一个控件渲染正常

### ISSUE THREAD

**Issue by SmiMi** [xaboy/form-create#144]
版本号 / version 
1.0.3

使用的 UI 框架 (element-ui / iview)
element-ui

UI 框架的版本 
2.11.1

问题描述 
多个控件时，仅第一个控件渲染正常。第二个控件没有element ui的样式

 复现步骤
举例，使用如下json是两个el-input，仅第一个可以显示正常。且formCreate无报错信息

[{
	"type": "el-row",
	"title": "栅格布局",
	"props": {
		"gutter": 0,
		"justify": "start",
		"align": "top",
	},
	"children": [{
		"type": "el-col",
		"props": {
			"span": 12
		},
		"children": [{
			"type": "input",
			"title": "单行文本",
			"props": {
				"type": "text",
				"width": "100%",
				"placeholder": "请输入",
				"disabled": false,
			},
			"key": "1572516667000_93798",
			"model": "input_1572516667000_93798",
			"rules": [],
			"field": "business_id",
			"validate": [],
			"col": {
				"span": 24
			},
			"emit": [],
			"on": {
				
			},
			"options": [],
			"value": ""
		}],
		"validate": [],
		"col": {
			
		},
		"emit": [],
		"on": {
			
		},
		"options": [],
		"value": "",
		"field": ""
	},
	{
		"type": "el-col",
		"props": {
			"span": 12
		},
		"children": [{
			"type": "input",
			"title": "单行文本",
			"props": {
				"type": "text",
				"width": "100%",
				"placeholder": "请输入",
				"disabled": false
			},
			"key": "1572516669000_69468",
			"rules": [],
			"validate": [],
			"col": {
				
			},
			"emit": [],
			"on": {
				
			},
			"options": [],
			"value": "",
			"field": ""
		}],
		"validate": [],
		"col": {
			
		},
		"emit": [],
		"on": {
			
		},
		"options": [],
		"value": "",
		"field": ""
	}],
	"rules": [],
	"validate": [],
	"field": ""
}]

期望的结果
所有控件显示正常

**Comment by SmiMi** [comment]
算了，我自己实现了一套

**Comment by xaboy** [comment]
我检查了下是因为没有定义 field 字段,所以按照自定义组件生成的.所以只生成了一个 input

**Comment by xaboy** [comment]
@SmiMi

**Comment by xaboy** [comment]
如果不需要定义 field,可以将 type 设置为:el-input
