### ISSUE TITLE
开启injectEvent: true 上传插件showFileList  不会回显

### ISSUE THREAD

**Issue by Mrjingshan** [xaboy/form-create#146]

**Comment by Mrjingshan** [comment]
开启injectEvent: true 上传插件showFileList  不会回显

**Comment by xaboy** [comment]
贴一下代码,我看看

**Comment by Mrjingshan** [comment]
好的,稍等






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xaboy"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午3:04
收件人: "xaboy/form-create"<form-create@noreply.github.com&gt;; 
抄送: "Mr"<877945427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xaboy/form-create] 开启injectEvent: true 上传插件showFileList  不会回显 (#146)




贴一下代码,我看看

**Comment by Mrjingshan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xaboy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 下午3:04
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Mr"<877945427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] 开启injectEvent: true 上传插件showFileList  不会回显 (#146)




贴一下代码,我看看

**Comment by Mrjingshan** [comment]
我把我代码给你 在附件中

















------------------ 原始邮件 ------------------
发件人:&nbsp;"xaboy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 下午3:04
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Mr"<877945427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] 开启injectEvent: true 上传插件showFileList  不会回显 (#146)




贴一下代码,我看看

**Comment by xaboy** [comment]
没收到

**Comment by Mrjingshan** [comment]
> 没收到


[formC.zip](https://github.com/xaboy/form-create/files/3845341/formC.zip)

**Comment by xaboy** [comment]
2.5版本已优化
