### ISSUE TITLE
请问如何对表单中的两个input做联合校验

### ISSUE THREAD

**Issue by runlli** [xaboy/form-create#147]
"@form-create/element-ui": "^1.0.3"

请问如何对表单中的两个input做联合校验。比如 开始时间 需 小于结束时间

**Comment by Mrjingshan** [comment]
> "@form-create/element-ui": "^1.0.3"
> 
> 请问如何对表单中的两个input做联合校验。比如 开始时间 需 小于结束时间
嘤嘤嘤

**Comment by xaboy** [comment]
可以在第一个 input 组件的change 事件中修改第二个组件的验证规则

**Comment by Lysom** [comment]
最新版本的@form-create/element-ui 2.5.8 联合校验时修改规则的话，如果有group子表单形势的组件，怎么去修改规则，change方法里获取不到另一个组件的规则
