### ISSUE TITLE
upload的上传完东西后,校验不通过 为空 该怎么办

### ISSUE THREAD

**Issue by Mrjingshan** [xaboy/form-create#148]

**Comment by xaboy** [comment]
注意验证规则中的 `type`,验证数组的时候需要设置
```js
{type:'array',required:true}
```

**Comment by Mrjingshan** [comment]
> 注意验证规则中的 `type`,验证数组的时候需要设置
> 
> ```js
> {type:'array',required:true}
> ```

![image](https://user-images.githubusercontent.com/50735366/69017987-0d171a00-09e5-11ea-81f5-c7763e202223.png)
![image](https://user-images.githubusercontent.com/50735366/69017996-1acc9f80-09e5-11ea-887c-bb2cfd155a31.png)
![image](https://user-images.githubusercontent.com/50735366/69018003-228c4400-09e5-11ea-897a-24d84a94b98d.png)

**Comment by Mrjingshan** [comment]
![image](https://user-images.githubusercontent.com/50735366/69018028-48194d80-09e5-11ea-931d-0aa6f5499858.png)

**Comment by Mrjingshan** [comment]
![021488adcc69fd1e3532adc0b500c0c7](https://user-images.githubusercontent.com/50735366/69018226-48661880-09e6-11ea-8a5e-931ea2bd5996.jpg)
![a11954faeeef650852724a7cedba9e1a](https://user-images.githubusercontent.com/50735366/69018227-48feaf00-09e6-11ea-85c3-c4a8554cc32b.jpg)
![000cbb9e62de87fc1c360d7acfd93708](https://user-images.githubusercontent.com/50735366/69018230-4ac87280-09e6-11ea-9d2f-09926b6b3f3f.jpg)

**Comment by xaboy** [comment]
把错误信息展开看一下

**Comment by Mrjingshan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xaboy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 上午10:25
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Mr"<877945427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] upload的上传完东西后,校验不通过 为空 该怎么办 (#148)




把错误信息展开看一下

**Comment by xaboy** [comment]
什么都没收到

**Comment by Mrjingshan** [comment]
我不太会弄这个&nbsp; 我能加你微信吗?&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xaboy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 中午11:15
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Mr"<877945427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] upload的上传完东西后,校验不通过 为空 该怎么办 (#148)




什么都没收到

**Comment by xaboy** [comment]
可以加 qq 讨论群:28963712
