### ISSUE TITLE
是否支持可视化表单编辑器

### ISSUE THREAD

**Issue by lingkejia** [xaboy/form-create#151]
能否提供一个可视化的表单编辑器，类似[http://form.xiaoyaoji.cn/#/zh-CN/](http://form.xiaoyaoji.cn/#/zh-CN/)，这样结合表单生成器可应用的场景就更多了，甚至可以集成到工作流的自定义表单设计

**Comment by kangning1206** [comment]
我也在找方法，我们的流程引擎，供应商的提供了一个表单设计器，但生成后显示界面太丑，版本实现方式很老旧，现在想使用vue前后端分离，只实现前端表单自动生成，后台接口返回json数据，楼主你找到方案可吗？本周看了 form-create的源码，目前还一头雾水，我是antd-vue版本，挣扎中...

**Comment by xaboy** [comment]
form-create 可视化表单设计器已发布 https://github.com/xaboy/form-create-designer 
@lingkejia  @kangning1206
