### ISSUE TITLE
可以生成单个组件吗？

### ISSUE THREAD

**Issue by stunievi** [xaboy/form-create#152]
例如 ： { type: "input", field: "goods_name", title: "商品名称", value: "mi" }
只生成一个input 而不需要el-form

**Comment by xaboy** [comment]
好像不行,会自动识别成内置组件

**Comment by stunievi** [comment]
我想跟vue-draggable配合来做拖拽生成表单，这样不行的话有什么好办法吗？

**Comment by xaboy** [comment]
你想生成的 input 是原生的 input标签 还是 ui 框架的 input 组件?

**Comment by stunievi** [comment]
ui框架的 element

**Comment by xaboy** [comment]
`type:'el-input'` 这样就可以了
