### ISSUE TITLE
Checkbox的 size/text-color/fill無效，因為三個元素只針對按鈕形式有用

### ISSUE THREAD

**Issue by stanleylu3216** [xaboy/form-create#153]
**版本号 / version** 
1.0.4

**使用的 UI 框架 (element-ui / iview)**
element-ui 2.13

**UI 框架的版本**
Vue 2.6.10

**问题描述**
Checkbox提供的參數有size, text-color, fill，這些參數都是只對按鈕形式的checkbox有作用，但目前form-create僅提供打勾形式的checkbox，亦即form-create提供的此三個參數無效

<img width="484" alt="Screen Shot 2019-12-07 at 1 59 13 pm" src="https://user-images.githubusercontent.com/48779712/70369806-d2c0de80-18f9-11ea-95bd-d7d398bb9c22.png">

**复现步骤**
```
const rule = {
  type: 'checkbox',
  options: {
     props: Object
     disabled: false
     fill: "#14CCD9"
     max: 100
     min: 2
     size: "small"
     text-color: "#AFB723"
  }
}
```
**期望的结果**
給了 size, text-color, fill，會有變化

**建议**
多給個prop，checboxType{ 'button' | 'border' }

**Comment by xaboy** [comment]
通过设置 `props.type = 'button'`,可以以按钮的形式显示.

**Comment by stanleylu3216** [comment]
thanks
