### ISSUE TITLE
ts版本已引入报错

### ISSUE THREAD

**Issue by 497983606** [xaboy/form-create#154]
vue-cli3 ts 版本  vue 2.6.10

element-ui

2.13.0

vue-cli3 ts 版本  vue 2.6.10  引入框架报错

无法找到模块“@form-create/element-ui”的声明文件。“f:/work/kodev/ui-code/kodev/node_modules/@form-create/element-ui/dist/form-create.min.js”隐式拥有 "any" 类型。
  Try `npm install @types/form-create__element-ui` if it exists or add a new declaration (.d.ts) file containing `declare module '@form-create/element-ui';`

按照vue cli3 安装 ts版本，在main.ts按照网站说明内引入@form-create/element-ui

**Comment by xaboy** [comment]
目前还不支持 ts

**Comment by xaboy** [comment]
1.0.6版本已支持
