### ISSUE TITLE
局部使用报错

### ISSUE THREAD

**Issue by zaaoda** [xaboy/form-create#155]
版本 1.6.6

全局没问题局部报错

报错信息
vue-router.esm.js?8c4f:2079 TypeError: form_create_element__WEBPACK_IMPORTED_MODULE_0___default.a.$form is not a function
at eval

**Comment by xaboy** [comment]
1.6.6版本没有`$form`这个方法.
`$form`是v2版本的

**Comment by zaaoda** [comment]
> 版本1.6.6
> 
> 全局没问题局部报错
> 
> 报错信息
> vue-router.esm.js？8c4f：2079 TypeError：form_create_element__WEBPACK_IMPORTED_MODULE_0 ___ default.a。$ form
> 在eval时不起作用
