### ISSUE TITLE
动态渲染的select无法触发change事件

### ISSUE THREAD

**Issue by key1012** [xaboy/form-create#156]

**Comment by key1012** [comment]
[{field: "categoryId", options: [{label: "ssm", value: "0a01563a14484f61b94dbe4840f84107"},…],…}
field: "categoryId"
options: [{label: "ssm", value: "0a01563a14484f61b94dbe4840f84107"},…]
type: "select"
title: "设备分类"
event: {change: "(checked)=>{alert(checked)}"}]

**Comment by key1012** [comment]
[{
field: "categoryId"
options: [{label: "ssm", value: "0a01563a14484f61b94dbe4840f84107"},…]
type: "select"
title: "设备分类"
event: {change: "(checked)=>{alert(checked)}"}

**Comment by xaboy** [comment]
请问form-create的版本是多少?

**Comment by key1012** [comment]
1.0.3

**Comment by xaboy** [comment]
iviewUI 的话应该是
```
event: {"on-change": "(checked)=>{alert(checked)}"}
//或者
on: {"on-change": "(checked)=>{alert(checked)}"}
```
elementUI 的话应该是
```
on: {"change": "(checked)=>{alert(checked)}"}
```

**Comment by key1012** [comment]
解决了，elementui 是on  ，麻烦还是在API里说明一下，谢谢

**Comment by xaboy** [comment]
好的. 你在哪看到的,链接给我发一下

**Comment by key1012** [comment]
http://form-create.com/v2/element-ui/components/select.html

最下面的event

**Comment by key1012** [comment]
你好 还有一个问题 现在是
"on": {
		"change": (checked)=>{alert(checked)}
	}
这样可以用，但是后台返回来json是
"on": {
		"change": ”(checked)=>{alert(checked)}”
	}

这样才是json格式，你上面的没有“”才可以用，如果没有“”就违反了json格式，这个怎么处理

**Comment by xaboy** [comment]
可以先在前端生成好表单后通过$f.toJson()转换成 json 格式

**Comment by key1012** [comment]
您没有明白我的意思，我现在的组件数据是后台返回的json，json可是是{"change":"(checked)=>{alert(checked)}"}
但是您的form-create组件需要的是{"change":(checked)=>{alert(checked)}}，你需要的是没有“”

**Comment by xaboy** [comment]
后台返回
```
{"change":"function(checked){alert(checked)}"}
```
然后通过 `formCreate.parseJson` 方法转换

**Comment by key1012** [comment]
不行，直接报转化错误

**Comment by xaboy** [comment]
```
formCreate.parseJson('[{"change":"function(checked){alert(checked)}"}]') 
```
这边测试没有问题

**Comment by key1012** [comment]
好了
谢谢，因为后台返回的是json格式  需要stringify一下再使用你的formCreate.parseJson就可以了，
非常感谢
