### ISSUE TITLE
验证的 内置消息 希望可以提供配置方法

### ISSUE THREAD

**Issue by loqhcn** [xaboy/form-create#158]
最新版

验证的 内置消息 希望可以提供配置方法, 目前是默认英文的

**Comment by xaboy** [comment]
通过验证规则的 message属性可以配置提示信息. [验证规则](http://www.form-create.com/v2/guide/other/validation-rules.html#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)
