### ISSUE TITLE
建议：希望支持嵌套对象，组件数组，甚至是动态Map

### ISSUE THREAD

**Issue by StickChen** [xaboy/form-create#159]
希望支持嵌套对象，组件数组，甚至是动态Map，搜了下这个项目实现了，希望能跟进一下
https://vue-dynamic-form.quincychen.cn/zh/
还有一种是根据下拉选择框控制展示不同类型嵌套对象

**Comment by chris-js** [comment]
同上，强烈需要支持，我现在是没办法，使用vue-dynamic-form.quincychen.cn这个 ，很多基础的组件不支持，自己在封装，上传框已经实现了，checkbox又卡住了，太烦了

**Comment by xaboy** [comment]
下个版本支持 @StickChen @chris-js

**Comment by xaboy** [comment]
1.0.7版本已支持
