### ISSUE TITLE
select远程搜索怎么样更改当前options的值呢

### ISSUE THREAD

**Issue by PixelMapping** [xaboy/form-create#160]
singledrop: {
                type: "select",
                options: [],
                props:{
                  filterable:true,
                  remote:true,
                  loading:false,
                },
                on:{
                  'on-query-change':function(query){
                    console.log(query)
                  },
                },
                validate: [
                  {
                    required: item.Required,
                    message: item.ControlHintMsg,
                    type:'number',
                    trigger: "change"
                  }
                ]
              },

**Comment by xaboy** [comment]
可以通过开启事件注入来快速获取当前规则
```js
singledrop: {
type: "select",
inject: true,
options: [],
props:{
filterable:true,
remote:true,
loading:false,
},
on:{
'on-query-change':function(inject,query){
console.log(query)
// 修改当前options
// inject.self.options = [.... ]
},
},
validate: [
{
required: item.Required,
message: item.ControlHintMsg,
type:'number',
trigger: "change"
}
]
}
```

**Comment by PixelMapping** [comment]
大佬可以加个qq或者微信沟通下吗，开启了还是拿不到这个inject,qq:1401248808,wx:18551920460

**Comment by xaboy** [comment]
可以加一下 qq 群: 28963712
