### ISSUE TITLE
全局配置 怎么使用

### ISSUE THREAD

**Issue by chris-js** [xaboy/form-create#164]
^1.0.5

element 

^2.13.0

全局配置 怎么使用，文档打开404 
组件公共配置 写了 放哪里

**Comment by xaboy** [comment]
可以参考一下[文档>全局配置](http://www.form-create.com/v2/guide/global-options.html#%E8%AE%BE%E7%BD%AE%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE)

**Comment by chris-js** [comment]
主要是不知道写在哪里，main.js 里面 
import formCreate from '@form-create/element-ui'
Vue.use(formCreate);

然后怎么加入这个，没看懂额
vm.$formCreate(rule,option)
window.formCreate.create(rule,option)
