### ISSUE TITLE
element  Cascader 多级联动，异步获取数据,数据未更新

### ISSUE THREAD

**Issue by ZthStudy** [xaboy/form-create#165]
![image](https://user-images.githubusercontent.com/30645249/72592543-c2ab0e80-393d-11ea-877f-190da2d4a69e.png)
![image](https://user-images.githubusercontent.com/30645249/72592557-ca6ab300-393d-11ea-9456-fdd005a54bb8.png)
form-create中options有值，element未更新

**Comment by xaboy** [comment]
@ZthStudy 使用$set 方法修改`options`试试

**Comment by ZthStudy** [comment]
@xaboy    
`this.$set(this.model.address,` 'options', `this.provinces);`
这样写不行，更新的对象应该是this.model吧

**Comment by xaboy** [comment]
可以直接修改生成规则的`options`或者通过`$f.updateRule`方法修改

**Comment by ZthStudy** [comment]
` const rule = this.fApi.updateRule('address', {
        options: this.provinces,
 });
 console.log('this.rule', rule);
`
![image](https://user-images.githubusercontent.com/30645249/72595242-5253bb80-3944-11ea-9b4a-71fff623c20d.png)
两种方法都是form-create有值，element没值

**Comment by xaboy** [comment]
可能是 bug,可以先试试用`$f.sync`或者`$f. refresh `方法手动刷新组件

**Comment by ZthStudy** [comment]
也尝试了手动刷新，暂时也是不管用，谢谢作者大佬的解答，期待解决，嘻嘻。

**Comment by xaboy** [comment]
可能是你赋错值了,应该是给`rule.props.options`赋值

**Comment by ZthStudy** [comment]
哎  是的  sorry  之前写顺手了，谢谢你。
