### ISSUE TITLE
提交按钮布局问题

### ISSUE THREAD

**Issue by sugar0828** [xaboy/form-create#167]
v2

elementui

2.13.0

submitBtn布局目前都是block另起一行，offset，push试过了。能否设置inline，跟在最后一个form-item后面

设置inline，跟在最后一个form-item后面

**Comment by xaboy** [comment]
当全局配置中 `form.inline`为 `true` 的时候,按钮会自动设置成`inline:true`,也可以通过 `submitBtn.col` 设置按钮的布局规则

**Comment by a303557339** [comment]
设置了inline:true和submitBtn.col均无效，是什么原因
options: {
        form: {
          inline: true,
          labelCol: { span: 6 },
          wrapperCol: { span: 18 }
        },
        submitBtn: {
          col: {
            span: 5
          },
          block: false,
          innerText: '查询'
        },
        resetBtn: true,
        onSubmit: formData => {
          console.log(formData)
        }
      },
