### ISSUE TITLE
重置按钮缺少提交事件

### ISSUE THREAD

**Issue by Joevin-Tang** [xaboy/form-create#169]
V2

iview

iview v4.0

重置按钮没有提供事件

希望重置按钮也提供一个事件提交，以方便对应的业务实现。

**Comment by xaboy** [comment]
@Joevin-Tang 可以通过全局配置`resetBtn.click`重写表单重置按钮的点击事件

**Comment by Joevin-Tang** [comment]
已经实现，多谢！
