### ISSUE TITLE
使用form的changeField改变field的值不会触发change事件

### ISSUE THREAD

**Issue by wzqiang1332** [xaboy/form-create#17]
使用form的changeField改变field的值不会触发change事件

**Comment by xaboy** [comment]
不会触发

**Comment by wzqiang1332** [comment]
如果需要触发怎么做，现在是通过脚本去赋值的都不会触发change事件，但是不可避免的会有一些是通过脚本赋值的

**Comment by xaboy** [comment]
我看下能不能实现

**Comment by xaboy** [comment]
不出意外,下个版本能实现双向数据绑定,是不是就不用change事件了
