### ISSUE TITLE
Element 设置Col比较小的时候不换行

### ISSUE THREAD

**Issue by pslxx** [xaboy/form-create#170]
2.0

element

2.13

所有的表单组件全部在一个Row里面
当设置Col比较小的时候，连续的组件会显示在一行

![image](https://user-images.githubusercontent.com/8417207/73880146-cbd23000-4898-11ea-8869-ef9a3ae10618.png)
![image](https://user-images.githubusercontent.com/8417207/73880162-d8568880-4898-11ea-87e1-7cd786138c26.png)

不知道我是参数设置的有问题，还是什么情况

比如：第一个input 占 4个span
第二个input 站 6个span
但是它们应该是换行的分别在不同的Row里面

**Comment by pslxx** [comment]
> 2.0
> 
> element
> 
> 2.13
> 
> 所有的表单组件全部在一个Row里面
> 当设置Col比较小的时候，连续的组件会显示在一行
> 
> ![image](https://user-images.githubusercontent.com/8417207/73880146-cbd23000-4898-11ea-8869-ef9a3ae10618.png)
> ![image](https://user-images.githubusercontent.com/8417207/73880162-d8568880-4898-11ea-87e1-7cd786138c26.png)
> 
> 不知道我是参数设置的有问题，还是什么情况
> 
> 比如：第一个input 占 4个span
> 第二个input 站 6个span
> 但是它们应该是换行的分别在不同的Row里面

刚看到了那个自定义布局的文档
http://www.form-create.com/v2/guide/layout.html

我后台用的是php-form-builder生成的表单，而且从源码里看了，也有group相关的支持，应该就是用来生成这个自定义布局的，但是我没有找到任何文档关于这块的说明~~~~
![image](https://user-images.githubusercontent.com/8417207/73882148-8adc1a80-489c-11ea-8ce9-7da7ce56b46a.png)

**Comment by pslxx** [comment]
php-form-builder里面 用group注解 + 自定义布局 解决了这个问题。。
不过在那个文档里竟然没有搜到任何跟group相关的内容，而且好像也只能用注解实现

**Comment by xaboy** [comment]
form-create 目前不支持分组,这块可以再优化一下.
目前可以通过自定义组件的方式实现分组
```js
{
    type:'el-row',
    children:[
         //组件规则...
    ]
}
```
那个文档里没有是因为忘记加了...

**Comment by pslxx** [comment]
其实php-form-builder的分组 返回的rule 其实也就是前端自定义布局的数据格式，
已经可以实现了相关功能。
