### ISSUE TITLE
$f.removeField方法调用之后，调用$f.field()发现还在

### ISSUE THREAD

**Issue by zoro-11** [xaboy/form-create#173]

**Comment by xaboy** [comment]
form-create 是那个版本?

**Comment by zoro-11** [comment]
1.0.6的，我的实际需求是更新这个字段的 type，从input更新到radio，没发现用更新的方法，后来我采用removeField后再添加字段，现在用this.$nexttick解决了，但是遇到新的问题，重复此操作几次之后，出现 “Error in render: "TypeError: Cannot read property 'required' of null"”这个错误。不知道什么原因。

**Comment by xaboy** [comment]
不建议直接修改 type,应该先拷贝一份组件的生成规则然后再进行修改

**Comment by xaboy** [comment]
2.5版本已优化
