### ISSUE TITLE
Types error

### ISSUE THREAD

**Issue by MrRumpel** [xaboy/form-create#175]
"@form-create/element-ui": "^1.0.6",

element-ui

"element-ui": "^2.13.0",

node_modules\@form-create\core\types\index.d.ts(40,22)

Parameter 'definition' implicitly has an 'any' type.ts(7006) 

Typescript 3.7.4

(id: string, definition): void; -> (id: string, definition: any): void;

**Comment by xaboy** [comment]
Thanks for your feedback, this issue will be fixed in the next version
