### ISSUE TITLE
界面加载速度比较慢

### ISSUE THREAD

**Issue by poweel** [xaboy/form-create#176]
form-create v1.6.6

 iviewUI

1.15.0

用你们的demo界面，直接保存成一个html的方式，用浏览器打开，速度比较慢，大概要3s

写一个html文件，js脚本都下载到本地，用浏览器打开

1s内能打开

**Comment by xaboy** [comment]
你确定能优化到1s 内打开吗

**Comment by poweel** [comment]
对于前端我是个新手，也不确定理论上能不能优化到1s。
还有一个问题咨询下，form-create支持预编译吗，就是我在编译时渲染出html页面，浏览器只取这个html页面，速度就比较快了。
