### ISSUE TITLE
upload 如何能全局挂上onSucces事件,和 添加headers

### ISSUE THREAD

**Issue by pslxx** [xaboy/form-create#178]
后台用的PHP-Form-Builder
用json返回使用upload组件的时候,我都需要在前台手动处理下
1.要添加token到headers里
2.添加onSuccess方法,用来处理图片上传结果
3.不能自定义上传的那个大小,在默写情况下,那个上传的框子和图片显示的太小了

**Comment by xaboy** [comment]
formBuilder 目前支持全局配置,支持的不是很好,下个版本可以再优化以下.
可以通过设置全局配置实现
