### ISSUE TITLE
每个表单类型可以添加一个提示信息

### ISSUE THREAD

**Issue by junjiem** [xaboy/form-create#179]
对于每个表单类型可以支持添加提示信息，如i帮助help-icon提示信息。

**Comment by xaboy** [comment]
可以通过 info 配置设置提示消息,[文档](http://www.form-create.com/v2/guide/rule.html#%E5%9F%BA%E7%A1%80%E8%A7%84%E5%88%99)

**Comment by junjiem** [comment]
这个只显示了图表 内容显示不出来  最新的form-create/element-ui版本
