### ISSUE TITLE
获取不到自第一按钮的点击事件

### ISSUE THREAD

**Issue by chenqiao123** [xaboy/form-create#180]
iview4.0

我自定义了一个按钮组件，目前捕获不到按钮组件的点击事件，在vue-devtools 的Events中可以看到点击事件，比如，在你的组件模式生成中， @xaboy-on-change="change", change: function (arguments) {
                    console.log("arguments=====",arguments);
                },,这里面的打印没有触发，打印不出来

希望可以触发change事件

**Comment by xaboy** [comment]
自定义组件定义 `field`时,事件名称是`${field}-${emit}`,没有定义 field 时事件名称是`${emitPrefix}-${emit}`

**Comment by chenqiao123** [comment]
![T KYES_G(BKQKWX6V {FSBA](https://user-images.githubusercontent.com/32537079/75653993-9ce18b00-5c99-11ea-8814-c8265f9dc375.png)
,我一直没有办法触发change事件

**Comment by xaboy** [comment]
我看看生成规则,[参考文档](http://www.form-create.com/v2/guide/rule.html#%E6%89%A9%E5%B1%95%E8%A7%84%E5%88%99)

**Comment by chenqiao123** [comment]
我自定义了一个按钮，rule=[{
        type:'i-button',
        htmlType: 'button',
        name: 'btn',
        "col": {
          "span": 4
        },
        props:{
          type:'default',
          field:'btn',
         
        },
        emit: ['on-click'],
       emitPrefix: 'del',
        children:['删除']
      }]
  <form-create :rule="rule"  @del-on-click="onClick"> </form-create>, 
 methods: {
                onClick:function(){
                    console.log("什么时候触发这里被调用，点击onClick"); 
                }
}
一直没有办法触发点击函数，是什么原因呢？

**Comment by xaboy** [comment]
按钮点击事件名称是`click`吧,不是`on-click`

**Comment by chenqiao123** [comment]
可以了，太感谢了，谢谢
