### ISSUE TITLE
form-create自定义控件name时出现大小写敏感问题

### ISSUE THREAD

**Issue by Gotham-Joker** [xaboy/form-create#181]
element-ui 2.8.2

form-create 1.0.7

在form-create.js的第2460行代码中，
if (global[parser.type] || global[parser.originType]) {
          pCol = global[parser.type].col || global[parser.originType].col || {};
}，
这段代码造成了我的表单渲染时报错。

自定义一个表单控件，并且控件的name命名中有大小写，例如： name:"SignInOut"，
然后在form-create中定义:  formCreate.component(SignInOut.name, SignInOut);
并且在form-create的global配置中定义: "SignInOut":{ props:{} },当后端接口返回的rule中包含该控件时，例如  [{type:"SignInOut",value:""}]，此时form-create.js执行到上面那个问题所在的代码行数时，
报错提示 'col' 属性是undefined。

我个人期望的结果是：既然控件的name在formCreate.component(SignInOut.name, SignInOut)时就已经传进去了，控件渲染时，就应该以传进来的name为标准优先判断。即应该先判断"SignInOut"这个originType而不是先判断"signinout"这个type

因此我认为，form-create.js的第2460行代码应该把originType和type的位置互换，也就是以下写法：
if (global[parser.type] || global[parser.originType]) {
          pCol = global[parser.originType].col || global[parser.type].col || {};
}

**Comment by xaboy** [comment]
感谢你的反馈,下个版本修复

**Comment by xaboy** [comment]
1.0.8版本已修复
