### ISSUE TITLE
type="group"点击添加时报错

### ISSUE THREAD

**Issue by junjiem** [xaboy/form-create#183]
for element-ui最新版本 
![image](https://user-images.githubusercontent.com/6293598/76074573-878c9980-5fd6-11ea-9444-af22cc2d6a00.png)

**Comment by xaboy** [comment]
这是 bug,下个版本修复.
暂时可以先通过`Vue.use(formCreate)`方法兼容

**Comment by junjiem** [comment]
行，那我试下全局注册from-create方式

**Comment by junjiem** [comment]
可以了，感谢

**Comment by junjiem** [comment]
但是这个group中很多其他问题，比如add和remove事件没有传入index，无法判断是添加和删除的是第几个

**Comment by junjiem** [comment]
我重新自定义了新的组件

**Comment by xaboy** [comment]
下个版本会传入 index

**Comment by xaboy** [comment]
1.0.8版本已支持
