### ISSUE TITLE
在select类型中，给on-query-change事件加上emitPrefix后，事件无效

### ISSUE THREAD

**Issue by CandiceCaiYu** [xaboy/form-create#184]
1.0.3

    "@form-create/element-ui": "^1.0.3",

"element-ui": "2.11.0",

在select类型中，给query-change事件加上emitPrefix后，事件无效

比如articleno-query-change

期望query-change加了emitPrefix以后还能生效

**Comment by xaboy** [comment]
配置`emit`了吗? 发一下生成规则我看看

**Comment by CandiceCaiYu** [comment]
![image](https://user-images.githubusercontent.com/19375834/76142571-eec74e00-60a9-11ea-8e43-d4e7111fd02c.png)
![image](https://user-images.githubusercontent.com/19375834/76142580-056da500-60aa-11ea-9d4e-098b687e0f12.png)
我刚刚看了一下，on-query-change是form-create2的功能.我的版本还是第一版

**Comment by CandiceCaiYu** [comment]
![image](https://user-images.githubusercontent.com/19375834/76142635-7f9e2980-60aa-11ea-99c4-bbddc04dc6cb.png)
所以实际上第一版不支持搜索词改变后触发事件？

**Comment by xaboy** [comment]
你用的就是 v2版本, 这个`articleno-query-change`需要写在`<form-create>`标签上 [文档](http://www.form-create.com/v2/guide/event.html#%E9%80%9A%E8%BF%87-emit-%E6%96%B9%E5%BC%8F%E7%BB%91%E5%AE%9A%E4%BA%8B%E4%BB%B6)

**Comment by CandiceCaiYu** [comment]
是写在标签上的。因为articleno-change是生效了的，但是articleno-query-change没有.....
![image](https://user-images.githubusercontent.com/19375834/76142732-43b79400-60ab-11ea-9517-83c7799b6c17.png)
![image](https://user-images.githubusercontent.com/19375834/76142740-4fa35600-60ab-11ea-9ab0-775aa383ab3b.png)

**Comment by xaboy** [comment]
我看了以下 select 组件的文档,没有`query-change`这个事件呀

**Comment by CandiceCaiYu** [comment]
呃，好像只有iview的select 支持query_change 。那如果我用的是elementui 得ui库，是不是没发监听搜索词的变化？

**Comment by xaboy** [comment]
这个`filter-method`属性应该可以

**Comment by CandiceCaiYu** [comment]
嗯嗯，好的，谢谢🙏
