### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by flamingolqx** [xaboy/form-create#186]
1.0.7

element-ui

2.13.0

typescript@3.8.3

Failed to compile with 2 errors  ：
node_modules@form-create\core\types\index.d.ts
395:9 'clearSubValidateState', which lacks return-type annotation, implicitly has an 'any' return type.
397:20 Parameter 'field' implicitly has an 'any' type.

npm run build:dev

**Comment by xaboy** [comment]
下个版本修复

**Comment by xaboy** [comment]
1.0.8版本已修复
