### ISSUE TITLE
目前学习网站在线示例都处于不可访问状态，不利于新手快速上手，望作者恢复，谢谢！

### ISSUE THREAD

**Issue by B08050313** [xaboy/form-create#188]

**Comment by B08050313** [comment]
希望作者可以恢复在线示例页面。

**Comment by xaboy** [comment]
我更新一下

**Comment by B08050313** [comment]
我刚刚发现了，是原网站域名发生了变化，链接前缀统一改成jsrun.pro即可。

**Comment by B08050313** [comment]
感谢作者的积极快速响应！

**Comment by xaboy** [comment]
已更新, 感谢支持😁

**Comment by B08050313** [comment]
&nbsp; &nbsp; 感谢作者及时准确地更新，我将会一如既往的支持您的工作。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xaboy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 中午12:08
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"秋の恋歌"<1099124830@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] 目前学习网站在线示例都处于不可访问状态，不利于新手快速上手，望作者恢复，谢谢！ (#188)





 
已更新, 感谢支持😁
