### ISSUE TITLE
生成的表单元素没有挂载到指定的标签

### ISSUE THREAD

**Issue by simpv** [xaboy/form-create#190]
1.0.8

iview

4.1.3

        <div id="taskForm"></div>

        const root = document.getElementById('taskForm')
        const { $f, mount, remove, destroy } = window.formCreate.init(
                rules,
                {
                  el: root,
                  submitBtn: false,
                  resetBtn: false,
                  inline:true,
                  onSubmit: function (formData) {
                    $f.btn.loading()
                  }
                })
        mount(root)
生成的表单没有挂载到id="taskForm"元素下。直接生成到body标签中去了，请问这是啥情况

**Comment by xaboy** [comment]
当 `el` 配置项不存在的时候就默认生成到 body 中了
