### ISSUE TITLE
control配置项问题

### ISSUE THREAD

**Issue by catundercar** [xaboy/form-create#191]
通过control配置项实现表单联动，需要使用iview版的formcreate,请问element ui版的有方法实现control的功能嘛

**Comment by xaboy** [comment]
所有ui版本都支持 control 配置项

**Comment by catundercar** [comment]
噢噢，谢谢回复。
请问使用了v-model会对这个功能有影响嘛

**Comment by xaboy** [comment]
什么意思? 在哪里使用了 v-model?

**Comment by catundercar** [comment]
`<script type="text/javascript" src="../static/axios.min.js"></script>`
`<script src="./md5/md5.js"></script>`
`<script src="./vue/js/vue.min.js"></script>`
`<script src="./vue-router@2.0.0/dist/vue-router.js"></script>`
  ` <script src="./element-ui@2.13.0/lib/index.js"></script>`
 ` <script src="./@form-create/element-ui@1.0.5/dist/form-create.min.js"></script>`
 ` <link rel="stylesheet" href="./element-ui@2.13.0/lib/theme-chalk/index.css">`


 


我导入了以上这些js，不知道为啥渲染不出来。以前没了解过vue，难受。。
在component里面用了这一句

`<el-scrollbar style="height: 90%">`
`<form-create ref="fc" v-model="fApi" :rule="rule" :option="option" @select-change="selectChange"></form-create>`
`</el-scrollbar>`

**Comment by catundercar** [comment]
大佬，知道了，版本问题。。。
谢谢
