### ISSUE TITLE
rule赋值过去, 浏览器整个卡死

### ISSUE THREAD

**Issue by LWJcoder** [xaboy/form-create#192]
最新cdn的

iview

使用17条rule进行初始化, 然后火狐浏览器卡死, 报错:
此页面的某个脚本可能正忙，或者已停止响应。您可以立即终止该脚本、在调试器中打开该脚本，或者继续等待该脚本完成。

脚本： http://localhost:8080/agent/public/plugin/vue.min.js:7

控制台报错:

Exception { message: "", result: 2147549183, name: "NS_ERROR_UNEXPECTED", filename: "", lineNumber: 0, columnNumber: 0, data: null, stack: "" } vue.min.js:7:26818
to</o() vue.min.js:7

Error: Script terminated by timeout at:
O/<.get@http://localhost:8080/agent/public/plugin/vue.min.js:6:2520
z@http://localhost:8080/agent/public/plugin/vue.min.js:6:5161
J@http://localhost:8080/agent/public/plugin/vue.min.js:6:5369
rt/n.prototype._render@http://localhost:8080/agent/public/plugin/vue.min.js:6:18435
ue/r@http://localhost:8080/agent/public/plugin/vue.min.js:6:9300
So.prototype.get@http://localhost:8080/agent/public/plugin/vue.min.js:7:30854
So.prototype.run@http://localhost:8080/agent/public/plugin/vue.min.js:7:31497
me@http://localhost:8080/agent/public/plugin/vue.min.js:6:10688
to</</<@http://localhost:8080/agent/public/plugin/vue.min.js:7:27254
e@http://localhost:8080/agent/public/plugin/vue.min.js:7:26713

**Comment by xaboy** [comment]
可以把生成规则给我, 我本地调试一下吗?

**Comment by LWJcoder** [comment]
我换了高版本的vue.js, 现在不会卡死了, 打扰了

**Comment by LWJcoder** [comment]
再问一个问题, 不知道validate的type是否有floag类型? 是否可以给出一个具体的文档?

**Comment by LWJcoder** [comment]
还有一个问题: {"type":"input","field":"creditAmount","title":"授信金额","value":"","validate":[{"message":"必填","required":true,"type":"float"}],"props":{"type":"text"}},
{"type":"input","field":"creditPeriodLimit","title":"授信期限","value":"","validate":[{"message":"必填","required":true,"type":"number"}],"props":{"type":"text"}}
这两个输入框输入了数字, 但是校验还是提示必填

**Comment by xaboy** [comment]
可能是验证规则的类型不对,因为`input`组件的值是 `string` 类型

**Comment by xaboy** [comment]
组件验证规则的说明文档 https://github.com/yiminghe/async-validator#type
