### ISSUE TITLE
扩展ts类型支持，目前Vue.use(formCreate)类型报错

### ISSUE THREAD

**Issue by Kntt** [xaboy/form-create#196]
版本号: 1.0.9

使用的 UI 框架: element-ui

UI 框架的版本:  2.13.0f

vue-cli4.0创建的ts项目，使用插件时，install的类型不对，建议修复一下

![image](https://user-images.githubusercontent.com/20291026/78865556-67864500-7a70-11ea-9a6a-646206aa9333.png)

- Vue.use(formCreate) 时会提示，类型不匹配

- 还有，没有对Vue原型扩展方法$formCreate，做类型的注释，在使用上不是很方便

期望的结果：
 - use时的类型修复
- 对原型方法的类型扩展

建议：
- install 方法使用 vue提供的 PluginFunction 描述类型
- 扩展vue的类型

**Comment by Kntt** [comment]
![image](https://user-images.githubusercontent.com/20291026/78868872-37da3b80-7a76-11ea-8fd8-f0bbc0a94987.png)
建议：FormConfig，按钮的类型描述， 扩展boolean的类型支持

**Comment by xaboy** [comment]
感谢反馈,下个版本会做优化.也欢迎直接 PR

**Comment by xaboy** [comment]
1.0.11版本已全部修复
