### ISSUE TITLE
组件嵌套中为什么不支持生成自定义组件呢？

### ISSUE THREAD

**Issue by TwinkleLeon** [xaboy/form-create#198]
@form-create/element-ui 1.0.9

element-ui

2.13.0

使用组件嵌套功能里面的rules字段配置表单的时候，不能解析自定义表单组件

**Comment by TwinkleLeon** [comment]
并且嵌套组件内无法监听到change事件

**Comment by xaboy** [comment]
可以发下生成规则吗

**Comment by TwinkleLeon** [comment]
> 可以发下生成规则吗
这个是改组件嵌套型表单的规则，其中XImgUpload是在注册在全局的Vue组件，单独使用是能渲染出来，但是用在组里面就不行了，然后就是数组嵌套的话，外层没有chnage事件，不太好处理联动的逻辑
{
          type:"group",
          title:"添加推荐商品：",
          subtype:'attrs',
          field:"recommend",
          value:[],
          props:{
              rules:[
                {
                  type: 'input',
                  field: 'picurl',
                  value: '', //表单值
                  title: '推荐商品图片链接：',
                  props: {
                  }
                },
                {
                  title: '',
                  type: 'XImgUpload',
                  field: 'picurls',
                  subtype: 'attrs', //attrs or styles
                  value: [], //表单值
                  props: {
                    mode: 'list'
                  }
                }
              ]
          },
          on:{
            change(){
               //无该事件响应，不太方便
            }
         }
      }

**Comment by xaboy** [comment]
XImgUpload这个组件内部有抛出 `change` 事件吗

**Comment by TwinkleLeon** [comment]
> XImgUpload这个组件内部有抛出 `change` 事件吗

内部是有的

**Comment by TwinkleLeon** [comment]
> > XImgUpload这个组件内部有抛出 `change` 事件吗
> 
> 内部是有的

但是目前XImgUpload这个组件无法解析出来，不过看其他同级的内置表单，是有change事件抛出的

**Comment by xaboy** [comment]
你看看组件内部执行了吗,我用`input`组件测试没有问题,`change`事件触发正常

**Comment by TwinkleLeon** [comment]
> 你看看组件内部执行了吗,我用`input`组件测试没有问题,`change`事件触发正常

嗯嗯 好
自定义组件无法解析那个能否帮忙看看~

**Comment by xaboy** [comment]
自定义组件无法解析? 那个?

**Comment by TwinkleLeon** [comment]
> 自定义组件无法解析? 那个?

如果自定义组件放在组件嵌套里面，这边在组中无法展示出来

**Comment by xaboy** [comment]
我这边测试也没有问题.. 你用 `el-button` 组件测试一下看看

**Comment by TwinkleLeon** [comment]
> 我这边测试也没有问题.. 你用 `el-button` 组件测试一下看看

em...我试试  难道是我姿势不对

**Comment by TwinkleLeon** [comment]
> 我这边测试也没有问题.. 你用 `el-button` 组件测试一下看看

这个无法解析，是因为无法识别驼峰的写法XImgUpload，必须用分隔符

**Comment by TwinkleLeon** [comment]
`{
          type:"group",
          title:"标签",
          field:" label",
          value:[],
          props:{
              min:1,
              max:5,
              rule:{
                  type:'input',
                  field:'input',
                  on:{
                    change(){
                      //这个能触发
                      console.log('in change')
                    }
                  }
              }
          },
          on:{
            change(){
              //这个不能触发
              console.log('out change')
            }
          }
      }`
但是我这边使用这种方式，在外层依旧监听不到数组中某个表单的change

**Comment by xaboy** [comment]
你说的是 group 组件的 change 事件吗

**Comment by TwinkleLeon** [comment]
> 你说的是 group 组件的 change 事件吗

是的

**Comment by TwinkleLeon** [comment]
> 你说的是 group 组件的 change 事件吗

我需要监听每个表单的改变然后做一个获取最新表达值 去回写到另外地方的操作
目前group组件中嵌套的表单虽然能响应change，但是change的回调中无法获取整个group的值

**Comment by xaboy** [comment]
目前 group 组件没有 change 事件,这个可以加

**Comment by TwinkleLeon** [comment]
> 目前 group 组件没有 change 事件,这个可以加

嗯嗯 ！谢谢耐心解答
