### ISSUE TITLE
control 在 elemnet-ui 下会多包裹一层 div

### ISSUE THREAD

**Issue by belier-cn** [xaboy/form-create#199]
1.0.9

element-ui

2.13.1

control 在 elemnet-ui 下会多包裹一层 div

![20200415122956.png](https://i.loli.net/2020/04/15/rHkjGzT5F3J8Ovd.png)

代码示例：https://jsrun.net/fAfKp/edit?v=2

**Comment by belier-cn** [comment]
行内表单的样式就会有问题

**Comment by xaboy** [comment]
下个版本修复

**Comment by xaboy** [comment]
1.0.10已修复
