### ISSUE TITLE
使用DatePick组件出现的问题

### ISSUE THREAD

**Issue by lzlu** [xaboy/form-create#200]
版本号：^1.0.9

使用的 UI 框架：element-ui

UI 框架的版本：2.13.1

使用DatePick的value-format属性，设置值是timestamp，通过$f.submit获取的值依然是yyyy-MM-dd，而不是timestamp

写了个小demo  https://codepen.io/Expelliarmus923/full/OJyMopO

返回timestamp

**Comment by xaboy** [comment]
可能是因为 form-create 内部对 datePciker 组件的值进行了转换. 通过 `type:ElDatePicker`生成内部就不会做处理了

**Comment by lzlu** [comment]
> 可能是因为 form-create 内部对 datePciker 组件的值进行了转换. 通过 `type:ElDatePicker`生成内部就不会做处理了

通过ref拿formData貌似可以了。
```
this.$refs.fc.formData
```

**Comment by xaboy** [comment]
这样操作不规范
