### ISSUE TITLE
级联

### ISSUE THREAD

**Issue by jiangxiaohua1234** [xaboy/form-create#202]
v2

element-ui

2.13.0

级联的changeOnSelect属性设置不生效，不起作用

从后台生成json渲染表单，级联属性不能单独选择某一项菜单，只能选择最后那一项属性

希望可以实现 选择任意一级选项

**Comment by xaboy** [comment]
通过`type:'el-cascader'`生成试试

**Comment by jiangxiaohua1234** [comment]
把type换成这个连选项都加载不出来了，我在那个实例用iview试了一下，发现是可以的，是不是因为element文档中的这是属性是props.checkStrictly = true，我后台渲染这个属性也不行，您看看是什么问题呢

**Comment by xaboy** [comment]
可以提供一个复现的在线示例吗

**Comment by jiangxiaohua1234** [comment]
将
props: {
    changeOnSelect: true
}
的属性 改为
props: {
    props: {
        checkStrictly: true
    }
}
就可以了 感谢大神
