### ISSUE TITLE
是否有添加手机号及验证组件的计划

### ISSUE THREAD

**Issue by TIMtechnology** [xaboy/form-create#203]

**Comment by xaboy** [comment]
支持验证规则,可以通过自定义验证或者正则实现对手机号验证 [组件验证](http://www.form-create.com/v2/guide/other/validation-rules.html)

**Comment by TIMtechnology** [comment]
验证码组件 不好意思 没写清楚

**Comment by xaboy** [comment]
这个也可以通过[自定义表单组件](http://www.form-create.com/v2/guide/custom-form-component.html)实现

**Comment by TIMtechnology** [comment]
好的 多谢 我去看看
