### ISSUE TITLE
upload组件 vue2.6x版本以上不兼容

### ISSUE THREAD

**Issue by 439740394** [xaboy/form-create#207]
最新版本

element-ui

upload 上传 设置value时 报错
`<transition-group> children must be keyed: <li>`

**Comment by xaboy** [comment]
我检查一下

**Comment by LoneKingCode** [comment]
更新了下也发现了，上传后
[Vue warn]: <transition-group> children must be keyed: <li>

**Comment by xaboy** [comment]
@LoneKingCode  我这边没有复现出来,这是 ui 库报的错还是 form-create 报的错?

**Comment by LoneKingCode** [comment]
> @LoneKingCode 我这边没有复现出来,这是 ui 库报的错还是 form-create 报的错?

 "vue": "^2.6.11",  "@form-create/element-ui": "^1.0.12",
vue的错， 和1楼的错误一样，在上传文件结束的事件onSuccess执行完之后，提示，
但是我看你代码那每个组件也都设置了unique key了

**Comment by LoneKingCode** [comment]
![image](https://user-images.githubusercontent.com/11244921/80981205-3aa13400-8e5c-11ea-8e5f-2bbb086410e7.png)

**Comment by xaboy** [comment]
可能是 ElementUI 报的错

**Comment by LoneKingCode** [comment]
> 可能是 ElementUI 报的错

今天闲了看了下element ui 的upload组件代码，发现了问题所在。
file的uid问题， element ui 的upload组件是以file.uid为li标签的key的，而作者对于filelist转换时，只根据url提取了文件名，以及url，缺少一个uid字段，导致element ui报错。
下面这两张是单独修改element ui的upload组件后就正常，设置index为key
![111](https://user-images.githubusercontent.com/11244921/88907272-0686b500-d28b-11ea-9222-08fd8c08a75e.png)
![222](https://user-images.githubusercontent.com/11244921/88907285-0981a580-d28b-11ea-9de2-003e28be53f4.png)
作者这应该加个字段uid，然后就可以工作了
![333](https://user-images.githubusercontent.com/11244921/88907293-0ab2d280-d28b-11ea-9ab1-88a31e7aec06.png)

希望作者及时更新下。

**Comment by xaboy** [comment]
感谢反馈,下个版本修复 @LoneKingCode

**Comment by xaboy** [comment]
1.0.18版本已修复
