### ISSUE TITLE
function parseJson(json) 解析失败

### ISSUE THREAD

**Issue by wuzhiping** [xaboy/form-create#213]
当json的一些文本内容包含“ function ”关键字的时候，
会导致错误 ，它被错误的识别为function
       v.indexOf('function') > -1

**Comment by xaboy** [comment]
感谢反馈, 这是个bug. 
处理这个问题可能会导致之前通过 toJson 方法生成的数据无法使用, 这块我再想办法优化一下

**Comment by xaboy** [comment]
1.0.15版本已修复,使用`parseJson(json, true)`解析即可,但是可能需要重新生成一下 json
