### ISSUE TITLE
动态生成tabs时会出现tab-bar的子节点数量与tab-content的子节点数量不匹配

### ISSUE THREAD

**Issue by jankey415** [xaboy/form-create#218]
1.0.14

ivew

ivew4.0.2

动态生成tabs时rule中有7个tab，根据条件渲染，tab-bar中是6个，但是tab-content会生成7个

```
<template>
  <Tabs :value="currentValue"
        :v-model="currentValue"
        :type="type"
        @on-click="handleClick"
        @on-tab-remove="handleRemove">
    <slot></slot>
  </Tabs>
</template>
```
这是tabs组件的自定义模板

```
<template>
  <TabPane v-if="visible"
           class="tabPane"
           :name="label?label:'标签'"
           :label="label?label:'标签'"
           :icon="icon"
           :disabled="disabled"
           :closable="closable"
           :tab="tab"
           :index="index">
    <div v-if="visible" class="scroll">
      <slot v-if="visible"></slot>
    </div>
  </TabPane>
</template> 
```
这是tabpane的自定义模板
7个tab，有一个tab的visible属性是false，理论上应该生成6个标签和对应的标签区域，实际结果是生成6个标签，但是有7个tab-content区域，其中一个生成的是`<div class="ivu-col ivu-col-span-24"><div class="ivu-form-item"><!----> <div class="ivu-form-item-content" style="margin-left: 0px;"><!----> <!----></div></div></div>` 占了一个空白区域，导致这个应该隐藏的标签后的标签都不能切换出来

tab-bars的子节点数量与tab-content数量保持一致

**Comment by jankey415** [comment]
```
<template>
  <Tabs :value="currentValue"
        :v-model="currentValue"
        :type="type"
        @on-click="handleClick"
        @on-tab-remove="handleRemove">
    <slot></slot>
  </Tabs>
</template>
```
这是tabs组件的自定义模板
```
<template>
  <TabPane v-if="visible"
           class="tabPane"
           :name="label?label:'标签'"
           :label="label?label:'标签'"
           :icon="icon"
           :disabled="disabled"
           :closable="closable"
           :tab="tab"
           :index="index">
    <div v-if="visible" class="scroll">
      <slot v-if="visible"></slot>
    </div>
  </TabPane>
</template> 
```
这是tabpane的自定义模板
7个tab，有一个tab的visible属性是false，理论上应该生成6个标签和对应的标签区域，实际结果是生成6个标签，但是有7个tab-content区域，其中一个生成的是`<div class="ivu-col ivu-col-span-24"><div class="ivu-form-item"><!----> <div class="ivu-form-item-content" style="margin-left: 0px;"><!----> <!----></div></div></div>`  占了一个空白区域，导致这个应该隐藏的标签后的标签都不能切换出来

**Comment by xaboy** [comment]
可以发下生成规则吗

**Comment by jankey415** [comment]
> 可以发下生成规则吗
规则很长，我截取了tabs这个组件的部分内容
`{
	"native": false,
	"props": {
		"type": "line",
		"closable": false,
		"animated": false,
		"capture-focus": false,
		"tabLayoutStyle": 0,
		"tabOrientation": 0,
		"relaEntityId": 0,
		"entityId": 0,
		"relaEntityColId": 0,
		"mapEntityColId": 0,
		"entityColId": 0,
		"refEntityColId": 0,
		"controlId": 2728927,
		"name": "JeezTabControl1",
		"disabled": false,
		"isRequired": false,
		"baseDataType": 0,
		"relationalQuery": false,
		"window_id": 271,
		"pageType": "window"
	},
	"type": "i-tabs",
	"field": "2728927",
	"children": [
		{
			"props": {
				"label": "常规费用项目",
				"closable": false,
				"tab": "JeezTabPage1",
				"index": 0,
				"boderStyle": 3,
				"visible": true,
				"font": 0,
				"relaEntityId": 0,
				"entityId": 0,
				"relaEntityColId": 0,
				"mapEntityColId": 0,
				"entityColId": 0,
				"refEntityColId": 0,
				"controlId": 2728928,
				"disabled": false,
				"isRequired": false,
				"baseDataType": 0,
				"relationalQuery": false,
				"window_id": 271,
				"pageType": "window"
			},
			"type": "i-tab-pane",
			"field": "2728928",
			"children": [
				{
					"native": false,
					"props": {
						"data": [
							{}
						],
						"columns": [
							{
								"title": "常规费用",
								"key": "TollID",
								"width": 80,
								"minWidth": 0,
								"maxWidth": 0,
								"align": "left",
								"fixed": "left",
								"ellipsis": false,
								"tooltip": false,
								"sortable": false,
								"filterMultiple": true,
								"editable": true,
								"editType": "auto",
								"filterable": false,
								"showModal": true,
								"gridColId": 4509772,
								"hide": false,
								"isUserSetVisibleProp": false,
								"columnStyle": 0,
								"colDataType": 3,
								"allowRowFiltering": 0,
								"currencyChar": "",
								"decimalDigits": 0,
								"digitLength": 0,
								"maxValue": 0,
								"minValue": 0,
								"editMode": 0,
								"formatString": "",
								"promptChar": " ",
								"showRed": false,
								"defaultValue": "",
								"entityId": 607,
								"entityColId": 9877,
								"refEntityColId": 0,
								"relaEntityId": 0,
								"relaEntityColId": 0,
								"mapEntityColId": 0,
								"formula": "",
								"serverFormula": "",
								"isServer": false,
								"isMergedCell": false,
								"statFunc": 0,
								"relationalQuery": false
							}
						],
						"window_id": 271,
						"pageType": "window",
						"pType": "window",
						"selectIndex": -1,
						"dataChangeFlag": false
					},
					"type": "Tables",
					"field": "4208763",
					"tabIndex": 0,
					"lifeline": "0&1&10&0&0&0&0&",
					"on": {}
				}
			],
			"tabIndex": 0,
			"lifeline": "0&1&10&0&0&0&"
		},
		{
			"props": {
				"label": "抄表费用项目",
				"closable": false,
				"tab": "JeezTabPage2",
				"index": 0,
				"boderStyle": 3,
				"visible": true,
				"font": 0,
				"relaEntityId": 0,
				"entityId": 0,
				"relaEntityColId": 0,
				"mapEntityColId": 0,
				"entityColId": 0,
				"refEntityColId": 0,
				"controlId": 2728929,
				"disabled": false,
				"isRequired": false,
				"baseDataType": 0,
				"relationalQuery": false,
				"window_id": 271,
				"pageType": "window"
			},
			"type": "i-tab-pane",
			"field": "2728929",
			"children": [
				{
					"native": false,
					"props": {
						"data": [
							{}
						],
						"columns": [
							{
								"title": "抄表费用",
								"key": "TollID",
								"width": 80,
								"minWidth": 0,
								"maxWidth": 0,
								"align": "left",
								"fixed": "left",
								"ellipsis": false,
								"tooltip": false,
								"sortable": false,
								"filterMultiple": true,
								"editable": true,
								"editType": "auto",
								"filterable": false,
								"showModal": true,
								"gridColId": 4509792,
								"hide": false,
								"isUserSetVisibleProp": false,
								"columnStyle": 0,
								"colDataType": 3,
								"allowRowFiltering": 0,
								"currencyChar": "",
								"decimalDigits": 0,
								"digitLength": 0,
								"maxValue": 0,
								"minValue": 0,
								"editMode": 0,
								"formatString": "",
								"promptChar": " ",
								"showRed": false,
								"defaultValue": "",
								"entityId": 608,
								"entityColId": 9881,
								"refEntityColId": 0,
								"relaEntityId": 0,
								"relaEntityColId": 0,
								"mapEntityColId": 0,
								"formula": "",
								"serverFormula": "",
								"isServer": false,
								"isMergedCell": false,
								"statFunc": 0,
								"relationalQuery": false
							}
						],

						"window_id": 271,
						"pageType": "window",
						"pType": "window",
						"selectIndex": -1,
						"dataChangeFlag": false
					},
					"type": "Tables",
					"field": "4208764",
					"tabIndex": 0,
					"lifeline": "0&1&10&0&0&1&0&",
					"on": {}
				}
			],
			"tabIndex": 1,
			"lifeline": "0&1&10&0&0&1&"
		},
		{
			"props": {
				"label": "车位费用项目",
				"closable": false,
				"tab": "JeezTabPage3",
				"index": 0,
				"boderStyle": 3,
				"visible": false,
				"font": 0,
				"relaEntityId": 0,
				"entityId": 0,
				"relaEntityColId": 0,
				"mapEntityColId": 0,
				"entityColId": 0,
				"refEntityColId": 0,
				"controlId": 2728930,
				"disabled": false,
				"isRequired": false,
				"baseDataType": 0,
				"relationalQuery": false,
				"window_id": 271,
				"pageType": "window"
			},
			"type": "i-tab-pane",
			"field": "2728930",
			"children": [
				{
					"native": false,
					"props": {
						"data": [
							{}
						],
						"columns": [
							{
								"title": "车位费用",
								"key": "TollID",
								"width": 80,
								"minWidth": 0,
								"maxWidth": 0,
								"align": "left",
								"fixed": "left",
								"ellipsis": false,
								"tooltip": false,
								"sortable": false,
								"filterMultiple": true,
								"editable": true,
								"editType": "auto",
								"filterable": false,
								"showModal": true,
								"gridColId": 4509812,
								"hide": false,
								"isUserSetVisibleProp": false,
								"columnStyle": 0,
								"colDataType": 3,
								"allowRowFiltering": 0,
								"currencyChar": "",
								"decimalDigits": 0,
								"digitLength": 0,
								"maxValue": 0,
								"minValue": 0,
								"editMode": 0,
								"formatString": "",
								"promptChar": " ",
								"showRed": false,
								"defaultValue": "",
								"entityId": 609,
								"entityColId": 9885,
								"refEntityColId": 0,
								"relaEntityId": 0,
								"relaEntityColId": 0,
								"mapEntityColId": 0,
								"formula": "",
								"serverFormula": "",
								"isServer": false,
								"isMergedCell": false,
								"statFunc": 0,
								"relationalQuery": false
							}	
						],
						"window_id": 271,
						"pageType": "window",
						"pType": "window",
						"selectIndex": -1,
						"dataChangeFlag": false
					},
					"type": "Tables",
					"field": "4208765",
					"tabIndex": 0,
					"lifeline": "0&1&10&0&0&2&0&",
					"on": {}
				}
			],
			"tabIndex": 2,
			"lifeline": "0&1&10&0&0&2&"
		},
		{
			"props": {
				"label": "临时费用项目",
				"closable": false,
				"tab": "JeezTabPage4",
				"index": 0,
				"boderStyle": 3,
				"visible": true,
				"font": 0,
				"relaEntityId": 0,
				"entityId": 0,
				"relaEntityColId": 0,
				"mapEntityColId": 0,
				"entityColId": 0,
				"refEntityColId": 0,
				"controlId": 2728931,
				"disabled": false,
				"isRequired": false,
				"baseDataType": 0,
				"relationalQuery": false,
				"window_id": 271,
				"pageType": "window"
			},
			"type": "i-tab-pane",
			"field": "2728931",
			"children": [
				{
					"native": false,
					"props": {
						"data": [
							{}
						],
						"columns": [
							{
								"title": "临时费用",
								"key": "TollID",
								"width": 80,
								"minWidth": 0,
								"maxWidth": 0,
								"align": "left",
								"fixed": "left",
								"ellipsis": false,
								"tooltip": false,
								"sortable": false,
								"filterMultiple": true,
								"editable": true,
								"editType": "auto",
								"filterable": false,
								"showModal": true,
								"gridColId": 4509830,
								"hide": false,
								"isUserSetVisibleProp": false,
								"columnStyle": 0,
								"colDataType": 3,
								"allowRowFiltering": 0,
								"currencyChar": "",
								"decimalDigits": 0,
								"digitLength": 0,
								"maxValue": 0,
								"minValue": 0,
								"editMode": 0,
								"formatString": "",
								"promptChar": " ",
								"showRed": false,
								"defaultValue": "",
								"entityId": 610,
								"entityColId": 9889,
								"refEntityColId": 0,
								"relaEntityId": 0,
								"relaEntityColId": 0,
								"mapEntityColId": 0,
								"formula": "",
								"serverFormula": "",
								"isServer": false,
								"isMergedCell": false,
								"statFunc": 0,
								"relationalQuery": false
							}
						],
						"window_id": 271,
						"pageType": "window",
						"pType": "window",
						"selectIndex": -1,
						"dataChangeFlag": false
					},
					"type": "Tables",
					"field": "4208766",
					"tabIndex": 0,
					"lifeline": "0&1&10&0&0&3&0&",
					"on": {}
				}
			],
			"tabIndex": 3,
			"lifeline": "0&1&10&0&0&3&"
		},
		{
			"props": {
				"label": "支付金额",
				"closable": false,
				"tab": "JeezTabPage5",
				"index": 0,
				"boderStyle": 3,
				"visible": true,
				"font": 0,
				"relaEntityId": 0,
				"entityId": 0,
				"relaEntityColId": 0,
				"mapEntityColId": 0,
				"entityColId": 0,
				"refEntityColId": 0,
				"controlId": 2728932,
				"disabled": false,
				"isRequired": false,
				"baseDataType": 0,
				"relationalQuery": false,
				"window_id": 271,
				"pageType": "window"
			},
			"type": "i-tab-pane",
			"field": "2728932",
			"children": [
				{
					"native": false,
					"props": {
						"data": [
							{}
						],
						"columns": [
							{
								"title": "收费项目",
								"key": "TollItem",
								"width": 114,
								"minWidth": 0,
								"maxWidth": 0,
								"align": "left",
								"ellipsis": false,
								"tooltip": false,
								"sortable": false,
								"filterMultiple": true,
								"editable": false,
								"editType": "input",
								"filterable": false,
								"showModal": true,
								"gridColId": 4509845,
								"hide": false,
								"isUserSetVisibleProp": false,
								"columnStyle": 0,
								"colDataType": 3,
								"allowRowFiltering": 0,
								"currencyChar": "",
								"decimalDigits": 0,
								"digitLength": 0,
								"maxValue": 0,
								"minValue": 0,
								"editMode": 3,
								"formatString": "",
								"promptChar": " ",
								"showRed": false,
								"defaultValue": "",
								"entityId": 0,
								"entityColId": 0,
								"refEntityColId": 0,
								"relaEntityId": 0,
								"relaEntityColId": 0,
								"mapEntityColId": 0,
								"formula": "",
								"serverFormula": "",
								"isServer": false,
								"isMergedCell": false,
								"statFunc": 0,
								"relationalQuery": false
							}
						],
						"window_id": 271,
						"pageType": "window",
						"pType": "window",
						"selectIndex": -1,
						"dataChangeFlag": false
					},
					"type": "Tables",
					"field": "4208779",
					"tabIndex": 0,
					"lifeline": "0&1&10&0&0&4&0&",
					"on": {}
				}
			],
			"tabIndex": 4,
			"lifeline": "0&1&10&0&0&4&"
		},
		{
			"props": {
				"label": "新增预收款",
				"closable": false,
				"tab": "JeezTabPage6",
				"index": 0,
				"boderStyle": 3,
				"visible": true,
				"font": 0,
				"relaEntityId": 0,
				"entityId": 0,
				"relaEntityColId": 0,
				"mapEntityColId": 0,
				"entityColId": 0,
				"refEntityColId": 0,
				"controlId": 2728933,
				"disabled": false,
				"isRequired": false,
				"baseDataType": 0,
				"relationalQuery": false,
				"window_id": 271,
				"pageType": "window"
			},
			"type": "i-tab-pane",
			"field": "2728933",
			"children": [
				{
					"native": false,
					"props": {
						"data": [
							{}
						],
						"columns": [
							{
								"title": "收费项目",
								"key": "TollItem",
								"width": 200,
								"minWidth": 0,
								"maxWidth": 0,
								"align": "left",
								"ellipsis": false,
								"tooltip": false,
								"sortable": false,
								"filterMultiple": true,
								"editable": true,
								"editType": "selectlist",
								"filterable": false,
								"showModal": true,
								"gridColId": 4509848,
								"hide": false,
								"isUserSetVisibleProp": false,
								"columnStyle": 0,
								"colDataType": 3,
								"allowRowFiltering": 0,
								"currencyChar": "",
								"decimalDigits": 0,
								"digitLength": 0,
								"maxValue": 0,
								"minValue": 0,
								"editMode": 0,
								"formatString": "",
								"promptChar": " ",
								"showRed": false,
								"defaultValue": "",
								"entityId": 0,
								"entityColId": 0,
								"refEntityColId": 0,
								"relaEntityId": 0,
								"relaEntityColId": 0,
								"mapEntityColId": 0,
								"formula": "",
								"serverFormula": "",
								"isServer": false,
								"isMergedCell": false,
								"statFunc": 0,
								"relationalQuery": false
							}	
						],
						"window_id": 271,
						"pageType": "window",
						"pType": "window",
						"selectIndex": -1,
						"dataChangeFlag": false
					},
					"type": "Tables",
					"field": "4208780",
					"tabIndex": 0,
					"lifeline": "0&1&10&0&0&5&0&",
					"on": {}
				}
			],
			"tabIndex": 5,
			"lifeline": "0&1&10&0&0&5&"
		},
		{
			"props": {
				"label": "退款",
				"closable": false,
				"tab": "JeezTabPage7",
				"index": 0,
				"boderStyle": 3,
				"visible": true,
				"font": 0,
				"relaEntityId": 0,
				"entityId": 0,
				"relaEntityColId": 0,
				"mapEntityColId": 0,
				"entityColId": 0,
				"refEntityColId": 0,
				"controlId": 2728934,
				"disabled": false,
				"isRequired": false,
				"baseDataType": 0,
				"relationalQuery": false,
				"window_id": 271,
				"pageType": "window"
			},
			"type": "i-tab-pane",
			"field": "2728934",
			"children": [
				{
					"native": false,
					"props": {
						"data": [
							{}
						],
						"columns": [
							{
								"title": "费用单",
								"key": "BillNo",
								"width": 80,
								"minWidth": 0,
								"maxWidth": 0,
								"align": "left",
								"ellipsis": false,
								"tooltip": false,
								"sortable": false,
								"filterMultiple": true,
								"editable": false,
								"editType": "input",
								"filterable": false,
								"showModal": true,
								"gridColId": 4509860,
								"hide": false,
								"isUserSetVisibleProp": false,
								"columnStyle": 0,
								"colDataType": 3,
								"allowRowFiltering": 0,
								"currencyChar": "",
								"decimalDigits": 0,
								"digitLength": 0,
								"maxValue": 0,
								"minValue": 0,
								"editMode": 3,
								"formatString": "",
								"promptChar": " ",
								"showRed": false,
								"defaultValue": "",
								"entityId": 0,
								"entityColId": 0,
								"refEntityColId": 0,
								"relaEntityId": 0,
								"relaEntityColId": 0,
								"mapEntityColId": 0,
								"formula": "",
								"serverFormula": "",
								"isServer": false,
								"isMergedCell": false,
								"statFunc": 0,
								"relationalQuery": false
							}
						],
						"window_id": 271,
						"pageType": "window",
						"pType": "window",
						"selectIndex": -1,
						"dataChangeFlag": false
					},
					"type": "Tables",
					"field": "4208784",
					"tabIndex": 0,
					"lifeline": "0&1&10&0&0&6&0&",
					"on": {}
				}
			],
			"tabIndex": 6,
			"lifeline": "0&1&10&0&0&6&"
		}
	]
}`

**Comment by xaboy** [comment]
我这边复现不出来

**Comment by jankey415** [comment]
> 我这边复现不出来

你这边生成有几个tab，有没有根据我前面`<template>
  <TabPane **v-if="visible"**
           class="tabPane"
           :name="label?label:'标签'"
           :label="label?label:'标签'"
           :icon="icon"
           :disabled="disabled"
           :closable="closable"
           :tab="tab"
           :index="index">
    <div class="scroll">
      <slot></slot>
    </div>
  </TabPane>
</template> ` `根据visible这个条件去渲染，规则里有七个页签，根据条件渲染时，第三个（visible=false）不会渲染，实际情况确认是生成了6个tab，但是tab-content区域有7个，其中那个条件为false的会成<div class="ivu-col ivu-col-span-24"><div class="ivu-form-item"> <div class="ivu-form-item-content" style="margin-left: 0px;"> </div></div></div>，里面的子组件table确实也没有渲染，但是因为生成上面的这个空白的div，导致第二个页签以后的页签点击时不会显示在当前可视区域`

**Comment by xaboy** [comment]
你能不能写一个在线的 demo
