### ISSUE TITLE
升级到 v1.0.15 版本页面卡死

### ISSUE THREAD

**Issue by ZengTianShengZ** [xaboy/form-create#219]
升级版本为了解决 [数组组件在删除后无法进行校验 ](https://github.com/xaboy/form-create/issues/216) 这个问题，但升级后动态创建表单出现卡死现象，上个版本  `^1.0.9` 虽然也报错 disabled expected boolean，但不会卡死

```
    "@form-create/element-ui": "^1.0.15",
```

![image](https://user-images.githubusercontent.com/15622519/83507660-6ff07e80-a4fb-11ea-8f21-663c960d44c1.png)

**Comment by xaboy** [comment]
可以发下生成规则吗，明天我检查一下


------------------ 原始邮件 ------------------
发件人: 曾田生 <notifications@github.com&gt;
发送时间: 2020年6月2日 18:09
收件人: xaboy/form-create <form-create@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xaboy/form-create] 升级到 v1.0.15 版本页面卡死 (#219)





 
升级版本为了解决 数组组件在删除后无法进行校验  这个问题，但升级后动态创建表单出现卡死现象，上个版本  ^1.0.9 虽然也报错 disabled expected booleand，但不会卡死
     "@form-create/element-ui": "^1.0.15",

**Comment by ZengTianShengZ** [comment]
我单独用这份规则去渲染是没问题的，我先自行排查下哈，估计我这边的问题
