### ISSUE TITLE
实例方法append添加进去的值在提交的是验证有问题

### ISSUE THREAD

**Issue by djkloop** [xaboy/form-create#22]
![image](https://user-images.githubusercontent.com/21050914/43635800-c38412a0-9742-11e8-8dc2-7176adf42763.png)
点击提交的时候
![image](https://user-images.githubusercontent.com/21050914/43635822-dbac1c7e-9742-11e8-871e-b0a525d122ac.png)

**Comment by djkloop** [comment]
我自己fock了一份改了下代码里面的函数名 但是其他代码都没动 ...

**Comment by xaboy** [comment]
稍等 我看一下

**Comment by xaboy** [comment]
`{required:true,trigger:'blur',type:Number}`这样就可以了,默认sring类型,数组的话就是`type:Array`

**Comment by xaboy** [comment]
没明白, 是控制生成出来表单的样式还是什么

**Comment by djkloop** [comment]
@xaboy emm...就是假如生成每一个input我需要给这个input添加一些独立的样式，或者某几个input是在一行其他的则在下一行这种...
这是百度找的图片
就是类似这种有一些特定样式结构的
![image](https://user-images.githubusercontent.com/21050914/43638673-4e466272-974c-11e8-898f-d92c3af86f41.png)

**Comment by xaboy** [comment]
目前不支持这个,不过应该可以实现

**Comment by djkloop** [comment]
@xaboy 如果要加入row 和col这个是不是感觉就能实现这个功能了然后在规则里面加入一个span参数貌似就可以

**Comment by xaboy** [comment]
嗯 但是还要考虑怎么分组

**Comment by xaboy** [comment]
你有什么好的建议吗,怎么指定一个row里面放哪几个规则

**Comment by djkloop** [comment]
@xaboy 一个row里面有几个col是根据iview的栅格里面的规定的24格 然后根据span决定有几个 我大概是这样想的。在rules里面增加一个span属性或者叫什么都行对应的是iview的Col上的span, 然后应该就能达到目的...但是我昨天看了您的源码....我没想到如何用动态创建的col包裹动态创建出来的input组件..这步还在思考...

**Comment by xaboy** [comment]
我想到两个方法
麻烦的就是增加一个row的元素，在这个规则里面再设置这个row里面有哪些元素
简单的是最外层套一个row，给每个元素增加col属性，让元素自动排列。
我准备用简单的方法😁

**Comment by djkloop** [comment]
@xaboy 是的 col如果超过24也会自己到下一行去

**Comment by djkloop** [comment]
@xaboy 我觉得您可以建立个什么QQ群之类的这样可以实时反馈是个挺好的方法...~

**Comment by xaboy** [comment]
好的,听取你的建议创建了QQ群
