### ISSUE TITLE
[Ant-Design-Vue]select设置props.placeholder有问题

### ISSUE THREAD

**Issue by ZMK2017** [xaboy/form-create#221]
## 版本号 (version)
1.0.15

## 使用的 UI 框架 (element-ui / iview)
ant-design-vue

## UI 框架的版本 (UI version)
1.6.2

## 问题描述 (Issue) 
当`rule[i].type === 'select'`时，设置rule[i].field绑定字段之后，无法正常设置placeholder

## 复现步骤/生成规则 (Duplicate steps/generate rules) 
```html
  <form-create v-model="model" :rule="rule" ></form-create>
```
```html
export default {
  data () {
    return {
      model: {},
      rule: [
        {
          type: 'select',
          // field: 'selectField',
          props: {
            placeholder: '请选择'
          }
        }
      ]
    };
  },
```

## 期望的结果 (Desired outcome) 
placeholder正常显示

## 建议 (Advice) 
增加props.allowClear = true后，点击清除按钮发现placeholder正常显示了，怀疑是设置组件设置默认值时导致问题出现

**Comment by xaboy** [comment]
感谢反馈 我刚刚测试了下确实有问题,下个版本修复

**Comment by xaboy** [comment]
1.0.16版本已修复
