### ISSUE TITLE
Group组件remove事件修改值UI不更新

### ISSUE THREAD

**Issue by kangyifan** [xaboy/form-create#222]
1.0.15

element-ui 

2.13.2

在group的remove事件中修改其他项的值UI不会被更新（获取group的value已经变化了）

删除group的一个条目，修改其他条目的值

ui跟组件value一致

**Comment by xaboy** [comment]
这是个 bug,下个版本修复

**Comment by Tildenwy** [comment]
Group

> 这是个 bug,下个版本修复

请问，Group 中有下拉框，使用setValue()赋值，但是下拉框并不会渲染 ，页面直接显示的下拉的value 而不是相应的label，并且下拉选择内容失效，是相同的问题吗

**Comment by xaboy** [comment]
直接显示 value 可能是因为在 option 里没有匹配到,
要注意的是value需要和 option.value 全等

**Comment by Tildenwy** [comment]
> 直接显示 value 可能是因为在 option 里没有匹配到,
> 要注意的是value需要和 option.value 全等

使用elementUI 的下拉，采用远程查询方式的更新options，UI没有反应，但是重新添加的时候，却可以显示刚刚下拉查询的结果。请问我要如何才能更新group中下拉options。页面才能实时的改变下拉内容呢

**Comment by xaboy** [comment]
1.0.16版本已修复 @kangyifan

**Comment by xaboy** [comment]
使用 `Vue.set` 方法赋值试试 @Tildenwy
