### ISSUE TITLE
也许 能否提供根据当前生成的表单 提供生成源码的操作

### ISSUE THREAD

**Issue by sc1994** [xaboy/form-create#223]
能否提供根据当前生成的表单 提供生成源码的操作
比如 
我用`json`(或者其他方式创建一个表单), 但是我想在现有的基础上做些改动(虽然当前功能已经很强大了, 但是产品就是想要), 如: 给title换个颜色(别说用jquery), 或者加个行样式. 
如果能提供源码导出的功能, 大概我只需要导出源码, 稍加修改就能达到目的, 尽量小的学习成本.

只是建议, 如果因为我对该库的理解不够深刻, 曲解了该库的用途. 还请见谅, 
如有更好的去处, 还望指教.

如果太麻烦了, 直接忽视吧~~~

😊

**Comment by xaboy** [comment]
目前不支持直接导出表单源码,后面可以考虑,
title 换颜色目前也不支持,不过下个版本应该可以增加这个功能
增加行样式可以通过自定义组件实现

**Comment by sc1994** [comment]
多谢解答
❤
