### ISSUE TITLE
如何给element Cascader 加ref 

### ISSUE THREAD

**Issue by 0703gaoxiaobo** [xaboy/form-create#225]

**Comment by xaboy** [comment]
可以通过`$f.el`方法获取

**Comment by 0703gaoxiaobo** [comment]
{
                    type: "cascader",
                    title: "区域",
                    field:  "areaId",
                    props: {
                        expandTrigger: 'hover',
                        clearable:true,
                        props: {
                            label: "name",
                            value: "id",
                            checkStrictly: true,
                            ref:"myCascader",
                        },
                    },
                },
这样添加 ref 好像也获取不到啊

**Comment by 0703gaoxiaobo** [comment]
> 可以通过`$f.el`方法获取

{
type: "cascader",
title: "区域",
field: "areaId",
props: {
expandTrigger: 'hover',
clearable:true,
props: {
label: "name",
value: "id",
checkStrictly: true,
ref:"myCascader",
},
},
},
这样添加 ref 好像也获取不到啊

**Comment by xaboy** [comment]
表单生成后通过$f.el('areaId') 获取

**Comment by 0703gaoxiaobo** [comment]
> 表单生成后通过$f.el('areaId') 获取



> 表单生成后通过$f.el('areaId') 获取

请问，是不是我 ref写的位置是不是不对啊


> 表单生成后通过$f.el('areaId') 获取

 {
                    type: "cascader",
                    title: "区域",
                    field: "areaId",
                    props: {
                        expandTrigger: 'hover',
                        clearable:true,
                        props: {
                            label: "name",
                            value: "id",
                            checkStrictly: true,
                            ref:"myCascader",
                        },
                    },
                    on:{
                        change(e){
                            console.log(e)
                                $f.el('areaId').dropDownVisible = false;
                        }
                    }
这样写好像也没有效果

**Comment by xaboy** [comment]
看起来没什么问题,有没有报错

**Comment by 0703gaoxiaobo** [comment]
> 看起来没什么问题,有没有报错

![image](https://user-images.githubusercontent.com/49136063/86333073-ff658a80-bc7d-11ea-9321-b01db30aef6a.png)

**Comment by xaboy** [comment]
看一下文档,如何获取$f
