### ISSUE TITLE
control修改某个控件的属性

### ISSUE THREAD

**Issue by hanfengcan** [xaboy/form-create#227]
1.0.14

iview-4.2.0

有这么一个场景，发送短信验证码的。当手机号为空是，发送按钮灰色。当号码不为空是，按钮变成可以按的状态。

但是我发现control是新加一个控件，而不是修改原有控件的prop属性。

如果刚好这个控件有较多的配置项，那就需要写多一份代码了。

是否考虑用修改某个控件的prop属性，这种逻辑呢

**Comment by xaboy** [comment]
目前不支持,后面可以针对这个问题优化一下

**Comment by hanfengcan** [comment]
![image](https://user-images.githubusercontent.com/4559753/86888414-b0f83600-c12c-11ea-8fd3-9191c88c38cb.png)

另外， 上面这种布局。 如果用control控制按钮的有无， 按钮的位置也不对。

![image](https://user-images.githubusercontent.com/4559753/86888524-e13fd480-c12c-11ea-807b-63d18d59b38b.png)

**Comment by xaboy** [comment]
这个应该是生成规则不对

**Comment by hanfengcan** [comment]
现在先用事件+更新规则解决
