### ISSUE TITLE
日期框valueFormat绑定之格式化属性无效

### ISSUE THREAD

**Issue by wc-willa** [xaboy/form-create#228]
@form-create/element-ui v1.0.12

element-ui 

2.13.2

给日期框指定绑定值的格式为“yyyy-MM-dd”，但是最后获得的值仍然为“yyyy”

{
          type: "DatePicker",
          field: "countyAssessYear",
          compareType: 0,
          title: "",
          props: {
            clearable: true,
            name: 'countyAssessYear',
            type: 'year',
            valueFormat: 'yyyy-MM-dd',
            pickerOptions: {
              disabledDate(time) {
                return time.getTime() > today;
              }
            }
          }
        },

希望在选中日期后获得值格式为“yyyy-MM-dd”，而不是“yyyy”

**Comment by xaboy** [comment]
我检查一下

**Comment by wc-willa** [comment]
有结果了吗

**Comment by xaboy** [comment]
这个是bug,下个版本会修复

**Comment by wc-willa** [comment]
好的

**Comment by AHIMOTU** [comment]
升到1.0.17，还是无效

**Comment by xaboy** [comment]
@AHIMOTU 怎么复现,我这边测试没有问题

**Comment by AHIMOTU** [comment]
@xaboy 我又试了一下，确实是可以了。可能是我周五的时候版本搞错了。。打扰了
