### ISSUE TITLE
form inline true 出现 样式错乱问题

### ISSUE THREAD

**Issue by 672064406zerui** [xaboy/form-create#229]
1.0.16

element-ui

2.13.2

form inline true 模式

表单 都是 display:inline-block
1.提交和重置按钮是浮动，导致布局样式出错。
2.slider ui也出错

例子example 里的 element-ui  自行修改 即可复现

布局样式正常，表单无问题

尽快修改

**Comment by 672064406zerui** [comment]
表单的div class 都是el-form-item
按钮的class 是el-col 
slider 是宽度有问题

**Comment by xaboy** [comment]
我检查一下, inline 模式建议隐藏内置的表单提交按钮,使用自定义组件

**Comment by 672064406zerui** [comment]
但是隐藏的话 那种后台管理上面的表单 就换行了 不满足样式了。
 form-create 插件也不带slot的   所以暂时没什么办法，除非 内部修改你css
有时间的话，你看下

**Comment by xaboy** [comment]
内置的按钮组件下个大版本会重构,目前确实问题比较多

**Comment by xaboy** [comment]
2.5版本已优化

**Comment by 672064406zerui** [comment]
http://jsrun.net/NQhKp/edit   你 demo 地址  修改inline true  slider 滑块 依然是样式错乱。。。。你没验证下吗

**Comment by 672064406zerui** [comment]
rate等一些组件 inline true 上下也对不齐。。。问题如去年8月份一样 依旧

**Comment by xaboy** [comment]
我在 iview 官网测试了一下, 也存在这个问题
