### ISSUE TITLE
自定义表单组件首次加载会触发校验

### ISSUE THREAD

**Issue by chengcan0717** [xaboy/form-create#230]
version：1.0.15

UI 框架：element-ui

UI version： 2.13.0

问题描述：
自定义了一个表单组件，使用时，首次加载就会触发校验；不知道是不是我定义组件的问题

复现步骤/生成规则：https://codesandbox.io/s/brave-cache-z28ut

 期望的结果：
首次加载不触发校验

**Comment by xaboy** [comment]
应该是组件内部触发了`change`事件导致的,框架内部会通过 change 事件进行验证.
解决方法有2个:
1. 修改组件 `change`事件触发逻辑
2. 在验证规则中指定`targger` 触发方式
