### ISSUE TITLE
使用$f.validate方法验证表单，页面必填项提示不展示

### ISSUE THREAD

**Issue by damonsong110** [xaboy/form-create#231]
"@form-create/iview4": "^1.0.16",

iview

"view-design": "^4.3.1",

使用$f.validate方法验证表单，页面必填项提示不展示
![QQ20200710-163428](https://user-images.githubusercontent.com/20758150/87134418-416c7d00-c2cb-11ea-822b-6f114e381945.png)

**Comment by damonsong110** [comment]
this.$f.validate(valid => {
        if (valid) {
          //TODO 验证通过
        } else {
          //TODO 验证未通过
        }
      });

**Comment by xaboy** [comment]
检查全局配置
可以发下生成规则吗.我复现一下

**Comment by damonsong110** [comment]
//model框
<Modal v-model="modal1" @on-ok="ok" @on-cancel="cancel" loading>
      <p slot="header" style="color:#19be6b;text-align:center">
        <span>新增明细</span>
      </p>
      <form-create v-model="fApi" :rule="rule" :option="option" />
  </Modal>

规则
rule:[
  {
    type: 'input',
    field: 'goods_name',
    title: '流程',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name1',
    title: '名称',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name2',

    title: '风控项编码',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_nam3',
    title: '有效时长',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name4',
    title: '限制时长(天)',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,
    }
  },
]

点击事件：
ok(){
let $f = formCreate.create(rule)
=$f.validate(valid => {
        if (valid) {
          //TODO 验证通过
        } else {
          //TODO 验证未通过
        }
      });
}

**Comment by damonsong110** [comment]
![image](https://user-images.githubusercontent.com/20758150/87136306-ea1bdc00-c2cd-11ea-942f-052b5837c75a.png)
![image](https://user-images.githubusercontent.com/20758150/87136389-091a6e00-c2ce-11ea-9362-610cde70b56d.png)
[
  {
    type: 'input',
    field: 'goods_name',
    title: '流程',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name1',
    title: '名称',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name2',

    title: '风控项编码',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_nam3',
    title: '有效时长',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name4',
    title: '限制时长(天)',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,
    }
  },
]

**Comment by damonsong110** [comment]
![image](https://user-images.githubusercontent.com/20758150/87136599-4ed73680-c2ce-11ea-8b5f-aa4b445f5a95.png)
![image](https://user-images.githubusercontent.com/20758150/87136647-5dbde900-c2ce-11ea-93bf-1c9a4b8c6b58.png)
[
  {
    type: 'input',
    field: 'goods_name',
    title: '流程',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name1',
    title: '名称',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name2',

    title: '风控项编码',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_nam3',
    title: '有效时长',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,

    }
  },
  {
    type: 'input',
    field: 'goods_name4',
    title: '限制时长(天)',
    validate: [{ type: 'string', required: true, message: '请输入名称' }],
    col: {
      span: 20,
      push: 1,
    }
  },
]

**Comment by damonsong110** [comment]
> 检查全局配置

没有做全局配置相关文件。每个页面写一次😆

**Comment by damonsong110** [comment]
<template>
  <div>
    <form-create v-model="fApi" :rule="rule" :option="option" />
    <button @click="ok">ok</button>
  </div>
</template> 
<script>
export default {
  data() {
    return {
      fApi: {},
      rule: [
        {
          type: "input",
          field: "goods_name",
          title: "流程",
          validate: [{ type: "string", required: true, message: "请输入名称" }],
          col: {
            span: 20,
            push: 1
          }
        },
        {
          type: "input",
          field: "goods_name1",
          title: "名称",
          validate: [{ type: "string", required: true, message: "请输入名称" }],
          col: {
            span: 20,
            push: 1
          }
        },
        {
          type: "input",
          field: "goods_name2",
          title: "风控项编码",
          validate: [{ type: "string", required: true, message: "请输入名称" }],
          col: {
            span: 20,
            push: 1
          }
        },
        {
          type: "input",
          field: "goods_nam3",
          title: "有效时长",
          validate: [{ type: "string", required: true, message: "请输入名称" }],
          col: {
            span: 20,
            push: 1
          }
        },
        {
          type: "input",
          field: "goods_name4",
          title: "限制时长(天)",
          validate: [{ type: "string", required: true, message: "请输入名称" }],
          col: {
            span: 20,
            push: 1
          }
        }
      ],
      option: {
        submitBtn: false
      }
    };
  },
  methods: {
    ok() {
      let $f = formCreate.create(this.rule);
      $f.submit(
        (formData, api) => {
          alert(1);
          //提交表单
        },
        api => {
          alert(2);
          //验证未通过
        }
      );
      $f.validate(valid => {
        if (valid) {
          //TODO 验证通过
        } else {
          //TODO 验证未通过
        }
      });
      this.$Message.info("Clicked ok");
    }
  }
};
</script>

<style lang="less" scoped>
</style>

**Comment by xaboy** [comment]
我这边测试好着, 没有复现

**Comment by damonsong110** [comment]
好的 我在研究研究
