### ISSUE TITLE
规则不填value时，formData()取到值变为null

### ISSUE THREAD

**Issue by skrpolar** [xaboy/form-create#233]
版本号：
1.0.16

使用的 UI 框架：
element-ui

 UI 框架的版本：
2.12.0

问题描述：
从1.0.5升级到1.0.16，配置项没有设置value属性并且不填为空时，formData() 对应配置项获得的值变为null，升级版本前获得的值为空字符串""

目前测试是1.0.7以后才会变成null，1.0.5 1.0.6 都为空字符串""

![image](https://user-images.githubusercontent.com/25026033/87137659-d7a2a200-c2cf-11ea-8934-92a81b2bdf8d.png)

复现步骤/生成规则：

> >

     {
        title: "配置",
        form: [
          {
            type: "input",
            field: "desc",
            title: "描述",
            props: {
              placeholder: "请填写描述",
              clearable: true
            }
          }
        ]
     }
      

期望的结果：
不填的时候可以改回原来的空字符串""吗，或者有什么办法能让配置不填或者不设置value属性的时候跟以前一样为空字符串""

**Comment by xaboy** [comment]
空字符串可能会和单选复现的选项冲突,所以改成 null 了
