### ISSUE TITLE
Parameter '$f' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by LBCoder955** [xaboy/form-create#238]
**版本号**：
1.0.17

 **UI 框架**: 
ant-design-vue

**UI 框架的版本**: 
1.6.4

**问题描述**：
最新`@vue/cli`生成项目，选择ts+eslint Standard下编译报错
![image](https://user-images.githubusercontent.com/24186351/88459588-20aa4700-cec9-11ea-81fe-d4ed7b251595.png)

**复现步骤/生成规则**：
1. @vue/cli 4.4.6 
2. `vue ui` 启动可视化程序
3. 新建项目，选择[`TypeScript`]功能、`ESLint + Standard` 校验
4. 配置`@form-create/ant-design-vue`
5. 编译项目

**期望的结果**:
增加相关类型定义

**Comment by xaboy** [comment]
感谢反馈,下个版会修复

**Comment by xaboy** [comment]
1.0.18版本已修复
