### ISSUE TITLE
图片查看无法关闭问题

### ISSUE THREAD

**Issue by LiaoFeiweiaini** [xaboy/form-create#24]
`Form::frameImageOne('image','产品主图片(305*305px)',Url::build('admin/widget.images/index',array('fodder'=>'image')))->icon('image')->width('100%')->height('550px'),`

点击眼睛按钮,可查看无法关闭,哪里可以写回调?还是有其他办法

**Comment by xaboy** [comment]
需要在frame内部用js手动关闭,`$f.closeModal() `关闭frame组件的弹出框

**Comment by LiaoFeiweiaini** [comment]
给点实例好不

**Comment by xaboy** [comment]
[https://github.com/xaboy/form-create/blob/master/demo/iframe.html](https://github.com/xaboy/form-create/blob/master/demo/iframe.html)
