### ISSUE TITLE
全局配置等问题

### ISSUE THREAD

**Issue by izaktan** [xaboy/form-create#241]
版本号 (version) 
1.0.17

使用的 UI 框架 (element-ui / iview) 
ant-design-vue

UI 框架的版本 (UI version) 
1.6.4

问题描述 (Issue)
1. checkbox或radio没有“其它，请注明”功能，即选择此选项后后面会多出一个input field，暂时可以用control解决。
2. 如何才能全局配置validator的默认错误信息？
3. 如何才能更改control中题目出现的位置？
4. 有没有能单纯写文字的框？

 期望的结果 (Desired outcome) 
2. 全局配置error message，不用在每一题的validate中配置一次
3. 能够选择增加的题目的位置，而不是直接在此题后增加

建议 (Advice) 
1. 增加other选项

**Comment by xaboy** [comment]
@izaktan  感谢反馈
1.没明白什么意思.
2.目前不支持全局配置默认错误信息
3.是控制control 规则插入的位置吗?目前不支持,不过这个可以优化
4.如果内置组件不满足你的需求,可以通过自定义组件显示

**Comment by izaktan** [comment]
![image](https://user-images.githubusercontent.com/33599274/89050283-1edafa80-d385-11ea-83f9-116c85c62be4.png)
1是这个意思

**Comment by xaboy** [comment]
内置的checkbox,radio组件不支持,需要通过自定义组件实现
