### ISSUE TITLE
描述中的表单表单生成器和表单设计器是两个东西嘛？

### ISSUE THREAD

**Issue by fu827707013** [xaboy/form-create#242]
描述中的表单表单生成器和表单设计器貌似和我理解的完全不同，
我本来是找表单设计器的，
而且github，官方文档，和码云中的demo地址都访问不效果了，看不到效果
我下载demo代码编译后，才看到效果，问题是和我需求完全不同。。。
我还是比较看好ivew的，所以对着文档看了半天，结果这回差的有点远了，
我想找这两种效果，可能是我跑错地方了
http://form.making.link/#/zh-CN/
https://form.avuejs.com/

**Comment by xaboy** [comment]
为了备案, 文档下午停止解析了 不好意思
设计器后续会开发,和你发的效果类似
这个项目的功能是让表单可以通过 `json`生成,方便后端控制前端的表单生成
