### ISSUE TITLE
ruoyi-vue引用报错

### ISSUE THREAD

**Issue by zzfF1** [xaboy/form-create#245]
2.0

element-ui

2.13.2

在.vue文件里导入form-create报错
![image](https://user-images.githubusercontent.com/44562386/89846659-6139de00-dbb4-11ea-9c10-ad11891f2d38.png)
引用:
![image](https://user-images.githubusercontent.com/44562386/89846835-e7eebb00-dbb4-11ea-8380-41fb7b49bfcb.png)
![image](https://user-images.githubusercontent.com/44562386/89846884-01900280-dbb5-11ea-915d-b3f949ab7e46.png)
![image](https://user-images.githubusercontent.com/44562386/89846906-0f458800-dbb5-11ea-94e9-ace080885648.png)

希望通过后台json生成表单界面;
谢谢!

**Comment by xaboy** [comment]
组件挂载方式错了,[文档](http://www.form-create.com/v2/guide/mount.html#formcreate)
`components: {formCreate:formCreate.$form()}`

**Comment by zzfF1** [comment]
谢谢!
