### ISSUE TITLE
iview 自定义表单规则方法

### ISSUE THREAD

**Issue by QQchu** [xaboy/form-create#246]
想对组件再进行封装
![image](https://user-images.githubusercontent.com/42673687/90106048-6e53fa00-dd79-11ea-8f4a-d3b4d8d08a18.png)
![image](https://user-images.githubusercontent.com/42673687/90106770-76606980-dd7a-11ea-8227-4e52a8276513.png)
不知道自定义表单验证方法放到哪里，只传入rule  自定义表单验证方法不生效
![image](https://user-images.githubusercontent.com/42673687/90107830-018e2f00-dd7c-11ea-9b65-1b6c44841769.png)

**Comment by xaboy** [comment]
this.isGtStartDate打印出来看看,应该是代码写的有问题

**Comment by QQchu** [comment]
> this.isGtStartDate打印出来看看,应该是代码写的有问题

 this.isGtStartDate方法里面含有this.fApi,这个this.fApi要到了formCreate主键里面才是一个有效对象

**Comment by xaboy** [comment]
表单提交的时候验证有效吗

**Comment by QQchu** [comment]
> 表单提交的时候验证有效吗
有效 进到里面 this.fApi 卡住了，如果要rule分离的话，需要子组件加载的时候把fApi对象传递给 外面的父组件 这样就好像可以运行

**Comment by xaboy** [comment]
2.5版本已优化
