### ISSUE TITLE
父组件给子组件传参赋值生成formCreate, validator验证无效

### ISSUE THREAD

**Issue by GISZZ** [xaboy/form-create#247]
"@form-create/element-ui": "^1.0.17"

element-ui 

 "element-ui": "^2.13.2",

v-for 遍历生成formCreate,  json生成表单，使用validator验证无效，不用validator这个自定义函数是可以的验证的，不用v-for遍历也能触发validator

dom:

  <div v-for="(item,index) in paramForm.data" :key="index">
      <formCreate :rule="item.list" v-model="item.fApi" :option="options" />
 </div>

json:

 {
                    type:'input',
                    field:'host',
                    title:'服务地址',
                    validate: [
                        {type: 'string', required: true, message:'不能为空'}
                    ]
                },
                {
                    type:'input',
                    field:'port',
                    title:'端口',
                    value:22,
                    validate:[
                        {
                            validator:(rule,val,d)=>{
                              console.log(rule,val,d, '11')
                            // val && !/^[a-z]+$/.test(val) ? d(true) : d()
                            },
                            message:"只能填写 a-z",required: true, trigger: 'change'
                        },
                    ]
                }

希望能触发

**Comment by xaboy** [comment]
有报错信息吗

**Comment by GISZZ** [comment]
> 有报错信息吗

没有报错信息，如果用v-for遍历生成formcreate 没有触发validator，如果不用v-for就可以触发validator

**Comment by xaboy** [comment]
可以写一个复现的 demo 吗

**Comment by GISZZ** [comment]
> 可以写一个复现的 demo 吗

你好 不是v-for的原因，应该是我这边写的组件的问题，我生成formCreate用的值是父组件给子组件传参，子组件里用watch监听到值再赋值的，不会触发validator的是这种情况，能够触发的都是我在子组件里自己写数据，我vue一般不太能找出为什么

**Comment by GISZZ** [comment]
解决了 我自己的问题 没有用$set 进行赋值，感谢author
