### ISSUE TITLE
请问怎么监听整个表单的change事件呢

### ISSUE THREAD

**Issue by TwinkleLeon** [xaboy/form-create#248]
1.0.18

ele

2.13.2

看到 1.0.10 的 更新日志里面有说可以监听整个表单的change事件，但是文档中没有说如何去监听

**Comment by xaboy** [comment]
```html
<form-create @change="onChange">
```

**Comment by TwinkleLeon** [comment]
> ```
> <form-create @change="onChange">
> ```

通过这种方式生成的表单不可以么 
`this.$f = window.formCreate.create(rules,config)`

**Comment by xaboy** [comment]
`$f.on('change', onChange)` 这样写应该也可以

**Comment by TwinkleLeon** [comment]
> `$f.on('change', onChange)` 这样写应该也可以

可以了...建议文档中提示一下 哈哈哈 试过教程中  事件监听  模块的几种方法  都不能做到全局监听
这个感觉可以放到API里面  属于实例的方法

**Comment by xaboy** [comment]
好的,下个版本我优化一下文档

**Comment by TwinkleLeon** [comment]
> 好的,下个版本我优化一下文档

nice  话说你是真的活跃- -  秒回 不用上班的么

**Comment by xaboy** [comment]
哈哈 感谢支持, 好用的话帮我点个 star 哟
