### ISSUE TITLE
大大可不可以考虑出一个 props配置项啊

### ISSUE THREAD

**Issue by GISZZ** [xaboy/form-create#250]
我跟后端字段名完全不一样 太惨了

**Comment by xaboy** [comment]
什么 props 配置项?

**Comment by GISZZ** [comment]
**JSON规则的配置项名称与组件生成器的配置方法名称相同,配置参数也相同**
比如：
{
  field:'test',
  type:'input',
  title:'textTitle'
  props:{
    disable:true
  },
  on:{
    change:function(){
    }
  }
}


里的field、type、title
