### ISSUE TITLE
支不支持collapse

### ISSUE THREAD

**Issue by liuya00** [xaboy/form-create#252]
form-create 有没有关于折叠效果的实例

**Comment by xaboy** [comment]
通过自定义组件是可以支持的,目前没有实例

**Comment by liuya00** [comment]
有没有参考文档呢， 我看官方也没有 相关的文档 介绍怎么写

**Comment by xaboy** [comment]
http://www.form-create.com/v2/guide/custom-component.html 可以参考一下这个

**Comment by liuya00** [comment]
那有没有 其他自定义组件的完整的例子参考 ，因为不太熟悉 写起来有点费劲

**Comment by xaboy** [comment]
可以从头到尾详细看下文档,很简单的

**Comment by liuya00** [comment]
好的  谢谢
