### ISSUE TITLE
"TypeError: Cannot read property 'autosize' of undefined"

### ISSUE THREAD

**Issue by simpv** [xaboy/form-create#253]
1.0.3

iview

4.1.2

提示 'autosize' of undefined" 。 看了一下源代码（form-create.min.js）， {var e=this.rule.props;e.autosize&&e.autosize.minRows&&$set(e,"rows",e.autosize.minRows||2)}}]),  
里面 e.autosize 我props里面如果没定义 autosize 这里肯定报错啊，这个autosize又不是必要属性

**Comment by xaboy** [comment]
你规则里的 props 是对象类型吗

**Comment by xaboy** [comment]
1.0.19已优化
