### ISSUE TITLE
group 组件回填会多出额外的一个

### ISSUE THREAD

**Issue by chen512** [xaboy/form-create#254]

**Comment by xaboy** [comment]
form-create 是那个版本

**Comment by chen512** [comment]
"@form-create/element-ui": "^1.0.7",
开发环境没有问题，打包后就有问题了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaboy/form-create"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 上午9:19
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Matt"<244927363@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] group 组件回填会多出额外的一个 (#254)





 
form-create 是那个版本

**Comment by xaboy** [comment]
更新一下版本试试

**Comment by chen512** [comment]
好的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaboy/form-create"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 上午9:29
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Matt"<244927363@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] group 组件回填会多出额外的一个 (#254)





 
更新一下版本试试

**Comment by chen512** [comment]
感谢作者您的回复，确实是线上安装的依赖用了1.05版本存在了这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaboy/form-create"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 上午9:29
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Matt"<244927363@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] group 组件回填会多出额外的一个 (#254)





 
更新一下版本试试

**Comment by xaboy** [comment]
1.0.19已发布,修复了几个 group 组件的问题.建议升级
[更新说明](http://www.form-create.com/v2/guide/update.html)
