### ISSUE TITLE
同时使用group和tree会导致tree子级样式不选中

### ISSUE THREAD

**Issue by ooodyn** [xaboy/form-create#257]
2.0版本同时使用group和tree，会导致tree最深子级在有默认值的情况下，而样式不选中（父类会选中）

**Comment by xaboy** [comment]
感谢反馈,可以发下生成规格吗.

**Comment by xaboy** [comment]
这个可能是因为多个子表单公用了同一份数据导致的

**Comment by ooodyn** [comment]
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>

    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/iview@2.14.3/dist/styles/iview.css">
    <script src="https://cdn.jsdelivr.net/npm/iview@2.14.3/dist/iview.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/@form-create/data/dist/province_city_area.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@form-create/iview@1.0.7/dist/form-create.min.js"></script>


    
    <script src="https://cdn.jsdelivr.net/npm/@form-create/iview/dist/form-create.min.js"></script>

---
var data = function () {
            return [{
                title: 'parent 1',
                expand: true,
                id: 1,
                children: [
                    {
                        title: 'parent 1-1',
                        expand: true,
                        id: 2,
                        children: [
                            {
                                title: 'leaf 1-1-1',
                                id: 11
                            },
                            {
                                title: 'leaf 1-1-2',
                                checked: true,
                                id: 12
                            }
                        ]
                    },
                    {
                        title: 'parent 1-2',
                        expand: true,
                        id: 3,
                        children: [
                            {
                                title: 'leaf 1-2-1',
                                checked: true,
                                id: 13,
                            },
                            {
                                title: 'leaf 1-2-1',
                                id: 14,
                            }
                        ]
                    }
                ]
            }];
        }

--- 

rule: [
                {
                    type: "tree",
                    title: "权限2",
                    field: "rule2",
                    value: [],
                    props: {
                        data: data(),
                        type: 'checked',
                        multiple: false,
                        showCheckbox: true,
                    }
                },
                {
                    type: 'group',
                    title: '編號',
                    field: 'group',
                    value: [],
                    button: true,
                    props: {
                        max: 5,
                        min: 1,
                        rules: [
                            {
                                type: 'col',
                                children: [
                                    {
                                        type: 'input',
                                        field: 'serial_number',
                                        title: '編號',
                                        validate: [{required: true}],
                                        col: {span: 12}
                                    },
                                    {
                                        type: 'input',
                                        field: 'itinerary_number',
                                        title: '自由行編號',
                                        validate: [{required: true}],
                                        col: {span: 12}
                                    },
                                ]
                            }
                        ]
                    },
                    validate: [
                        {required: true, min: 1, type: 'array', message: '最少增加1项'},
                    ]
                }
            ],

**Comment by ooodyn** [comment]
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.min.js"></script>

    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/iview@2.14.3/dist/styles/iview.css">
    <script src="https://cdn.jsdelivr.net/npm/iview@2.14.3/dist/iview.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/@form-create/data/dist/province_city_area.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@form-create/iview@1.0.7/dist/form-create.min.js"></script>


    
    <script src="https://cdn.jsdelivr.net/npm/@form-create/iview/dist/form-create.min.js"></script>

---
```javascript
var data = function () {
            return [{
                title: 'parent 1',
                expand: true,
                id: 1,
                children: [
                    {
                        title: 'parent 1-1',
                        expand: true,
                        id: 2,
                        children: [
                            {
                                title: 'leaf 1-1-1',
                                id: 11
                            },
                            {
                                title: 'leaf 1-1-2',
                                checked: true,
                                id: 12
                            }
                        ]
                    },
                    {
                        title: 'parent 1-2',
                        expand: true,
                        id: 3,
                        children: [
                            {
                                title: 'leaf 1-2-1',
                                checked: true,
                                id: 13,
                            },
                            {
                                title: 'leaf 1-2-1',
                                id: 14,
                            }
                        ]
                    }
                ]
            }];
        }
```

--- 

```javascript
rule: [
                {
                    type: "tree",
                    title: "权限2",
                    field: "rule2",
                    value: [],
                    props: {
                        data: data(),
                        type: 'checked',
                        multiple: false,
                        showCheckbox: true,
                    }
                },
                {
                    type: 'group',
                    title: '編號',
                    field: 'group',
                    value: [],
                    button: true,
                    props: {
                        max: 5,
                        min: 1,
                        rules: [
                            {
                                type:'col',
                                children:[
                                    formCreate.maker.date('时间','date','').native(false).col({span:12}),
                                    {
                                        type:'inputNumber',
                                        field:'field',
                                        title: '库存',
                                        props:{
                                            disabled:false
                                        },
                                        validate:[
                                            {required:true,min:10,type:'number'}
                                        ],
                                        col:{
                                            span:12
                                        }
                                    }
                                ]

                            },
                            {
                                type:'input',
                                field:'field2',
                                title: '名称',
                                props:{
                                    disabled:false
                                },
                                validate:[
                                    {required:true}
                                ]
                            }
                        ]
                    },
                    validate: [
                        {required: true, min: 1, type: 'array', message: '最少增加1项'},
                    ]
                }
            ],
```

**Comment by ooodyn** [comment]
就这一个表单

**Comment by ooodyn** [comment]
单独引入样例各自的css和js也不行 会有冲突 根据引入js的顺序 tree和group总会有一个用不了

**Comment by xaboy** [comment]
下个版本 group 组件的 rules 支持配置为` function`. 
在函数中返回生成规则就不会出现这个问题

**Comment by xaboy** [comment]
不好意思,我理解错了. tree 的选中状态是通过 value 来控制的
