### ISSUE TITLE
怎么设置formItem上error属性的值啊？

### ISSUE THREAD

**Issue by MainPri** [xaboy/form-create#258]
^1.0.19

element-ui

2.13.2

怎么设置formItem上的error属性的值?
![image](https://user-images.githubusercontent.com/25527317/93662650-405a8780-fa94-11ea-81ba-96d5479e8bad.png)

**Comment by xaboy** [comment]
感谢反馈. 目前不支持设置 error 属性,这个后面版本可以优化

**Comment by xaboy** [comment]
2.5版本已优化
