### ISSUE TITLE
radio组件的disabled属性不生效

### ISSUE THREAD

**Issue by hottaiger** [xaboy/form-create#260]
1.0.17

iview

3.5.1

调用updateRule方法，当修改的组件是radio时，disabled属性不生效。

$f.updateRule(field,{
  props:{
    disabled: true
  }
})

禁用属性disabled生效

**Comment by xaboy** [comment]
`$f.disabled(true,field)` 试试这生效不

**Comment by hottaiger** [comment]
> `$f.disabled(true,field)` 试试这生效不

没生效，233。没想到回复怎么快。

**Comment by xaboy** [comment]
还能秒回, 在 `props` 里预定义一个`disabled`试试

**Comment by hottaiger** [comment]
> 还能秒回, 在 `props` 里预定义一个`disabled`试试

还是不行。。。

**Comment by xaboy** [comment]
能提供一个在线的 demo 或者 发下生成规则我复现一下试试吗

**Comment by hottaiger** [comment]
`
<template>
  <div style="width: 400px;">
    <form-create v-model="form" :rule="formRule" :option="formOptions"></form-create>
  </div>
</template>

<script>
import { createCoupon, selectCouponList, updateCoupon } from '@/api/api-admin/coupon.js';

export default {
  data () {
    return {
      couponId: '',
      form: {},
      formRule: [
        {
          type: 'radio',
          title: '仅限新用户',
          field: 'isNewUser',
          value: 0,
          options: [
            { value: 0, label: '否' },
            { value: 1, label: '是' }
          ],
          validate: [
            { required: true, message: '仅限新用户必选' }
          ],
          props: {
            disabled: true
          }
        }
      ],
      formOptions: {
        mounted: ($f) => {
          $f.disabled(true, 'isNewUser');
        }
      }
    };
  },
};
</script>

<style lang="less" scoped>

</style>

`

**Comment by hottaiger** [comment]
> 能提供一个在线的 demo 或者 发下生成规则我复现一下试试吗

不知道为啥代码格式，复制不上去

**Comment by xaboy** [comment]
我检查了下,是 iview 的 redisGroup 组件不支持禁用. 所以不能生效

**Comment by hottaiger** [comment]
确实是这样。。。谢了
