### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by LeoZeda** [xaboy/form-create#261]
iview

iview 4

ERROR in ./node_modules/@form-create/core/src/core/index.js 105:23
Module parse failed: Unexpected token (105:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|             },
|             render() {
>                 return <form-create ref='fc' props={this.$data}/>
|             }
|         });
 @ ./node_modules/@form-create/core/src/index.js 1:0-59 13:0-16:2 18:15-31
 @ ./packages/iview4/src/core/index.js
 @ ./packages/iview4/src/index.js

npm run dev:iview4， 直接报错

**Comment by xaboy** [comment]
第1步:   `npm install`
第2步:  `npm run bootstrap`
第3步:  `npm run dev:iview4`

**Comment by LeoZeda** [comment]
npm run bootstrap 报下面的错误
`> form-create@ bootstrap /Users/leo/personal/test/form-create
> npm run clear-all && npm i && npm-run-all bootstrap:lerna


> form-create@ clear-all /Users/leo/personal/test/form-create
> rimraf package-lock.json packages/*/node_modules packages/*/package-lock.json

npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2020-09-29T06_43_02_570Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! form-create@ bootstrap: `npm run clear-all && npm i && npm-run-all bootstrap:lerna`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the form-create@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2020-09-29T06_43_02_625Z-debug.log`

**Comment by LeoZeda** [comment]
form-create 这个是只是根据json数据生成form表单吧，我想找托拉拽生成的

**Comment by xaboy** [comment]
对, 目前是通过 json 生成表单. 后面会出拖拽生成
