### ISSUE TITLE
form-create能在自定义组件内部访问 引入form-create组件的实例吗？

### ISSUE THREAD

**Issue by alphagege** [xaboy/form-create#262]
能通过什么方法在自定义组件内部访问 引入form-create组件的实例吗，目前的实现方式是采用在自定义组件内部用
this.$parent.$parent.$parent.$parent.$parent访问，但感觉这种方法风险太大了，求问有没有其他方法。

**Comment by xaboy** [comment]
可以自定义组件内定义一个`props.formCreate`,就可以拿到 `$f`

**Comment by alphagege** [comment]
谢谢大佬指点！有效果！！非常感谢！！！
