### ISSUE TITLE
JSON中配置自定义指令无效问题

### ISSUE THREAD

**Issue by alphagege** [xaboy/form-create#264]
您好，我想找官网上的jsx写法给input组件绑定自定义指令，诸如：
`<el-input v-model="aaa" placeholder v-hahaha></el-input>`

配置这么写的，hahaha指令尝试过全局注册，局部注册，但是不执行自定义指令，绑定无效。
`directives: [
            {
              name: "hahaha",
              value: "2"
            }
 ]`

<img width="657" alt="WX20201013-155159@2x" src="https://user-images.githubusercontent.com/29486562/95832033-5e05ce80-0d6c-11eb-8660-0a1865c99a89.png">

想请教下这是为什么。

**Comment by xaboy** [comment]
规则发出来我看看

**Comment by alphagege** [comment]
就是如下这个demo，自定义指令不执行，不知道是为什么。

![image](https://user-images.githubusercontent.com/29486562/95968748-6b8c8880-0e40-11eb-9e63-3b8db66b2471.png)

**Comment by xaboy** [comment]
自定义指令挂载到全局试试

**Comment by tong822218** [comment]
哥们 你的这个自定义指令无效的问题解决了吗 我这边也遇到这个问题了
