### ISSUE TITLE
Radio验证的时候验证的值是label 而不是 value

### ISSUE THREAD

**Issue by x67449123** [xaboy/form-create#265]
1.0.19

iview

iview 4.4.0

`{
    type: 'radio',
    title: '',
    field: '',
    value: 0,
    options: [
        { value: 0, label: '值0' },
        { value: 1, label: '值1' }
    ],
    col: {
        span: '24'
    },
    validate: [
        {
            required: true,
            validator: (rule, value, callback) => {
                console.log(value, isNaN(value));
                if (value === undefined || isNaN(value) === true) {
                    callback(new Error('必须选择'));
                }
                callback();
            },
            trigger: 'blur'
        }
    ]
}`

表单验证的时候 打印出来的value 是 '值0' 而不是0

**Comment by x67449123** [comment]
### 
    type: 'radio',
    title: '',
    field: '',
    value: 0,
    options: [
        { value: 0, label: '值0' },
        { value: 1, label: '值1' }
    ],
    col: {
        span: '24'
    },
    validate: [
        {
            required: true,
            validator: (rule, value, callback) => {
                console.log(value, isNaN(value)); // 打印显示 值0 和 true
                if (value === undefined || isNaN(value) === true) {
                    callback(new Error('必须选择'));
                }
                callback();
            },
            trigger: 'blur'
        }
    ]

抱歉上面的没有格式化好...这个比较容易看清楚..

**Comment by xaboy** [comment]
感谢反馈, 这是个bug. 下个版本修复

**Comment by xaboy** [comment]
我检查了下,这个是 iview  select 组件的事件 这个不算 bug. 建议自己做处理,或者用自定义组件封装. 如果我做处理后就不能和之间的版本兼容了
