### ISSUE TITLE
Group-Bug

### ISSUE THREAD

**Issue by weiyang627** [xaboy/form-create#269]
1.0.13

iview

3.5.2

同一个表单存在两个Group数组组件，若第一个数组的个数大于等于第二个数组个数的话，提交次数等于第一个数组里对象的个数，也就是说发送了多次请求。

![image](https://user-images.githubusercontent.com/26380234/97521945-91399600-19d9-11eb-914c-74daaa42fa40.png)

无论存在几个数组组件，提交次数只有一次。

**Comment by xaboy** [comment]
更新到最新版本试试

**Comment by weiyang627** [comment]
>

**Comment by xaboy** [comment]
还有问题吗? 这两天刚好要更新一个版本
