### ISSUE TITLE
移除表单事件监听器

### ISSUE THREAD

**Issue by zhengxiaodong502** [xaboy/form-create#270]
"@form-create/iview4": "^1.0.19",

iview

"view-design": "^4.4.0",

从API中没有看到相关的方法来进行移除事件

http://www.form-create.com/v2/instance.html#%E7%A7%BB%E9%99%A4%E8%A1%A8%E5%8D%95%E4%BA%8B%E4%BB%B6%E7%9B%91%E5%90%AC%E5%99%A8

**Comment by xaboy** [comment]
移除表单事件监听器? 意思是需要移除通过 `rule.on`配置的事件吗

**Comment by zhengxiaodong502** [comment]
嗯嗯 我是通过on方法监听事件，然后采用的是 this.fApi.on(``, fn);方式绑定事件的，现在我想删除，找不到对应的方法

**Comment by xaboy** [comment]
通过 `this.fApi.off(eventName)` 或者 `this.fApi.off(eventName, fn)`. 文档上不完整, 我补充一下

**Comment by zhengxiaodong502** [comment]
大佬，有没有一次性可以移除表单所有事件的方法

**Comment by xaboy** [comment]
如果没有提供参数，则移除所有的事件监听器 `this.fApi.off()`

**Comment by zhengxiaodong502** [comment]
好的，谢谢大佬，我试试
