### ISSUE TITLE
element ui  ,resetBtn,submitBtn设置show=false无效

### ISSUE THREAD

**Issue by LoneKingCode** [xaboy/form-create#271]
"@form-create/element-ui": "^1.0.18",
     "element-ui": "2.13.2",
     "vue": "^2.6.11"

设置show=false无效，但是设置disabled、icon都是有用的，是哪里配置有问题吗？

    <form-create :option="option" :rule="rule" :style="{ height: dialogHeight }" ref="fc" v-model="fApi"></form-create>
      option: {
        form: {
          labelWidth: "120px",
        },
        submitBtn: {
          show: true,
          icon: "el-icon-circle-check",
        },
        resetBtn: {
          show: false,
          icon: "el-icon-refresh",
        },
    }

**Comment by xaboy** [comment]
我这边测试没有问题
```js
submitBtn: {
         show: false,
         icon: "el-icon-circle-check",
},
```
可以隐藏默认提交按钮
