### ISSUE TITLE
能否支持引入外部的UI框架

### ISSUE THREAD

**Issue by wangyan-tourise** [xaboy/form-create#274]
我工作中遇到的实际问题。公司有自己的一套UI框架，是用elementUI二次封装的（其实就是标签名称不同，其他都一样），之前使用form-create是没有问题的，动态生成的<el-xxx>标签也可以运行，但是后来公司要做自己的组件库，要求只用自己的框架，这个动态生成的<el-xxx>标签就运行不了了

**Comment by xaboy** [comment]
这个可以优化, 下个版本可以支持设置组件的别名.
目前默认是`input`组件映射的是`ElInput`组件
下个版本可以通过 `componentAlias`方法配置. 例如`formCreate.componentAlias('input','XxInput')` 修改内置的 `input` 组件映射为自定义的`XxInput`组件
