### ISSUE TITLE
数组组件/组件嵌套【group】的属性pops中  expand设置不生效

### ISSUE THREAD

**Issue by nonothingless** [xaboy/form-create#275]
`new Vue({
    el: "#app",
    data: {
        rule: [{
            type: 'group',
            title: '批量添加',
            field: 'group',
            value: [],
            props: {
                max: 5,
                min: 3,
                expand: 3,
                rules: [
                    {
                        type: 'col',
                        children: [
                            formCreate.maker.date('时间', 'date', '').native(false).col({ span: 12 }),
                            {
                                type: 'inputNumber',
                                field: 'field',
                                title: '库存',
                                props: {
                                    disabled: false
                                },
                                validate: [
                                    { required: true, min: 10, type: 'number' }
                                ],
                                col: {
                                    span: 12
                                }
                            }
                        ]
                    },
                    {
                        type: 'input',
                        field: 'field2',
                        title: '名称',
                        props: {
                            disabled: false
                        },
                        validate: [
                            { required: true }
                        ]
                    }
                ]
            },
            validate: [
                { required: true, min: 3, type: 'array', message: '最少增加3项' },
            ]
        }]
    }
})`

**Comment by nonothingless** [comment]
设置expand=3以后，没有默认展开

**Comment by xaboy** [comment]
form-create 是那个版本

**Comment by xaboy** [comment]
1.0.20版本测试没有问题测试没有问题
