### ISSUE TITLE
如何在控件的前后自定义文案

### ISSUE THREAD

**Issue by zhengxiaodong502** [xaboy/form-create#276]
"@form-create/iview4": "^1.0.19"

iview最新

**想要在控件的前后添加自定义备注文案**

**Comment by xaboy** [comment]
这个得看插槽是否支持,如果插槽不支持可以尝试用自定义组件实现

**Comment by zhengxiaodong502** [comment]
大佬 能不能举个例子，是在不知如何下手了

**Comment by xaboy** [comment]
2.1版本会支持, 通过`prefix`, `suffix` 配置组件的前后缀

**Comment by xaboy** [comment]
2.5版本已优化
