### ISSUE TITLE
什么时候支持Vue3？

### ISSUE THREAD

**Issue by JanusSpark** [xaboy/form-create#277]
"@form-create/element-ui": "^1.0.20"

element-ui 

"element-ui": "^2.14.0"

![image](https://user-images.githubusercontent.com/12661048/98807622-e5bb2780-2455-11eb-9fae-8bb3f6fb6e12.png)

使用Vue3初始化，引入插件即可复现

支持Vue3使用

**Comment by xaboy** [comment]
支持 vue3 得到明年了.
目前正在2.1版本重构,还有支持一个移动端的 ui 框架 @JanusSpark

**Comment by xaboy** [comment]
3.0版本已发布
