### ISSUE TITLE
服务器加载json配置,页面打开时会有一瞬间的空白.

### ISSUE THREAD

**Issue by zzfF1** [xaboy/form-create#278]
1.0.17

elementui

2.13.2

服务器端传输json表单配置,在vue界面根据json生成FORM表单; 页面打开时会出现表单还没有创建时的空白效果,一瞬间但是能明显看到, 有什么好的方式处理吗?

1.在create方法中调用方法加载服务器JSON数据
![image](https://user-images.githubusercontent.com/44562386/99142885-24d6bc00-2694-11eb-80a0-a2803f842d43.png)
![image](https://user-images.githubusercontent.com/44562386/99142897-3c15a980-2694-11eb-92ab-f8f2d4f52453.png)
form-create定义
![image](https://user-images.githubusercontent.com/44562386/99142908-5059a680-2694-11eb-80e0-420a01a01892.png)
页面打开时
![image](https://user-images.githubusercontent.com/44562386/99142943-99a9f600-2694-11eb-950b-e9059f0b686a.png)
正常刷新后
![image](https://user-images.githubusercontent.com/44562386/99142971-d4ac2980-2694-11eb-85a1-fec82bbd1852.png)

**Comment by xaboy** [comment]
生成的组件很多吗

**Comment by xaboy** [comment]
@zzfF1

**Comment by zzfF1** [comment]
现在我的例子是生成了4个input; 不算多.

**Comment by xaboy** [comment]
放到 mounted 里面试试, 有可能是正常的渲染时间
