### ISSUE TITLE
http://form-create.com/v2/element-ui/components/select.html

### ISSUE THREAD

**Issue by ruanheng159** [xaboy/form-create#279]
http://form-create.com/v2/element-ui/components/select.html

最下面的event

_Originally posted by @key1012 in https://github.com/xaboy/form-create/issues/156#issuecomment-569194510_

麻烦还是更新一下文档，event  -->  on ，
或者添加一个在GitHub编辑的按钮，可以帮助修改文档的错误
这个插件很强大，谢谢作者

**Comment by xaboy** [comment]
好的 感谢反馈, 稍后就把编辑按钮显示出来

**Comment by xaboy** [comment]
已优化
