### ISSUE TITLE
select doc not correct

### ISSUE THREAD

**Issue by qinst64** [xaboy/form-create#28]
http://fc.gd8.top/749570

you said `value` is not compulsory and `label` is. I however found they r in the opposite situation...

**Comment by xaboy** [comment]
![image](https://user-images.githubusercontent.com/21242408/49372293-1e640980-f735-11e8-8eb5-88065d368957.png)
Thank you, do you mean this location, it is recommended to have both `value` and `label`. The final display is 'label', which returns `value` (Google Translate:smile:)

**Comment by qinst64** [comment]
my bad, pls close this issue.
