### ISSUE TITLE
逐渐嵌套的  事件

### ISSUE THREAD

**Issue by yangtanyu** [xaboy/form-create#280]
element ui

2.14.1

请问一下  嵌套表单的  事件 有没有具体的例子

![image](https://user-images.githubusercontent.com/50374470/100416800-4d11e200-30ba-11eb-87f4-44c208f838f6.png)

**Comment by xaboy** [comment]
例如group的规则
```js
{
    type: 'group',
    title: '批量添加',
    field: 'group',
    value: [{date: '2121-12-12', field: 10, field2: '123123123'}],
    suffix: 'suffixsuffix',
    props: {
        max: 5,
        min: 3,
        field: 'field2',
        expand: 4,
        rule: {
            type: 'input',
            field: 'field2',
            props: {
                disabled: false
            },
            emit: ['change'],
            validate: [
                {required: true}
            ]
        }
    },
    on: {
        'field2-change': () => {
        }
    }
}
```
可以通过 `group`组件的 `field2-change` 事件 监听到 子表单中`field2`组件的`change`事件

**Comment by yangtanyu** [comment]
感谢指导，可以触发 但是   field  为小写才能触发  驼峰命名  就没有反应
![image](https://user-images.githubusercontent.com/50374470/100418771-4ab18700-30be-11eb-95bf-ecfe3b5262fa.png)

**Comment by yangtanyu** [comment]
![image](https://user-images.githubusercontent.com/50374470/100418835-5c932a00-30be-11eb-9a34-2e0b43e41d23.png)

**Comment by yangtanyu** [comment]
{
        type: 'group',
        title: '职位信息:',
        field: 'positionList',
        value: [],
        suffix: 'suffixsuffix',
        on: {
          itemMounted: (e) => {
            console.log(99999, e);
          },
          add: (e) => {
            console.log(10222, e);
          },
          'orgCode-change': (a, b, c) => {
            console.log(1077777777, a, b, c);
          },
        },
        props: {
          min: 1,
          expand: 1,
          rules: [
            {
              type: 'select',
              field: 'orgCode',
              title: '组织',
              emit: ['change'],
              options: [
                {
                  label: 'sssdddd',
                  value: 'dddd',
                },
                {
                  label: 'sss1',
                  value: 'dddd1',
                },
              ],
              props: {

              },
              validate: [{ required: true }],
              col: {
                md: {
                  span: 8,
                },
              },
              value: 'dddd',
            },
            {
              type: 'select',
              field: 'operationType',
              title: '操作类型',
              options: [
                {
                  label: 'n:新建职位',
                  value: 'n',
                },
                {
                  label: 'h:已有职位',
                  value: 'h',
                },
              ],
              control: [
                {
                  handle: (val) => val === 'n',
                  rule: [
                    {
                      type: 'select',
                      field: 'positionLevelCode',
                      title: '职位级别',
                      props: {
                        disabled: false,
                      },
                      validate: [{ required: true }],
                      col: {
                        md: {
                          span: 8,
                        },
                      },
                    },
                  ],
                },
                {
                  handle: (val) => val === 'h',
                  rule: [
                    {
                      type: 'select',
                      field: 'positionCode',
                      title: '职位',
                      props: {
                        disabled: false,
                      },
                      validate: [{ required: true }],
                      col: {
                        md: {
                          span: 8,
                        },
                      },
                    },
                  ],
                },

              ],
              on: {
                change: (e) => {
                  console.log(128888, e);
                },

              },
              props: {
                disabled: false,
              },
              validate: [{ required: true }],
              col: {
                md: {
                  span: 8,
                },
              },
            },

            {
              type: 'select',
              field: 'primaryFlag',
              title: '是否主职位',
              dictCode: 'yes_or_no',
              props: {
                disabled: false,
              },
              validate: [{ required: true }],
              col: {
                md: {
                  span: 8,
                },
              },
            },
            {
              type: 'input',
              field: 'roleList',
              title: '权限角色',
              props: {
                disabled: false,
              },
              validate: [{ required: true }],
              col: {
                md: {
                  span: 8,
                },
              },
            },
            {
              type: 'input',
              field: '64333',
              title: '流程角色',
              props: {
                disabled: false,
              },
              validate: [{ required: true }],
              col: {
                md: {
                  span: 8,
                },
              },
            },
            {
              type: 'input',
              field: '36533',
              title: '上级',
              props: {
                disabled: false,
              },
              validate: [{ required: true }],
              col: {
                md: {
                  span: 8,
                },
              },
            },
          ],
        },
        validate: [
          {
            required: true, type: 'array', min: 1, message: '最少添加1个职位',
          },
        ],
      };

**Comment by xaboy** [comment]
`orgCode ` 会自动转换为`org-code `

**Comment by yangtanyu** [comment]
哦哦   谢谢 解答

**Comment by rookiechw** [comment]
子组件是否也可以通过emit加emitPrefix来配置事件调用方法？
我想可以通过在子组件上通过配置emit与emitPrefix来调用定义在vue methods的方法。

```
<form-create v-model='fApi' :rule='rule' :option='option' @xaboy-on-change='onChange' @xaboy-on-blur='onBlur'></form-create>

data() {
 return {
  ...
   rule: [
    {
            type: 'group',
            title: '流程基本信息',
            field: 'baseGroup',
            value: [{}],
            inject: true,
            props: {
                max: 1,
                min: 1,
                rules: [
                    {
                        type: 'input',
                        field: 'field2',
                        title: '编码',
                        props: {
                            disabled: false
                        },
                        validate: [
                            {required: true}
                        ],
                        col: {
                            span: 12
                        },
                        emit: ['on-change'],
                        emitPrefix: 'xaboy'
                    }
                ]
            }
    }
  ]
 ...
 }
},
methods: {
    onChange(inject, val) {
        alert('aaa')
    }
  }
```
是否能调用onChange方法？

**Comment by xaboy** [comment]
@rookiechw 监听` group` 组件的 `field2-on-change`  事件

**Comment by rookiechw** [comment]
> @rookiechw 监听` group` 组件的 `field2-on-change` 事件

感谢回复，我换了另一种方式来实现我的需求。
```code
var rules = [
                    {
                        type: 'select',
                        field: 'sendMessage',
                        title: '是否发送消息',
                        inject: true,
                        value: '',
                        options: [],
                        props: {
                            'clearable': true,
                            'multiple': false,
                            'filterable': true,
                            'placeholder': '请选择',
                            'not-found-text': '无匹配数据',
                            'placement': 'bottom'
                        },
                        validate: [
                            {required: true}
                        ],
                        col: {
                            span: 12
                        },
                        ttxEmit: [
                            {
                                name: 'on-open-change',
                                inject: '自定义信息'
                            }
                        ]
                    }
                ]
      for (var rule of rules) {
          bindEvent(rule)
      }
      function bindEvent(rule) {
        if (rule.type === 'select' && rule.ttxEmit) {
            let on = {}
            if ((typeof rule.ttxEmit) === 'string') {
                if (rule.ttxEmit === 'on-open-change') {
                    on['on-open-change'] = (val) => {
                        vm.onOpenChange(val, null)
                    }
                }
            } else if (rule.ttxEmit instanceof Array) {
                for (let node of rule.ttxEmit) {
                    let name = node.name
                    let params = node.inject ? node.inject : null
                    if (name === 'on-open-change') {
                        on['on-open-change'] = (val) => {
                            vm.onOpenChange(val, params)
                        }
                    }
                }
            }
            rule.on = on
        }
      }
```
主要是想在点击时候,可以动态调用接口获取下拉框的值。
