### ISSUE TITLE
嵌套表单里面的  select  的 options  实时更新

### ISSUE THREAD

**Issue by yangtanyu** [xaboy/form-create#281]
element ui

 operationType  在嵌套表单里面   请问一下   嵌套表单里面的  select  的 options  如何获取 最新数据    现在的情况是   options  始终是第一次  挂载时的数据
![image](https://user-images.githubusercontent.com/50374470/100438580-506a9500-30dd-11eb-9c45-7d466908377e.png)

**Comment by xaboy** [comment]
这样写不行,必须给 rule.options 直接赋值才有效
