### ISSUE TITLE
关于select的option的设置

### ISSUE THREAD

**Issue by 6gunner** [xaboy/form-create#282]
**版本号 (1.0.20)** 

**使用的 UI 框架 (ant-design-vue)** 

**UI 框架的版本 (1.7.2)** 

**问题描述 (Issue)** 
如果组件初始化的时候，没有办法设置好select类型的options，如何异步的设置form的option。或者说，如何等数据准备好的时候去设置form的option？

**复现步骤/生成规则 (Duplicate steps/generate rules)**
```
data() {
return {
  rule: [
        {
          type: "select",
          field: "exchangeId",
          title: "",
          options: this.optionData(), // 我尝试使用一个方法，然后返回vuex的mapState。 无法得到这个数据。
          options: this.exchanges, //  也尝试过直接用vuex的mapState里的数据。 也无法得到这个数据。

        },
  ]
}
...
computed: {
      ...mapState("cache", ["exchanges"]),
},
methods: {
  optionData() {
     return this.exchanges;
  }
}
```

**期望的结果 (Desired outcome)** 
能够动态获取数据，毕竟我以为这个基础的绑定功能能支持。

**建议 (Advice)**
这个作为最常见的使用案例，我希望后期能支持一下，**如果不支持，替代的方案，希望文档里能补充一下说明，这个真的很重要**。
目前的文档场景只是一开始就设置了option，但是不可能所有的数据都是组件created时候就已经准备好了的。

**Comment by Fgoo9527** [comment]
如果下拉框明确是个远程搜索的形式，应该在表单生成前就执行获取下拉项的接口，在成功的回调里处理成符合规范的数组赋值给select的options

**Comment by 6gunner** [comment]
> 如果下拉框明确是个远程搜索的形式，应该在表单生成前就执行获取下拉项的接口，在成功的回调里处理成符合规范的数组赋值给select的options

我这里倒不是说是一个远程搜索的接口，因为这个数据是全局缓存的，很多地方都需要用到。

**Comment by 6gunner** [comment]
anyway， 我总结一下我现在找到的用法吧、

### 第一种
通过updateRule来更新option。
```
  methods: {
    handleCreate() {
      this.modalVisible = true;
      // 因为我是放在modal里的，所以要等modal显示出来，且form-create组件被初始化之后，才能拿到fapi去更新field
      this.$nextTick(() => {
        this.fapi.updateRules({
          exchangeId: {
            options: this.exchanges,
          },
        });
      });
    }
  }
```


### 第二种
通过visibleChange事件来更新option

```
rule: [{
          type: "select",
          field: "exchangeId",
          title: '',
          inject: true,
          on: {
          dropdownVisibleChange: (inject, open) => {
            if (open) {
                 inject.self.options = this.exchanges;
             }
           },
        },
]
```
