### ISSUE TITLE
当有隐藏项时 select 值不能被置空

### ISSUE THREAD

**Issue by lolocoo** [xaboy/form-create#283]
1.0.20
element-ui 2.13.2

在弹窗里创建表单， 然后根据不同的规则隐藏项。
当有隐藏项时，被设置值的 select (没有隐藏) 的值不能被置空。
当全部展示时可以被置空

错误提示： vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'resetField' of undefined"

期望有隐藏值的时候表单的值能被正常初始化。

**Comment by xaboy** [comment]
这个报错是因为 `form-create` 还没初始化完成, `$f` 还没拿到

**Comment by angularwang** [comment]
> 这个报错是因为 `form-create` 还没初始化完成, `$f` 还没拿到

已经初始化完了，我打开的是一个dialog， 在dialog里面的一个表单，beforeclose  的时候调用resetFields的方法。其他的项都能正常清空，唯有select不行。

**Comment by xaboy** [comment]
2.5版本已优化
