### ISSUE TITLE
group 里面的组件怎么布局

### ISSUE THREAD

**Issue by muziling** [xaboy/form-create#284]
用的是iviewui版本， 图片上标题和输入框是各一行，怎么让标题和输入框在同一行
https://user-images.githubusercontent.com/26380234/97521945-91399600-19d9-11eb-914c-74daaa42fa40.png

**Comment by xaboy** [comment]
默认就是在同一行的. 可能是图中一行放不下,所以导致自动换行了

**Comment by leochen-g** [comment]
> 默认就是在同一行的. 可能是图中一行放不下,所以导致自动换行了

element正常，iview 比较特殊，他form-item内部嵌套的form-item的样式，强制写死了margin-left: 0!important;  这个太恶心了，目前还没找到好的方式处理；
![image](https://user-images.githubusercontent.com/20028566/109480580-a83ae280-7ab6-11eb-9f8e-1e0e59869411.png)

**Comment by xaboy** [comment]
是呀, 这个我也没办法控制. 建议自己根据需求写 css 覆盖

**Comment by leochen-g** [comment]
> 是呀, 这个我也没办法控制. 建议自己根据需求写 css 覆盖

我试了覆盖 但是只能自定义最外层class 会影响内嵌全部的样式。不能指定某个form-item，现在内嵌的我都不写label了😂

**Comment by muziling** [comment]
郁闷了，工程所有页面是用iview，单个页面再引入element-ui ，element-ui的datepicker组件用不了 ，可能是两个冲突了
group有没有办法改成tab样式？避开这个雷 @xaboy
