### ISSUE TITLE
自定义表单组emit input会触发prop value的改变

### ISSUE THREAD

**Issue by wopelo** [xaboy/form-create#285]
1.0.19

element-ui 

2.13.2

自定义表单组件，使用vm.$emit('input',newValue)更新组件的值，这个操作会导致组件prop value发送变化，如果组件内部watch了value，则每次更新组件值时，watch函数就会执行，可能带来意料之外的结果

**Comment by xaboy** [comment]
因为`props.value` 需要和 `newValue`保持同步,所以当通过`input`提交`newValue`的时候 `props.value` 也会同步更新 @wopelo
