### ISSUE TITLE
upload组件在切换隐藏状态后第一张图片上传异常

### ISSUE THREAD

**Issue by canomh** [xaboy/form-create#288]
1.0.20

element-ui

2.12.0

 问题描述：
upload类型组件，在调用fApi.hidden函数隐藏并显示后，第一张图片上传无法正常显示

复现步骤：
1. 表单渲染upload组件
1. 通过hidden切换此组件的隐藏状态
1. 上传一张图片（此图片无法正常预览）

期望：upload组件在切换显示隐藏状态后，第一张图片上传无异常

**Comment by xaboy** [comment]
感谢反馈, 我检查一下

**Comment by xaboy** [comment]
2.5版本已优化
