### ISSUE TITLE
组件被隐藏后，校验规则失效

### ISSUE THREAD

**Issue by canomh** [xaboy/form-create#289]
1.0.20

element-ui

2.14.1、2.12.0

问题描述：
在组件被隐藏后，被隐藏的组件无法被校验。
在ElementUI的validateField函数中，通过this.fields获取的组件仅包含当前显示的组件，而隐藏的组件不存在于这个数组中，导致无法调用校验函数。

复现步骤：
1. 调用$f.hidden(true,field)隐藏某个组件
2. 调用$f.validateField(field, function(){})校验该字段
3. ElementUI输出警告：[Element Warn]please pass correct props!

期望：
组件被隐藏后仍然可以进行表单验证（$f.validate、$f.validateField）

**Comment by xaboy** [comment]
2.5版本已优化
