### ISSUE TITLE
how to make upload disabled?

### ISSUE THREAD

**Issue by qinst64** [xaboy/form-create#29]
I am not able to find a 'disabled' propertiy for the 'upload' component. pls help

**Comment by xaboy** [comment]
Sorry, `upload` does not support the `disabled` attribute.
The 'maxLength' attribute can be set. When the number of uploads is greater than `maxLength`, the upload button will be automatically hidden.
Or controlled by `props.beforeUpload`(Google Translate😄)
```js
beforeUpload(){
//disabled
return false;
//esle
//return true;
}

```

**Comment by qinst64** [comment]
thank you!
