### ISSUE TITLE
ant-design-vue 下拉多选 multible:true 没有多选效果

### ISSUE THREAD

**Issue by 804434940** [xaboy/form-create#290]
@form-create/ant-design-vue": "^1.0.20"

ant-design-vue

1.7.2

JSON，使用下拉多选，开启multible:true，且验证规则设置type:'array'，但是依然是单选效果

**rule:**
```js
{
                    type: "select",
                    field: "cate_id",
                    title: "产品分类",
                    value: ["103","104"],
                    options: [
                        {"value": "103", "label": "生态蔬菜", "disabled": false},
                        {"value": "104", "label": "新鲜水果", "disabled": false},
                    ],
                    props: {
                        "placement": "bottom",

                        multiple: true
                    },
                    validate: [{ required: true, message: 'please input!', type: 'array' }]
                }
````
![image](https://user-images.githubusercontent.com/51938617/102865355-97477280-4470-11eb-896c-73f885765c9b.png)
并且验证会报：cate_id is not an array

**Comment by xaboy** [comment]
ant-design-vue 设置的方式是 `props.mode = 'multiple'` 
详细说明可以参考[官方文档](https://www.antdv.com/components/select-cn/#Select-props)

**Comment by 804434940** [comment]
明白了 非常感谢！！
http://www.form-create.com/v2/ant-design-vue/components/select.html

希望这里的文档关于多选的配置修改下&nbsp; 很容易误解呀

---原始邮件---
发件人: "xaboy"<notifications@github.com&gt;
发送时间: 2020年12月22日(周二) 下午4:22
收件人: "xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送: "804434940"<804434940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xaboy/form-create] ant-design-vue 下拉多选 multible:true 没有多选效果 (#290)




 
ant-design-vue 设置的方式是 props.mode = 'multiple'
 详细说明可以参考官方文档
