### ISSUE TITLE
动态修改group展开项expand没有效果

### ISSUE THREAD

**Issue by nimiumiu** [xaboy/form-create#291]
### 版本号 (version)
1.0.20

### 使用的 UI 框架
element-ui 

### 问题描述 (Issue)
动态修改group展开项没有效果
`
$f.updateRules({ "useList":  {props: {expand: 2}} });
`

**Comment by xaboy** [comment]
目前 `expand` 配置只在首次初始化的时候有效

**Comment by nimiumiu** [comment]
怎么实现动态的展示数组每一项

**Comment by xaboy** [comment]
这个后面版本可以优化
目前可以通过修改 value 来实现,例如需要展开2个就设置 value 为`[{},{}]`

**Comment by nimiumiu** [comment]
试了用setValue动态修改，改变不了expand默认展开设定的个数，必须要在初始化时设置value、expand才有效果，还有其他的解决办法吗

**Comment by xaboy** [comment]
下个版本我优化一下

**Comment by xaboy** [comment]
2.5版本已优化
