### ISSUE TITLE
怎么批量修改group下item的rules

### ISSUE THREAD

**Issue by nimiumiu** [xaboy/form-create#292]
### 版本号 (version)
1.0.20

### 使用的 UI 框架
element-ui 

### 问题描述 (Issue)
怎么批量修改group下item的rules
目前这样修改不是很便捷

```
$f.updateRules({
  "filed": {
    props: {
      button: false,
      disabled: true,
      rules: [
        {
          children: [
            {props: {disabled: true}},
            {props: {disabled: true}},
            {props: {disabled: true}},
            {props: {disabled: true}},
            {props: {disabled: true}}
          ]
        }
      ]
    }
  }
});
```

**Comment by xaboy** [comment]
试试 `$f.disabled(true, 'filed')`

**Comment by nimiumiu** [comment]
这样写初始化有效，group新添加的控制不了

**Comment by nimiumiu** [comment]
更新到2.5版本的，group 用.disabled禁用还是无效果

**Comment by xaboy** [comment]
`group`的规则和子表单的规则的`props`中定义`disabled`了吗

**Comment by nimiumiu** [comment]
未定义不能直接用.disabled方法禁用吗

**Comment by xaboy** [comment]
不定义有时没有触发 vue 的渲染机制导致没有及时刷新. 
可以在.disabled之后手动调用一下 `refresh`或者`reload` 方法

**Comment by nimiumiu** [comment]
group的规则和子表单的规则的props中定义disabled后，当group的值数组长度大于一的时候，使用.disabled方法禁用group，只有第一个被禁用，后面的没有被禁用，使用refresh方法也没有效果

**Comment by xaboy** [comment]
规则发下我试试, 我这边没有复现

**Comment by nimiumiu** [comment]
group的值是动态写入的 fApi.setValue，后使用 fApi.disable(true)禁用、fApi.refresh()，只有group第一个表单被禁用，后面表单中radio可点击

**Comment by nimiumiu** [comment]
动态写入数据后，使用nextTick方法执行fApi.disable(true)禁、fApi.refresh()，才生效

**Comment by xaboy** [comment]
我这边复现出来了, 下个版本优化一下

**Comment by xaboy** [comment]
2.5.0-alpha.5版本已优化

**Comment by nimiumiu** [comment]
我当前就是2.5.0-alpha.5版本的，这个问题是在这个版本之前提出的

**Comment by xaboy** [comment]
2.5.0-alpha.5刚刚才发布的. 
怎么复现, 我适用fApi.setValue后使用 fApi.disable(true)禁用测试没有问题

**Comment by nimiumiu** [comment]
搞错了 我是2.5.0-alpha.4版本的
