### ISSUE TITLE
group目前可以禁止移除某项吗 没找到相关的办法

### ISSUE THREAD

**Issue by 804434940** [xaboy/form-create#296]
ant-design-vue

 "@form-create/ant-design-vue": "^1.0.20",

禁止某项被移除

**Comment by xaboy** [comment]
不支持, 这个可以在下个版本可以优化一下

**Comment by 804434940** [comment]
> 不支持, 这个可以在下个版本可以优化一下

那有监听移除的事件吗

**Comment by xaboy** [comment]
有 `remove` 事件, [group组件说明](http://form-create.com/v2/guide/group.html#on-%E4%BA%8B%E4%BB%B6)

**Comment by 804434940** [comment]
谢谢！
