### ISSUE TITLE
自定义指令不生效-急急急 😂

### ISSUE THREAD

**Issue by tong822218** [xaboy/form-create#297]
通过json role 配置自定义指令不生效

rule:[{
  type:'select',
  title:'公司'，
  field:'abc',
  style:'width:10px',
  directives:[{
   name:'el-select-loadmore',
  value:2  
 }]  
}]
其中 style 和 directives都没有生效

正常设置style 和directives

**Comment by tong822218** [comment]
style生效了，，，就是 directives 不生效 ，麻烦大佬给个思路

**Comment by xaboy** [comment]
这个自定义指令挂载全局了吗

目前指令必须挂载到全局才可以生效

**Comment by tong822218** [comment]
在main.js里面挂到全局了，在这里卡住好久了，，，，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaboy/form-create"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 下午3:09
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Calm"<327637616@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] 自定义指令不生效-急急急 😂 (#297)





 
这个自定义指令挂载全局了吗
 
目前指令必须挂载到全局才可以生效

**Comment by xaboy** [comment]
我检查一下

**Comment by tong822218** [comment]
给大佬点赞




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaboy/form-create"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 下午4:09
收件人:&nbsp;"xaboy/form-create"<form-create@noreply.github.com&gt;;
抄送:&nbsp;"Calm"<327637616@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaboy/form-create] 自定义指令不生效-急急急 😂 (#297)





 
我检查一下

**Comment by xaboy** [comment]
可以加qq群, 28963712
