### ISSUE TITLE
elementui 怎么获Cascader选中的label 合集

### ISSUE THREAD

**Issue by nimiumiu** [xaboy/form-create#299]
使用$f.el(field).getCheckedNodes() 提示 is not a function
放在$nextTick 中获取也是一样报错

**Comment by xaboy** [comment]
这个需要在组件生成成功后执行,可以放在 `form-create` 的 `mounted`事件中执行试试

**Comment by nimiumiu** [comment]
点击提交的时候组件已经生成了提示 is not a function

**Comment by xaboy** [comment]
form-create 是那个版本,我检查一下

**Comment by nimiumiu** [comment]
"@form-create/element-ui": "^1.0.20",

**Comment by xaboy** [comment]
2.5版本已优化
