### ISSUE TITLE
请问自定义按钮怎么设置?

### ISSUE THREAD

**Issue by meihangbo** [xaboy/form-create#30]
大神,请问自定义按钮怎么显示出文字, 我这样设置,按钮出来了,但是没有问题,图标也没出来.
`
{
  type: "i-button",
  field: "mySubmit",
  value: "搜索",
  props: {
    "type": "primary",
    "loading": true,
    "icon": "md-search"
  },
  col:{
    span:8
  }
}
`

**Comment by xaboy** [comment]
是不是`md-search`这个图标不存在

**Comment by meihangbo** [comment]
图标用的iview的,应该存在的,文字不知道怎么设置

**Comment by xaboy** [comment]
iview2和3有些图标名字变了
http://jsrun.net/ychKp/edit 可以参考一下这个

**Comment by meihangbo** [comment]
明白了,谢谢大神  @xaboy
