### ISSUE TITLE
fApi.fields()无法获取表单字段

### ISSUE THREAD

**Issue by canomh** [xaboy/form-create#302]
2.5.0-alpha.2

element-ui

2.12.0

在表单加载完成后，使用fApi.fields()函数无法获取表单字段，返回值为[]。（通过fApi.form验证，表单实际有字段）

在全局配置中，使用mounted属性，在函数中输出fApi.fields()。（规则文件较大，不便展示）
当将规则简化为如下形式后，仍存在此问题。
```json
[
    {
      type: 'input',
      field: 'projectBase-projectNum',
      title: '选题序号'
    },
    {
      type: 'input',
      field: 'projectBase-projectName',
      title: '项目名称'
    }
]
```

使用fApi.fields()函数可以获取表单字段

无

**Comment by xaboy** [comment]
感谢反馈 ,我检查一下

**Comment by xaboy** [comment]
@canomh 我这边没有复现,在 option.mounted 中能正常获取到 fields. [在线示例](http://jsrun.net/NQhKp/edit)

**Comment by canomh** [comment]
非常感谢，我再看一下具体原因。

**Comment by canomh** [comment]
@xaboy 你好，

**Comment by canomh** [comment]
@xaboy 你好，

**Comment by canomh** [comment]
@xaboy 你好，
由于我的表单规则文件较多，采用了动态import的方式加载rule，在使用此方式的基础上，mounted函数中无法正常输出fApi.fields()的值，即便对rule的加载使用了async和await（fields的使用等待rule加载的完成），仍然无法正确获取fields。
该方法在2.5.0版本之前是生效的，请问应该如何处理来适配2.5.0版本？

**Comment by xaboy** [comment]
我这边先检查一下

**Comment by canomh** [comment]
相关代码如下
```javascript
  // 规则加载函数
  let module = await import('@/utils/form/rule/'+ ruleName)
  const ruleFunc = module.default
  const ruleArray = ruleFunc()
  _.each(ruleArray, function(value) {
    rule.push(value)
  })

  // 调用规则加载函数
  this.ruleLoaded = dispatch(this.ruleName, this.rule);

  // 使用表单fields的值
  await this.ruleLoaded 
  let fields = this.fApi.fields()
  console.debug('使用表单属性', fields)
```

**Comment by xaboy** [comment]
2.5.0-alpha.5 版本优化了下 你再试试

**Comment by canomh** [comment]
谢谢！经过验证，此问题已解决。
