### ISSUE TITLE
官网文档有错

### ISSUE THREAD

**Issue by iFTY-R** [xaboy/form-create#303]
1.0.18

iview

3.2.2

http://www.form-create.com/v2/guide/editor.html#%E7%A4%BA%E4%BE%8B
官方文档  富文本组件 有问题
![图片](https://user-images.githubusercontent.com/40951966/109266146-98b36380-7842-11eb-9293-605cb5491649.png)

**Comment by xaboy** [comment]
感谢反馈

**Comment by xaboy** [comment]
已优化
