### ISSUE TITLE
时间选择器TimePicker配置pickerOptions参数无效果

### ISSUE THREAD

**Issue by nimiumiu** [xaboy/form-create#304]
最新版本使用TimePicker，配置pickerOptions参数如下后，时间开始、结束、间隔都没生效，如图：
![图片](https://user-images.githubusercontent.com/17876928/110063799-cbaba900-7da6-11eb-8982-055c32f79e20.png)

```
{
    type: "TimePicker",
    field: "section_time",
    title: "活动时间",
    value: [],
    props: {
        isRange:true,
        pickerOptions: {
          start: '08:30',
          step: '00:15',
          end: '18:30'
        }
    },
}
```

**Comment by xaboy** [comment]
@nimiumiu  那个UI版本

**Comment by nimiumiu** [comment]
最新版本2.5.0

**Comment by nimiumiu** [comment]
有解决方案吗？急着用

**Comment by xaboy** [comment]
`type`修改为`ElTimeSelect`就好了

**Comment by nimiumiu** [comment]
form-create官方文档中没看到这个组件，是还没更新吗

**Comment by xaboy** [comment]
`ElTimeSelect`相当于是自定义组件, form-create 可以生成任何 vue 组件. 
内置组件`TimePicker`只是相当于自定义组件`ElTimePicker`+内部处理

**Comment by xaboy** [comment]
pickerOptions是`ElTimeSelect`组件的配置项,所以在`ElTimePicker`组件上无效. 这个问题下个版本会优化一下

**Comment by xaboy** [comment]
好用的话可以点个 `star` 支持一下 感谢
