### ISSUE TITLE
全局col布局配置失效

### ISSUE THREAD

**Issue by canomh** [xaboy/form-create#306]
@form-create/element-ui@2.5.0

element-ui@2.8.2

通过全局配置中的global配置项，配置所有组件的col为span: 12时，组件渲染后实际是span: 24。

```json
global: {
      '*': {
        col: {
            span: 12
        }
}
```

通过global可以配置全局col布局

无

**Comment by xaboy** [comment]
我这边检查一下

**Comment by xaboy** [comment]
感谢反馈. 这是个 bug. 下个版本修复.

**Comment by xaboy** [comment]
2.5.0-alpha.6已发布

**Comment by canomh** [comment]
经验证，此问题已解决。
感谢 @xaboy !
