### ISSUE TITLE
组件间联动

### ISSUE THREAD

**Issue by EdwardCheck** [xaboy/form-create#307]
@form-create/element-ui@2.5.0

//2.13.0

rules通过后端返回json格式，现有A/B 2个表单组件，A组件选择一个远程数据后（例如select），B组件需要根据A的已选数据来作为参数请求后端数据，这个要怎么写？当前用到了新版本的control，但是后端传递json数据不能写handle这样的function格式。

**Comment by xaboy** [comment]
目前建议是通过自定义属性,然后在自定义属性的初始化回调中设置不支持 json 传递的数据 @EdwardCheck 
相关文档: http://form-create.com/v2/guide/effect.html
