### ISSUE TITLE
请问 AutoComplete 自动完成 这个组件有计划开发进去吗？

### ISSUE THREAD

**Issue by trensy** [xaboy/form-create#31]
AutoComplete 自动完成 这个组件后台开发经常会用到，不知道大牛有计划开发没有

**Comment by xaboy** [comment]
有需要的话,下个版本或下下个版本可以增加这个组件.

**Comment by trensy** [comment]
👍有需要的，做crm这块经常需要，另外php-formbuild看能不能也更新一下 😆

**Comment by xaboy** [comment]
form-builder 更新估计得到下个月了😂

**Comment by trensy** [comment]
👍神速

**Comment by xaboy** [comment]
👍

**Comment by xaboy** [comment]
1.5.0版本已支持该组件 @trensy
