### ISSUE TITLE
表单提交时出现Cannot read property 'validate' of undefined异常

### ISSUE THREAD

**Issue by canomh** [xaboy/form-create#310]
@form-create/element-ui@2.5.0-alpha.6

element-ui@2.15.1

表单提交时出现Cannot read property 'validate' of undefined异常
![image](https://user-images.githubusercontent.com/7709455/111759509-a0fa3e00-88d8-11eb-921a-7ea2711b9b9d.png)

**Comment by xaboy** [comment]
这个是通过`hidden`隐藏了 `group`,`object`组件导致的

**Comment by canomh** [comment]
> 这个是通过`hidden`隐藏了 `group`,`object`组件导致的

我们表单字段较多，通过hidden控制分为多个tab展示字段，请问这个现象有什么方法可以避免？

**Comment by canomh** [comment]
该问题已经通过将hidden替换为display解决了。
@xaboy ，谢谢！
