### ISSUE TITLE
在group中设置自定义组件，修改自定义组件值，group值不更新

### ISSUE THREAD

**Issue by hothear** [xaboy/form-create#311]
我自定义一个fupload组件用于文件上传，现在通过数组组件的方式实现自定义增减发现在首次上传文件后gulp的值可以更新，在此删除或者上传文件group中的值就不更新了，奇怪的是在不使用group数组组件式，值可以正常的更新，还望大佬指点一下，谢谢！
![image](https://user-images.githubusercontent.com/12608488/111788313-e92a5800-88fa-11eb-8131-f722564763b7.png)

**Comment by xaboy** [comment]
`group` 和 `object`组件的`props.rule`不支持修改.
如果要修改子表单的值,必须通过修改`group`组件的`value`来实现 @hothear
