### ISSUE TITLE
是否支持antdesignvue2.x

### ISSUE THREAD

**Issue by wsxe9988** [xaboy/form-create#312]
是否支持antdesignvue2.x

**Comment by xaboy** [comment]
这个会在适配 vue3时同步适配. 在计划中但是没有那么快, 当前的任务是拖拽 @wsxe9988

**Comment by wsxe9988** [comment]
嗯很好。今年有roadmap嘛 ？你说的现在在做拖拽 是这个框架对应可视化编辑器嘛

**Comment by xaboy** [comment]
没有, 是的 直接通过拖拽组件创建表单的规则

**Comment by longkele** [comment]
支持vue3 有排期吗？

**Comment by xaboy** [comment]
vue3已经在适配中 @longkele

**Comment by xaboy** [comment]
3.0版本已发布
