### ISSUE TITLE
通过模板生成的组件存在不合理的margin-left样式

### ISSUE THREAD

**Issue by canomh** [xaboy/form-create#313]
@form-create/element-ui@2.5.0-alpha.6

2.15.1

当使用type:'template'的方式生成组件（且未声明title属性），生成元素的父div存在不合理的margin-left。
此margin-left为全局labelWidth配置的值，当存在title并生成label时，此样式是合理的。

```json
    {
      type: 'template',
      field: 'fund-head',
      template: '<label style="text-align: center; font-weight: bold;">金额</label>',
      col: {
        span: 4
      }
    }
```

template类型自定义组件生成的元素样式中不预留左侧label空间。

**Comment by canomh** [comment]
可通过对template类型组件配置特殊的labelWidth解决此问题

**Comment by xaboy** [comment]
这个问题可以优化,我再评估一下

**Comment by xaboy** [comment]
2.5.2版本已优化

**Comment by canomh** [comment]
谢谢！@xaboy
