### ISSUE TITLE
TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by Jinming6** [xaboy/form-create#314]
![image](https://user-images.githubusercontent.com/57794614/111960836-3725a280-8b2b-11eb-88a9-553b38e989bc.png)

从1.*版本升级至2.5.1后，运行项目，出现该问题。

无

无

**Comment by xaboy** [comment]
可能是 rule 没有定义 type 导致的

**Comment by Jinming6** [comment]
> 可能是 rule 没有定义 type 导致的

1、创建MyComponentA.vue
2、Home页将MyComponentA.vue导入，并注册.
3、rule: [
   {
       type: MyComponentA
   }
]

-------------------------------------
type都定义了，怀疑是因为自定义组件的问题。

**Comment by xaboy** [comment]
type 是字符串,不是组件
