### ISSUE TITLE
Wrap element for submitBtn 

### ISSUE THREAD

**Issue by sondh0127** [xaboy/form-create#315]
Is there any option to add [https://element.eleme.io/#/en-US/component/popconfirm](https://element.eleme.io/#/en-US/component/popconfirm) for submitBtn

**Comment by xaboy** [comment]
Currently not supported, it is recommended to hide the built-in buttons and implement them through custom buttons 
[reference](http://form-create.com/en/v2/guide/default-button.html)

**Comment by sondh0127** [comment]
> Currently not supported, it is recommended to hide the built-in buttons and implement them through custom buttons
> [reference](http://form-create.com/en/v2/guide/default-button.html
Thank you, awesome work :fire:!
