### ISSUE TITLE
mergeRule 更新问题

### ISSUE THREAD

**Issue by LZHD** [xaboy/form-create#317]
form-create/element-ui@2.5.1
如果 `rule` 中对应组件的某个非必要属性未定义（比如 `props` 中的某个属性），用 `mergeRule` 更新对应的属性是不生效的吗？
也可能是我理解的有问题，谢谢啦。

**Comment by xaboy** [comment]
不提前定义可能会导致 vue 检测不到数据变化,所以导致视图没有渲染 @LZHD

**Comment by LZHD** [comment]
@xaboy 谢谢哦。
应该跟这个也有关系，但是文档里面的 demo 更新 rule 是生效的，可能是我代码那写的有问题。

**Comment by LZHD** [comment]
@xaboy 谢谢哦。
应该跟这个也有关系，但是文档里面的 demo 更新 rule 是生效的，可能是我代码那写的有问题。

**Comment by LZHD** [comment]
还有个跟文档相关的问题，codepen.io 相关的示例单标签写法 `<form-create />` 之后的内容不渲染，标签驼峰式写法比如 `ElButton` 渲染也有问题。
