### ISSUE TITLE
removeFields方法无效

### ISSUE THREAD

**Issue by vuvivian** [xaboy/form-create#319]
"@form-create/element-ui": "^1.0.19",

   "element-ui": "^2.13.2",

问题描述 ：removeFields方法无效

直接调用实例的removeField方法：
`this.formModelApi.removeField(field);`

 期望的结果 removeFields方法可以删除掉指定field

**Comment by xaboy** [comment]
可以套在$nextTick 方法里面试试,
或者更新到最新的2.5.2版本
