### ISSUE TITLE
option中global属性异常丢失

### ISSUE THREAD

**Issue by canomh** [xaboy/form-create#320]
@form-create/element-ui@2.5.2

2.15.1

在表单初始化时配置了option的global属性，但在加载后引用option时缺少global属性。
该问题导致global中设置的布局、属性全部失效。

this.option.formData = someValue;

**Comment by xaboy** [comment]
怎么复现 @canomh

**Comment by canomh** [comment]
在created方法中对form-create的option属性进行赋值，此时表单global配置存在、渲染正常。
当表单数据重新加载时（即对option赋值时），global配置的值丢失。
```vue
<form-create :rule="rule" v-model="fApi" :option="options" />



created: function() {
    this.options = getOption()
}


methods: {
    reload(formData) {
        this.options.formData = convert(formData)
    }
}

```

**Comment by xaboy** [comment]
global 失效问题下个版本修复. 但是 formData 只在初始化的时候生效一次,二次赋值是没有效果的. 
推荐使用 `value.sync`属性 [相关文档](http://form-create.com/v2/guide/v-model.html)

**Comment by canomh** [comment]
谢谢！@xaboy

**Comment by xaboy** [comment]
2.5.4版本已修复
