### ISSUE TITLE
updateRule之后导致根组件已经设置的$watch失效

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#321]
@form-create/element-ui@1.0.20

element 
2.15.1

updateRule更新部分rule之后，根组件的watcher都被更新导致$watch失效

重新生成规则，应用updateRule更新之后，根组件的watcher失效

根组件$watch的监听应该依然有效

**Comment by Lysom** [comment]
update第三个参数为true

**Comment by xaboy** [comment]
怎么复现?
