### ISSUE TITLE
fetch配置中的data，不支持嵌套的json对象吗？

### ISSUE THREAD

**Issue by zcgelppa** [xaboy/form-create#324]
{
                  type:'select',
                  field:'city',
                  title:'城市',
                  value:'',
                  options: [],
                  effect:{
                      fetch: {
                          action:'/api/get',
                          to: 'options',
                          method:'POST',
                          data: {'Dicts[]':{'Dicts':{'@column':'id,name'}}},
                          parse(res){
                              return res['[]'].map(row=>{
                                  return {
                                      label: row.name,
                                      value: row.id
                                  }
                              })
                          }
                      }
                  }
              }
这样发送给后端的数据是 Dicts[] [object Object]
我如何单独替代fetch.js?

**Comment by xaboy** [comment]
`2.5.5`版本已支持
