### ISSUE TITLE
notarget No matching version found for @form-create/component-elm-frame@^2.5.4

### ISSUE THREAD

**Issue by EdwardCheck** [xaboy/form-create#334]
版本号 (version) 
 @form-create/element-ui@2.5.5 

> 

 问题描述 (Issue) 
安装时提示内部依赖找不到？这个有遇到吗
npm install @form-create/element-ui 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @form-create/component-elm-frame@^2.5.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@form-create/element-ui'        
npm ERR! notarget

**Comment by xaboy** [comment]
是不是设置了国内镜像, component-elm-frame`2.5.4`版本是存在的

**Comment by EdwardCheck** [comment]
> 是不是设置了国内镜像, component-elm-frame`2.5.4`版本是存在的

嗯，是的，已经解决了，因为私服用的国内镜像，最新版本还停在2.5.2，代理地址换成npmjs的可以安装
