### ISSUE TITLE
没有datatimepicker组件吗

### ISSUE THREAD

**Issue by muziling** [xaboy/form-create#335]
文档和例子里只有TimePicker和DatePicker，没有同时选择日期和小时的组件吗？类似这个：https://element.eleme.cn/#/zh-CN/component/datetime-picker

**Comment by xaboy** [comment]
datetimepicker 组件与 datePicker 合并在一起,通过 datePicker 组件生成即可.

**Comment by muziling** [comment]
有使用说明例子吗，试了几种方式都不行

**Comment by xaboy** [comment]
```js
        {
            type:'DatePicker',
            field:'datePicker',
            props:{
                type:'datetime'
            }
        }
```

说明文档: http://form-create.com/v2/element-ui/components/date-picker.html#props
