### ISSUE TITLE
input 后缀为选择框无法选值

### ISSUE THREAD

**Issue by catandrat111** [xaboy/form-create#337]
@form-create/element-ui@2.5.5 
 element-ui: 2.15.1

 {
          type: 'input',
          field: 'dixiaomoney',
          title: 'sss',
          value: 'qq',
          validate: [{ type: 'string', required: true, message: '请输入名称' }],
          suffix: {
            type: 'select',
            field: 'select1',
            value: null,
            children: [
              {
                validate: [{ required: true, message: '请选择名称' }],
                props: {
                  multiple: false
                },
                options: [
                  {
                    value: '1',
                    label: '低消用量'
                  },
                  {
                    value: '2',
                    label: '低消金额'
                  }
                ]
              }
            ]
 }
选择框无法选值 报 Missing required prop: "value"

**Comment by xaboy** [comment]
目前组件的前缀,后缀还不支持表单组件
