### ISSUE TITLE
是否有获取vue代码的api

### ISSUE THREAD

**Issue by houxieyu** [xaboy/form-create#342]
我比较喜欢从数据库配置的json生成vue代码，然后再添加到项目里，这样交给别人维护比较好交接。纯用json动态生成的话，维护起来不方便的。
如果能给一个从配置json转成vue代码的api那就太美啦。感谢，爆赞

**Comment by xaboy** [comment]
没有这个功能😅

**Comment by houxieyu** [comment]
兄弟费心了
