### ISSUE TITLE
是否会考虑支持group 更改布局/新增删除图标修改

### ISSUE THREAD

**Issue by MasterHung** [xaboy/form-create#349]

**Comment by xaboy** [comment]
目前不支持, 后面版本会考虑

**Comment by lbc19920615** [comment]
这个需求还是挺重要的 求优先处理

**Comment by longkele** [comment]
这个功能不复杂，可以考虑 熟悉下源码，提交pr；

**Comment by muziling** [comment]
+1 ,希望能改成动态tab个数布局之类的，  group 套 iview 样式都乱了。

**Comment by xaboy** [comment]
后面会出 table 布局

**Comment by Jimxinfang** [comment]
> +1 ,希望能改成动态tab个数布局之类的， group 套 iview 样式都乱了。

老哥解决了吗，这个问题

**Comment by im-not-a-programmer** [comment]
请问这个问题解决了吗？

**Comment by im-not-a-programmer** [comment]
> > +1 ,希望能改变动态tab个数布局之类的，组iview样式都乱了。
> 
> 老哥解决了吗，这个问题

老哥，您这个问题解决了吗？

**Comment by BelenLuo-tech** [comment]
> > +1 ,希望能改成动态tab个数布局之类的， group 套 iview 样式都乱了。
> 
> 老哥解决了吗，这个问题

您好，请问问题解决了吗？
