### ISSUE TITLE
在vue中使用， 上传图片无法回显

### ISSUE THREAD

**Issue by lxdora** [xaboy/form-create#356]
在vue中使用， 上传图片无法回显， 可能是我用的不对， 看着文档不是很理解， 直接在onSuccess里面返回url不能显示， 下面写$f.uploadPush(), 但是我没有$f,不太明白该如何处理
 "onSuccess": function(res) {
        return res.data.file_url
      },
      //文件上传成功时的钩子，返回字段为 response, file, fileList, 使用$f.uploadPush(field,filePath) 将上传后的路径添加到value中

**Comment by xaboy** [comment]
这样操作即可
```js
        onSuccess:function (res, file) {
            file.url = res.data.file_url;
        }
```
相关文档: http://form-create.com/v2/element-ui/components/upload.html

**Comment by lxdora** [comment]
> 这样操作即可
> 
> ```js
>         onSuccess:function (res, file) {
>             file.url = res.data.file_url;
>         }
> ```
> 
> 相关文档: http://form-create.com/v2/element-ui/components/upload.html

非常感谢
