### ISSUE TITLE
在ssr的server环境全局注册，报name is not undefine

### ISSUE THREAD

**Issue by busyShadow** [xaboy/form-create#357]
@form-create/element-ui@2.5.7

 UI 框架的版本:ant-design-vue  V1.7.4

  组件库在ssr环境里引入，前端是使用Vue.use进行全局注册，如果不在 nuxt-config.js  => plugins对象里设置应用范围为client，会报错提示name is not undefine并阻塞浏览器渲染

该组件库有计划支持ssr，server环境渲染组件吗？

**Comment by xaboy** [comment]
目前还没有兼容 ssr

**Comment by mei2015** [comment]
你好 nuxt3 引入使用报 $formCreate 未定义 怎么回事 是不支持 nuxt3吗
![image](https://github.com/xaboy/form-create/assets/10136065/aa2a0152-416d-4ba0-9246-7fc882aed546)

`import formCreate from '@form-create/element-ui'
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(formCreate)
})`
> 目前还没有兼容 ssr

**Comment by jarvis000000** [comment]
> 你好 nuxt3 引入使用报 $formCreate 未定义 怎么回事 是不支持 nuxt3吗 ![image](https://user-images.githubusercontent.com/10136065/243373926-aa2a0152-416d-4ba0-9246-7fc882aed546.png)
> 
> `import formCreate from '@form-create/element-ui' export default defineNuxtPlugin((nuxtApp) => { nuxtApp.vueApp.use(formCreate) })`
> 
> > 目前还没有兼容 ssr

同样的问题，nuxt3 不使用 ssr 只使用 client 的该怎么引入啊

**Comment by mengyangdy** [comment]
请问在nuxt3中使用，有解决方法了吗？
