### ISSUE TITLE
formCreate is not defined

### ISSUE THREAD

**Issue by yhdufei** [xaboy/form-create#36]
在main.js 文件中 import formCreat from 'form-create'
然后在 其它vue文件中，<form-create></form-create>。就报错了
能不能有一个iview   非引用CDN的DEMO吖，很想用，无奈刚手，研究了好几天，没用上

**Comment by yhdufei** [comment]
main.js:


import Vue from 'vue';
import App from './App';
import router from './router';
import store from './store';
import './mock/index.js';  
import './login.js'; 
import './ui.js' ;

import '../mytheme/index.less' ;
import "../mytheme/iconfont/iconfont.less";


import formCreat from 'form-create'//获取生成器
// import { maker } from 'form-create'//三级联动数据,不用可以不引入
// import 'form-create/district/province_city_area.js'


import axios from 'axios' //引入axios  
import echarts from 'echarts'
 

Vue.prototype.$echarts = echarts ;
Vue.prototype.$ajax=axios //修改Vue的原型属性
Vue.prototype.HOME='/'   

Vue.config.productionTip = false;
var vm=new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: { App }
}) 

子页面类似这样：
然后就报错了。。望速救。。
<template>
  <div>
   <form-create></form-create>
</div>
</template>
<script>
   export default {
        data () {
            return {}
         },
         mounted(){ } 
   } 
</script>

**Comment by xaboy** [comment]
可以把错误信息发一下吗
