### ISSUE TITLE
input 设置默认值 异步获取数据

### ISSUE THREAD

**Issue by nightgu** [xaboy/form-create#367]
我使用fetch异步加载数据的方式 希望将 获取的值返回到input value里，通过这种方式设置input的默认值

rule() {
        return {
            type: 'input',
            field: uniqueId(),
            title: '姓名',
            value: '',
            effect: {
                fetch: {
                    action:'http://datavmap-public.oss-cn-hangzhou.aliyuncs.com/areas/csv/100000_province.json',
                    to: 'value',
                    method:'GET',
                    parse(res){
                        return res.rows[0].name;
                    }
                }
            },
            props: {
                type: "text",
                placeholder: '请输入用户名',
            }
        };

希望指导一下，谢谢~

**Comment by xaboy** [comment]
目前好像不支持给`value`赋值, 这个可以优化

**Comment by xaboy** [comment]
2.5.8版本 parse 方法新增第二个参数, rule. 可以手动设置
```
parse(body, rule, api){
   rule.value = body;
}
```

**Comment by youzhiyong** [comment]
> 

除了通过fetch.parse方法给input组件赋默认值外，可以使用props给value赋默认值吗？
[在线编辑器](http://jsrun.net/7ehKp/edit) 上运行不会赋默认值
在`"@form-create/designer": "^1.0.7"  、"element-ui": "^2.15.6"、"vue": "2.7.2"`  版本上可以赋值，但默认值无法进行修改
代码如下：
```
rule:[
        {
            type:"input",
            field:"2q05w96o9wvz",
            title:"age",
            _fc_drag_tag:"input",
            props:{
                value:"18"
            },
            hidden:false,
            display:true
        }
    ]
```
