### ISSUE TITLE
npm run bootstrap 报错

### ISSUE THREAD

**Issue by xiam12345ming** [xaboy/form-create#369]
sh: 1: rimraf: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! form-create@ clear-all: `rimraf package-lock.json node_modules packages/*/node_modules components/*/*/node_modules packages/*/package-lock.json components/*/*/package-lock.json`

**Comment by xaboy** [comment]
执行一下 `npm install rimraf  -g`
