### ISSUE TITLE
control配置里的prepend属性值写第一个组件name时,插入的组件会插到所有组件最后面

### ISSUE THREAD

**Issue by BogenZ** [xaboy/form-create#370]
`    rules: [
              {
                type: "select",
                field: "reportItemName",
                title: "",
                props: {
                  placeholder: "报告单项"
                },
                value: "",
                options: [],
                col: {
                  span: 6,
                  labelWidth: 0
                },
                effect: {
                  fetch: {
                    action: 'http://localhost:8081/easyserver/get/reportItems',
                    to: 'options',
                    method: 'GET',
                    parse(res) {
                      return res.list.map(row => {
                        return {
                          label: row.title,
                          value: row.name
                        }
                      })
                    }
                  }
                },
              },
              {
                type: "select",
                field: "relationName",
                title: "",
                value: "",
                props: {
                  placeholder: "关系"
                },
                col: {
                  span: 6,
                  labelWidth: 0
                },
                options: [
                  {value: "==", label: '等于'},
                  {value: "!=", label: '不等于'},
                  {value: ">", label: '大于'},
                  {value: "<", label: '小于'},
                  {value: "<=", label: '小于等于'},
                  {value: ">=", label: '大于等于'},
                  {value: "between", label: '在某个范围内'},
                  {value: "like", label: '搜索某种模式'}],
                control: [
                  {
                    handle: function (val, fApi) {
                      return fApi.parent.children.length > 1
                    },
                    prepend: 'reportItemName',
                    rule: [
                      {
                        type: "select",
                        field: "logical",
                        title: "",
                        value: "",
                        col: {
                          span: 6,
                          labelWidth: 0
                        },
                        props: {
                          placeholder: '逻辑符'
                        },
                        options: [
                          {value: "&&", label: '和'},
                          {value: "||", label: '或'}],
                      }
                    ]
                  },
                ]
              },
              {
                type: 'input',
                title: "",
                field: "relationValue",
                value: "",
                col: {
                  span: 6,
                  labelWidth: 0
                },
                props: {
                  type: "text",
                  placeholder: '请输入项值'
                },
              },
            ],`
希望插到reportItemName也就是第一个组件前面,但是却插在了rules最后一个组件的后面

**Comment by xaboy** [comment]
我检查一下

**Comment by xaboy** [comment]
2.5.8版本已修复
