### ISSUE TITLE
upload回显问题

### ISSUE THREAD

**Issue by klonhj2015** [xaboy/form-create#378]
我们的需求是upload会将文件上传至阿里云的对象存储中，回显需要再请求一下后台获取对象存储中的图片访问链接。
回显的地址不是固定的，需要请求后台API生成，这种我们应该怎么实现呢

**Comment by xaboy** [comment]
可以自己写一个 upload 组件,通过 form-create 生成即可

**Comment by klonhj2015** [comment]
自己写一个组件的demo有可参考的吗

**Comment by xaboy** [comment]
自定义表单组件 : http://form-create.com/v2/guide/custom-form-component.html
