### ISSUE TITLE
rule 后续有考虑 field字段中的值以对象嵌套的形式设置吗？

### ISSUE THREAD

**Issue by daughterRui** [xaboy/form-create#380]
**版本号**
@form-create/element-ui@2.5.0 

**UI 框架的版本**
2.13.0

**问题描述 (Issue)** 

rule 后续有考虑 field字段中的值以对象嵌套的形式设置吗？

类似这种  'field': 'queryParams.id'

现在设置成对象嵌套是报错的

**Comment by xaboy** [comment]
后面针对这个问题做处理

**Comment by miligao** [comment]
请问现在支持这种形式了吗？
