### ISSUE TITLE
group 设置button: false无效 可否group添加button slot并且设置add remove自定义方法

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#381]
@form-create/element-ui@2.5.8

2.15.5

group 设置button: false无效 可否group添加button slot并且设置add remove自定义方法

https://codepen.io/pen?&editors=101
在此设置button: false也是无效的

button: false生效

可否group添加button slot并且设置add remove自定义方法，方便自定义样式和方法

**Comment by xaboy** [comment]
group 组件目前有 button 动态插槽

https://github.com/xaboy/form-create/blob/38222f131937d6a4bc3552939b9cd832808d5772/components/element-ui/group/src/component.jsx#L204

**Comment by yyuezhou** [comment]
> group 组件目前有 button 动态插槽
> 
> https://github.com/xaboy/form-create/blob/38222f131937d6a4bc3552939b9cd832808d5772/components/element-ui/group/src/component.jsx#L204

请问怎么使用呢
