### ISSUE TITLE
DatePicker不支持date类型返回值

### ISSUE THREAD

**Issue by EdwardCheck** [xaboy/form-create#384]
@form-create/element-ui@2.5.0 

问题描述 (Issue) 
DatePicker有支持date类型返回值吗，多数情况下后端都是直接返回date格式而不是string类型，希望能补充。

**Comment by xaboy** [comment]
type定义为`el-date-picker`,就会返回 `date` 类型

**Comment by EdwardCheck** [comment]
> �type定义为`el-date-picker`,就会返回 `date` 类型

感谢解答
