### ISSUE TITLE
父组件A引入form-create，怎么在form-create自定义组件中inject A provide的变量

### ISSUE THREAD

**Issue by Lysom** [xaboy/form-create#389]
@form-create/element-ui@2.5.8

element-ui@2.15.2

如题

rule中自定义子组件想通过inject方式引入根组件方法状态，从而操作根组件状态

**Comment by xaboy** [comment]
这个能正常获取到吧

**Comment by Lysom** [comment]
从子组件this中获取$root是rule中顶层规则的组件，而如果把父组件this通过props形式传入rule顶层规则组件，则会报栈溢出的错误

**Comment by Lysom** [comment]
如果方便的话，请问该怎么获取呢

**Comment by Lysom** [comment]
找到原因，通过组件实例this.$formCreate方式创建动态表单，会有此问题
改为<form-create></form-create>创建则是正常的

**Comment by xaboy** [comment]
通过 this.$formCreate创建的表单和当前组件不是上下级关系,所以获取不到
