### ISSUE TITLE
表单中两个或多个select数据联动

### ISSUE THREAD

**Issue by daughterRui** [xaboy/form-create#394]
版本号 (version) 
@form-create/element-ui@2.5.8

UI 框架的版本 (UI version)
2.11.1

问题描述 (Issue)：
当表单中有两个select，后面一个select的option数据是根据前一个select中option的value值通过请求得到的，这种需求该怎么做，版本2.5.8有实现吗？如果有实现请告知一下技术文档，谢谢

**Comment by xaboy** [comment]
可以通过update 回调实现 http://form-create.com/v2/guide/attr-update.html

**Comment by daughterRui** [comment]
这个实现不了，这个只能说是第一个select值变化后，能走第二个select的update方法。并且update的两个参数都是第二个select的。
我现在的需求是第二个select的下拉数据是第一个select选择后，通过接口拿到的

**Comment by xaboy** [comment]
在第一个 select 的 update回调中加载第二个 select 的下拉数据并赋值

**Comment by daughterRui** [comment]
请问有关于多个select数据联动的例子吗？参考一下

**Comment by xaboy** [comment]
```js
[
    {
        type:'select',
        field:'select1',
        update(val,rule,fapi){
            //api 是第二个select选择项的接口
            api(val).then(res=>{
                fapi.getRule('select2').options = res.data
            })
        }
    },{
        type:'select',
        field:'select2',
        options: []
    }
]

**Comment by daughterRui** [comment]
好的   了解了   没注意到文档上update方法的第三个参数fapi
