### ISSUE TITLE
form-create支持uniapp吗

### ISSUE THREAD

**Issue by cmcc2018** [xaboy/form-create#397]
form-create支持uniapp吗

**Comment by xaboy** [comment]
不支持

**Comment by cmcc2018** [comment]
> 不支持

后续有考虑兼容uniapp吗，毕竟uniapp现在用户群体挺大的

**Comment by xaboy** [comment]
有时间的话会考虑.  目前太忙了, 主要精力在适配 vue3

**Comment by nnbbnbzb** [comment]
现在有开始适配uniapp了么

**Comment by transtone** [comment]
https://ext.dcloud.net.cn/plugin?id=18349
