### ISSUE TITLE
能否支持tag标签生成

### ISSUE THREAD

**Issue by taochangle** [xaboy/form-create#399]
大牛有没有计划
![image](https://user-images.githubusercontent.com/7435144/131107941-62946b7b-58ae-4ccb-9797-118675d224b3.png)

**Comment by xaboy** [comment]
```js
{type:'el-tag',children:['Tag']}
```

**Comment by taochangle** [comment]
> ```js
> {type:'el-tag',children:['Tag']}
> ```

后面的输入框怎么渲染出来呢，http://www.form-create.com/v2/element-ui 没看到这个组件的文档
![image](https://user-images.githubusercontent.com/7435144/131277952-e188c7ae-d435-4c9a-91c6-5320373c522c.png)
