### ISSUE TITLE
sync属性在rules里的正确写法是什么？

### ISSUE THREAD

**Issue by yinancx** [xaboy/form-create#400]
`
props: {
id: this.id
},
sync: ['id']
`
`
props: {
'id.sync': this.id
}
`
都不对，正确写法是怎样的？

**Comment by xaboy** [comment]
`{props:{id:'1'},sync:['id']}`
当组件里面通过`$emit('update:id',2)`事件更新 `id`后,规则里面的 id 会更新为2
