### ISSUE TITLE
组件用emit传递this, 会错误提示

### ISSUE THREAD

**Issue by sujiewen** [xaboy/form-create#401]
"@form-create/element-ui": "^2.5.8",

vue.runtime.esm.js:619 [Vue warn]: Error in v-on handler: "TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Vue'
    |     property '$options' -> object with constructor 'Object'
    |     property 'router' -> object with constructor 'VueRouter'
    --- property 'app' closes the circle"

引起这个代码一行代码：

this.$emit('returnObjectBack', this)

form-create 2.0以下版本没有问题

**Comment by xaboy** [comment]
转 JSON 的时候报错了, this 不支持转 json

**Comment by sujiewen** [comment]
我子组件向父组件传递this对象，都不行？
