### ISSUE TITLE
@form-create/iview4在使用分组group中使用Cascader出现class遗漏

### ISSUE THREAD

**Issue by menkeydyvh** [xaboy/form-create#403]
版本号：@form-create/iview4@2.5.7
ui框架：view-design@4.5.0

在group中使用Cascader 控件时 Cascader 下拉出来得列表出现class 遗漏  漏掉了ivu-cascader-transfer或者ivu-cascader的设置

出现问题时的样子和源码检测状态
![image](https://user-images.githubusercontent.com/20472494/131975684-6deb42c8-5912-46a3-ab64-07e0c41640dc.png)
![image](https://user-images.githubusercontent.com/20472494/131975731-8fef41fd-4da9-44db-9dab-67d3c0312a8d.png)

正常适合的状态和正常适合的源码
![image](https://user-images.githubusercontent.com/20472494/131975845-e14711fd-2308-4f37-b093-9acc4efb820c.png)
![image](https://user-images.githubusercontent.com/20472494/131975894-88bc98fb-d191-4edb-ac06-25d5a922e513.png)

**Comment by xaboy** [comment]
我这边测试正常,没有复现
