### ISSUE TITLE
有计划支持ant design vue么？

### ISSUE THREAD

**Issue by pangafu** [xaboy/form-create#41]
看最新的代码，好像已经用工厂类去做不同的组件了
应该是可以支持ant design vue的吧？

**Comment by xaboy** [comment]
目前还没有计划,先把 elementUI 支持了.这个以后可以考虑支持😃

**Comment by pangafu** [comment]
感谢你的工作，这个很好用

**Comment by xaboy** [comment]
谢谢你的支持

**Comment by lx3xun** [comment]
同求啊

**Comment by pangafu** [comment]
加油加油，就等着了
现在ant design vue的用户群还挺大的

**Comment by xaboy** [comment]
估计要等很久了,目前还没有计划😨

**Comment by zengxiaowengit** [comment]
作者加油！最近我也有这个想法，想做成可视化界面开发的前端框架。但是后台根据json设计出组件这部分，想法没有你的好。目前做成这样很棒了！有计划后续加入界面拖拽，配置属性，生成页面这样的功能吗？这样的话前端的开发难度又在vue的基础上降低和加速一大截！

**Comment by xaboy** [comment]
@zengxiaowengit  感谢你的支持 有做页面拖拽功能的想法,但是这个工作量太大了,平时上班也比较忙,所有目前还没有计划.

**Comment by zengxiaowengit** [comment]
好的。加油！ant-design-vue靠你来支持了！我学习一下你的代码，希望能把可视化整合进去，要是有一定可行性的话，希望能一起合作！这个项目我觉得价值还是蛮大的！

**Comment by mseaspring** [comment]
我也需要这个功能，有兄弟改造成功的吗，按道理都是同类的，不过我是前端菜鸟- -靠各位大神了

**Comment by xaboy** [comment]
目前没有计划,等ant-design 4.0出来了再定

**Comment by samchenws** [comment]
同求啊

**Comment by ZMK2017** [comment]
ant-design-vue 1.5出了formModel了，大佬整一波？🙄

**Comment by xaboy** [comment]
没有吧, 文档里我没看到 @ZhongMingKun

**Comment by zengxiaowengit** [comment]
> 没有吧, 文档里我没看到 @ZhongMingKun
FormModel确实出来了，看看这个链接
https://www.antdv.com/components/form-model-cn/#components-form-model-demo-dynamic-form-item

**Comment by xaboy** [comment]
666, 我看一下. 可以的话清明假期爆个肝

**Comment by zengxiaowengit** [comment]
> 666, 我看一下. 可以的话清明假期爆个肝

给你点赞赞，拉star 
:)

**Comment by qriv** [comment]
@xaboy 清明假期已经过了,  肝爆了有进展吗? :)

**Comment by xaboy** [comment]
除 upload 组件外基本适配完成, 目前还在调优. 
最近比较忙,还需要一些时间

**Comment by qriv** [comment]
> 除 upload 组件外基本适配完成, 目前还在调优.
> 最近比较忙,还需要一些时间

出dev版本吗?  还是直接出稳定版

**Comment by xaboy** [comment]
这段时间比较忙.大家不要着急,快了

**Comment by xaboy** [comment]
@qriv  @zengxiaowengit  @ZhongMingKun  @samchenws  @pangafu @lx3xun 
ant-design-vue 版已发布,[文档](http://www.form-create.com/v2/ant-design-vue/)

**Comment by fandudu** [comment]
design好像还不支持啊，用design必须得安装element么
