### ISSUE TITLE
安装包错

### ISSUE THREAD

**Issue by wangi4myself** [xaboy/form-create#410]
想在现有的业务上加入form-create 但是运行后报了一堆core-js/modules/es.array.concat.js丢失的问题
![image](https://user-images.githubusercontent.com/26651458/135218809-7c343236-7917-4233-800d-8fea022f3e66.png)

{
  "name": "guixin2-web-admin",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "build:uat": "vue-cli-service build --mode uat",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@form-create/ant-design-vue": "^2.5.9",
    "ant-design-vue": "^1.7.6",
    "axios": "^0.21.1",
    "echarts": "^5.1.2",
    "element-ui": "^2.15.6",
    "jquery": "^3.6.0",
    "js-cookie": "^3.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "qrcodejs2": "0.0.2",
    "quill": "^1.3.7",
    "quill-image-resize-module": "^3.0.0",
    "v-viewer": "^1.6.4",
    "vue": "^2.6.11",
    "vue-amap": "^0.5.10",
    "vue-cropper": "^0.5.6",
    "vue-quill-editor": "^3.0.6",
    "vue-router": "^3.2.0",
    "vue-ueditor-wrap": "^2.4.4",
    "vuedraggable": "^2.24.3",
    "vuex": "^3.4.0",
    "vxe-table": "^3.3.10",
    "webpack-jquery-ui": "^2.0.1",
    "xe-utils": "^3.3.1",
    "xlsx": "^0.17.2"
  },
  "devDependencies": {
    "@babel/plugin-syntax-jsx": "^7.14.5",
    "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
    "@vue/babel-preset-jsx": "^1.2.4",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "less": "^4.1.1",
    "less-loader": "^6.0.0",
    "lint-staged": "^9.5.0",
    "prettier": "^2.2.1",
    "vue-template-compiler": "^2.6.11"
  }
}

能够正常运行

看文档ant-desgin-vue 是支持到1.5.2 自己的版本是1.7.2不清楚是有有影响

**Comment by xaboy** [comment]
看报错好像是`core-js`包的版本问题

**Comment by wangi4myself** [comment]
之前node版本从12.21.0 安装出错，后面安装到14.18.0出现上述情况，现在升级到最新的16.10.0已经解决问题。感谢作者的及时回复
