### ISSUE TITLE
You may have an infinite update loop in watcher with expression "rule"

### ISSUE THREAD

**Issue by anzai1990** [xaboy/form-create#416]
控制台输出 You may have an infinite update loop in watcher with expression "rule"

从一个页面跳转另一个页面,后一个页面加载时执行this.rule = myRule操作,如果有control规则,会报错You may have an infinite update loop in watcher with expression "rule",去掉control部分则不会报错,当前页面直接刷新也不会出现报错,修改为this.rule = JSON.parse(JSON.stringify(myRule)) 报错也会消失

**Comment by xaboy** [comment]
生成规则发下 , 我试试

**Comment by anzai1990** [comment]
`[
      {
        type: 'div',
        class: 'bg_f9 pad_20 h2 mar_b20 color_3 bold overHide',
        children: ['分销等级设定'],
      }, {
        type: "radio",
        title: "",
        field: "level",
        value: 3,
        options: [
          {
            value: 1,
            label: "一级分销",
            disabled: false
          },
          {
            value: 2,
            label: "二级分销",
            disabled: false
          },
          {
            value: 3,
            label: "三级分销",
            disabled: false
          },
          {
            value: 0,
            label: "不开启",
            disabled: false
          },
        ],
      }, {
        type: 'div',
        class: 'bg_f9 pad_20 h2 mar_b20 color_3 bold overHide',
        children: ['分享设置'],
      }, {
        type: "radio",
        title: "",
        field: "share_type",
        value: 0,
        options: [{
            value: 0,
            label: "分享生成海报方式",
            disabled: false
          },
          {
            value: 1,
            label: "分享链接方式",
            disabled: false
          },
        ],
        control: [
          {
            value: 0,
            rule: [
              {
                type: "upload",
                props:{
                  multiple:false,
                  limit: 1,
                },
                field: "share_img",
                title: "海报首页上传：",
                value:''
              },
              {
                type: "input",
                field: "share_title",
                title: "分享标题：",
              },
            ]
          },
          {
            value: 1,
            rule: [
              {
                type: "upload",
                props:{
                  multiple:false,  
                  limit:  1,
                },
                field: "share_img",
                title: "分享缩略图上传：",
                value:''
              },
              {
                type: "input",
                field: "share_title",
                title: "分享标题：",
              },
              {
                type: "input",
                field: "share_content",
                title: "分享链接内容添加：",
                class: 'textarea_w',
                props: {
                  type: 'textarea',
                  rows: 5,
                },
              }
            ]
          }
        ]
      },
      {
        type: 'div',
        class: 'bg_f9 pad_20 h2 mar_b20 color_3 bold overHide',
        children: ['成为分销商的条件'],
      },
      {
        type: "radio",
        title: "",
        field: "share_condition",
        value: 0,
        options: [
          {
            value: 0,
            label: "无条件",
            disabled: false
          },          {
            value: 1,
            label: "申请",
            disabled: false
          }
        ],
      },
      {
        type: 'div',
        class: 'bg_f9 pad_20 h2 mar_b20 color_3 bold overHide',
        children: ['成为下线条件'],
      },
      {
        type: "radio",
        title: "",
        field: "condition",
        value: 0,
        options: [
          {
            value: 0,
            label: "首次点击分享链接",
            disabled: false
          },{
            value: 1,
            label: "首次下单",
            disabled: false
          },{
            value: 2,
            label: "首次付款",
            disabled: false
          }
        ],
      },
      {
        type: 'div',
        class: 'bg_f9 pad_20 h2 mar_b20 color_3 bold overHide',
        children: ['须知协议'],
      },
      {
        type: "input",
        field: "content",
        title: "佣金用户须知：",
        class: 'textarea_w',
        props: {
          type: 'textarea',
          rows: 5,
        },
      },{
        type: "input",
        field: "agree",
        title: "分销协议：",
        class: 'textarea_w',
        props: {
          type: 'textarea',
          rows: 5,
        },
      }
    ],`

**Comment by xaboy** [comment]
我这边测试没有报错, 用的是2.5.11版本

**Comment by xaboy** [comment]
2.5.12版本做了一些优化
