### ISSUE TITLE
problem with "_vue.extend is not a function"

### ISSUE THREAD

**Issue by hironaokato** [xaboy/form-create#417]
Hello there, I'm using Vite , Vue3 and Element UI (actually Element Plus) 
written under Composition API style.

I tried to very first template code from Usage section on your https://github.com/xaboy/form-create 
but I got this error.

`Uncaught TypeError: _vue.extend is not a function
    at FormCreateFactory (index.js:72)
    at elmFormCreate (index.js:27)
    at index.js:3
    at @form-create_element-ui.js?v=f45a280b:13
    at node_modules/@form-create/element-ui/dist/form-create.min.js (@form-create_element-ui.js?v=f45a280b:14)
    at __require2 (chunk-A2XPJTG4.js?v=f45a280b:19)
    at dep:@form-create_element-ui:1`

I followed the installation and my code is just copy and pasted from the Usage Page, but browser didn't start because of this error. 

Do you have any idea what I can do with? Or if there is anything I should do with, please let me know ;)

Best

**Comment by xaboy** [comment]
Vue3 version is not currently supported, but adaptation is already in progress

**Comment by xaboy** [comment]
form-create3.0 version has been released. Adapt to vue3.0
