### ISSUE TITLE
You may have an infinite update loop in a component render function.

### ISSUE THREAD

**Issue by enjoy-learning-everything** [xaboy/form-create#418]
2.5.8版本正常， 2.5.9开始报错，使用了单选按钮组+组件联动的时候就切换不了属性，会报错You may have an infinite update loop in a component render function.甚至浏览器网页卡死，经排查后，发现就是control规则的问题

简化后的规则为:
[{"type":"object","field":"msgCreator","title":"消息生成方式","info":"","props":{"rule":[{"type":"radio","field":"key","title":"输出类型","info":"","options":[{"value":"aaa","label":"aaa"},{"value":"bbb","label":"bbb"},{"value":"ccc","label":"ccc"},{"value":"ddd","label":"ddd"}],"_fc_drag_tag":"select","hidden":false,"display":true,"control":[{"value":"aaa","rule":[{"type":"object","field":"param","title":"参数","info":"","value":{},"props":{"rule":[{"type":"inputNumber","field":"aaa","title":"A值","info":"","props":{"min":1,"controlsPosition":"default"},"_fc_drag_tag":"inputNumber","hidden":false,"display":true,"value":""}]},"hidden":false,"display":true}]},{"value":"bbb","rule":[{"type":"object","field":"param","title":"参数","info":"","value":{},"props":{"rule":[{"type":"inputNumber","field":"bbb","title":"B值","info":"","props":{"min":0,"step":1,"stepStrictly":true},"_fc_drag_tag":"inputNumber","hidden":false,"display":true,"value":0}]},"hidden":false,"display":true}]},{"value":"ddd","rule":[{"type":"object","field":"param","title":"参数","info":"","value":{},"props":{"rule":[{"type":"inputNumber","field":"ccc","title":"C值","info":"","props":{"min":0,"step":1,"stepStrictly":true},"_fc_drag_tag":"inputNumber","hidden":false,"display":true,"value":0}]},"hidden":false,"display":true}]}],"value":"ddd"}]},"hidden":false,"display":true,"value":{}}]

**Comment by xaboy** [comment]
感谢反馈, 我这边检查一下
