### ISSUE TITLE
选项数据获取时附带数据如何配置成动态获取表单其他属性值

### ISSUE THREAD

**Issue by cn-sy-yl** [xaboy/form-create#419]
![image](https://user-images.githubusercontent.com/29668940/139816014-5a967a08-7b9a-4eb3-a135-8de1123ad8c1.png)
单选框选项数据通过接口获取，但接口需要判断表单中另一个属性的值来动态获取，这种情况该如何配置实现

**Comment by douZiG** [comment]
> ![image](https://user-images.githubusercontent.com/29668940/139816014-5a967a08-7b9a-4eb3-a135-8de1123ad8c1.png) 单选框选项数据通过接口获取，但接口需要判断表单中另一个属性的值来动态获取，这种情况该如何配置实现

老哥 这个实现了吗
