### ISSUE TITLE
radio属性结合event里的change属性问题

### ISSUE THREAD

**Issue by Jackfinal** [xaboy/form-create#42]
点击radio属性，这个change只能获取到点击之前的值，点击之后的值获取不到。。。
麻烦作者怎么能获取点击之后的值
我看了change属性是点击的时候触发，应该是改变值之前触发的，建议增加changed属性，表示点击之后。

**Comment by xaboy** [comment]
你好,请问你使用的是哪个版本?

**Comment by Jackfinal** [comment]
1. iview 3.1.5
2.  form-create v1.5.3

**Comment by xaboy** [comment]
form-create 升级到1.5.5版本应该就没问题了
