### ISSUE TITLE
group组件的onBeforeRemove没有指定将要移除的是哪一项的参数

### ISSUE THREAD

**Issue by EdenAde** [xaboy/form-create#420]
版本号 (version) 
    @form-create/iview@2.5.11

    UI 框架的版本 (UI version) 
    iview@3.5.4

 问题描述 (Issue) 
group组件的onBeforeRemove没有指定将要移除的是哪一项的参数。

期望的结果 (Desired outcome) 
group组件的onBeforeRemove添加指定将要移除的是哪一项的参数。

**Comment by xaboy** [comment]
2.5.12版本增加第二个参数 index
