### ISSUE TITLE
是否支持ts

### ISSUE THREAD

**Issue by NotEdibleSalt** [xaboy/form-create#428]
请问是否支持ts?，我使用的是vue3 + ts + ant-design 在main.ts引入组件时提示：无法找到模块“@form-create/ant-design-vue”的声明文件

**Comment by xaboy** [comment]
3.0目前没有, 后面会完善

**Comment by NotEdibleSalt** [comment]
> 3.0目前没有, 后面会完善

**Comment by NotEdibleSalt** [comment]
好的，期待ts版本的到来
