### ISSUE TITLE
2.5.11 group嵌套时输入子项目，会清空所有数据

### ISSUE THREAD

**Issue by chauncey123** [xaboy/form-create#430]
2.5.11

element-ui 2.13.0

group嵌套时输入子项目，会清空所有数据

group嵌套group
group下面用 control 判断 true、false。
false时显示 子group，增加子group，输入数据，会清空数据

[
          {
            type: 'switch',
            title: '后台分页',
            field: 'backTable',
            value: false,
            props: {
              trueValue: true,
              falseValue: false,
              slot: {
                open: '是',
                close: '否'
              }
            }
          },
          {
            type: 'input',
            title: '接口地址',
            field: 'url',
            value: '',
            validate: [{ type: 'string', required: true, message: '请输入接口地址' }],
            props: {
              class: 'wd400',
              placeholder: '请输入接口地址'
            }
          },
          {
            type: 'input',
            title: '输入请求方法',
            field: 'method',
            value: 'get',
            validate: [{ type: 'string', required: true, message: '请输入请求方法' }],
            props: {
              class: 'wd400',
              placeholder: '请输入输入请求方法'
            }
          },
          {
            type: 'group',
            field: 'filedList',
            title: '字段配置',
            value: [{ label: '', field: '', searchAble: false, type: '' }],
            props: {
              style: 'width: 800px',
              rules: [
                {
                  type: 'input',
                  field: 'label',
                  title: '标题',
                  validate: [{ type: 'string', required: true, message: '请输入标题' }],
                  props: {
                    placeholder: '请输入标题'
                  },
                  col: {
                    span: 12
                  }
                },
                {
                  type: 'input',
                  field: 'field',
                  title: '字段名',
                  validate: [{ type: 'string', required: true, message: '请输入字段名' }],
                  props: {
                    placeholder: '请输入字段名'
                  },
                  col: {
                    span: 12
                  }
                },
                {
                  type: 'select',
                  field: 'type',
                  title: '类型',
                  options: [
                    {
                      'value': 'input',
                      'label': 'input'
                    },
                    {
                      'value': 'select',
                      'label': 'select'
                    }
                  ],
                  validate: [{ type: 'string', required: true, message: '请输入类型' }],
                  props: {
                    placeholder: '请输入类型'
                  },
                  col: {
                    span: 12
                  },
                  control: [
                    {
                      value: 'select',
                      rule: [
                        {
                          type: 'switch',
                          title: '后台分页',
                          field: 'backSearch',
                          value: false,
                          props: {
                            trueValue: true,
                            falseValue: false,
                            slot: {
                              open: '是',
                              close: '否'
                            }
                          },
                          col: {
                            span: 12
                          },
                          control: [
                            {
                              value: true,
                              rule: [
                                {
                                  type: 'input',
                                  field: 'searchUrl',
                                  title: '查询地址',
                                  validate: [{ type: 'string', required: true, message: '请输入查询地址' }],
                                  props: {
                                    placeholder: '请输入查询地址'
                                  },
                                  col: {
                                    span: 12
                                  }
                                }
                              ]
                            },
                            {
                              value: false,
                              rule: [
                                {
                                  type: 'group',
                                  field: 'option',
                                  title: '搜索参数',
                                  key: 'option',
                                  value: [{ key: '', value: '' }],
                                  props: {
                                    rule: [
                                      {
                                        type: 'input',
                                        field: 'key',
                                        title: '标题',
                                        validate: [{ type: 'string', required: true, message: '请输入标题' }],
                                        props: {
                                          placeholder: '请输入标题'
                                        },
                                        col: {
                                          span: 12
                                        }
                                      },
                                      {
                                        type: 'input',
                                        field: 'value',
                                        title: '值',
                                        validate: [{ type: 'string', required: true, message: '请输入标题' }],
                                        props: {
                                          placeholder: '请输入标题'
                                        },
                                        col: {
                                          span: 12
                                        }
                                      }
                                    ]
                                  }
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  type: 'switch',
                  field: 'searchAble',
                  title: '可搜索',
                  props: {
                    placeholder: '请输入字段名'
                  },
                  col: {
                    span: 12
                  }
                }
              ]
            }
          }
        ]

希望能正常增加行，输入数据

**Comment by xaboy** [comment]
![image](https://user-images.githubusercontent.com/21242408/143764517-0f93f6a9-101b-4697-9561-744d22adff06.png)

@chauncey123 我这边测试没有问题

**Comment by chauncey123** [comment]
@xaboy 你用的哪个版本

**Comment by xaboy** [comment]
2.5.12 @chauncey123
