### ISSUE TITLE
移动端支持

### ISSUE THREAD

**Issue by chengpeng666** [xaboy/form-create#431]
请问有没有适配移动端的计划，或者有没有基于现在版本的解决方案

**Comment by xaboy** [comment]
目前没有计划

**Comment by reaink** [comment]
移动端的支持是基于使用的框架的兼容程度的，像输入框什么的，放在一个百分比内就会自动填满

**Comment by LuoRiWuSheng** [comment]
> 请问有没有适配移动端的计划，或者有没有基于现在版本的解决方案

移动端 感觉很难， 企业里 一个正常的 H5或者小程序类， UI程度高的， 做这个是非常耗费成本，且还原度也不是很符合预期； 所以拖拽生成的 H5  和UI还原度差距较大，且还要处理  类似 异形屏兼容问题，比如 iphone X下面的  横条，比如顶部的刘海屏
比如  safari 浏览器里面的 api兼容问题
