### ISSUE TITLE
使用fetch加载异步数据时如何为headers设置token

### ISSUE THREAD

**Issue by xubinlife** [xaboy/form-create#433]
使用json生成表单，为组件设置加载异步数据时，只能在json中为fetch设置静态headers，如何将用户登录状态下的token动态设置到fetch headers，有哪位大佬实现过类似的需求？

**Comment by swuecho** [comment]
token 放到cookie里面，然后后端用 nginx 来把cookie 里面的token 加到header 里面。

https://github.com/PostgREST/postgrest/issues/773

不到万不得已 慎用。

**Comment by xaboy** [comment]
2.5.14版本fetch支持设置为函数, 这样就可以在函数中获取 token 了
