### ISSUE TITLE
ElementPlus select 无法设置options

### ISSUE THREAD

**Issue by wgbbiao** [xaboy/form-create#436]
版本号 (version) 
    例如: @form-create/element-ui@3.0.0-alpha.2 

    UI 框架的版本 (UI version) 
    "element-plus": "^1.2.0-beta.6",

**Comment by xaboy** [comment]
已知 bug, 下个版本修复

**Comment by xaboy** [comment]
3.0.0-alpha.3版本已修复

**Comment by mylove132** [comment]
naive ui组件这个功能设置完成后，页面没有渲染出来。需要点击2次才可以

**Comment by xaboy** [comment]
@mylove132  我这边检查下, 有没有复现规则
