### ISSUE TITLE
clearValidateState called Uncaught TypeError: Cannot read properties of undefined (reading 'tidyFields')

### ISSUE THREAD

**Issue by reaink** [xaboy/form-create#441]
版本号 (version) ：
```
"@form-create/ant-design-vue": "^3.0.0-alpha.4",
```
 UI 框架的版本 (UI version) ：
```
"ant-design-vue": "^3.0.0-beta.7",
```
问题描述 (Issue) ：

未找到  api.helper.tidyFields 方法

已知 3.0.0-alpha.2 没有这个问题

复现步骤/生成规则 (Duplicate steps/generate rules) ：
调用  fApi.clearValidateState()

**Comment by xaboy** [comment]
3.0.1版本已修复
