### ISSUE TITLE
elementUI 不能用

### ISSUE THREAD

**Issue by ttnkh21** [xaboy/form-create#45]
elementUI 不能用 不显示

**Comment by xaboy** [comment]
有错误信息吗，form-create是那个版本？

**Comment by ttnkh21** [comment]
版本是1.6，没有错误信息只显示提交两个字

**Comment by xaboy** [comment]
可以发一下代码吗

**Comment by ttnkh21** [comment]
new Vue({
        el:'#app',
        data:{
            fApi:{},
            model: {},
            rule:[{
                type:"radio",
                title:"是否包邮",
                field:"is_postage",
                value:"0",
                options:[
                    {value:"0",label:"不包邮",disabled:false},
                    {value:"1",label:"包邮",disabled:true},
                ],

            }],

        },
        mounted:function () {
           // this.model = this.fApi.model();
        }
    });

**Comment by xaboy** [comment]
我这边测试没有问题,elementUI版本是2.5.2
