### ISSUE TITLE
按需引入引入 lib 模块而非 es 模块，在Vite中尚无法使用

### ISSUE THREAD

**Issue by reaink** [xaboy/form-create#465]
版本号 (version) 
"@form-create/ant-design-vue": "3.1.1",
"ant-design-vue": "^3.0.0-beta.10",

问题描述 (Issue)
按需引入引入 lib 模块而非 es 模块，在Vite中尚无法使用，不支持 非es模块
https://github.com/xaboy/form-create/blob/22995844f0b3eb7c77302e9e779a1706ece85d4c/packages/ant-design-vue/auto-import.js#L1-L4

在Vite中会报错
``` sh
Uncaught Error: Dynamic require of "web/node_modules/.pnpm/ant-design-vue@3.0.0-beta.10_vue@3.2.31/node_modules/ant-design-vue/lib/style/index.css" is not supported
```

期望的结果 (Desired outcome)
兼容引入模式

建议 (Advice) 
引入时选择引入模式，如
``` ts
formCreate.use(install, {
    // use commonjs build or esm
    cjs: false
})
```

**Comment by xaboy** [comment]
下个版本修复

**Comment by xaboy** [comment]
3.1.2已修复
