### ISSUE TITLE
v3 自定义fetch 请求不能接收一个Promise async 函数，希望优化

### ISSUE THREAD

**Issue by reaink** [xaboy/form-create#466]
自定义  effect  fetch 请求数据函数不能接收一个Promise async 函数，希望优化

**Comment by xaboy** [comment]
promise 返回的数据是最终的数据吗

**Comment by reaink** [comment]
现在所使用的是 .then xxx ，设置数据是通过 rule.options = then 返回拿到的数据
``` ts
{
  type: 'select',
  field: 'roles',
  ...
  effect: {
    fetch(rule: any, api: any) {
      gql
        .query({
          query: FindManyRoleDocument,
        })
        .then(({ data }) => {
          rule.options = data.findManyRole
        })
        .catch(logError)
    },
  }
}
```

期望的写法是fetch 改为一个 await 函数，可以让其直接await 写法

``` ts
{
  type: 'select',
  field: 'roles',
  ...
  effect: {
    async fetch(rule: any, api: any) {
      let { data } = await client.query({
        query: FindManyRoleDocument,
      })
      rule.options = data.findManyRole
    },
  }
}
```

**Comment by xaboy** [comment]
我这边通过这种语法测试功能正常 没发现什么问题

**Comment by reaink** [comment]
我写了个Demo，可以查看 async 的请求最终确实没有发出，而then的成功了
![image](https://user-images.githubusercontent.com/45023042/156538342-6a995f33-9ba7-4f9b-bc55-c93596f3c0c4.png)

地址：https://stackblitz.com/edit/vitejs-vite-krmnr3?devtoolsheight=33&file=src/App.vue
需要您手动运行一下 npm run dev

**Comment by xaboy** [comment]
在 rule 里面预定义一个 options = []

**Comment by reaink** [comment]
加上了，相同结果
https://stackblitz.com/edit/vitejs-vite-hb8crn?devtoolsheight=33&file=src/App.vue

**Comment by xaboy** [comment]
我检查了下,发现是个 bug. 因为 toStirng 返回的是 [object AsyncFunction], 不是 [object Function]. 所以条件没通过. 下个版本优化一下

**Comment by xaboy** [comment]
3.1.3版本已修复
