### ISSUE TITLE
Component Language

### ISSUE THREAD

**Issue by go4cas** [xaboy/form-create#48]
Some of the components seems to have Chinese labels. Examples:
- `ColorPicker`: OK and Cancel button
- `DatePicker`: Day names

Is there a  global setting to use a specific language?

**Comment by go4cas** [comment]
I have fixed this by adding passing in the `locale` to the iview object, in the plugin instantiation:

```javascript
import locale from 'iview/dist/locale/en-US'

Vue.use(iView, {
  transfer: true,
  size: 'small',
  locale
})
```

**Comment by xaboy** [comment]
Element and Iview components use Chinese internally by default. [element](http://element.eleme.io/#/en-US/component/i18n) [iview](https://www.iviewui.com/docs/guide/i18n-en)

**Comment by xaboy** [comment]
So far there are some places in form-create that are Chinese, not customizable, and the next version can all support customization.

**Comment by xaboy** [comment]
Thank you for your support

**Comment by xaboy** [comment]
Already supported in version 1.6.1
