### ISSUE TITLE
自定义插槽异步改变数据视图没更新

### ISSUE THREAD

**Issue by createnana** [xaboy/form-create#482]
@form-create/element-ui": "^2.5.19

2.15.6

异步变动数据视图未更新

![image](https://user-images.githubusercontent.com/12572607/162375447-1c1c2d73-f8f5-4855-9591-4f7205e03bc1.png)
![image](https://user-images.githubusercontent.com/12572607/162375491-66a05eda-524c-4fc6-b5be-09df98462e64.png)

**Comment by xaboy** [comment]
需要在 test 变化后通过调用fapi.sync('name')方法手动同步一下, 这个问题在后面版本可以优化

```
{
            type:'test-slot',
            title:'title',
            native: false,
            name:'name'
}
```

**Comment by xaboy** [comment]
配置 rule.cache = false 即可
