### ISSUE TITLE
建议表单提交获取到的formData仅包含rule定义的字段(2.5.7版本状态就是这样的，新版本就出问题了)

### ISSUE THREAD

**Issue by simplestart-cn** [xaboy/form-create#485]
最新版本表单提交能否不返回非表单定义的字段
低于2.5.7版本是仅返回rule定义的字段的但新版本都会返回额外字段了

如rule:[{
type: 'input',
field: 'title',
value: '',
}]
设置表单值时包含了规则以外的字段
如:api.setValue({
title: 'test',
create_time: '2022/04/08',
update_time: '2022/04/08'
})

赋值后重新提交表单仅返回rule定义的字段 title

建议赋值后重新提交表单仅返回rule定义的字段 title，其他字段如需获取可以自己定义hidden，因为表单赋值往往包含很多后台中间件运算结果或额外自动生成的数据以及一些不同的数据结构，这些数据一般用于显示重新提交容易造成数据混乱甚至报错，一个一个删除又实在头大

**Comment by xaboy** [comment]
下个版本优化一下

**Comment by xaboy** [comment]
2.5.20版本已优化, options 新增 appendValue 配置项, 控制 formData 中是否包含表单中不存在的字段,默认为false
