### ISSUE TITLE
关于2.5.19版本update属性对null值的bug

### ISSUE THREAD

**Issue by chengpeng666** [xaboy/form-create#488]
[
  {
    "info": "",
    "link": [
      ""
    ],
    "type": "input",
    "field": "remainingAmount",
    "props": {
      "disabled": false,
      "readonly": true
    },
    "title": "Remaining Amount",
    "hidden": false,
    "update": "[[FORM-CREATE-PREFIX-function update(val, rule, fApi) {\n    console.log(\"循环\")\n    var totalAmount = fApi.getValue(\"totalAmount\");\n    var waivedAmount=fApi.getValue(\"waivedAmount\");\n    var m = null;\n    fApi.setValue(\"remainingAmount\",m)\n}-FORM-CREATE-SUFFIX]]",
    "display": true,
    "validate": [
      {
        "required": false
      }
    ],
    "_fc_drag_tag": "input"
  }
]

fApi.setValue如果设置值为null会循环触发update，旧版本不会循环触发

**Comment by xaboy** [comment]
2.5.20版本已修复
