### ISSUE TITLE
No validation rules on compiled prod env

### ISSUE THREAD

**Issue by titeya** [xaboy/form-create#489]
@form-create/naive-ui@next
naive-ui 2.28.2

Build tool: vite 2.9.6

When the schema has an array (group) or object component, validation rules are not applied to children.
The problem only impacts the compiled version of the project.
No problem on the development environment.

```
 {
    type: 'group',
    field: 'emails',
    title: 'Emails',
    value: [],
    props: {
      rule: [
        {
          type: 'input',
          field: 'email',
          title: 'Email',
          props: {
            placeholder: 'Email address',
          },
          validate: [{ required: true, message: 'This field is required', trigger: ['input', 'blur', 'change'] }],
        },
      ],
      expand: 1,
    },
  }
```

**Comment by titeya** [comment]
Same behavior with Element-plus (v2.1.11) / @form-create/element-ui 3.1.5 /  vite 2.9.6

**Comment by xaboy** [comment]
Thanks for the feedback, I'll check it out here

**Comment by xaboy** [comment]
I didn't reproduce the problem you asked
link: https://stackblitz.com/edit/vitejs-vite-ktg8ey?file=index.html

**Comment by titeya** [comment]
Thank you for answering.
I was using version 3.1.5 which was problematic. It works fine with version 3.1.3.

**Comment by titeya** [comment]
I reopen this issue because since version 1.4, the validation rules do not work with nested components (object, group).

See below :

[https://stackblitz.com/edit/vitejs-vite-kndjxf?file=src%2FApp.vue,package.json](https://stackblitz.com/edit/vitejs-vite-kndjxf?file=src%2FApp.vue,package.json)

**Comment by xaboy** [comment]
Thanks for the feedback, it will be fixed in the next version

**Comment by xaboy** [comment]
The 3.1.18 version has been released
