### ISSUE TITLE
[QUESTION] - Pre-polutaing Form Data

### ISSUE THREAD

**Issue by go4cas** [xaboy/form-create#49]
@xaboy, are there any helper methods to pre-populate a form with data? I want to be able to pass in an object (JSON data) to the form, and based on the `field` property, be populated with data from the object.

Example data object:
```javascript
{
  name: 'John Smith',
  email: 'john@example.com'
}
```

Form rules:
```javascript
[{
  type: 'input',
  field: 'name',
  title: 'name',
},
  type: 'input',
  field: 'email',
  title: 'email',
}]
```

**Comment by xaboy** [comment]
[$f.setValue](http://form-create.com/guide/instance.html#f-setvalue)
Can this solve your current problem?

**Comment by go4cas** [comment]
Thanks, @xaboy . But that means I need to call `setValue` for every field, right?

```javascript
showModal(entity) {
      this.$f.setValue('name',entity.name)
      this.$f.setValue('email',entity.email)
      this.editModal = true
}
```

**Comment by xaboy** [comment]
There are many ways to modify the worth.😃

```js
$f.bind().field= value
$f.model().field.value = value
rule[2].value = value
$f.changeValue(field,value)
$f.setValue(field,value)
```

**Comment by go4cas** [comment]
Thanks, @xaboy. I have fixed my issue with this:

```javascript
for (let prop in entity) {
  if (prop[0] !== '_') {
    this.fApi.setValue(prop,entity[prop])
  }
}
```
