### ISSUE TITLE
3.1.6/3.1.7  出现错误警告，无法修改内容 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by reaink** [xaboy/form-create#496]
版本号 (version) 
@form-create/ant-design-vue": "^3.1.6"

UI 框架的版本 (UI version) 
ant-design-vue": "^3.2.3"

问题描述 (Issue)
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'apply')
```
![image](https://user-images.githubusercontent.com/45023042/167249571-f6ca5a46-1c73-4ffe-8f12-9d69a90c675e.png)

**Comment by xaboy** [comment]
感谢反馈, 我这边检查下. 可以发下生成规则吗

**Comment by reaink** [comment]
我找到问题了，是因为传入
``` ts
fApi.value.hidden(visible: boolean, field: string)
```
如果visible 传入数字，就会导致抛出错误，现在因为没有ts辅助，我以为可以隐式转换emmm


https://stackblitz.com/edit/vitejs-vite-krmnr3?devtoolsheight=33&file=src%2Fmain.ts,src%2FApp.vue

这里查看控制台

**Comment by reaink** [comment]
我找到他们的类型了，谢谢 @xaboy 
![image](https://user-images.githubusercontent.com/45023042/167341380-d5a762da-2467-4a75-9525-0f1527b0b5a9.png)

**Comment by reaink** [comment]
不对，我发现正常的设置 hidden 也会导致这个错误出现了

  fApi.value.hidden(true, 'user');

请查看 https://stackblitz.com/edit/vitejs-vite-krmnr3?file=src%2FApp.vue

**Comment by xaboy** [comment]
3.1.8版本已修复
