### ISSUE TITLE
Frame 框架width等modal窗口属性无效

### ISSUE THREAD

**Issue by liny1224** [xaboy/form-create#498]
@form-create/iview4@ 2.5.16+

   "view-design": "^4.2.0",

Frame 框架width等modal窗口属性无效。
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/54567105/167390279-93a030a1-1fdd-45a6-a504-7eb85ed09329.png">

跟踪源码发现以下代码可能有问题：
h("Modal", helper([{}, _objectSpread2({
        width: width,
        title: title
    }, this.modal)

ivew需要加 "attrs": {}：
例如：
h("Modal", helper([{}, _objectSpread2({
         "attrs": {
            width: width,
            title: title
          }
    }, this.modal)

**Comment by xaboy** [comment]
@liny1224 你用的是@form-create/element-ui + view-design吗

**Comment by leeseng1224** [comment]
@form-create/iview4  + view-design

**Comment by liny1224** [comment]
form-create/iview4 + view-design吗

**Comment by xaboy** [comment]
2.5.21版本已修复
