### ISSUE TITLE
组件联动control下的rule为字符串时，渲染出错

### ISSUE THREAD

**Issue by gmj-ll** [xaboy/form-create#499]
@form-create/element-ui@3.1.6 

UI 框架的版本: 2.1.11 

问题描述 
组件联动的时候，如果control下面的rule数组内容是字符串的话，刚开始渲染的时候，如果渲染条件为false，会把hidden的在cache中把vnode置空，所以不会渲染，但是当渲染条件改为true时候，cache中这个id的node为undefined，之后在renderCtx函数里面调用return (...args) => this.getCache(ctx)(...args)这一行的时候会报错，因为undefined不是函数，导致渲染出错

复现步骤/生成规则
rule: [
        {
          type: 'checkbox',
          field: 'is_random',
          value: false,
          options: [
            {
              label: '随机时长',
            },
          ],
          control: [
            {
              value: true,
              rule: ['created_at'],
            },
          ],
        },
        {
            type: 'datePicker',
            field: 'created_at',
            title: '创建时间',
        }
      ],

期望的结果：
正常渲染

建议：
return (...args) => this.getCache(ctx)(...args) 改成 return this.getCache(ctx) ? (...args) => this.getCache(ctx)(...args) : undefined

**Comment by xaboy** [comment]
这个问题最新版本已经修复, 更新一下试试
