### ISSUE TITLE
提交按钮配置,设置为false时不显示按钮

### ISSUE THREAD

**Issue by williamBoss** [xaboy/form-create#5]
请问提交按钮不显示如何设置为false

**Comment by xaboy** [comment]
`this.$formCreate(mock,{
            el:root,
           //提交按钮配置,设置为false时不显示按钮
           submitBtn:false
 });`

**Comment by williamBoss** [comment]
谢谢

**Comment by williamBoss** [comment]
请问表单生成的顺序是按照mock的数组顺序生成的吗

**Comment by xaboy** [comment]
是的

**Comment by williamBoss** [comment]
谢谢
