### ISSUE TITLE
生成的表单能否支持跨行显示呢？比如我有个上传照片的上传控件，想在表单下跨3行显示，可以实现吗？

### ISSUE THREAD

**Issue by sweetboy897** [xaboy/form-create#50]

**Comment by xaboy** [comment]
应该是可以的,内置的组件不适用也可以用自定义组件

**Comment by xiongshuo** [comment]
武汉地区 招聘VUE前端开发，有意者私信

------------------------------------------------------------------
发件人：sweetboy897 <notifications@github.com>
发送时间：2019年3月14日(星期四) 18:27
收件人：xaboy/form-create <form-create@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[xaboy/form-create] 生成的表单能否支持跨行显示呢？比如我有个上传照片的上传控件，想在表单下跨3行显示，可以实现吗？ (#50)
