### ISSUE TITLE
Naive UI - some components don't return a value

### ISSUE THREAD

**Issue by titeya** [xaboy/form-create#500]
@form-create/naive-ui@next
naive-ui 2.9.0

See the example below with (InputNumber et TimePicker) :
[https://stackblitz.com/edit/vitejs-vite-ktytp5?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-ktytp5?file=src%2FApp.vue)

**Comment by xaboy** [comment]
Thanks for the feedback, I'll check it out here

**Comment by xaboy** [comment]
Thanks for the feedback, next version optimization. 
At present, you can change the first letter to lowercase and it can be used normally

**Comment by xaboy** [comment]
Fixed in version 3.1.9
