### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by hljhrbgsj** [xaboy/form-create#501]
@form-create/element-ui@3.0 

ElementPlus^2.0

.
npm run dev:ele  后报下面的错

 error  in /node_modules/@form-create/component-elm-frame/src/component.jsx

Module parse failed: Unexpected token (171:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         },
|         makeInput() {
>             return <ElInput {...{
|                 type: 'text',
|                 modelValue: (this.fileList.map(v => this.getSrc(v))).toString(),

....
error  in /node_modules/@form-create/component-elm-select/src/component.jsx

Module parse failed: Unexpected token (30:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     },
|     render() {
>         return <ElSelect {...this.$attrs} modelValue={this.value}
|             onUpdate:modelValue={(v) => this.$emit('update:modelValue', v)}
|             v-slots={getSlot(this.$slots, ['default'])}>{this.options().map((props, index) => {

刚开始学习vue，不知道这个问题怎么解决，能帮忙看一下吗
谢谢

**Comment by xaboy** [comment]
运行流程
```
npm install
lerna bootstrap
npm run dev:ele
```

**Comment by jiahengaa** [comment]
> @form-create/element-ui@3.0
> 
> ElementPlus^2.0
> 
> .
> npm run dev:ele 后报下面的错
> 
> error in /node_modules/@form-create/component-elm-frame/src/component.jsx
> 
> Module parse failed: Unexpected token (171:19) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | }, | makeInput() {
> 
> > ```
> >         return <ElInput {...{
> > ```
> 
> | type: 'text', | modelValue: (this.fileList.map(v => this.getSrc(v))).toString(),
> 
> .... error in /node_modules/@form-create/component-elm-select/src/component.jsx
> 
> Module parse failed: Unexpected token (30:15) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | }, | render() {
> 
> > ```
> >     return <ElSelect {...this.$attrs} modelValue={this.value}
> > ```
> 
> | onUpdate:modelValue={(v) => this.$emit('update:modelValue', v)} | v-slots={getSlot(this.$slots, ['default'])}>{this.options().map((props, index) => {
> 
> 刚开始学习vue，不知道这个问题怎么解决，能帮忙看一下吗 谢谢

解决了吗，如何处理，碰到同样的情况

**Comment by jiahengaa** [comment]
环境版本不对吗
![image](https://github.com/xaboy/form-create/assets/9588909/b28f42c1-fc43-4511-b15f-a6e6acbc83b3)
