### ISSUE TITLE
Unexpected behavior with control & resetFields

### ISSUE THREAD

**Issue by titeya** [xaboy/form-create#506]
@form-create/naive-ui 3.1.9
naive-ui 2.30.2

[https://stackblitz.com/edit/vitejs-vite-5tegwq?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-5tegwq?file=src%2FApp.vue)

To reproduce the bug, turn on the switch and reset the form with the resetBtn. After that, the input disappear.

**Comment by xaboy** [comment]
Thanks for the long-term feedback, this problem will be optimized in the next version.

**Comment by xaboy** [comment]
Version 3.1.10 has been fixed
