### ISSUE TITLE
 无法设置submitBtn的布局

### ISSUE THREAD

**Issue by a303557339** [xaboy/form-create#508]
设置了inline:true和submitBtn.col均无效，是什么原因
options: {
form: {
inline: true,
labelCol: { span: 6 },
wrapperCol: { span: 18 }
},
submitBtn: {
col: {
span: 5
},
block: false,
innerText: '查询'
},
resetBtn: true,
onSubmit: formData => {
console.log(formData)
}
},

**Comment by xaboy** [comment]
表单的行内模式下内置的提交按钮不支持布局
