### ISSUE TITLE
在不使用提交按钮时能有办法触发规则校验么？

### ISSUE THREAD

**Issue by yunchanmian** [xaboy/form-create#509]
"@form-create/element-ui": "^2.5.22",

    "@form-create/element-ui": "^2.5.22",

在不使用提交按钮时似乎没办法做validate的校验，在自定义提交按钮时规则校验无法触发，如使用
this.$refs.formCreateRule.validate的方式会在作用域中找不到formCreateRule

![image](https://user-images.githubusercontent.com/107395827/174220513-6fcbab74-c517-4115-acb2-9fb890011c6a.png)

**Comment by xaboy** [comment]
通过fapi.validate 方法可以手动验证, 内置按钮也是通过这个方法验证的.
相关文档: http://form-create.com/v2/instance.html#%E9%AA%8C%E8%AF%81%E8%A1%A8%E5%8D%95
