### ISSUE TITLE
[QUESTION] - Using component methods from within onSubmit

### ISSUE THREAD

**Issue by go4cas** [xaboy/form-create#51]
How would I call a method defined on the component in the `onSubmit`? Currently `this.add(formData)` does not work.

**Comment by xaboy** [comment]
Sorry,I didn't understand what you mean. You can manually submit the form via `$f.submit`. When the form is verified, the `onSubmit` method can be triggered.

**Comment by go4cas** [comment]
@xaboy, in my component file, I have a method `add`, which i use to update the entity to the API. I would like to call this method from within `onSubmit`.

export default {
  name: 'BrandList',
  mounted: async function () {
    this.model = this.fApi.model()
  },
  methods: {
    add(entity) {
      // call API to insert
    }
  },
  data () {
    return {
      fApi: {},
      model: {},
      option: {
        onSubmit: function (formData) {
          this.add(formData)
        }
      },

**Comment by xaboy** [comment]
```js
export default {
  name: 'BrandList',
  mounted: async function () {
    this.model = this.fApi.model()
  },
  methods: {
    add(entity) {
      // call API to insert
    }
  },
  data () {
    const vm = this
    return {
      fApi: {},
      model: {},
      option: {
        onSubmit: function (formData) {
          vm.add(formData)
        }
      },

```

**Comment by go4cas** [comment]
@xaboy , great thanks!

Another question: I see you use `$f` throughout your docs and examples. But, I can't find where or how to define `$f`.

**Comment by xaboy** [comment]
`$f` is the instance object returned by `form-create`,you can refer to here 
[http://form-create.com/en/guide/instance.html](http://form-create.com/en/guide/instance.html)
