### ISSUE TITLE
upload 组件，在异步数据返回后，没有显示出来，input都可以正常显示

### ISSUE THREAD

**Issue by leochen-g** [xaboy/form-create#510]
"@form-create/ant-design-vue": "^3.1.9",

"ant-design-vue": "^3.2.6",

开发环境：Vue3 + vite + ts

在使用upload组件时，上传没有问题，但是加载完异步数据，进行回显时，页面上upload 组件没有展示出来
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/20028566/174289901-664d6e4d-9209-42fc-8e4b-63555214bdba.png">

希望能够回显

**Comment by leochen-g** [comment]
附上一个在线demo 链接：[https://codesandbox.io/s/lively-bush-nnlynm?file=/src/App.vue](https://codesandbox.io/s/lively-bush-nnlynm?file=/src/App.vue)

**Comment by xaboy** [comment]
3.1.10版本已修复
