### ISSUE TITLE
rule.tile.children渲染到了rule.title.title的前面

### ISSUE THREAD

**Issue by Timo534** [xaboy/form-create#514]
版本号： 
@form-create/ant-design-vue@3.1.10

 UI 框架的版本： 
3.1.0-rc.6

 问题描述:
设置rule.title.children配置（类型声明文件有rule.title.children配置声明），children里面的东西渲染到了rule.title.title的前面

生成规则：
`
{
        type: 'input',
        field: 'field1',
        title: {
          title: 'Title',
          children: ['Children']
        }
      }
`

期望的结果:
设置rule.title.children配置，希望children里面的东西渲染到rule.title.title的后面

建议：
在makeInfo的函数里面新增处理一下rule.title.children的配置的逻辑

**Comment by xaboy** [comment]
感谢反馈 我检查一下
