### ISSUE TITLE
ant-design-vue能否新增一个自定义渲染表单label的功能

### ISSUE THREAD

**Issue by Timo534** [xaboy/form-create#515]
问题描述：
当遇到需要自定label的需求时，无法实现

建议 ：
在makWrap函数中修改一下生成label插槽的逻辑

**Comment by xaboy** [comment]
支持的 可以通过rule.title:{type:'xxx',title:'xxx' ,style: 'xxx'}

**Comment by Timo534** [comment]
> 支持的 可以通过rule.title:{type:'xxx',title:'xxx' ,style: 'xx

**Comment by Timo534** [comment]
> 支持的 可以通过rule.title:{type:'xxx',title:'xxx' ,style: 'xxx'}

想要在自定义组件中获取到整个rule，有什么好的办法吗，配置title.props.rule = rule，提示循环引用问题
