### ISSUE TITLE
可以升级一下vue版本么，vue3.2的版本下引入后报错

### ISSUE THREAD

**Issue by coderzhouyu** [xaboy/form-create#523]
在vue3.2 下引入后报错
Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableSpread (form-create.esm.js:195:9)
    at _toConsumableArray (form-create.esm.js:166:98)
    at setup (form-create.esm.js:2010:21)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
_
显示另外 74 个框架

<template>
  <formCreate  :rule="rule"></formCreate>
</template>

<script setup>

const rule = [
  {
    type: 'input',
    field: 'goods_name',
    title: '商品名称'
  },
  {
    type: 'datePicker',
    field: 'created_at',
    title: '创建时间'
  }
]

升级vue版本

**Comment by xaboy** [comment]
感谢反馈 我检查一下

**Comment by xaboy** [comment]
我这边测试没有问题 可以正常渲染 @coderzhouyu 

```js
<template>
  <div>
    <form-create :rule="rule" />
  </div>
</template>

<script setup>
const rule = [ { type: 'input', field: 'goods_name', title: '商品名称' }, { type: 'datePicker', field: 'created_at', title: '创建时间' } ]
</script>
```

**Comment by vsme** [comment]
```
<template>
  <div>
    <form-create :rule="rule" />
  </div>
</template>

<script setup>
import FormCreate from "@form-create/arco-design";

const rule = [ { type: 'input', field: 'goods_name', title: '商品名称' }, { type: 'datePicker', field: 'created_at', title: '创建时间' } ]
</script>
```

TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

**Comment by xaboy** [comment]
https://github.com/xaboy/form-create/issues/529#issuecomment-1231487031

**Comment by xaboy** [comment]
#529
