### ISSUE TITLE
group数组规则中加入自定义组件报错 组件不存在   在基本规则中是能正确显示的（引入组件正确）

### ISSUE THREAD

**Issue by Feellove** [xaboy/form-create#525]
版本号 (version) 
@form-create/element-ui@2.5.0 

 UI 框架的版本 (UI version) :view-design4.7

group数组规则中加入自定义组件报错 组件不存在   在基本规则中是能正确显示的（引入组件正确）

 a = {
                    type: "group",
                    field: "group712-93000",
                    title: "",
                    value: [
                        {
                            hazards: "有",
                            hazardName: "2",
                            hazardsNumber: "2",
                            hazardsLevel: "四级",
                            hazardsAssessment: "2",
                            hazardsRecord: "备案中",
                            hazardAssessmentReport: "未编制",
                            attach: ""
                        }
                    ],
                    orderSeq: 93000,
                    className: "btn-o mb0",
                    props: {
                        button: true,
                        disabled: false,
                        fontSize: 22,
                        defaultValue: {},
                        rules: [
                            {
                                type: "fieldComponent",
                                field: "attach",
                                title: "评估报告附件",
                                value: "",
                                orderSeq: 100000,
                                className: "  width-half",
                                col: {
                                    span: 12,
                                    labelWidth: 180
                                }
                            }
                        ]
                    },
                    on: {},
                    options: [],
                    children: [],
                    hidden: false,
                    display: true
                };

**Comment by xaboy** [comment]
组件需要全局挂载或者通过 form-create 挂载

**Comment by Feellove** [comment]
再问下 ，为什么用iview  使用group 分组无论是下拉框还是输入框这些第一次操作都会无效，每一组只有操作过其中一个才可以正常使用下拉 输入这些操作

**Comment by xaboy** [comment]
更新一下 form-create 的版本再试试 @Feellove

**Comment by Feellove** [comment]
用了  fapi.refresh();解决了

**Comment by Feellove** [comment]
@xaboy  怎么对group 组的按钮进行 操作 有api方法？

**Comment by xaboy** [comment]
没有API, 只能通过插槽修改
