### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by michelveloso** [xaboy/form-create#532]
Hi,

I cloned the "next" branch from the last commit: https://github.com/xaboy/form-create/commit/0d301463e3b6cf287b310bba70c794fd1aa5b418 and then I ran:

yarn install
lerna bootstrap

And finally:
yarn dev:ele

But I got a error when the project open in the browser:

![image](https://user-images.githubusercontent.com/346317/189497233-e5488bef-e277-448c-963d-7277d5b5f47d.png)

![image](https://user-images.githubusercontent.com/346317/189497270-54cf27e1-33c9-4985-b6a9-a6e95828eeff.png)

Can you help me to solve this?

Regards

**Comment by xaboy** [comment]
Thanks for the feedback, what is the Vue version you are using?  @michelveloso

**Comment by michelveloso** [comment]
@xaboy this is my version: 

"vue": "^3.2.38",
"vite": "^3.0.9",

**Comment by xaboy** [comment]
If the component is not mounted globally, this needs to be declared in the setup @michelveloso 
```vue
<template>
  <Fc :rule="rule"></Fc>
</template>
<script setup>
//Import form-create
import formCreate from "@form-create/element-ui";
//Get the formCreate component
const Fc = formCreate.$form();
const rule = [
  {
    type:'input',
    field:'goods_name',
    title:'商品名称',
    value:'form-create'
  },
];
</script>
```
