### ISSUE TITLE
vue2,element2.13,上传组件upload有一些问题

### ISSUE THREAD

**Issue by lishuncoder** [xaboy/form-create#533]
vue2
"@form-create/element-ui": "^2.5.26"

"element-ui": "2.13.2",

vue2,element2.13,上传组件upload有一些问题

http://www.form-create.com/v2/element-ui/components/upload.html
element-admin-template项目，如文档中一样的设置，但图片个数为1个，此时删除数据并点击提交，alert处理来的pic并没有得到删除，只有>=2个图片url时，才能删除，这是为何？

一个的时候难道不应该一并删除吗？

**Comment by lishuncoder** [comment]
![image](https://user-images.githubusercontent.com/35674916/189959733-e6b42e3f-ab39-4770-8cd7-e7df75797084.png)

如图所示，
<form-create v-model="fApi" :rule="rule" :value.sync="value" @submit="test(value)" @change="test(value)" />
无论是submit还是change，都无法捕捉到pic元素只有一个时的变动

**Comment by xaboy** [comment]
感谢反馈, 我这边检查一下 @411906015

**Comment by lishuncoder** [comment]
> 感谢反馈, 我这边检查一下 @411906015

我大概可以猜到原因，我因为加载顺序的问题，如果我如下图所示去进行赋值，那就没有这个问题，我猜想是因为加载顺序的问题
![image](https://user-images.githubusercontent.com/35674916/190169295-f041a75a-fd6a-42f3-935e-6dfa33d8b381.png)
