### ISSUE TITLE
组件没有正确显示

### ISSUE THREAD

**Issue by ybqdren** [xaboy/form-create#534]
相关组件版本号如下：

```
"@form-create/element-ui": "^3.1.14",
"element-plus": "^2.2.16",
"vue": "^3.2.37",
```

<br>

引入`FormCreate`组件后，无法在浏览器上正确显示，只显示“提交”两个字，如下：
![图片](https://user-images.githubusercontent.com/46752566/190056532-33e5b444-3e26-4f11-98ba-81234db49e53.png)

<br>

上述问题实现代码如下：
```
<script setup>
import FormCreate from '@form-create/element-ui'

const Fc = FormCreate.$form()
const rule = [
  { type: 'input', field: 'goods_name', title: '商品名称' },
]
</script>

<template>
  <div>
    <Fc :rule="rule" />
  </div>
</template>
```

> 代码参考：https://github.com/xaboy/form-create/issues/529

<br>

期望的结果是能正确显示`input`输入框，并显示指定的标题

**Comment by xaboy** [comment]
看截图像是elementPlus 没有挂载 @ybqdren
