### ISSUE TITLE
setValue not work

### ISSUE THREAD

**Issue by liangxp** [xaboy/form-create#54]
`
$f.setValue(field,value)
$f.setValue({
  field1:value1,
  field2:value2,
  field3:value3
});
`
调用setValue后，通过[$f.formData](http://www.form-create.com/guide/instance.html#f-formdata)获取到值已经发生改变，但是控件view内容并未发生改变，请问是什么原因呢

**Comment by xaboy** [comment]
form-create 和 ui的版本是多少?

**Comment by liangxp** [comment]
@xaboy 

    "form-create": "^1.6.1",
    "iview": "^3.0.0",
    "vue": "^2.5.16",

**Comment by xaboy** [comment]
可以发下生成规则吗或者说一下那个组件value 修改后view内容没有发生改变

**Comment by liangxp** [comment]
@xaboy 在演示地址http://jsrun.net/NQhKp/edit中，演示代码mounted方法替换为如下代码：
`
mounted: function() {
    $f = this.$refs.fc.$f;
		this.$refs.fc.$f.setValue({"goods_name":"fdsfdsfd"})
    //动态添加表单元素
    //$f.append($r, 'pic');
  }
`

**Comment by xaboy** [comment]
不好意思,这个是演示的代码版本有点老了,写的有点问题.我刚刚更新了下已经好了

**Comment by liangxp** [comment]
我本地需要更新下么？我本地意思一样的情况

**Comment by xaboy** [comment]
你可以参考一下我刚刚新的代码  http://jsrun.net/NQhKp/edit
