### ISSUE TITLE
自定义form组件如何接收和传递form-create调用时的参数

### ISSUE THREAD

**Issue by 1373720368** [xaboy/form-create#540]
大佬，请问一下，如何实现业务调用formcreate时，能够将业务的参数带到自定义的form组件中，比如自己封装的下拉组件，这个下拉组件的数据源依赖外边传进来的参数，formCreate如何传递，我直接绑定在实例上初始化的时候无法实现响应式

**Comment by xaboy** [comment]
可以通过 props.formCreateInject 参数接收
[文档](http://form-create.com/v2/guide/custom-component.html#%E9%A2%84%E5%AE%9A%E4%B9%89-props)
