### ISSUE TITLE
naiveui fcRow组件不存在

### ISSUE THREAD

**Issue by lin-code-world** [xaboy/form-create#547]
@form-create/naive-ui: 3.1.15
naive-ui：2.33.5

//问题描述
`<form-create :rule="rule" :option="opt" :key="id" />
const rule= [
  {
    "type": "FcRow",
    "children": [
      {
        "type": "col",
        "props": {
          "span": 12
        },
        "children": [
          {
            "type": "input",
            "field": "month_problem",
            "title": "存在问题及措施",
            "info": "",
            "props": {
              "rows": 4,
              "type": "textarea"
            },
            "_fc_drag_tag": "input",
            "hidden": false,
            "display": true
          }
        ],
        "_fc_drag_tag": "col",
        "hidden": false,
        "display": true
      },
      {
        "type": "col",
        "props": {
          "span": 12
        },
        "children": [
          {
            "type": "input",
            "field": "month_nextprocesstarget",
            "title": "下月进度目标",
            "info": "",
            "props": {
              "type": "textarea",
              "rows": 4
            },
            "_fc_drag_tag": "input",
            "hidden": false,
            "display": true
          }
        ],
        "_fc_drag_tag": "col",
        "hidden": false,
        "display": true
      }
    ],
    "_fc_drag_tag": "row",
    "hidden": false,
    "display": true
  }
]
`
//出现告警：Failed to resolve component: fcRow

**Comment by xaboy** [comment]
感谢反馈, 我这边检查一下
