### ISSUE TITLE
使用Input组件时，value为number 时，校验无法通过

### ISSUE THREAD

**Issue by jacktao007** [xaboy/form-create#548]
使用Input组件时，value为number 时，校验无法通过

![1667490349161](https://user-images.githubusercontent.com/1073365/199768251-82e40926-e1f0-420b-957f-b406d1c3533c.jpg)

**Comment by LuoRiWuSheng** [comment]
> 使用Input组件时，value为number 时，校验无法通过
> 
> ![1667490349161](https://user-images.githubusercontent.com/1073365/199768251-82e40926-e1f0-420b-957f-b406d1c3533c.jpg)

猜测这个可能是  不是bug  正常来说  用户输入的都应该是  String类型的内容，触发你指定  Input的 type为 number  才会给你返回number类型的值
这里你以为输入的 1是数字，其实是字符串  "1"
