### ISSUE TITLE
next 分支 运行 npm run bootstrap 报错

### ISSUE THREAD

**Issue by byc233518** [xaboy/form-create#549]
版本号 (version) 
    [v3.1.16](https://github.com/xaboy/form-create/commit/41af60432b767d7a11b9b14a211f1c7594695e54)

UI 框架的版本 (UI version) 
    element-plus

问题描述 (Issue) 

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/13425815/200208455-c3f66fad-ffed-40f5-b229-3e06a4de970a.png">

复现步骤/生成规则 (Duplicate steps/generate rules)
1. clone源码 
2. 目录下运行 npm run bootstrap

期望的结果 (Desired outcome) 
能够正常运行并继续往后的步骤

**Comment by byc233518** [comment]
其他信息补充: 
bai@MacBook-Pro-2 form-create % sw_vers
ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
bai@MacBook-Pro-2 form-create % node -v
v16.0.0
bai@MacBook-Pro-2 form-create % npm -v
8.19.2

**Comment by lyudongzhou** [comment]
+1

**Comment by 00001x** [comment]
执行 npm install eslint@^6.0.0即可解决，或者npm install eslint-plugin-vue@6.1.3 -g

**Comment by SeanHooo** [comment]
> 执行 npm install eslint@^6.0.0即可解决，或者npm install eslint-plugin-vue@6.1.3 -g

我这边的解决方式是：npm install eslint@6.0.0
