### ISSUE TITLE
[QUESTION] - validate for select

### ISSUE THREAD

**Issue by go4cas** [xaboy/form-create#55]
@xaboy, I have a `select` defined with:
```javascript
    {
      type: 'select',
      field: 'brandId',
      title: 'brand',
      props: {
        clearable: true,
        placeholder: null
      },
      validate: [
        {
          required: true,
          message: 'required',
          trigger: 'blur'
        }
      ]
    },
```

When I submit the form the `required validation` displays, even though I have set a value in the select:
![2019-03-24_11-15-12](https://user-images.githubusercontent.com/12674784/54877365-1e902e00-4e26-11e9-8c53-d99250339cb8.png)

**Comment by xaboy** [comment]
Can you send your `options`? The problem may be that `type` is not set. You can refer to it here[http://form-create.com/other/validation-rules.html](http://form-create.com/other/validation-rules.html).
For example, value is a number and you need to set `type:'number'.

**Comment by go4cas** [comment]
@xaboy, do you have the validation rules page in English?

**Comment by xaboy** [comment]
[async-validator](https://github.com/yiminghe/async-validator#type)

**Comment by go4cas** [comment]
@xaboy, I build my `options` list dynamically. Here's the function:
```javascript
    let dataObject = {
      value: item.id,
      label: item[displayKey],
      type: 'number'
    }
```

**Comment by go4cas** [comment]
Okay, setting `type to `number` worked! Thanks, @xaboy!

**Comment by xaboy** [comment]
If your `option.value` is a number, you need to set `type:'number' in validate`.
```
validate:[
    {
          required: true,
          message: 'required',
          trigger: 'blur',
          type: 'number'
    }
]
```
