### ISSUE TITLE
插件引入报错Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by oxygen1999** [xaboy/form-create#550]
@form-create/element-ui@3.1.16
UI 框架的版本 (UI version) 2.13.0
使用报错
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/62201108/200484109-8e158194-ed66-464a-b4b8-c3007966f0dd.png">
如何处理

**Comment by 52Lau** [comment]
@oxygen1999 同样遇到了，老哥怎么解决的

**Comment by xaboy** [comment]
vue2使用 form-create2.x 版本 @52Lau
