### ISSUE TITLE
文本输入框输入任何字符立刻被删除

### ISSUE THREAD

**Issue by jun4rui** [xaboy/form-create#552]
版本号 (version) 
@form-create/element-ui@2.5.27 

UI 框架的版本 (UI version) 
2.15.7

问题描述 (Issue)
偶尔在生成表单的文本输入框中，输入任何文字就会自动删除掉。可以看到文字出现在输入框了，但很快就没了。
主要是偶尔才出现，规则都是一样的，刷新以后就没事了。

**Comment by xaboy** [comment]
表单创建后是不是有 setValue 等操作把值覆盖了 @jun4rui

**Comment by jun4rui** [comment]
> 

有一次setValue操作，但应该不至于无法输入，无论多久只要键入任何内容就会被自动删掉，应该是input有个什么事件触发了

**Comment by xaboy** [comment]
生成规则发一下, 我这边试试 @jun4rui

**Comment by jun4rui** [comment]
> 生成规则发一下, 我这边试试 @jun4rui

仔细排查了一下是别的问题，有别的同事谢了watch导致无法输入，谢谢xaboy的热心回答。
