### ISSUE TITLE
vue2 安装报错

### ISSUE THREAD

**Issue by ryan0562** [xaboy/form-create#553]
vue2 安装报错

import formCreate from '@form-create/element-ui';
Vue.use(formCreate);

element-UI版本：2.15.10

引入后发现报错
Uncaught TypeError: vue.createElementVNode is not a function

看了源码，代码里用的是element-plus ,这个应该是vue3的组件库
这边应该修改文档制定版本号

**Comment by xaboy** [comment]
vue2使用2.x 版本,vue3使用3.x 版本
