### ISSUE TITLE
control组件联动，可以做到不销毁渲染吗

### ISSUE THREAD

**Issue by helei945** [xaboy/form-create#554]
版本号 (version)
@form-create/element-ui@2.5.27

UI 框架的版本 (UI version)
2.15.7

问题描述 (Issue)
![rule js - form-create - Visual Studio Code 2022_11_16 16_50_50](https://user-images.githubusercontent.com/39692240/202133661-113ebe93-870a-4d16-bfb2-9c37a6f986a1.png)

control组件联动，可以做到不销毁渲染吗

通过display控制隐藏

**Comment by xaboy** [comment]
通过这种方式可以实现不销毁
```js
{
    value: 1,
    rule: ['field1', 'name2']
}
```

**Comment by helei945** [comment]
可以的，感谢
