### ISSUE TITLE
UploadOnPreview方法无法自定义，上传附件成功后文件名显示问题

### ISSUE THREAD

**Issue by Cabbage-Leon** [xaboy/form-create#558]
版本号 (version) 
    @form-create/designer": "^3.0.2",

    UI 框架的版本 (UI version) 
   "vue": "^3.2.41"
  "element-plus": "^2.2.20",

问题描述 (Issue)
   1.Upload上传附件成功后OnPreview方法无法自定义
   2.上传成功后文件名直接取URL后面的参数,filelist不能接收{name:'', url:''}格式

复现步骤/生成规则 (Duplicate steps/generate rules)
   
![image](https://user-images.githubusercontent.com/31495215/202604860-6f9401cc-02c3-406e-9616-e5d1ff83ed1b.png)
![image](https://user-images.githubusercontent.com/31495215/202604961-10d77d47-f3df-4046-984a-d8ded2c98ef7.png)
![image](https://user-images.githubusercontent.com/31495215/202604985-7cb6b2dd-f53a-4167-b16a-e85a2be476ef.png)
![image](https://user-images.githubusercontent.com/31495215/202605011-cac64652-5e1f-475d-87e4-67f81e3ac7fa.png)

 期望的结果 (Desired outcome
 1.支持onPreview， 点击已上传文件可以自定义展示
 2.文件名显示名如果有name取name的

 建议 (Advice)
 1.upload上传文件非图片的时候能够点击下载
 2.file.url 是否支持为{name:'', url:''}格式，回显自定义文件名

**Comment by thpngj** [comment]
老哥，我用的是 ant 的组件 也是相同的问题，因为上传不单单只 上传图片，还有文件呢，没办法预览，应该显示个文件名，但看源码 貌似 不支持～也没办法自定义～

**Comment by xaboy** [comment]
目前内置的上传组件值记录一个文件链接, 这个问题后面可以优化一下. 建议先通过自定义组件一个上传组件实现
