### ISSUE TITLE
怎么在重置和提交按钮后面新增操作按钮

### ISSUE THREAD

**Issue by GodX-18** [xaboy/form-create#560]

**Comment by xaboy** [comment]
在`options`中增加 submitBtn=false, resetBtn=false 即可

**Comment by Evring** [comment]
> 在`options`中增加 submitBtn=false, resetBtn=false 即可

我想在重置后面增加个导出，这样要写三个按钮，还要把提交跟重置再写一遍。

要是能给按钮增加个顺序，灵活末尾按钮的顺序就好了
