### ISSUE TITLE
iview Upload组件，自定义onSuccess、onRemove方法修改了传给表单的value，会导致无法预览以及移除已上传文件

### ISSUE THREAD

**Issue by nicholasfung68** [xaboy/form-create#562]
onSuccess传递的函数
![image](https://user-images.githubusercontent.com/35166755/205797197-d9034367-b9b6-4d7d-81c4-bd81fc89a028.png)
![image](https://user-images.githubusercontent.com/35166755/205798086-156f65b1-ff9f-4408-83de-433a74d76695.png)

iview 自定义onSuccess、onRemove方法修改了传给表单的value，会导致无法预览以及移除已上传文件
![image](https://user-images.githubusercontent.com/35166755/205794845-861985bb-74e4-4267-a782-9a9117f0d6ae.png)

![image](https://user-images.githubusercontent.com/35166755/205794808-e9e9285b-2cf4-494a-8347-436395ad9cc8.png)

![image](https://user-images.githubusercontent.com/35166755/205794955-25d52bda-cf20-4438-81c3-7d649c53dafe.png)
![image](https://user-images.githubusercontent.com/35166755/205795248-49e4b0d9-61b8-4698-af3e-c7ec5f885844.png)

不论用户自定义onSuccess、onRemove函数里修改了self对象自己的value与否，以上传文件应该都可以正常响应预览以及移除文件事件。

建议修改 parseFile 方法，将文件的 status 属性存放进去。

**Comment by xaboy** [comment]
在 onSuccess里面 fileName 直接赋值就 file.url 就会自动修改value, 当前可以先在事件中修改 value 时加点延迟,保证功能正常.

**Comment by nicholasfung68** [comment]
> 在 onSuccess里面 fileName 直接赋值就 file.url 就会自动修改value, 当前可以先在事件中修改 value 时加点延迟,保证功能正常.
 
目前就是这么干的——在nextTick中操作Upload的fileList，加上了status属性……
