### ISSUE TITLE
动态级联生成表单，数据更新但是视图没有更新，期待回复~~

### ISSUE THREAD

**Issue by xxxlgloverd** [xaboy/form-create#569]
"@arco-design/web-vue": "^2.37.4",
    "@form-create/arco-design": "^3.1.17",

下拉选定某一个值时去动态加载生成相应的表单配置，使用update去监听value值变化，然后去更改下拉配置的control中rule的值，现在数据可以进行响应式更新，但是视图上是显示上一个值的表单，并且数据清空，渲染并没有清空，而是在累加，也使用了fApi.refresh()去进行表单配置更新，还是不可以！！！

codesandbox代码
https://codesandbox.io/s/blazing-dust-qiek70?file=/src/App.vue

我想请教一下这块如何处理比较好呢？目前没有什么头绪，期待回复，并且过年好~~

**Comment by xaboy** [comment]
感谢反馈, 新年快乐~~ @xxxlgloverd 
control 中的 rule 不支持动态添加,删除, 需要在规则中提前确定好规则. 可以通过修改生成规则或者通过修改的 rule.children 实现

**Comment by xxxlgloverd** [comment]
大佬能在详细说说吗？我是想着先把所有的数据先提前确定好规则，切换哪个下拉就显示哪个（只是进行dom层的展示隐藏，数据层不做增删），这样的思路在这个插件中能实现吗？？

**Comment by xxxlgloverd** [comment]
> 感谢反馈, 新年快乐~~ @xxxlgloverd control 中的 rule 不支持动态添加,删除, 需要在规则中提前确定好规则. 可以通过修改生成规则或者通过修改的 rule.children 实现

大佬能在详细说说吗？我是想着先把所有的数据先提前确定好规则，切换哪个下拉就显示哪个（只是进行dom层的展示隐藏，数据层不做增删），这样的思路在这个插件中能实现吗？？

**Comment by xaboy** [comment]
第一种是用 control, 在 control中把每种情况都提前定义好
第二种是在 update 中根据业务逻辑,生成好新规则后将规则添加到对应的位置  @xxxlgloverd

**Comment by xxxlgloverd** [comment]
> 第一种是用 control, 在 control中把每种情况都提前定义好 第二种是在 update 中根据业务逻辑,生成好新规则后将规则添加到对应的位置 @xxxlgloverd

好 我试试 update
