### ISSUE TITLE
ant-design-vue:v1.7.8中使用select选择器配置多选无效

### ISSUE THREAD

**Issue by liuyuliang092** [xaboy/form-create#570]
"@form-create/ant-design-vue": "^2.5.27"

"ant-design-vue": "^1.7.8"

使用select选择器配置多选无效

<form-create v-model="formData" :rule="rule" :option="option" @submit="onSubmit"> </form-create>
this.rule = [
  {
    "type": "select",
    "field": "transform_col_names",
    "title": "transform_col_names",
    "info": "",
    "effect": {
      "fetch": ""
    },
    "props": {
      "multiple": true
    },
    "options": [
      {
        "label": "1",
        "value": "1"
      },
      {
        "label": "2",
        "value": "2"
      },
      {
        "label": "3",
        "value": "4"
      }
    ],
    "_fc_drag_tag": "select",
    "hidden": false,
    "display": true
  }
]

可以多选，实际还是只能单选

**Comment by xaboy** [comment]
`multiple:true` 改为 `mode:"multiple"`  参考 [ant-design-vue 文档](https://www.antdv.com/components/select)
