### ISSUE TITLE
validate ts类型错了

### ISSUE THREAD

**Issue by joker77877** [xaboy/form-create#571]
@form-create/element-ui@3.1.18

 2.13.0

validate ts类型错了
![image](https://user-images.githubusercontent.com/62642184/217406596-cca87e10-2c68-4c39-b066-65312eaa201c.png)

修改类型

**Comment by xaboy** [comment]
哪里错了,有什么报错信息吗? @joker77877

**Comment by joker77877** [comment]
> 哪里错了,有什么报错信息吗? @joker77877

这里嵌套了两个callback没看出来吗。。。

**Comment by joker77877** [comment]
![image](https://user-images.githubusercontent.com/62642184/218363637-2af93477-74c0-48a8-94d6-cd3bf5eabd59.png)

**Comment by xaboy** [comment]
感谢反馈,下个版本修复

**Comment by yang131323** [comment]
这个问题请问是否修复了一个版本？我看还是有问题，定义还是有点问题

**Comment by yang131323** [comment]
> 这个问题请问是否修复了一个版本？我看还是有问题，定义还是有点问题

![image](https://github.com/xaboy/form-create/assets/32360827/4d014366-4881-4004-9fbe-fccc9ad764b9)

**Comment by xaboy** [comment]
更新到最新版本即可
