### ISSUE TITLE
emit怎么传自定义参数

### ISSUE THREAD

**Issue by HelenSilas** [xaboy/form-create#572]

**Comment by HelenSilas** [comment]
<form-create
        v-model="fApiA"
        :rule="baseRules"
        :value.sync="baseRowData"
        @history-click="testChange"
      />
 //baseRules.js    
{
      type: 'span',
      slot: 'action',
      filed: 'otherNum',
      children: [{
        type: 'i',
        class: 'iconfont icon-lishidingdan'
      }, '历史信息'],
      update(val, rule) {
        rule.title = val;
        rule.children[1] = `历史信息(${val || 0})`;
      },
      emit: ['click'],
      emitPrefix: 'history'
    }
需要触发emit传自定义参数

**Comment by xaboy** [comment]
可以开启事件注入,会增加一个参数.具体用法查看文档

**Comment by HelenSilas** [comment]
你好能粘贴下文档的链接呢，我找了半天也没找到，辛苦了
