### ISSUE TITLE
部分组件动态更改disabled无法立即生效

### ISSUE THREAD

**Issue by suyana** [xaboy/form-create#58]
以element demo为基础，修改时发现，动态修改disabled=true，部分组件无法立即生效，**需值改变后才会锁定**。

组件有：radio，checkbox，select，switch，DatePicker，TimePicker，InputNumber，ColorPicker，rate，slider

对于radio和checkbox，额外设置options的disabled=true也不行。
但是如果一开始json设置为true，则是可以锁定的。

看了下官方文档，有写到：
> > 说明: 如果修改后没有生效,需要提前在生成规则里定义该规则

我的json这些rule都有定义disabled=false

代码如下：
for(let i in $f.rule){
    let rule=$f.rule[i];
    if(_vm.readonly){
        rule.props.disabled=true;
        if(rule.type=="radio" || rule.type=="checkbox2" ){
            for(let z in rule.options)rule.options[z].disabled=true;
        }
    }
}

请问是不支持还是哪里有问题？

------------------------------------
代码是今天刚下的版本
组件模式+json数据方式
form-create v1.6.2 elementUI
element-ui@2.6.3
vue 2.5.22
------------------------------------

PS：刚测试了一下，json定义disabled=true，通过代码动态设为false，这样是可以的

**Comment by xaboy** [comment]
感谢你的反馈.
这个可能是 bug,我检查一下.你可以试试用`Vue.set`方法修改行不行

**Comment by suyana** [comment]
经过测试，Vue.set可以，谢谢
`
rule.props.disabled=true;
Vue.set(_vm.rule,i,rule);
`

**Comment by xaboy** [comment]
好的 
 这样设置应该也可以 `Vue.set(rule.props,'disabled',true)`

**Comment by suyana** [comment]
`Vue.set(rule.props,'disabled',true)`，这个我试了，不行...

**Comment by xaboy** [comment]
IViewUI 的 redio组件和checkbox组件不支持禁用
