### ISSUE TITLE
升级到"element-plus": "2.2.35",设计器打开浏览器崩溃

### ISSUE THREAD

**Issue by date13** [xaboy/form-create#580]
版本号 @form-create/element-ui@2.5.0 

UI 框架的版本 ("element-plus": "2.2.35",) 

element-plus升级到2.2.35 打开设计器
[form-create-designer](https://github.com/xaboy/form-create-designer)
Public,直接浏览器(edge)崩溃
控制台警告

runtime-core.esm-bundler.js:40 
        
       [Vue warn]: Maximum recursive updates exceeded in component <ElScrollbar>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

设计器的属性编辑器这一块直接也是用的form-create,能尽快修复吗?
![1678276507606](https://user-images.githubusercontent.com/5069437/223706965-c0e1925b-98ea-4087-8d2b-4f721dee17de.jpg)

**Comment by date13** [comment]
"element-plus"升级到"2.2.36"就可以了,一天之内就修复了,给力

**Comment by xaboy** [comment]
我还什么都没做😅  @date13

**Comment by date13** [comment]
不用做啥,elment-plus的bug
