### ISSUE TITLE
getOption()获取表单配置与设置表单方法setOption()的参数不一致

### ISSUE THREAD

**Issue by 910253720** [xaboy/form-create#582]
-----版本：
    "@form-create/designer": "^3.1.1",
    "@form-create/element-ui": "^3.1.18",
    "element-plus": "^2.2.36"

-----问题：
表单设计器创建表单时，用getOption()获取表单配置与设置表单方法setOption()的参数不一致，导致在表单创建后，再次编辑时配置出错（提交和重置按钮）
getOption()获取的配置
![image](https://user-images.githubusercontent.com/44550351/224207288-9b2fab90-255d-483e-a410-9eaf398fd2d1.png)
setOption()需要的配置
![image](https://user-images.githubusercontent.com/44550351/224207442-3d6a15da-135f-444c-b7a1-45849de86086.png)

-----原因（源码部分）：
![image](https://user-images.githubusercontent.com/44550351/224207163-7a0b61c7-4eac-4c34-983c-cd31582485aa.png)

**Comment by xaboy** [comment]
感谢反馈, 这个问题已知,设计器的下个版本会修复  @910253720

**Comment by yss0729** [comment]
我今天也遇到这个问题，暂时先把submitBtn和resetBtn放进option.form里，等修复后再更新吧
