### ISSUE TITLE
【update回调】希望可以给出触发的来源rule

### ISSUE THREAD

**Issue by vonlyinno** [xaboy/form-create#586]
@form-create/core@2.5.27

如题。

type update = (val:any, rule:FormRule, fApi:fApi)=>Boolean|void
增加一个from或者trigger参数

**Comment by xaboy** [comment]
需要通过来源来区分什么?  @vonlyinno

**Comment by vonlyinno** [comment]
比如：是通过link触发的update还是自身change触发的

**Comment by leochen-g** [comment]
支持 +1

**Comment by leochen-g** [comment]
如果是在Object组件中link 外部的field ，不会触发update方法，这个能解决吗

**Comment by xaboy** [comment]
3.1.22已增加
