### ISSUE TITLE
更新select的rule报错

### ISSUE THREAD

**Issue by Didiwei1314** [xaboy/form-create#587]
版本号 (version) 
例如: @form-create/element-ui@3.1.18 

UI 框架的版本 (UI version) 
"element-plus": "^2.2.8"

问题描述 (Issue) 
通过mergeRule或者updateRule更新select组件中props的multiple属性时
由true设置为false正常，由false设置为true会报错

**Comment by xaboy** [comment]
修改multiple字段的同时修改一下rule.key可以避免报错

**Comment by denyuijin** [comment]
"@form-create/designer": "^1.0.8",
 "@form-create/element-ui": "^2.5.27",
"element-ui": "^2.15.13",

也会报错，也是这么改么？
