### ISSUE TITLE
Upload组件只上传了一个文件时，编辑表单历史数据，删掉文件后提交表单，文件url没有清空。

### ISSUE THREAD

**Issue by gmbl666** [xaboy/form-create#589]
版本号 (version)  @form-create/element-ui@2.5.27
UI 框架的版本 (UI version) 2.14.0

![示例图1](https://user-images.githubusercontent.com/37998684/227475351-bf2b10b7-928a-44d5-a841-7591001e0c2e.png)
![示例图2](https://user-images.githubusercontent.com/37998684/227478281-c225d974-03e2-4975-9bb5-9b2120b3da98.png)
![示例图3](https://user-images.githubusercontent.com/37998684/227478319-0e7a0237-6bb9-43d9-88f3-d30acab8ae76.png)

编辑已上传了一个文件的历史数据时，删除这个文件后提交表单，请求入参中文件的url值依然存在。
请问是我在给数据回显时setValue中上传组件给的是由文件url组成的数组这个方式不对，还是组件本身有问题？求大佬帮帮。

注：编辑上传了多个文件的历史数据时，删除一个或多个文件，提交数据结果都是正常的，目前只有上述的这一种场景会出现这个问题。

**Comment by gmbl666** [comment]
翻了翻issue找到解决办法了，把setValue相较setForm延后能规避这种问题。
![image](https://user-images.githubusercontent.com/37998684/227861861-4a31b38e-3af5-42a9-9ec7-aa3053968f9c.png)

**Comment by Jingjingsixgod** [comment]
这个方法是在什么时候加载的？
