### ISSUE TITLE
how to compile by webpack?

### ISSUE THREAD

**Issue by tiger54910** [xaboy/form-create#59]
Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator'

**Comment by djkloop** [comment]
@tiger54910 
可能是网络原因造成的。导致很多包安装不上...换成yarn或cnpm试一试。
能否提供下 webpack配置和package.json

**Comment by tiger54910** [comment]
就是这个git工程下载，编译出错，cnpm用了也不行；

**Comment by tiger54910** [comment]
ERROR in ./src/components/element/upload/render.js
Module not found: Error: Can't resolve 'core-js/modules/es6.reflect.get' in 'D:\projects\form-create\src\components\element\upload'
 @ ./src/components/element/upload/render.js 11:0-41
 @ ./src/components/element/upload/index.js
 @ ./src/components/element/index.js
 @ ./src/element.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/element.js

**Comment by djkloop** [comment]
@tiger54910 这个项目编译不是用的webpack，webpack只是用来开发用的。

**Comment by djkloop** [comment]
@tiger54910  在.babelrc里面添加一行
![image](https://user-images.githubusercontent.com/21050914/55683337-14674700-5971-11e9-9e23-6df60639289e.png)



解决方案来自：
https://github.com/vuejs/vuepress/issues/1471

**Comment by djkloop** [comment]
@tiger54910 
![image](https://user-images.githubusercontent.com/21050914/55683351-4ed0e400-5971-11e9-80a3-03868de4d7a3.png)

**Comment by tiger54910** [comment]
谢谢，的确是这样，加上即可以了。
