### ISSUE TITLE
数据清除后视图没有更新

### ISSUE THREAD

**Issue by yewandexin** [xaboy/form-create#590]
版本号 (version) 
   "@form-create/element-ui": "^3.1.17",
    UI 框架的版本 (UI version) 
    "element-plus": "2.2.34",

我使用v-model绑定一个空对象
在我对v-model绑定的这个对象置空时数据置空了，视图上的数据没有变化，使用resetFields方法置空时也存在同样的问题，
以下是我对你们组件的使用方式，可能存在我有些不理解的规则，忘告知，我的规则和可选项都是使用表单生成器获得的数据，
![code](https://user-images.githubusercontent.com/92660264/230872727-0efc61b0-603f-4076-91dd-a3d69c3e616c.png)

这个是我的数据
option
"{\"form\":{\"labelPosition\":\"right\",\"size\":\"mini\",\"labelWidth\":\"auto\",\"hideRequiredAsterisk\":false,\"showMessage\":true,\"inlineMessage\":false},\"submitBtn\":false,\"resetBtn\":false}"
rule
"[{\"type\":\"input\",\"field\":\"F26e5yi2ijykb\",\"title\":\"输入框\",\"info\":\"\",\"_fc_drag_tag\":\"input\",\"hidden\":false,\"display\":true,\"$required\":\"输入值\"},{\"type\":\"checkbox\",\"field\":\"Fjrt5yi2ikfq6\",\"title\":\"多选框\",\"info\":\"\",\"effect\":{\"fetch\":\"\"},\"options\":[{\"value\":\"1\",\"label\":\"选项1\"},{\"value\":\"2\",\"label\":\"选项2\"}],\"_fc_drag_tag\":\"checkbox\",\"hidden\":false,\"display\":true},{\"type\":\"rate\",\"field\":\"Fveg5yi2ile87\",\"title\":\"评分\",\"info\":\"\",\"_fc_drag_tag\":\"rate\",\"hidden\":false,\"display\":true,\"value\":0}]"

期望能给我回复，万分感谢，

**Comment by xaboy** [comment]
rule不能使用计算属性 @yewandexin

**Comment by yewandexin** [comment]
> 

非常感谢！
