### ISSUE TITLE
select组件 fetch异步获取的数据无法拿到options或者label

### ISSUE THREAD

**Issue by joker77877** [xaboy/form-create#599]
3.1.18

2.3.4

``
[
    {
        "type": "select",
        "field": "Fpne5yutaw3l7",
        "title": "选择器",
        "info": "",
        "effect": {
            "fetch": {
                "action": "/workflow/api/v1/sf-cmdb/services",
                "method": "GET",
                "data": null,
                "headers": {
                    "Authorization": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgzNzAxODM2LCJpYXQiOjE2ODM2MTM0MjUsImp0aSI6IjM2OTJlMTk3NTU3MzRkMTE5ZTQzNDM0Njc2OGZjOWQyIiwidXNlcl9pZCI6OCwia2V5IjoiYXV0aGVudGljYXRpb24iLCJpZCI6ImJlbmphbWluLnlpbkBiaXRnZXQuY29tIn0.Fqv4Jzyfh2Qp67xCKTgM689mgl8EWOLk3_dikQxoaoeB90WphiHSpbLk4joXF6Q67Z2FmOB302D3uwJMkue5EEYk1t-7Fg_dwzaQfO2IZfdNBAQt3iU7ixJUh3p0HS7INRYnwyH6pqYxMSb2CAFWVnObpTFmhNLLioHKgSTpwZaYIcwmQr-TMTdu--tMhphD5RwXIQ9SEtCy7QQbydTEuZPr3gDEX4C5bDwqYUdwc1995_ks0zwpzlf55TiNRpRTeUaUItXgqbfxqFE6u78vPxirJ4l3otjL1kqiZ2Yim6_7Fec4SK1V7RYMCEVB5R-5Mxqyvk3f6CfQII2BRmBaiQ"
                },
                "_parse": "function(res){let options=[];res.map((item)=>{options.push({label:item.service_name,value:item.service_name})});return options}",
                "to": "options"
            },
            "_fc": false
        },
        "props": {
            "_optionType": 1
        },
        "_fc_drag_tag": "select",
        "hidden": false,
        "display": true
    }
]
``

期望可以拿到

**Comment by chenyidong520** [comment]
问题一样，如果再自定义了header  是不是要用ts.    能不能用axios 来拿数据？
