### ISSUE TITLE
上传图片预览问题

### ISSUE THREAD

**Issue by williamBoss** [xaboy/form-create#6]
请问以前版本的上传图片之后点击预览的事件，现在是否需要自己写了，还是可以继续延续之前的方法

**Comment by xaboy** [comment]
之前没有写,需要自己重写.因为左边的图标是可以自定义的,不一定是预览.点击事件是`onHandle`

**Comment by xaboy** [comment]
下个版本可以加个默认预览方法

**Comment by williamBoss** [comment]
谢谢

**Comment by williamBoss** [comment]
iview 上传不是有一个默认的预览方法吗

**Comment by williamBoss** [comment]
请问一下，field字段的值是数字的话，表单是不是会按照field字段进行排序

**Comment by xaboy** [comment]
不会,始终按照数组的顺序排序. 你是什么业务逻辑?不能确定数组的顺序?

**Comment by williamBoss** [comment]
数组由于是后台动态传输给我的，刚刚试了一下如果是这种形式的传到前台——field: field,其中field是数字的话，生成的表单将会按照fieId字段进行排序，如果改成field : '"'+field+'"',这样的话，这个问题就不存在了

**Comment by xaboy** [comment]
我刚刚试了下,还真有这个问题.我处理一下

**Comment by xaboy** [comment]
还有什么问题吗,我一次都修改了

**Comment by xaboy** [comment]
字段排序问题修复了,默认预览图片功能增加了

**Comment by xaboy** [comment]
npm 1.1.7版本发布了,你可以更新一下
