### ISSUE TITLE
建议作者增加一个select+tree可以实现下拉搜索树

### ISSUE THREAD

**Issue by Liuyaoyao123** [xaboy/form-create#601]

**Comment by 1025946443** [comment]
不能支持么 我看form-create文档没写 但是按照element 或者ant文档中组件属性应该可以的把
ant 下 我的form-create treeSelect 生成代码 (没用自定义组件)
`{
        "type": "treeSelect",
        "field": "parentDeptIdx",
        "title": "归属机构",
        "info": "",
        "props": {
            "treeData": [],
            "placeholder": "请选择归属机构",
            "showSearch": true,
        },
        "_fc_drag_tag": "tree",
        "hidden": false,
        "display": true,
        "$required": "归属机构不能为空"
    }`
