### ISSUE TITLE
upload上传组件bug

### ISSUE THREAD

**Issue by zhangwinfei** [xaboy/form-create#603]
## form-create版本
@form-create/element-ui@2.5.16及后续2.5.x所有版本

## UI 框架的版本
elementUI 2.15.13

## 问题描述
upload上传组件，点击删除按钮删除图片后，formData未发生变化

### 2、在App.vue对监听事件进行log输出
![微信图片_20230530191948](https://github.com/xaboy/form-create/assets/37200641/3a4d97d2-fb74-40c8-a544-ef1fdb90a6d2)

### 3、举例input输入框内容变更后，会触发以上的console.log，打印内容
![微信图片_20230530192000](https://github.com/xaboy/form-create/assets/37200641/dc005c99-6674-4718-a949-2b7fc9e96876)

### 4、如果生成表单的规则中 upload组件存在默认值
![微信图片_20230530191956](https://github.com/xaboy/form-create/assets/37200641/fdb3503d-dba8-433e-b723-b6cdd8548c12)

### 5、点击图片的删除按钮删除图片后，未触发复现流程2的console.log，formData数据也未发生更改
![微信图片_20230530192004](https://github.com/xaboy/form-create/assets/37200641/6c8b4321-c313-4551-b3ca-73ae08d7ded0)

### 6、在App.vue将fapi挂载到window上，点击图片的删除按钮删除图片后，通过控制台输出 fapi.value.form ，里面的内容也没有被删除
![微信图片_20230530193323](https://github.com/xaboy/form-create/assets/37200641/d06fdac1-55ba-4990-a6ec-a3899c34752c)
![微信图片_20230530193326](https://github.com/xaboy/form-create/assets/37200641/944578cd-9bfc-4e27-a0eb-e477abcab738)

**Comment by xaboy** [comment]
感谢反馈, 我这边检查一下 @zhangwenfeis

**Comment by xaboy** [comment]
2.5.29版本已修复
