### ISSUE TITLE
Use of eval in "node_modules/.pnpm/@form-create+element-ui@3.1.21_vue@3.2.47/node_modules/@form-create/element-ui/dist/form-create.esm.js" is strongly discouraged as it poses security risks and may cause issues with minification.

### ISSUE THREAD

**Issue by wangjinqiao** [xaboy/form-create#606]
打包时报错Use of eval in "node_modules/.pnpm/@form-create+element-ui@3.1.21_vue@3.2.47/node_modules/@form-create/element-ui/dist/form-create.esm.js" is strongly discouraged as it poses security risks and may cause issues with minification.

**Comment by xaboy** [comment]
看看能不能屏蔽这个报错

**Comment by jswangtao** [comment]
怎么屏蔽报错

**Comment by circlewang** [comment]
请问这个问题解决了吗，我现在也遇到了，不知道该怎么屏蔽

**Comment by xaboy** [comment]
下个版本针对这个问题优化一下, 目前可以先通过Babel 配置,
如果你的项目使用了 Babel 进行代码转换和编译，可以通过在 Babel 配置中添加特定的插件或预设来解决该问题。例如，可以考虑使用 babel-plugin-transform-remove-strict-mode 插件来移除严格模式下的 eval。

**Comment by xaboy** [comment]
3.1.23已修复

**Comment by circlewang** [comment]
> 

感谢大大，但是还有个@form-create/designer这个组件也有这个报错，node_modules/.pnpm/registry.npmmirror.com+@form-create+designer@3.1.3_vue@3.3.0/node_modules/@form-create/designer/dist/index.es.js (264:9) Use of eval in "node_modules/.pnpm/registry.npmmirror.com+@form-create+designer@3.1.3_vue@3.3.0/node_modules/@form-create/designer/dist/index.es.js" is strongly discouraged as it poses security risks and may cause issues with minification.
