### ISSUE TITLE
info使用object类型报错

### ISSUE THREAD

**Issue by 498755303** [xaboy/form-create#607]
版本号:@form-create/ant-design-vue@2.5.28

控制台报错多个
![image](https://github.com/xaboy/form-create/assets/28357943/4fc2b9f3-0b5c-4b9e-9e4c-215beddebbe1)
![image](https://github.com/xaboy/form-create/assets/28357943/0d93b04b-7144-452e-9311-db3143309b02)
![image](https://github.com/xaboy/form-create/assets/28357943/839c5c0b-97cf-4653-8b67-557064b526da)

配置如下规则：
`{
		"type": "input",
		"field": "name",
		"title": "名",
		"info": {
			"info": "名长度在1-255之间",
                        "align": "left"
		},
		"props": {
			"type": "text",
			"maxLength": 255,
			"minLength": 1,
			"placeholder": "请输入名",
			"allowClear": true
		},
		"validate": [{
			"required": true,
			"message": "请输入合法的名,长度在1~255之间",
			"mix": 1,
			"max": 255,
			"trigger": "blur"
		}]
	}
`

解决报错

**Comment by xaboy** [comment]
<img width="1568" alt="image" src="https://github.com/xaboy/form-create/assets/21242408/800e1524-4200-497e-ba50-4533534f38ad">
配置中align参数是个对象类型.你传参错了 @498755303
