### ISSUE TITLE
fcGroup 组件

### ISSUE THREAD

**Issue by CodeGather** [xaboy/form-create#609]
版本号 (version) 
例如: @form-create/element-ui@3.1.21

UI 框架的版本 (UI version) 
例如: 2.13.0

问题描述 (Issue) 

复现步骤/生成规则 (Duplicate steps/generate rules)

期望的结果 (Desired outcome)

fcGroup 组件下希望可以动态设置field字段

**Comment by xaboy** [comment]
动态设置field字段? 请详细说说

**Comment by CodeGather** [comment]
弄好了
