### ISSUE TITLE
@form-create/element-ui 使用时间控件导致内存溢出的问题

### ISSUE THREAD

**Issue by starrytky** [xaboy/form-create#610]
"@form-create/element-ui": "^3.1.12"

"element-plus": "^2.2.16"

有时间控件的表单项存在内存溢出的问题，一个时间控件的表单约导致2.5m的内存无法释放，数量足够会导致浏览器崩溃

重复打开有时间控件的表单页面

期望：内存可以不存在溢出问题；
或有对应的建议：比如升级到哪个版本或者降级到哪个版本可以不出现该问题

将版本号和UI框架对应版本列举出来并有明显的指引
vue3版的文档可以增加搜索功能，不然文档的使用很困难

**Comment by xaboy** [comment]
提供一下生成规则,我这边复现检查下 @starrytky 
文档下半年会优化

**Comment by luqiudi** [comment]
> 提供一下生成规则,我这边复现检查下 @starrytky 文档下半年会优化

我看 官方的实例里面,即使安装了 `import formCreate from '@form-create/element-ui@next',还是从 '@form-create/element-ui' 这个包导入formCreate 这个组件,这是文档写错了,还是就这么用的呢?

**Comment by xaboy** [comment]
@next是vue3版本, 不带@next就是vue2的版本. 这是声明的是包的标签
