### ISSUE TITLE
关于源码本地运行

### ISSUE THREAD

**Issue by 0321long** [xaboy/form-create#611]
源码拉取到本地无法运行，本地node版本16.20.0和18.16.0都无法运行，请问需要还考虑哪些方面的因素？

**Comment by xaboy** [comment]
1. `npm install`
2. `npm run bootstrap`

**Comment by keda** [comment]
本地运行成功后，浏览器访问异常是怎么处理？
本地环境：

> 分支：next
> env: node v16.15.0   npm 8.5.5
> 浏览器：chrome  114.0.5735.198（正式版本）

<img width="621" alt="image" src="https://github.com/xaboy/form-create/assets/1555397/6c0c62db-7817-40d0-9a73-2fb0579a0ac1">

<img width="1141" alt="image" src="https://github.com/xaboy/form-create/assets/1555397/d5250301-37e7-4637-8ba8-7de18b62d629">

<img width="741" alt="image" src="https://github.com/xaboy/form-create/assets/1555397/86b340f7-0c13-4990-968b-841933ec3c61">

**Comment by jelly006** [comment]
帅哥 访问异常最后怎么解决的啊 @keda

**Comment by xqdsnow** [comment]
node 版本 ：v16.14.0
目前看来，应该是包管理器的原因
使用yarn安装依赖即可
yarn install 或者 yarn -i
