### ISSUE TITLE
iview的checkbox组件手动设值时，勾选的checkbox存在问题

### ISSUE THREAD

**Issue by bkbow** [xaboy/form-create#612]
在最新版本，使用iview的checkbox组件，当options有如下值时，使用fApi.setValue后，勾选的checkbox项不正确
`options:[{value: "1", label:"第一个"},{value: "2", label:"第二个"},{value: "12", label:"第十二个"}]`
此时通过fApi.setValue方式给字段设值为12后，value为1和value为12的checkbox都会被勾选

分析：
跟踪到代码【components/iview/checkbox/src/component.jsx 】：42行，如下：
````
update() {
            this.trueValue = this.value ? this.options().filter((opt) =>  this.value.indexOf(opt.value)  !== -1)
                .map((option) => option.label) : []
        }
````

导致此问题出现的原因是这段代码：`this.value.indexOf(opt.value) !== -1`

希望修复该问题，辛苦了。

**Comment by xaboy** [comment]
2.5.29版本已修复
