### ISSUE TITLE
vue3 + naive使用中resetFields无效

### ISSUE THREAD

**Issue by ItsHeart** [xaboy/form-create#616]
![image](https://github.com/xaboy/form-create/assets/55654863/7359c42c-1c5f-4f05-9f89-83c376245a05)

resetFields无效

```
<template>
  <form-create :rule="rule" v-model:api="fapi" />
  <n-button type="primary" @click="reset">重置</n-button>
</template>

<script setup>
import { ref } from "vue";

const rule = ref([
  {
    type: "input",
    title: "姓名",
    field: "name",
  },
]);

const fapi = ref();

const reset = () => {
  console.log(1);
  fapi.value.resetFields();
};
</script>
```

resetFields重置表单

**Comment by xaboy** [comment]
这边检查是个bug, 目前可以先在rule里面加个`rule.value:''`解决
```
{
    type: "input",
    title: "姓名",
    field: "name",
    value: "",
  },
```

**Comment by xaboy** [comment]
3.1.23版本已修复

**Comment by ItsHeart** [comment]
经过测试，仅有input通过resetFields可以解决，但是select和其他组件仍然不行

**Comment by fit2cloudwxx** [comment]
我这边也是按照楼主一楼的写法 但是目前 也是清空校验不生效是什么原因
![image](https://github.com/xaboy/form-create/assets/138425844/6a6e457b-5ea1-40af-8291-d81db212d6da)
![image](https://github.com/xaboy/form-create/assets/138425844/1181a844-5693-4140-8dfe-6d6d3dd95dd2)
