### ISSUE TITLE
建议：官方文档里能不能全部提供组合式 API 的写法

### ISSUE THREAD

**Issue by tlerbao** [xaboy/form-create#617]
3.0官方文档现在全部是选项式 API 的写法示例，对于我这种前端小白来说，直接上 Vue3 的 <script setup> 
没有组合式 API 的示例有时候看起来挺困难的哈

PS：目前大家也都是 <script setup> ，很少有人写选项式了吧。

小小建议，感谢开源

**Comment by xaboy** [comment]
感谢反馈, 后面优化一下文档

**Comment by tlerbao** [comment]
@xaboy 还有前端小白请教一下，既然上了 ts 的贼船，请问form-create的类型各种类型怎么引入定义能不能一同卸载文档里，现在完全不知道怎么引入类型哈哈 ，全是 any
