### ISSUE TITLE
自定义组件中如何读取到注入的 formCreateInject？

### ISSUE THREAD

**Issue by ghost** [xaboy/form-create#618]
@form-create/element-ui": "^2.5.6"

"vue": "^2.6.14"

将 JSON 字符串转换为表单，子组件需要读取到 formCreate 相关的API，但是无法获取。

<img width="854" alt="image" src="https://github.com/xaboy/form-create/assets/111226919/ee80d20d-e64f-4468-925c-85e3a997e780">

![image](https://github.com/xaboy/form-create/assets/111226919/0611122d-ca52-4489-b151-04bfcd09a5ee)

![image](https://github.com/xaboy/form-create/assets/111226919/22fbab07-12a4-440d-acde-4f6dac33a5a5)

期望可以获取到 formCreateInject 。

![image](https://github.com/xaboy/form-create/assets/111226919/b97f10a3-0eed-433f-9d87-1cab36edf810)

**Comment by xaboy** [comment]
formCreateInject定义在props中,不是inject里面 @baburwang

**Comment by ghost** [comment]
> formCreateInject定义在props中，而不是inject里面@baburwang

哦哦，原来如此，解决了感谢🙏
