### ISSUE TITLE
在根据页面上比如单选按钮值隐藏某些字段，怎么同时禁用字段验证，否则无法提交？

### ISSUE THREAD

**Issue by tiger54910** [xaboy/form-create#62]
在根据页面上比如单选按钮值隐藏某些字段，怎么同时禁用字段验证，否则无法提交？
比如页面上选择不包邮，则不显示地址；包邮则显示地址功能。

**Comment by xaboy** [comment]
目前禁用不了,只有删除组件才不会验证.
这个应该可以优化

**Comment by tiger54910** [comment]
能不能在验证字段的时候判断下props的hidden为真，如果为真，则返回验证成功呢？可是我没有发现验证字段的那个函数validateFiled如何返回验证通过。

**Comment by xaboy** [comment]
表单验证是直接调用UI 框架的方法

**Comment by xaboy** [comment]
我的思路也是这样,目前没有想到更好的办法

**Comment by xaboy** [comment]
2.5版本已优化
