### ISSUE TITLE
检验规则 validator 的方法获取 fApi

### ISSUE THREAD

**Issue by chengpeng666** [xaboy/form-create#622]
可否支持在验证规则的 validation 方法中添加 fapi 参数。当前方法定义是 function(rule, value, callback)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xaboy** [comment]
<img width="697" alt="image" src="https://github.com/xaboy/form-create/assets/21242408/646cfd31-cbbb-4b83-be24-df31e79ce9dd">
在方法中通过getApi方法拿到对应表单的api

**Comment by fazcube** [comment]
[在验证规则中获取表单数据
在 FormCreate 中，validator 方法的 this 指向已修改为包含 api 属性。通过 this.api，开发者可以访问表单 API 以获取或操作其他字段的值。](https://www.form-create.com/v3/examples/validate#%E5%9C%A8%E9%AA%8C%E8%AF%81%E8%A7%84%E5%88%99%E4%B8%AD%E8%8E%B7%E5%8F%96%E8%A1%A8%E5%8D%95%E6%95%B0%E6%8D%AE)
