### ISSUE TITLE
ElementPlus按需加载时，分割线divider组件出错

### ISSUE THREAD

**Issue by Yhxang** [xaboy/form-create#624]
```
"@form-create/element-ui": "^3.1.22",
"element-plus": "^2.3.9",
```

按需加载时，使用el-divider出错。
经检查，似乎是`packages/element-ui/auto-import.js`中遗漏了注册组件。

**Comment by xaboy** [comment]
内置的组件里面没有用到el-divider, 需要自己手动挂载一下 @Yhxang

**Comment by Yhxang** [comment]
感谢回复，我用form-create-designer时看到有分割线，所以导出数据后，以为内置也就带了。
