### ISSUE TITLE
重置表单resetFields()不生效

### ISSUE THREAD

**Issue by fit2cloudwxx** [xaboy/form-create#625]
设置了表单必填项，进行校验的时候 下次打开弹窗的时候 Api.value.resetFields() 不生效

![image](https://github.com/xaboy/form-create/assets/138425844/4890ba2d-3f44-40a9-91eb-21fc59abfaef)

![image](https://github.com/xaboy/form-create/assets/138425844/8594bbee-f04d-4700-8a5a-0ca6fa322d65)
![image](https://github.com/xaboy/form-create/assets/138425844/81dc6ddb-cade-4d84-8a34-f280fda603c2)

翻看之前的issues是说的 3.1.23版本的会修复，是否和版本有关系，在群里问了相关问题，暂时没有说是版本的问题 希望能回复

**Comment by xaboy** [comment]
rule需要用ref包一下 

`const rule = ref([])`

**Comment by ItsHeart** [comment]
[https://github.com/xaboy/form-create/issues/616#issuecomment-1637197655](url)

**Comment by ItsHeart** [comment]
#620 naive的其他组件待解决
#616 这个解决了naive的select
