### ISSUE TITLE
数组组件里面子表单事件监听

### ISSUE THREAD

**Issue by chengtzu** [xaboy/form-create#626]
版本号 (version) 
@form-create/element-ui@2.5.32

UI 框架的版本 (UI version) 
element-ui@^2.15.8

使用数组组件 动态添加的每一行内的子组件 如何去绑定一个事件

这个选择按钮 的点击事件需要怎么绑定
rule:[
   {
                "type":"group",
                "field":"goods",
                "title":"产品信息",
                "props":{
                    "min":1,
                    "rules": [
                        {
                            "type":"el-col",
                            "props":{"span":24},
                            "children":[
                                { "type":"hidden", "field":"product_id","title":"","col":{"span":6}},
                                { "type":"hidden", "field":"product_code","title":"","col":{"span":6}},
                                { "type":"input", "field":"product_name","title":"产品名称","col":{"span":6},"effect":{"required":true},
                                    "children": [
                                        {
                                            "type": "el-button",
                                            "children": ["选择"],
                                            "slot": "suffix",
                                            "nativeEmit":["click"],
                                            "emitPrefix": "addgoods"
                                        }
                                    ]
                                },
                                { "type":"inputNumber", "field":"count","title":"数量","col":{"span":6},"effect":{"required":true}},
                                { "type":"input", "field":"price","title":"单价","col":{"span":6},"props":{"disabled":true}}
                            ]
                        }
                    ]
                },
                on:{
                    add:()=>{
                        
                    }
                }
            }
]

**Comment by chengtzu** [comment]
数组组件里面 子表单的 disabled 属性无效

**Comment by chengtzu** [comment]
![图片](https://github.com/xaboy/form-create/assets/42203765/98170271-98fa-4e65-a76d-fffe61b4c954)

**Comment by xaboy** [comment]
1. group组件生成的子表单的禁用状态是由group组件的props.disabled控制的,props.rule中的disabled无效
2. 子表单的事件例如按钮点击事件`addgoods-click`, 可以通过group规则的rule.on.addgoods-click = xxx来监听 @chengtzu
