### ISSUE TITLE
mixin.js中的_changeValue多次触发

### ISSUE THREAD

**Issue by tiger54910** [xaboy/form-create#63]
点击一次单选按钮，_changeValue函数触发了3次；不知道是什么原因？

**Comment by xaboy** [comment]
这个应该是已知的 bug,下个版本修复

**Comment by tiger54910** [comment]
哦，谢谢及时回复，这个lib非常适合我现在的项目；

**Comment by xaboy** [comment]
感谢你的支持 😃

**Comment by tiger54910** [comment]
http://www.form-create.com/guide/instance.html#f-component网址上的实例方法名字有错误，代码中没问题。可以修改下更好。
$f.claerValidateState 1.5.5+
用法：

$f.claerValidateState();

$f.claerValidateState(field);

$f.claerValidateState([field1,field2]);
清除组件的验证信息

**Comment by tiger54910** [comment]
我看这个网址文档的时候，觉得这个命名很奇怪，是单词写错了吧，不过白璧微瑕，呵呵

**Comment by xaboy** [comment]
是单词写错了,下次版本更新会修改

**Comment by xaboy** [comment]
已修复
