### ISSUE TITLE
嵌套对象中属性的field映射问题

### ISSUE THREAD

**Issue by 1025946443** [xaboy/form-create#630]
"@form-create/ant-design-vue": "^3.1.24",
    "ant-design-vue": "^4.0.0",

我有一个嵌套对象 我不知道field怎么写才能正确双向绑定到表单的值
比如 一个学生对象student 存了成绩如下
`
```
student:
 {
    name: '学生名称',
    gender: '性别',
    math: {
        socer: '数学成绩',
        time: '数学考试时间',
        rank: '数学排名'
    },
    chinese: {
        socer: '语文成绩',
        time: '语文考试时间',
        rank: '语文排名'
    }

}
form-create:
      <FormCreate ref="formRef" v-model="student" :rule="rule" :option="option" :disabled="disabled"/>

```

`
      <FormCreate ref="formRef" v-model="data" :rule="rule" :option="option" :disabled="disabled"/>

我rule中的子元素应该如何写才能正常映射呢?

```
[
...,
{
            "type": "input",
            "field": "??",
            "title": "数学成绩",
            "info": "",
            "_fc_drag_tag": "input",
            "hidden": false,
            "display": true
          },
...
]
```

期望以后可以:
数组["math","sorce"]或者字符串"math.sorce"

**Comment by xaboy** [comment]
不支持`.`操作, 只能通过子表单组件或者数组组件来实现对象结构

**Comment by 1025946443** [comment]
大佬能否写个 通过子表单组件实现该功能的例子

**Comment by 1025946443** [comment]
> 不支持`.`操作, 只能通过子表单组件或者数组组件来实现对象结构

大佬能否写个 通过子表单组件实现该功能的例子

**Comment by 1025946443** [comment]
> > 不支持`.`操作, 只能通过子表单组件或者数组组件来实现对象结构
> 
> 大佬能否写个 通过子表单组件实现该功能的例子

@xaboy 大佬有时间能否看下(#^.^#)

**Comment by xaboy** [comment]
```js
{
    type:'object',
    field:'student',
    props:{
        rule: [
            {
                type:'input',
                title:'生名称',
                field:'name',
            },
            {
                type:'object',
                field:'math',
                props: {
                    rule: [
                        {
                            type:'input',
                            title:'数学成绩',
                            field:'socer',
                        }
                    ]
                }
            }
        ]
    }
}
```
大概就是这样 @1025946443

**Comment by 1025946443** [comment]
> ```js
> {
>     type:'object',
>     field:'student',
>     props:{
>         rule: [
>             {
>                 type:'input',
>                 title:'生名称',
>                 field:'name',
>             },
>             {
>                 type:'object',
>                 field:'math',
>                 props: {
>                     rule: [
>                         {
>                             type:'input',
>                             title:'数学成绩',
>                             field:'socer',
>                         }
>                     ]
>                 }
>             }
>         ]
>     }
> }
> ```
> 
> 大概就是这样 @1025946443

感谢!!

**Comment by yanjiajun2020** [comment]
{
    name: '学生名称',
    gender: '性别',
    math#socer: '数学成绩',
    math#time: '数学考试时间',
    math#rank: '数学排名'
    chinese#socer: '语文成绩',
    chinese#time: '语文考试时间',
    chinese#rank: '语文排名'
}

rule：
            {
                type:'input',
                title:'数学成绩',
                field:'math#socer',
            }

json扁平化后传入FormCreate，返回数据再还原回来。 @1025946443

**Comment by leleccccc** [comment]
> ```js
> {
>     type:'object',
>     field:'student',
>     props:{
>         rule: [
>             {
>                 type:'input',
>                 title:'生名称',
>                 field:'name',
>             },
>             {
>                 type:'object',
>                 field:'math',
>                 props: {
>                     rule: [
>                         {
>                             type:'input',
>                             title:'数学成绩',
>                             field:'socer',
>                         }
>                     ]
>                 }
>             }
>         ]
>     }
> }
> ```
> 
> 大概就是这样 @1025946443

试了，赋值回显确实可以，但是我发现被嵌套的type:'input'的props的disabled为true会无效？其他属性却可以正常传入，感觉可能是个新问题
