### ISSUE TITLE
表单上传文件，如何动态设置请求头

### ISSUE THREAD

**Issue by ReedZheng** [xaboy/form-create#632]
版本号 (version) 
@form-create/designer": "^3.1.0
@form-create/element-ui": "^3.1.17

问题描述 (Issue)
![image](https://github.com/xaboy/form-create/assets/24835451/e3f12dcf-ca81-4cae-a2f4-f88613254b18)

期望的结果 (Desired outcome)
期望可以动态设置请求头信息，可以如何处理

**Comment by ReedZheng** [comment]
"vue": "3.2.47"
有大佬可以帮忙解答一下吗

**Comment by zhang011207** [comment]
同问，在里面编写localStorage会直接执行变为json

**Comment by xaboy** [comment]
可以通过定义options.beforeFetch方法,设置动态的请求头
