### ISSUE TITLE
tree组件 type为selected时左侧的checkbox有勾选状态显示异常的bug

### ISSUE THREAD

**Issue by zhangwinfei** [xaboy/form-create#636]
### 版本
2.5.*

### 问题描述
element-ui，tree组件 type为selected时，左侧的checkbox有勾选状态显示异常的bug

### 生成规则 
![微信图片_20230926125828](https://github.com/xaboy/form-create/assets/37200641/9aaf7fef-08da-4f16-b8ba-399890737be2)

### 源代码
![微信图片_20230926125429](https://github.com/xaboy/form-create/assets/37200641/1831cfd8-6deb-42a5-96b5-a1e339a3ef16)

### 修改后的代码
![微信图片_20230926125429_1](https://github.com/xaboy/form-create/assets/37200641/76ff2fb5-ade1-4612-b80c-3d02778cbc4b)

经测试，修改后的代码在单选模式下，同时只会有一个checkbox被选中，多选模式下也正常使用

**Comment by xaboy** [comment]
感谢反馈,我这边检查一下
