### ISSUE TITLE
form-create 嵌套form-create，外层的form-create的submit会导致嵌套的form-create校验触发。

### ISSUE THREAD

**Issue by bigbangfather** [xaboy/form-create#638]
form-create rule中使用了自定义的组件，自定义的组件也是一个form-create，但是当外部的form-create提交时候会触发自定义组件内的form-create校验，我认为这是一个奇怪的行为，导致我无法主动控制自定义组件内form-create的行为

期望可以解决嵌套时校验的触发方式。

**Comment by xaboy** [comment]
父表单校验时,自动校验子表单,这个是正常逻辑吧. 什么场景下不需要校验子表单呢? @bigbangfather

**Comment by bigbangfather** [comment]
> 父表单校验时,自动校验子表单,这个是正常逻辑吧. 什么场景下不需要校验子表单呢? @bigbangfather

一个自定义组件是由基于form-create实现的，这个组件是应用在外层的form-create上，外层通过类型去控制此组件的渲染，当我切换类型的时候我希望保持录入的数据不被清空所以用了display控制显隐而没有使用hidden，但当我隐藏的时候，提交还是会触发组件内的校验，所以我期望能在使用display的时候不会触发隐藏组件内的form-create校验。

**Comment by xaboy** [comment]
这边测试hidden不会导致录入的数据被清空, 请问这个问题怎么复现 @bigbangfather
