### ISSUE TITLE
设计器中自定义一个tab组件，支持新增标签，并可以给当前标签中的tabPane中拖动任意组件，请问现在支持吗？感谢

### ISSUE THREAD

**Issue by BetterHelga** [xaboy/form-create#640]

**Comment by BetterHelga** [comment]
<img width="745" alt="image" src="https://github.com/xaboy/form-create/assets/46038900/4a7ca26a-a407-4e8c-8b37-d46c175939c1">

<img width="1091" alt="image" src="https://github.com/xaboy/form-create/assets/46038900/5ab866ed-6cfc-4df6-9f4c-bc1cd3d5f6ef">

**Comment by xaboy** [comment]
vue2版本由兼容问题,会导致浏览器卡死, 所以没做支持
