### ISSUE TITLE
vue3 通过配置项emit监听事件会导致控制台警告

### ISSUE THREAD

**Issue by minbingwen** [xaboy/form-create#642]
@form-create/ant-design-vue@next

 rule 添加 emit:['change'], 使用正常，但是控制台会警告没有组件 emits 注册这个事件或没有相应的props

Component emitted event "field-change" but it is neither declared in the emits option nor as an "onField-change" prop.

还有 ant-design-vue中radio 类似组件中  a-radio =>  a-radio-button 这种需要修改到标签并不是props 的属性怎么生效

**Comment by xaboy** [comment]
可以通过`props. optionType = 'button'`来控制
