### ISSUE TITLE
🔥 🔥 disabled 状态下的 Upload 组件，UI 样式是否能做区分

### ISSUE THREAD

**Issue by lynnn-o-o** [xaboy/form-create#643]
图中第一个是正常可以点击状态， 其他的是 disabled 状态， 看起来并无区别
<img width="545" alt="image" src="https://github.com/xaboy/form-create/assets/148303592/2d8d0244-b367-41b6-a55c-513d8a9a7885">

      

期望可以强化 disabled 状态下的上传组件样式

**Comment by xaboy** [comment]
这个可以有, 使用的是那个版本

**Comment by lynnn-o-o** [comment]
form-create/iview4
