### ISSUE TITLE
考虑支持ant-design-vue4.0及以上的版本吗？

### ISSUE THREAD

**Issue by shenmr** [xaboy/form-create#644]
@form-create/ant-design-vue

ant-design-vue4.0出来很久了，新项目基本用4.0版本了，form-create建议也做个升级吧

**Comment by xaboy** [comment]
应该是支持的,我这边在测试一下兼容问题

**Comment by shenmr** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by xaboy** [comment]
3.1.26版本兼容ant-design-vue4.0版本
