### ISSUE TITLE
【bug】vue2文档挂了

### ISSUE THREAD

**Issue by Talking-mute** [xaboy/form-create#649]
地址：http://www.form-create.com/
   
   针对vue版本：vue2
   
   报错信息：见图片
   
![image](https://github.com/xaboy/form-create/assets/45475842/d079d754-306f-43e7-94ad-9ddb93f967a4)

**Comment by cp1001** [comment]
请作者尽快修复vue2的文档，另外能否将文档放到github里方便查看呢

**Comment by xaboy** [comment]
已修复
