### ISSUE TITLE
有计划支持动态配置生成组件吗?

### ISSUE THREAD

**Issue by endingman** [xaboy/form-create#65]
各种组件的属性使用UI配置自定义生成需要的组件。
比如input里lable、filed、rules、width、height等等，定义了生成相应属性的input

**Comment by xaboy** [comment]
这个通过自定义组件就可以实现吧
(生成自定义组件)[http://www.form-create.com/guide/custom-component.html]

**Comment by endingman** [comment]
@xaboy 这个我看了，我的想法是create里面的参数由外部输入，比如在一个页面上输入组件一些属性然后调用里面的create或者生成json创建组件这样。
好像是提供维护UI，动态调用方法来生成这样。
不知道有没有说明白？

**Comment by xaboy** [comment]
可以通过 props 配置项给组件内部传递参数,
详细可以参考[vue 渲染函数 & JSX](https://cn.vuejs.org/v2/guide/render-function.html)
