### ISSUE TITLE
快速上手案例不显示表单

### ISSUE THREAD

**Issue by startcaft** [xaboy/form-create#651]
版本号：

> "@form-create/naive-ui": "^3.1.26"

> "naive-ui": "^2.34.3"

### 快速上手案例不显示表单
按照官网的Naive UI版本的快速上手，不显示表单，控制台看nform.form-create大小为0x0
![image](https://github.com/xaboy/form-create/assets/5905758/2cc73b65-340c-4a94-9c23-65b3e210fde4)

![image](https://github.com/xaboy/form-create/assets/5905758/58324734-7c6c-45b4-9173-ecb9ee6bec49)

**Comment by xaboy** [comment]
全局挂载一下naive-ui

**Comment by startcaft** [comment]
好的，谢谢，已经好了。
