### ISSUE TITLE
使用json构造动态表单，如何设置control和update这些函数？

### ISSUE THREAD

**Issue by balck-paint** [xaboy/form-create#652]
v3x

element-plus

![image](https://github.com/xaboy/form-create/assets/81019019/711712b1-9cca-4118-8895-d7693d836d64)
如图，我是通过json动态生成表单的，但是一些函数如何通过json去表示，如这个control的hanlde函数，或者update函数，如何通过json去实现？

**Comment by balck-paint** [comment]
通过json如何实现这种js文件的方式？
![image](https://github.com/xaboy/form-create/assets/81019019/91141375-6340-4030-823e-1df9a604fba2)

**Comment by lsm2208911** [comment]
![image](https://github.com/xaboy/form-create/assets/13296996/36663e64-f356-4e85-89f3-a367fa69ec49)
通过designer生成的代码是这样的。
