### ISSUE TITLE
希望新增配置去掉单行外层el-col

### ISSUE THREAD

**Issue by gaylen1** [xaboy/form-create#654]
版本号 (version) 
    例如: @form-create/element-ui@3.1.26

    element-plus
    例如: 2.3.14

##  问题描述 (Issue)
使用栅格布局。假如：一行四列的情况下，放大缩小都是按照百分比放大缩小，在放大缩小时栅格里面的input宽度也会跟着变。这个时候我希望自定义内联布局，在不改变input宽度的情况下自动换行，而不是等比例缩放。

## 期望的结果 (Desired outcome)
在一些小屏幕下希望不改变元素的宽度实现自动换行

**Comment by xaboy** [comment]
可以提供一下测试的规则吗?
可以通过规则设置不生成col组件
```
{type:'input',col:false}
```

**Comment by gaylen1** [comment]
规则跟你这个差不多的。

**Comment by gaylen1** [comment]
设置规则col:false外层el-col还是存在，可以在这个列子上查看dom元素https://stackblitz.com/edit/vitejs-vite-ys2weq?file=src%2FApp.vue

![image](https://github.com/xaboy/form-create/assets/35060559/ebbdde6a-7e18-45fd-9fc8-5b6128db0dbc)

**Comment by xaboy** [comment]
搞错了,应该是`{type:'input',col:{show: false}}`

**Comment by gaylen1** [comment]
谢谢！问题已经解决。
