### ISSUE TITLE
日期选择框问题

### ISSUE THREAD

**Issue by shenmr** [xaboy/form-create#657]
@form-create/ant-design-vue 3.1.26版本

rangePicker组件设置预设范围presets后，选择后不能关闭选择框，除非是双击或者点击外面才行

代码：
{
  type: 'rangePicker',
  field: 'date',
  title: '日期范围',
  props: {
    placeholder: ['开始日期', '结束日期'],
    valueFormat: 'YYYY-MM-DD',
    disabledDate: (current: Dayjs) => current && (current > dayjs().endOf('day') || current <= dayjs('2019-05-30')),
    presets: [{ label: '全部范围', value: [dayjs('2019-05-30'), dayjs()] }],
  }
}

**Comment by xaboy** [comment]
可能是antdv版本问题,我使用4.x版本没有复现

**Comment by shenmr** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by shenmr** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
