### ISSUE TITLE
FormCreate + ArcoDesign DatePicker组件props type为datetimerange没有效果

### ISSUE THREAD

**Issue by onlyColor54** [xaboy/form-create#659]
您好，很抱歉打扰到您，但这个问题我搞了好久没有任何进度，只能来请教您了
下面是package信息
"@form-create/arco-design":"^3.1.23“
“@arco-design/web-vue“:“^2.51.0“
用的是arco-design版本，DatePicker 日期选择器，按照示例props->type=datetimerange 这个参数无效，其他枚举类型也无效

**Comment by xaboy** [comment]
使用
```
{type:rangePicker}
```
或者
```
{type:'datePicker', props: {mode:'date', range: true }}
```

**Comment by onlyColor54** [comment]
可以的，我这边试了一下没问题，十分感谢
