### ISSUE TITLE
vue3 如何销毁表单

### ISSUE THREAD

**Issue by chiyandetaotie** [xaboy/form-create#661]
@form-create/element-ui 版本: 3.1.26
element-plus 版本: 2.4.1
由于同一页面需要切换不同表单内容，需要每次切换后，销毁之前的表单再重新创建，请问应该如何操作？V2版本中提供的
fApi.destroy()函数没有了吗？在V3版本中，应该如何销毁表单？

**Comment by xaboy** [comment]
销毁用`v-if`,生成规则如果存在复用的情况,兼容使用之前深拷贝一下
