### ISSUE TITLE
pnpm build时会报一个警告

### ISSUE THREAD

**Issue by huyuan9479** [xaboy/form-create#668]
form-designer-naiveui: "^1.1.0"
警告内容入下：node_modules/.pnpm/form-designer-naiveui@1.1.0_vue@3.2.47/node_modules/form-designer-naiveui/dist/index.es.js (176:13) Use of eval in "node_modules/.pnpm/form-designer-naiveui@1.1.0_vue@3.2.47/node_modules/form-designer-naiveui/dist/index.es.js" is strongly discouraged as it poses security risks and may cause issues with minification.

**Comment by xaboy** [comment]
你用的这个不是官方的包,可能是版本没有同步更新. 替换掉代码中的eval方法就好了 @huyuan9479
