### ISSUE TITLE
大佬，怎么向自定义组件中传值并且自定义组件能接收到。

### ISSUE THREAD

**Issue by NJHSFNAK** [xaboy/form-create#679]

**Comment by 1025946443** [comment]
https://www.form-create.com/v2/guide/custom-component.html
值用modalValue传递,一些自定义的值放在props下面

**Comment by fit2cloudwxx** [comment]
自定义组件更新的值通过emit Change 事件的时候 初始化的时候也会触发change 事件 比如要实现 改变某一个值要调用更新接口的时候 要怎么实现
