### ISSUE TITLE
表单提交问题

### ISSUE THREAD

**Issue by taoman** [xaboy/form-create#686]
form-create/ant-design-vue": "^3.1.28"

"element-plus": "^2.3.12",

在vue3里面使用，<form-create :rule="rule" v-model:api="fApi" :option="options" />，rule和options都是从后端接口拿过来的json数据去做渲染，渲染上去之后有提交和重置按钮，const fApi = ref<>({}); fapi这样定义，在onMounted里面写fApi.value.submit = (formData)=>{}，点击提交的时候没法触发，submit事件是应该怎么写，求解

**Comment by xaboy** [comment]
应该这么写: fApi.value.submit((formData)=>{})

**Comment by taoman** [comment]
> 应该这么写: fApi.value.submit((formData)=>{})

非常感谢，已解决，还想再问一下，表单设计器我是用iframe嵌入到我们的项目里面，很多时候往渲染区域拖拽了一个元素后，再拖拽别的元素的时候，会拖不进去，是一个禁用的标志，这是什么原因？
