### ISSUE TITLE
数组组件如何修改字段

### ISSUE THREAD

**Issue by hanfengcan** [xaboy/form-create#690]
@form-create/naive-ui: ^3.1.28

数组组件如何对字段进行setValue

```
{
  type: 'group',
  props: {
    rule: [
      ...字段1,
      ...字段2,
      {
        type: 'select',
        update(value, rule, fApi) {
          fApi.setValue(‘字段1’， 1)
          fApi.setValue(‘字段1’， 2)
        }
      }
    ]
}
```

在数组表单里面进行update监听，修改字段后，在最外层进行formData()读取不到设置的内容。对于数组表单，应该如何操作

**Comment by xaboy** [comment]
这边没有复现, 测试setValue后,group组件和最外层表单的值会同步变化

**Comment by hanfengcan** [comment]
哦，那我在测试测试

**Comment by hanfengcan** [comment]
```vue
<template>
  <form-create
    class="fc"
    :rule="itemConf.rule"
    :option="itemConf.option"
    @update:api="itemConf.fApi = $event"
  ></form-create>
  <div>
    <n-button class="ml-4" @click="add">add</n-button>
    <n-button type="primary" class="ml-4" @click="get">get</n-button>
  </div>
</template>

<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref, toRaw, watch } from 'vue'

/**@type {import('@form-create/naive-ui').FormRule[]} */
const rule = [
  {
    type: 'group',
    field: 'msgConf',
    props: {
      defaultValue: { type: 'msg' },
      /**@type {import('@form-create/naive-ui').FormRule[]} */
      rule: [
        {
          type: 'select',
          title: '类型',
          field: 'type',
          options: [
            { label: '消息', value: 'msg' },
            { label: '弹窗', value: 'mod' },
          ],
        },
        {
          type: 'input',
          title: '触发条件',
          field: 'condition',
          props: {
            type: 'textarea',
            placeholder: '请输入jsonata表达式',
          },
          // suffix: {
          //   type: 'span',
          //   children: [{ type: 'i', class: 'add i-me:terminal-box-line ml-4' }],
          // },
        },
        {
          type: 'input',
          title: '提示内容',
          field: 'msgVal',
          suffix: {
            type: 'span',
            children: [{ type: 'i', class: 'add i-fe:eye ml-4' }],
          },
        },
      ],
    },
  },
]
const itemConf = {
  rule,
  /**@type {import("@form-create/naive-ui").Api} */
  fApi: {},
  /**@type {import("@form-create/naive-ui").Options} */
  option: {
    submitBtn: false,
    form: {
      labelWidth: 70,
    },
    row: {
      'item-responsive': true,
      'x-gap': 10,
    },
    col: {
      span: '24',
    },
    wrap: {
      // style: 'user-select: none;',
    },
  },
}

function get() {
  console.log(itemConf.fApi.formData())
}
function add() {
  itemConf.fApi.setValue({
    msgConf: [{ type: 'msg' }, { type: 'msg' }],
  })
}

onMounted(() => {
  console.log('hello')
})
</script>

```

以上这个demo，通过coverValue或者setValue，设置值后，界面没有变化。但是设置值后获取值就有内容。

![image](https://github.com/xaboy/form-create/assets/4559753/d667cb2a-ae44-4718-825d-3002a0ad33f9)

**Comment by hanfengcan** [comment]
官网的例子也不行
```vue
<template>
  <div>
    <p>value: {{ value.group }}</p>
    <form-create v-model:api="fApi" v-model="value" :rule="rule" :option="options" />
  </div>
</template>

<script setup>
import { onMounted } from 'vue'
let fApi = {}
let value = {}
let options = {
  onSubmit: (formData) => {
    alert(JSON.stringify(formData))
  },
}
let rule = [
  {
    type: 'group',
    field: 'group',
    title: 'group',
    value: [],
    props: {
      defaultValue: { field1: 'field1', field2: 'field2' },
      rule: [
        { type: 'input', field: 'field1', title: 'field1' },
        { type: 'input', field: 'field2', title: 'field2' },
      ],
    },
  },
]
onMounted(() => {
  fApi.coverValue({
    group: [{ field1: '122', field2: '222' }],
  })
})
</script>
```
![image](https://github.com/xaboy/form-create/assets/4559753/533dd55f-cfb7-4a45-9a0e-8d38e5acc4a9)

**Comment by hanfengcan** [comment]
> 官网的例子也不行
> 
> ```
> <template>
>   <div>
>     <p>value: {{ value.group }}</p>
>     <form-create v-model:api="fApi" v-model="value" :rule="rule" :option="options" />
>   </div>
> </template>
> 
> <script setup>
> import { onMounted } from 'vue'
> let fApi = {}
> let value = {}
> let options = {
>   onSubmit: (formData) => {
>     alert(JSON.stringify(formData))
>   },
> }
> let rule = [
>   {
>     type: 'group',
>     field: 'group',
>     title: 'group',
>     value: [],
>     props: {
>       defaultValue: { field1: 'field1', field2: 'field2' },
>       rule: [
>         { type: 'input', field: 'field1', title: 'field1' },
>         { type: 'input', field: 'field2', title: 'field2' },
>       ],
>     },
>   },
> ]
> onMounted(() => {
>   fApi.coverValue({
>     group: [{ field1: '122', field2: '222' }],
>   })
> })
> </script>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/4559753/338043128-533dd55f-cfb7-4a45-9a0e-8d38e5acc4a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5OTk2MjQsIm5iZiI6MTcxNzk5OTMyNCwicGF0aCI6Ii80NTU5NzUzLzMzODA0MzEyOC01MzNkZDU1Zi1jZmI3LTRhNDUtOWEwZS04ZDM4ZTVhY2M0YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMDYwMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWVkM2Y1ZGI4OTEyYmUwOWNjN2FhZDljNjNmNGE3ODBiYWQzZDY2ZTc0N2QxZmVmZGM2NTI4YmI3MjJlMDBhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a5bdaAg70xMKRnRO4HVWzO57JoCDrV99vQ5rxjRoOuo)

把UI切换成饿了么，发现去除value:[]这行就可以正常显示。断点跟踪到，setValue成功后，触发了watch。重新设置成[]

**Comment by xaboy** [comment]
感谢反馈, 我这边检查一下 @hanfengcan

**Comment by hanfengcan** [comment]
> 感谢反馈, 我这边检查一下 @hanfengcan

感谢回复。我测试了。如果是naive-ui。这样写，就能正常显示

```
onMounted(async () => {
  console.log(fApi.value.setValue)
  await nextTick()
  fApi.value.setValue({
      group: [{field1: 'aaa', field2: 'sss'}, {field1: 'aaa', field2: 'sss'}]
    })
})
```

这个组件太庞大了，不知道如何定位问题，附上测试代码
[demo.zip](https://github.com/user-attachments/files/15757447/demo.zip)

**Comment by hanfengcan** [comment]
> ```
> <template>
>   <form-create
>     class="fc"
>     :rule="itemConf.rule"
>     :option="itemConf.option"
>     @update:api="itemConf.fApi = $event"
>   ></form-create>
>   <div>
>     <n-button class="ml-4" @click="add">add</n-button>
>     <n-button type="primary" class="ml-4" @click="get">get</n-button>
>   </div>
> </template>
> 
> <script setup>
> import { nextTick, onBeforeUnmount, onMounted, ref, toRaw, watch } from 'vue'
> 
> /**@type {import('@form-create/naive-ui').FormRule[]} */
> const rule = [
>   {
>     type: 'group',
>     field: 'msgConf',
>     props: {
>       defaultValue: { type: 'msg' },
>       /**@type {import('@form-create/naive-ui').FormRule[]} */
>       rule: [
>         {
>           type: 'select',
>           title: '类型',
>           field: 'type',
>           options: [
>             { label: '消息', value: 'msg' },
>             { label: '弹窗', value: 'mod' },
>           ],
>         },
>         {
>           type: 'input',
>           title: '触发条件',
>           field: 'condition',
>           props: {
>             type: 'textarea',
>             placeholder: '请输入jsonata表达式',
>           },
>           // suffix: {
>           //   type: 'span',
>           //   children: [{ type: 'i', class: 'add i-me:terminal-box-line ml-4' }],
>           // },
>         },
>         {
>           type: 'input',
>           title: '提示内容',
>           field: 'msgVal',
>           suffix: {
>             type: 'span',
>             children: [{ type: 'i', class: 'add i-fe:eye ml-4' }],
>           },
>         },
>       ],
>     },
>   },
> ]
> const itemConf = {
>   rule,
>   /**@type {import("@form-create/naive-ui").Api} */
>   fApi: {},
>   /**@type {import("@form-create/naive-ui").Options} */
>   option: {
>     submitBtn: false,
>     form: {
>       labelWidth: 70,
>     },
>     row: {
>       'item-responsive': true,
>       'x-gap': 10,
>     },
>     col: {
>       span: '24',
>     },
>     wrap: {
>       // style: 'user-select: none;',
>     },
>   },
> }
> 
> function get() {
>   console.log(itemConf.fApi.formData())
> }
> function add() {
>   itemConf.fApi.setValue({
>     msgConf: [{ type: 'msg' }, { type: 'msg' }],
>   })
> }
> 
> onMounted(() => {
>   console.log('hello')
> })
> </script>
> ```
> 
> 以上这个demo，通过coverValue或者setValue，设置值后，界面没有变化。但是设置值后获取值就有内容。
> 
> ![image](https://private-user-images.githubusercontent.com/4559753/338034106-d667cb2a-ae44-4718-825d-3002a0ad33f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDgzNjEsIm5iZiI6MTcxODAwODA2MSwicGF0aCI6Ii80NTU5NzUzLzMzODAzNDEwNi1kNjY3Y2IyYS1hZTQ0LTQ3MTgtODI1ZC0zMDAyYTBhZDMzZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMDgyNzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E3NTRjMmQzNGMxYWI1ZTA0MDg5MThiOGIwYTc3MmI1NWJhYzQzOTkzY2IzNDZhN2E5NDFkODFlOTUwYjY5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dH8Epp7_VgbQBGHuOfOaqQxcYWECtEghmY20iIg_K_g)

这里的itemConf需要用reactive包起来

**Comment by xaboy** [comment]
需要把itemConf和rule转换成响应式的, 分别用reactive和ref包起来. 我这边测试功能正常的 @hanfengcan
