### ISSUE TITLE
有没有配置在提交数据时不获取field对应的值

### ISSUE THREAD

**Issue by gaylen1** [xaboy/form-create#693]
版本号 @form-create/element-ui@3.1.27)

UI 框架的版本element-plus: 2.4.0

问题描述：rules规则里，每个规则组件都对应一个field，当由多个规则组成一个组件时。在获取保存数据是会获取到多个field。但其实我只有一项数据是需要保存的。这时其余field就成了脏数据。

案例截图：
这个是el-checkbox-group组，他下面放了多个checkbox组件。
![image](https://github.com/xaboy/form-create/assets/35060559/5704d257-d1ac-4197-a1bc-d74c4e9e819a)

但没个checkbox组件都有一个field值
![image](https://github.com/xaboy/form-create/assets/35060559/0130050c-808f-472f-a660-554c984d603d)

在提交时就会产生多个field对应的值，但实质上应该只有el-checkbox-group组件绑定v-model才是需要提交的。
![image](https://github.com/xaboy/form-create/assets/35060559/00099250-f3c3-48c2-8c13-8c0033eba448)

期望：
希望rules规则下新增配置来控制一些不需要收集的值。

**Comment by xaboy** [comment]
给el-checkbox不定义field字段就好了呀,改成props.modelValue @gaylen1
