### ISSUE TITLE
FormCreate放到 a-modal 弹框中时，resetFields 无效

### ISSUE THREAD

**Issue by kele59** [xaboy/form-create#697]
FormCreate放到 modal 弹框中时，resetFields 无效
"ant-design-vue": "^4.1.2"
"@form-create/ant-design-vue": "^3.1.28"

```
<a-modal
  v-model:open="open"
>
  <FormCreate
    v-model:api="fApi"
    v-model="value"
    :option="formCreateOptions"
    :rule="rule"
  >
  </FormCreate>

  <a-button @click="reset">reset</a-button>
</a-modal>

function reset() {
  fApi.value.resetFields() // 没有效果
}
```

把 a-modal 拿掉，就正常了
```

  <FormCreate
    v-model:api="fApi"
    v-model="value"
    :option="formCreateOptions"
    :rule="rule"
  >
  </FormCreate>

  <a-button @click="reset">reset</a-button>


function reset() {
  fApi.value.resetFields() // 正常
}
```

**Comment by wojss** [comment]
@zaxlct 请问，这个问题解决了吗，怎么处理的呢

> FormCreate放到 modal 弹框中时，resetFields 无效 "ant-design-vue": "^4.1.2" "@form-create/ant-design-vue": "^3.1.28"
> 
> ```
> <a-modal
>   v-model:open="open"
> >
>   <FormCreate
>     v-model:api="fApi"
>     v-model="value"
>     :option="formCreateOptions"
>     :rule="rule"
>   >
>   </FormCreate>
> 
>   <a-button @click="reset">reset</a-button>
> </a-modal>
> 
> function reset() {
>   fApi.value.resetFields() // 没有效果
> }
> ```
> 
> 把 a-modal 拿掉，就正常了
> 
> ```
> 
>   <FormCreate
>     v-model:api="fApi"
>     v-model="value"
>     :option="formCreateOptions"
>     :rule="rule"
>   >
>   </FormCreate>
> 
>   <a-button @click="reset">reset</a-button>
> 
> 
> function reset() {
>   fApi.value.resetFields() // 正常
> }
> ```
