### ISSUE TITLE
是否有 手动触发 rule.fetch 的api ?

### ISSUE THREAD

**Issue by willnewii** [xaboy/form-create#708]
"@form-create/naive-ui": "^3.1.35"
"naive-ui": "2.38.2"

问题描述 
需求：有两个下拉框，省市。省变更后市的options数据跟着变更。

目前的实现：在市 rule 中关联 省.当省值发生变化后,在update 中重新发起请求,并更新市的options.

想问一下有没有可以手动触发rule.effect.fetch的方法？这样就可以调整为  先更新 rule.effect.fetch.data,再触发rule.effect.fetch 重新获取options .

**Comment by xaboy** [comment]
fetch数据变化后会自动重新请求 @willnewii
