### ISSUE TITLE
2.5版本中的antdv中input组件使用updateRule改变type字段，组件却无法切换

### ISSUE THREAD

**Issue by eloves** [xaboy/form-create#709]
## 版本号 (version) 
   
> @form-create/ant-design-vue@2.5.37

## UI 框架的版本 (UI version) 
    

> ant-design-vue@1.7.2

## 问题描述 (Issue) 

2.5版本中的antdv中input组件使用updateRule改变type字段，组件却无法切换。其它组件可以正常切换，对应的其它框架input也没有这个问题。

## 复现步骤/生成规则 (Duplicate steps/generate rules)

规则：
```
rule:[
      {
          type:'input',
          field:'goods',
          title:'商品名称',
          value:'form-create'
      }
]
```

api调用：
```
updateRules({
  goods: {
    type: 'custom-com',
   children: ['**']
  }
})
```

## 期望的结果 (Desired outcome) 
希望可以正常切换type

## 建议 (Advice) 
优化antdv中input的render写法，判断ctx.type类型，再来判断使用ctx.$render.vNode.make或者ctx.$render.defaultRender

**Comment by xaboy** [comment]
感谢反馈, 下个版本修复

**Comment by xaboy** [comment]
已优化
