### ISSUE TITLE
表单项额外提示 extra/explain/help如何设置？

### ISSUE THREAD

**Issue by XiaoNode** [xaboy/form-create#711]
@form-create/iview": "^2.5.37  

view-design": "^4.5.0  

json生成表单，希望在表单项下方有一段自定义文字提示，如表单项上方是输入框，输入框下面有个常驻黄色提示：请核实填写

    {
        type: "input",
        title: "商品名称",
        //label名称
        field: "goods_name",
        //字段名称
        value: "",
        //input值,
        props: {
            type: "text",
            //输入框类型，可选值为 text、password、textarea、url、email、date
            clearable: false,
            //是否显示清空按钮
            disabled: false,
            //设置输入框为禁用状态
            readonly: false,
            //设置输入框为只读
            rows: 4,
            //文本域默认行数，仅在 textarea 类型下有效
            autosize: false,
            //自适应内容高度，仅在 textarea 类型下有效，可传入对象，如 { minRows: 2, maxRows: 6 }
            number: false,
            //将用户的输入转换为 Number 类型
            autofocus: false,
            //自动获取焦点
            autocomplete: "off",
            //原生的自动完成功能，可选值为 off 和 on
            placeholder: "请输入商品名称",
            //占位文本
            size: "default",
            //输入框尺寸，可选值为large、small、default或者不设置,
            spellcheck: false,
            //原生的 spellcheck 属性
            required: false
        },
        col: {
            span: 12
        },
        validate: [
            {
                required: true,
                message: "请输入商品名称",
                trigger: "blur"
            }
        ]
    },

能插入diy提示

抱歉官方文档上没找到，能否告知下怎么做到或者是否支持，感谢。
![img](https://github.com/xaboy/form-create/assets/13958654/20ba69a4-9fbf-47a1-a3a4-bf09b8c65bb8)

**Comment by xaboy** [comment]
可以通过`suffix`配置项实现, 帮助文档: https://www.form-create.com/v3/guide/side
