### ISSUE TITLE
源码下载之后项目启动报错

### ISSUE THREAD

**Issue by ZaL0-0** [xaboy/form-create#713]
@form-create/naive-ui github download 最新版本

源码下载安装依赖之后启动项目报错
![企业微信截图_17201470785215](https://github.com/xaboy/form-create/assets/22867745/334a2f4b-ca6c-40e5-9fdd-1ce12e1a19d3)

复现步骤
1.npm install
2.cd packages/naive-ui 
3.npm install

正常启动

**Comment by ZaL0-0** [comment]
node16版本

**Comment by kebokiller** [comment]
同样的问题

**Comment by haikuotiankong123** [comment]
我也是同样的问题；node版本18.4.0

**Comment by xaboy** [comment]
需要执行一下lerna bootstrap命令
