### ISSUE TITLE
elementui 使用栅格布局设置总分数为24,row值占一半 没有占满整个空间

### ISSUE THREAD

**Issue by Nextdoor1u** [xaboy/form-create#714]
版本号 @form-create/element-ui": "^3.2.0",

` {
    type: 'el-row',
    native: true,
    children: [
      {
        type: 'el-col',
        props: {
          span: 24,
        },
        children: [
          {
            type: 'input',
            title: '员工状态1 :',
            field: 'staffStatus',
            value: '试用',
            props: {
              type: 'text',
              disabled: true,
            },
          },
          {
            type: 'input',
            title: '员工状态3 :',
            field: 'staffStatus',
            value: '试用',
            props: {
              type: 'text',
              disabled: true,
            },
          },
        ],
      },
      {
        type: 'el-col',
        props: {
          span: 24,
        },
        children: [
          {
            type: 'input',
            title: '员工状态2 :',
            field: 'staffStatus',
            value: '试用',
            props: {
              type: 'text',
              disabled: true,
            },
          },
        ],
      },
    ],
  },`

![image](https://github.com/xaboy/form-create/assets/103915289/d8426170-14e2-409e-a94b-7035dd4adc65)
这是代码运行后的效果
下面 111 是el-row正常布局的结果
添加后没有占满一行是什么原因呢

**Comment by xaboy** [comment]
感谢反馈,我这边测试一下

**Comment by xaboy** [comment]
在规则中增加`style: width: 100%;`即可解决
```
{ 
            type: 'el-row', 
            native: true,
            style: 'width: 100%;',
            //....
}

```

**Comment by Nextdoor1u** [comment]
> 在规则中增加`style: width: 100%;`即可解决
> 
> ```
> { 
>             type: 'el-row', 
>             native: true,
>             style: 'width: 100%;',
>             //....
> }
> ```

好的谢谢大佬
