### ISSUE TITLE
我在uni-app引入@form-create/vant@^3 报错如下

### ISSUE THREAD

**Issue by melon-is** [xaboy/form-create#726]
![Uploading 微信图片_20240907112723.png…]()

**Comment by melon-is** [comment]
[vite]: Rollup failed to resolve import "vant" from "D:/work/jz_miniprogram/node_modules/@form-create/vant/dist/form-create.esm.js".
11:24:57.743 This is most likely unintended because it can break your application at runtime.
11:24:57.749 If you do want to externalize this module explicitly add it to
11:24:57.757 `build.rollupOptions.external`

**Comment by xaboy** [comment]
不支持uniapp和小程序
