### ISSUE TITLE
setData无法更新组件渲染数据

### ISSUE THREAD

**Issue by MorganMaohong** [xaboy/form-create#727]
"@form-create/element-ui": "^3.2.8"

    "element-plus": "2.7.3"

 使用fapi.setData()设置外部数据源页面不生效；但是fapi.getData()可以看到设置数据成功了；使用了fapi.refreshData();组件依然没有渲染数据源

![image](https://github.com/user-attachments/assets/7f81e2da-c917-4773-bdae-caf8d897bcbc)

![image](https://github.com/user-attachments/assets/ef5370e9-db9c-412a-9ece-ec797a5ba097)

![image](https://github.com/user-attachments/assets/464e3a52-99d9-4b8a-b795-daf360aa56a2)

setData()后组件可以正确显示下拉数据

 暂无

**Comment by xaboy** [comment]
生成规则发一下

**Comment by MorganMaohong** [comment]
const option = ref(
  formCreate.parseJson(
    '{"form":{"inline":false,"hideRequiredAsterisk":false,"labelPosition":"right","size":"default","labelWidth":"100px","labelSuffix":":","showMessage":true,"inlineMessage":false},"resetBtn":{"show":false,"innerText":"重置"},"submitBtn":{"show":false,"innerText":"提交"},"formName":"role"}'
  )
)
const rule = ref(
  formCreate.parseJson(
    '[{"type":"fcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"input","field":"username","title":"用户名","info":"","$required":true,"props":{"type":"text","maxlength":10},"_fc_id":"id_Fackm1agwjytb2c","name":"ref_F26zm1agwjytb3c","display":true,"hidden":false,"_fc_drag_tag":"input","class":"","id":""}],"_fc_id":"id_F9eqm1agwih0axc","name":"ref_F4wqm1agwih0ayc","display":true,"hidden":false,"_fc_drag_tag":"col"},{"type":"col","props":{"span":12},"children":[{"type":"input","field":"name","title":"姓名","info":"","$required":true,"_fc_id":"id_F107m1ah11p5bjc","name":"ref_F26zm1agwjytb3c","display":true,"hidden":false,"_fc_drag_tag":"input","props":{"type":"text","clearable":false}}],"_fc_id":"id_Fyhhm1agwih0azc","name":"ref_F08om1agwih0b0c","display":true,"hidden":false,"_fc_drag_tag":"col"}],"_fc_id":"id_Ft0pm1agwih0avc","name":"ref_Ffojm1agwih0awc","display":true,"hidden":false,"_fc_drag_tag":"fcRow"},{"type":"fcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"input","field":"phone","title":"手机号","info":"","$required":true,"_fc_id":"id_Ftd5m1ah11p5blc","name":"ref_F2dam1ai0vywdxc","display":true,"hidden":false,"_fc_drag_tag":"input","props":{"type":"text","clearable":true,"maxlength":20},"validate":[{"transform":"[[FORM-CREATE-PREFIX-function anonymous(val\\n) {\\nthis.type = Array.isArray(val) ? \'array\' : (typeof val); return val;\\n}-FORM-CREATE-SUFFIX]]","mode":"pattern","trigger":"blur","pattern":"^(?:(?:\\\\+|00)86)?1[3-9]\\\\d{9}$","message":"请输入正确手机号"}]}],"_fc_id":"id_Fclym1ah11p5bkc","name":"ref_F4wqm1agwih0ayc","display":true,"hidden":false,"_fc_drag_tag":"col"},{"type":"col","props":{"span":12},"children":[{"type":"input","field":"email","title":"邮箱","info":"","$required":false,"props":{"type":"text"},"_fc_id":"id_Fg5mm1agwl4cb5c","name":"ref_Fq37m1agwl4cb6c","display":true,"hidden":false,"_fc_drag_tag":"input","validate":[{"transform":"[[FORM-CREATE-PREFIX-function anonymous(val\\n) {\\nthis.type = Array.isArray(val) ? \'array\' : (typeof val); return val;\\n}-FORM-CREATE-SUFFIX]]","mode":"pattern","trigger":"submit"}]}],"_fc_id":"id_F911m1ah11p5bmc","name":"ref_F08om1agwih0b0c","display":true,"hidden":false,"_fc_drag_tag":"col"}],"_fc_id":"id_Fnwam1ah11p5bnc","name":"ref_Ffojm1agwih0awc","display":true,"hidden":false,"_fc_drag_tag":"fcRow"},{"type":"fcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"select","field":"sex","title":"性别","info":"","$required":true,"props":{"placeholder":"请选择性别","_optionType":2,"multiple":false,"clearable":false},"_fc_id":"id_Fqhdm1ah8ccxdec","name":"ref_Fnsnm1ah8ccxdfc","display":true,"hidden":false,"_fc_drag_tag":"select","value":""},{"type":"elTreeSelect","field":"departmentUid","title":"部门","info":"","effect":{"fetch":""},"$required":true,"props":{"nodeKey":"value","showCheckbox":true,"data":[],"placeholder":"请选择部门"},"_fc_id":"id_Fxj1m1ah8l55dkc","name":"ref_Fq8cm1ah8l55dlc","display":true,"hidden":false,"_fc_drag_tag":"elTreeSelect"}],"_fc_id":"id_Fn78m1ah861gd9c","name":"ref_F6u7m1ah861gdac","display":true,"hidden":false,"_fc_drag_tag":"col"},{"type":"col","props":{"span":12},"children":[{"type":"select","field":"roleUid","title":"角色","info":"","effect":{"fetch":""},"$required":true,"props":{"placeholder":"请选择角色"},"_fc_id":"id_F1gzm1ah8evbdhc","name":"ref_Fliim1ah8evbdic","display":true,"hidden":false,"_fc_drag_tag":"select"}],"_fc_id":"id_Fhrym1ah861gdbc","name":"ref_Fs4am1ah861gdcc","display":true,"hidden":false,"_fc_drag_tag":"col"}],"_fc_id":"id_Fi5sm1ah861gd7c","name":"ref_F73cm1ah861gd8c","display":true,"hidden":false,"_fc_drag_tag":"fcRow"}]'
  )
)

**Comment by MorganMaohong** [comment]
`const option = ref(
  formCreate.parseJson(
    '{"form":{"inline":false,"hideRequiredAsterisk":false,"labelPosition":"right","size":"default","labelWidth":"100px","labelSuffix":":","showMessage":true,"inlineMessage":false},"resetBtn":{"show":false,"innerText":"重置"},"submitBtn":{"show":false,"innerText":"提交"},"formName":"role"}'
  )
)
const rule = ref(
  formCreate.parseJson(
    '[{"type":"fcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"input","field":"username","title":"用户名","info":"","$required":true,"props":{"type":"text","maxlength":10},"_fc_id":"id_Fackm1agwjytb2c","name":"ref_F26zm1agwjytb3c","display":true,"hidden":false,"_fc_drag_tag":"input","class":"","id":""}],"_fc_id":"id_F9eqm1agwih0axc","name":"ref_F4wqm1agwih0ayc","display":true,"hidden":false,"_fc_drag_tag":"col"},{"type":"col","props":{"span":12},"children":[{"type":"input","field":"name","title":"姓名","info":"","$required":true,"_fc_id":"id_F107m1ah11p5bjc","name":"ref_F26zm1agwjytb3c","display":true,"hidden":false,"_fc_drag_tag":"input","props":{"type":"text","clearable":false}}],"_fc_id":"id_Fyhhm1agwih0azc","name":"ref_F08om1agwih0b0c","display":true,"hidden":false,"_fc_drag_tag":"col"}],"_fc_id":"id_Ft0pm1agwih0avc","name":"ref_Ffojm1agwih0awc","display":true,"hidden":false,"_fc_drag_tag":"fcRow"},{"type":"fcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"input","field":"phone","title":"手机号","info":"","$required":true,"_fc_id":"id_Ftd5m1ah11p5blc","name":"ref_F2dam1ai0vywdxc","display":true,"hidden":false,"_fc_drag_tag":"input","props":{"type":"text","clearable":true,"maxlength":20},"validate":[{"transform":"[[FORM-CREATE-PREFIX-function anonymous(val\\n) {\\nthis.type = Array.isArray(val) ? \'array\' : (typeof val); return val;\\n}-FORM-CREATE-SUFFIX]]","mode":"pattern","trigger":"blur","pattern":"^(?:(?:\\\\+|00)86)?1[3-9]\\\\d{9}$","message":"请输入正确手机号"}]}],"_fc_id":"id_Fclym1ah11p5bkc","name":"ref_F4wqm1agwih0ayc","display":true,"hidden":false,"_fc_drag_tag":"col"},{"type":"col","props":{"span":12},"children":[{"type":"input","field":"email","title":"邮箱","info":"","$required":false,"props":{"type":"text"},"_fc_id":"id_Fg5mm1agwl4cb5c","name":"ref_Fq37m1agwl4cb6c","display":true,"hidden":false,"_fc_drag_tag":"input","validate":[{"transform":"[[FORM-CREATE-PREFIX-function anonymous(val\\n) {\\nthis.type = Array.isArray(val) ? \'array\' : (typeof val); return val;\\n}-FORM-CREATE-SUFFIX]]","mode":"pattern","trigger":"submit"}]}],"_fc_id":"id_F911m1ah11p5bmc","name":"ref_F08om1agwih0b0c","display":true,"hidden":false,"_fc_drag_tag":"col"}],"_fc_id":"id_Fnwam1ah11p5bnc","name":"ref_Ffojm1agwih0awc","display":true,"hidden":false,"_fc_drag_tag":"fcRow"},{"type":"fcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"select","field":"sex","title":"性别","info":"","$required":true,"props":{"placeholder":"请选择性别","_optionType":2,"multiple":false,"clearable":false},"_fc_id":"id_Fqhdm1ah8ccxdec","name":"ref_Fnsnm1ah8ccxdfc","display":true,"hidden":false,"_fc_drag_tag":"select","value":""},{"type":"elTreeSelect","field":"departmentUid","title":"部门","info":"","effect":{"fetch":""},"$required":true,"props":{"nodeKey":"value","showCheckbox":true,"data":[],"placeholder":"请选择部门"},"_fc_id":"id_Fxj1m1ah8l55dkc","name":"ref_Fq8cm1ah8l55dlc","display":true,"hidden":false,"_fc_drag_tag":"elTreeSelect"}],"_fc_id":"id_Fn78m1ah861gd9c","name":"ref_F6u7m1ah861gdac","display":true,"hidden":false,"_fc_drag_tag":"col"},{"type":"col","props":{"span":12},"children":[{"type":"select","field":"roleUid","title":"角色","info":"","effect":{"fetch":""},"$required":true,"props":{"placeholder":"请选择角色"},"_fc_id":"id_F1gzm1ah8evbdhc","name":"ref_Fliim1ah8evbdic","display":true,"hidden":false,"_fc_drag_tag":"select"}],"_fc_id":"id_Fhrym1ah861gdbc","name":"ref_Fs4am1ah861gdcc","display":true,"hidden":false,"_fc_drag_tag":"col"}],"_fc_id":"id_Fi5sm1ah861gd7c","name":"ref_F73cm1ah861gd8c","display":true,"hidden":false,"_fc_drag_tag":"fcRow"}]'
  )
)`

**Comment by xaboy** [comment]
需要通过loadData字段关联, 文档: https://form-create.com/v3/guide/attr-load-data
