### ISSUE TITLE
升级vue3.5版本之后导致必填校验异常

### ISSUE THREAD

**Issue by yellowSTA** [xaboy/form-create#729]
## 版本号 (version) 
     @form-create/element-ui@3.2.5
     vue@3.5.8

## UI 框架的版本 (UI version) 
    element-plus@2.7.4

## 问题描述 (Issue)
![image](https://github.com/user-attachments/assets/0a581b17-337f-45e5-a48e-50501d415f2f)
升级到vue版本3.5之后，导致表单必填验证出现异常，填写数据也验证不通过，降级版本到vue@3.4.31即可正常

## 期望的结果 (Desired outcome)
期望兼容vue3.5.x以后得版本

**Comment by xaboy** [comment]
感谢反馈,我检查一下

**Comment by xaboy** [comment]
3.2.10版本已修复
