### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by go4cas** [xaboy/form-create#73]
@xaboy, can you please add release notes to each NPM release? It's difficult to figure out which features or bug fixes are included in each release. Thanks!

**Comment by xaboy** [comment]
@go4cas Sorry, because there are too few users of English documents, they have not been updated.
I will update the English version of the version update log later.
If you are willing to help with maintenance, then it is better.

**Comment by xaboy** [comment]
@go4cas  Version update log has been updated [update log](http://form-create.com/en/guide/update.html)
