### ISSUE TITLE
表单校验不对

### ISSUE THREAD

**Issue by small-touch** [xaboy/form-create#730]
新增编辑表单，在新增时输入数据后，鼠标失焦仍提示该项必填

![image](https://github.com/user-attachments/assets/5bce8a7a-d1ab-4731-bdb7-72546e4b48a0)

**Comment by small-touch** [comment]
"vue": "^3.4.29"
"element-plus": "^2.8.3"
"@form-create/element-ui": "^3"

**Comment by xaboy** [comment]
FormCreate更新到最新版本应该就好了
