### ISSUE TITLE
使用loadData加载外部数据，setData、并且refershData后不能更新

### ISSUE THREAD

**Issue by AngusFwhaks** [xaboy/form-create#732]
版本号 (version) ：@form-create/element-ui@3.2.8
UI 框架的版本 (UI version) : "element-plus": "^2.7.5",

使用loadData加载外部数据，setData、并且refershData后不能更新

根据订单号生成不同的产品信息，更改订单后调用setData，之后refershData，产品列表并未更新
onBeforeMount(() => {
  formCreate.component("SelectTable", SelectTable);
  formCreate.setData("productList", [{ label: "请选择产品名称", value: "" }]);
});
const getProductListByQuery = (orderId: string) => {
  getOrderDetailList(orderId).then(res => {
    const list = res.records.map(item => {
      return {
        label: item.materialTitle,
        value: item.id
      };
    });
    fApi.value.setData("productList", list);
    fApi.value.refreshData("productList");
    // fApi.value.getRule("productOutboundDetailList").props.rule[0].options =
    //   list;
    console.log(fApi.value.getData("productList"));
  });
};
const rule = ref<Rule[]>([
  {
    type: "hidden",
    field: "id",
    title: "ID",
    control: [
      {
        handle: (value: string) => !value,
        method: "disabled",
        rule: ["code"]
      },
      {
        handle: (value: string) => !value,
        rule: ["productOutboundDetailList", "orderId"]
      }
    ]
  },
  {
    type: "input",
    field: "code",
    title: "出库单号",
    props: {
      placeholder: "请输入出库单号",
      showWordLimit: true,
      maxlength: 90
    },
    validate: [
      {
        required: true,
        message: "请输入出库单号",
        trigger: "blur"
      },
      {
        min: 3,
        max: 90,
        message: "请输入3-90位字符",
        trigger: "blur"
      }
    ]
  },
  {
    type: "SelectTable",
    field: "orderId",
    title: "订单号",
    props: {
      placeholder: "请选择订单",
      search: search,
      columns: columns,
      url: "/v1/business/order/list",
      showFields: ["code"],
      onChange: (value: string) => {
        getProductListByQuery(value);
      }
    },
    validate: [
      {
        required: true,
        message: "请选择订单",
        trigger: "blur"
      }
    ]
  },
  {
    type: "DatePicker",
    field: "outboundDate",
    title: "出库日期",
    props: {
      type: "date",
      format: "YYYY-MM-DD",
      placeholder: "请选择出库日期",
      teleported: false
    },
    validate: [
      {
        required: true,
        message: "请选择出库日期",
        trigger: "blur"
      }
    ],
    style: {
      width: "100%"
    }
  },
  {
    type: "group",
    field: "productOutboundDetailList",
    title: "出库单明细",
    props: {
      rule: [
        {
          type: "select",
          field: "materialId",
          title: "产品名称",
          props: {
            placeholder: "请选择产品名称",
            filterable: true,
            clearable: true,
            teleported: false
          },
          validate: [
            {
              required: true,
              message: "请选择产品名称",
              trigger: "blur"
            }
          ],
          effect: {
            loadData: {
              // 数据名
              attr: "productList",
              // 插入位置
              to: "options"
            }
          },
          options: []
        },
        {
          type: "InputNumber",
          field: "quantity",
          title: "出库数量",
          inject: true,
          props: {
            min: 0,
            precision: 2,
            placeholder: "请输入出库数量"
          },
          validate: [
            {
              required: true,
              message: "请输入出库数量",
              trigger: "blur"
            }
          ],
          style: {
            width: "100%"
          }
        }
      ]
    },
    validate: [
      {
        required: true,
        message: "请选择出库单明细",
        trigger: "blur"
      }
    ],
    value: [
      {
        materialId: "",
        quantity: undefined
      }
    ]
  }
]);
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/8c91e195-f56f-4396-a55f-fa4ab086e4b9">
<img width="1797" alt="image" src="https://github.com/user-attachments/assets/46d5315e-8f30-4bed-8f65-51569a3f476b">

**Comment by xaboy** [comment]
更新到3.2.10版本试试
