### ISSUE TITLE
联动问题咨询

### ISSUE THREAD

**Issue by AsserHong** [xaboy/form-create#733]
由于我使用的历史系统中的动态表单设计不合理，需要将原本的动态表单底层框架切换为form-create

为了保持迁移成本最小，针对历史系统中动态表单的schema，我已经自行实现了一个adpater来转换成form-create的合法schema,
但是表单联动部分由于成本过高，无法像form-create文档中推荐的方式，使用control字段来进行联动控制。
目前我采取的办法是自行hack，然后通过form-create的rule相关API 修改表单rule，从而实现联动效果（如显示隐藏，修改字段值等）

1. 想请问下使用rule的相关API来曲线救国实现联动，跟control的联动实现会不会什么差别？（暂时不考虑性能方面影响）
2. 通过updateRule修改某个字段rule之后，比如将字段A的hidden属性设置为true, 但是在提交表单的过程中仍发现formData中存在A的值，想了解下为什么会这样？是不是因为我使用的方式不对，所以应该手动修改formData?

最后感谢作者辛苦付出贡献的框架，谢谢！

**Comment by xaboy** [comment]
1. 没有差异,内部也是通过`api`操作的
2. vue3最新版本已经支持不提交通过`hidden`隐藏的字段, 使用`options.ignoreHiddenFields = true`可以实现

@AsserHong

**Comment by AsserHong** [comment]
> 1. 没有差异,内部也是通过`api`操作的
> 2. vue3最新版本已经支持不提交通过`hidden`隐藏的字段, 使用`options.ignoreHiddenFields = true`可以实现
> 
> @AsserHong

感谢耐心解答！谢谢
