### ISSUE TITLE
resetFields方法不生效

### ISSUE THREAD

**Issue by lu-yanpeng** [xaboy/form-create#734]
## 版本

@form-create/element-ui@3.2.12
vue@3.5.12
element-plus@2.8.6

## 问题

```vue
<script setup lang="ts">
import { ref } from 'vue'

const fApi = ref(null);
// ...其他代码

const onReset = () => {
  // 不生效也不报错
  fApi.value.resetFields()
}
</script>

<template>
  <div>
    <form-create :rule="rule" v-model:api="fApi" :option="options"/>
    <el-button @click="onReset ">重置</el-button>
  </div>
</template>
``` 

在**vue3.5.12**的项目里，调用fApi的`resetFields`方法不生效也不报错，debugger的时候也不会进入到函数里面。试了一下api的几个方法都不行，好像关于formApi的所有方法都不会生效。回退到vue 3.4.38版本就正常

**Comment by xaboy** [comment]
感谢反馈,我这边检查一下

**Comment by kele59** [comment]
我也遇到这个问题了

**Comment by xaboy** [comment]
怎么复现, 我这边使用同样的版本没有复现出来,是不是rule没有包裹在ref中 @zaxlct

**Comment by kele59** [comment]
@xaboy 我也复现不出来了。。可能是像你说的rule没有包裹在ref。。
