### ISSUE TITLE
支持 field 是个数组的情况吗？

### ISSUE THREAD

**Issue by yuantongkang** [xaboy/form-create#75]
在一般的情况下，表单有个数组是很常见的

**Comment by xaboy** [comment]
目前不支持,如果有这个需要可以通过自定义组件实现

**Comment by yuantongkang** [comment]
希望作者能写个示例，不了解自定义组件去访问field

**Comment by xaboy** [comment]
[示例](https://jsrun.net/user/xaboy),这里有一些示例你可以参考一下
