### ISSUE TITLE
有没有打算支持注册已经存在的组件

### ISSUE THREAD

**Issue by byte9527** [xaboy/form-create#76]
如果在项目中存在已写好的自定义表单控件，能不能支持注册后使用。如果使用maker.template，需要重新去定义一次。

**Comment by xaboy** [comment]
把自己写好的组件挂载到 Vue上就可以通过自定义组件方式生成

**Comment by byte9527** [comment]
@xaboy    使用Vue.use 插件的方式？

**Comment by xaboy** [comment]
@byte9527 `Vue.use`和`Vue.component`都可以,只要保证挂载在 vue 全局就可以.
下个版本会支持局部挂载 form-create 和给 form-create 挂载自定义组件

**Comment by byte9527** [comment]
@byte9527 有没有demo看下，试了下没有成功，还没找出问题

**Comment by byte9527** [comment]
数据的问题怎么解决呢，对于这类自定义组件有没有什么要求呢

**Comment by jy1989** [comment]
> 把自己写好的组件挂载到 Vue上就可以通过自定义组件方式生成

请问有具体例子么？ 已经写好的component如何应用到表单中

**Comment by byte9527** [comment]
参考[(http://form-create.com/guide/custom-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E4%BA%8B%E4%BB%B6)]

**Comment by jy1989** [comment]
@byte9527  
你好  这个文档我已经看过了  
create和template方法好像也是直接定义出一个组件？不知道有没有理解错
我的情况是比如我有一个staffselect的组件，能放在表单中么？
![image](https://user-images.githubusercontent.com/1291756/59321198-b6096c80-8d03-11e9-918f-75f15bdca69e.png)

**Comment by byte9527** [comment]
可以，如果要做到统一的取值、校验会很麻烦。
1、先用vue.component()方法注册成全局组件，配置的时候type就是注册的组件名称。
2、这个组件需要有在值改变的时候emit出input事件，还需要有value属性。
3、如果要自动赋值、置空，则配置json的时候，加入‘fc-setValue’，‘fc-reset-field’，‘fc-input’的监听，使用maker的需要在maker的实例里面加入这些监听，参照作者给的链接 http://form-create.com/guide/custom-component.html#maker-template
4、还需要对form也就是element实例化的form，修改其model值（不要直接修改，修改model下的属性值，不然会报警告），才能通过校验。

**Comment by jy1989** [comment]
> 可以，如果要做到统一的取值、校验会很麻烦。
> 1、先用vue.component()方法注册成全局组件，配置的时候type就是注册的组件名称。
> 2、这个组件需要有在值改变的时候emit出input事件，还需要有value属性。
> 3、如果要自动赋值、置空，则配置json的时候，加入‘fc-setValue’，‘fc-reset-field’，‘fc-input’的监听，使用maker的需要在maker的实例里面加入这些监听，参照作者给的链接 http://form-create.com/guide/custom-component.html#maker-template
> 4、还需要对form也就是element实例化的form，修改其model值（不要直接修改，修改model下的属性值，不然会报警告），才能通过校验。
> 
> 代码在公司虚拟机上，不好直接贴出来

好的感谢，我先研究一下

**Comment by xaboy** [comment]
2.0版本就没有这么麻烦了,定义个`value`和`input`事件就能达到和内置组件一样的效果
