### ISSUE TITLE
使用日期组件时报错

### ISSUE THREAD

**Issue by xie147** [xaboy/form-create#77]
vue.esm.js?efeb:628 [Vue warn]: Error in nextTick: "TypeError: this.el.formatToString is not a function"

**Comment by xaboy** [comment]
@xie147 是不是这个组件首次渲染的时候没有显示?

**Comment by xie147** [comment]
有显示的，路由加载时就渲染了

**Comment by xaboy** [comment]
那是不是 ui 框架的版本太低了

**Comment by xie147** [comment]
好了，确实是版本问题，多谢
