### ISSUE TITLE
remoteMethod 回显问题

### ISSUE THREAD

**Issue by yuanweisuannai** [xaboy/form-create#78]
从服务端获取数据，如何显示

**Comment by xaboy** [comment]
用法可以参考 ui 框架的文档

**Comment by yuanweisuannai** [comment]
![QQ图片20190506141945](https://user-images.githubusercontent.com/18393171/57209175-fe998000-7009-11e9-9400-db3ff2b7e405.png)
这样写问题在哪

**Comment by xaboy** [comment]
`this.options`不对吧

**Comment by yuanweisuannai** [comment]
所以我不太明白要如何写，能否给个正确的写法，多谢了

**Comment by xaboy** [comment]
可以参考 #51 ,[文档](http://form-create.com/guide/question.html).只要正确获取都当前的规则就可以
类如
`vm.rule[1].option = json`
`$f.model()[field].option = json`
`$f.rule[1].option = json`

**Comment by yuanweisuannai** [comment]
问题解决了，多谢

**Comment by lsm2208911** [comment]
> 可以参考 #51 ,[文档](http://form-create.com/guide/question.html).只要正确获取都当前的规则就可以 类如 `vm.rule[1].option = json` `$f.model()[field].option = json` `$f.rule[1].option = json`

@xaboy  当我s使用`vm`和`$f`时，都出现了 `not defined` 的错误。
