### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by guojs** [xaboy/form-create#80]
element-ui 中使用form-create时报错

![image](https://user-images.githubusercontent.com/13706435/57446168-acb15e00-7286-11e9-9e35-c6288bf27cad.png)
![image](https://user-images.githubusercontent.com/13706435/57446220-cc488680-7286-11e9-85a4-dd77aa5e2a66.png)
![image](https://user-images.githubusercontent.com/13706435/57446233-d5395800-7286-11e9-87b7-75911328c5ab.png)

**Comment by xaboy** [comment]
这样挂载`form-create`
```js
{
    'form-create':formCreate.component('form-create')
}
```
