### ISSUE TITLE
from里面能不能嵌套form

### ISSUE THREAD

**Issue by byte9527** [xaboy/form-create#81]

**Comment by xaboy** [comment]
可以嵌套

**Comment by byte9527** [comment]
> 可以嵌套
刚才试了下，可以嵌套，只是rule和option需要包在props下面。        级联或者选择组件的option，能不能支持传入数组数据，且能支持映射数据中的key和option的关系。

**Comment by xaboy** [comment]
传入数组数据，且能支持映射数据中的key和option的关系,怎么映射?

**Comment by byte9527** [comment]
`{
            type: "radio",
            title: "加密级别",
            field: "is_postage",
            options: [
              { value: "1001", label: "普通", disabled: false },
              { value: "1002", label: "加密", disabled: false },
              { value: "1003", label: "绝密", disabled: false },
            ]
          }`
这是目前的option的方式，前提是要在option的数据准备好之后，再去生成form，
如果option的数据是来自于请求得到的如下数据，
`[
      { code: "1001", category: "普通" },
      { code: "1002", category: "加密" },
      { code: "1003", category: "绝密" },
    ]`
我是希望fromcreate的options里面增加一项source用来能够将此数据传入，同时rule里面添加optionMap的字段，如下面方式表达，
`{
      type: "radio",
      title: "加密级别",
      field: "encrypt",
      // options: [
      //   { value: "1001", label: "普通", disabled: false },
      //   { value: "1002", label: "加密", disabled: false },
      //   { value: "1003", label: "绝密", disabled: false }
      // ]
      opitonMap: {
        srcKey: "encryptLevel",
        lableKey: "category",
        valueKey: "code"
      }
    }`

**Comment by xaboy** [comment]
你可以先生成表单,然后异步获取 options,获取到后直接修改 radio规则的 options 就可以
