### ISSUE TITLE
可以删除默认显示的图片？

### ISSUE THREAD

**Issue by lisheng22222** [xaboy/form-create#83]

**Comment by xaboy** [comment]
默认显示的图片指的是?

**Comment by lisheng22222** [comment]
您好：
   我保存图片之后，打开页面是有图片了吧，然后我我去点击图片，怎么触发服务端去删除图片，参数是怎么带过来传个服务端去删除？
  还有一种情况我上传图片立即去删除可以，因为服务端返回了reponse 有参数我就可以删除了
                                                                                                                                               谢谢

**Comment by xaboy** [comment]
目前应该只能通过图片的地址去删除,这块我看能不能再优化一下. 感谢您的反馈
