### ISSUE TITLE
vue-cli 项目中使用自定义组件报错

### ISSUE THREAD

**Issue by guojs** [xaboy/form-create#85]
{
    type:'template',
    template:'<i-button :loading="loading">{{text}}</i-button>',
    vm:new Vue({
      data:{
        loading:true,
        text:'正在加载中'
      }
    })
  }
在vue-cli 构建的项目中通过JSON创建自定义组件报错，提示Vue未定义，如何处理

**Comment by xaboy** [comment]
应该是没有在当前文件里面导入 Vue 吧

**Comment by guojs** [comment]
引入进来没问题了，谢谢。现在有另一个问题：  
{
        type: 'template',
        title:'活动描述',
        field:'richdata2',
        template: '<div><el-input type="text" v-model="richData"></el-input></div>',
        vm: new Vue({
          data: {
            richData:'测试数据'
          }
        })
      }
我这样定义了个组件，最后onSubmit方法提交数据 时fromData里面没有这个组件的数据？

**Comment by xaboy** [comment]
这个可以参考文档 : [http://form-create.com/guide/custom-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E4%BA%8B%E4%BB%B6](http://form-create.com/guide/custom-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E4%BA%8B%E4%BB%B6)

**Comment by guojs** [comment]
![image](https://user-images.githubusercontent.com/13706435/58454971-a8c07f80-8152-11e9-9467-cdee0e9356ff.png)

**Comment by guojs** [comment]
控制自定义组件隐藏显示时报错：
      [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'props' of undefined"

found in

---> <ElRadioGroup> at packages/radio/src/radio-group.vue
       <ElFormItem> at packages/form/src/form-item.vue
         <ElCol>
           <ElRow>
             <ElForm> at packages/form/src/form.vue
               <FormCreate>
                 <HelloWorld> at src/components/HelloWorld.vue
                   <App> at src/App.vue
                     <Root>
warn @ vue.esm.js?eaf6:628
logError @ vue.esm.js?eaf6:1893
globalHandleError @ vue.esm.js?eaf6:1888
handleError @ vue.esm.js?eaf6:1848
invokeWithErrorHandling @ vue.esm.js?eaf6:1871
invoker @ vue.esm.js?eaf6:2188
invokeWithErrorHandling @ vue.esm.js?eaf6:1863
Vue.$emit @ vue.esm.js?eaf6:3891
(anonymous) @ element-ui.common.js?bea0:5729
invokeWithErrorHandling @ vue.esm.js?eaf6:1863
Vue.$emit @ vue.esm.js?eaf6:3891
dispatch @ emitter.js?49b0:29
(anonymous) @ element-ui.common.js?bea0:5615
(anonymous) @ vue.esm.js?eaf6:1989
flushCallbacks @ vue.esm.js?eaf6:1915
Promise.then (async)
timerFunc @ vue.esm.js?eaf6:1942
nextTick @ vue.esm.js?eaf6:1999
queueWatcher @ vue.esm.js?eaf6:4405
update @ vue.esm.js?eaf6:4547
notify @ vue.esm.js?eaf6:739
reactiveSetter @ vue.esm.js?eaf6:1064
set @ vue.esm.js?eaf6:1086
_changeFormData @ form-create.elm.js?4cbb:1706
onInput @ form-create.elm.js?4cbb:2373
(anonymous) @ form-create.elm.js?4cbb:2352
invokeWithErrorHandling @ vue.esm.js?eaf6:1863
invoker @ vue.esm.js?eaf6:2188
invokeWithErrorHandling @ vue.esm.js?eaf6:1863
Vue.$emit @ vue.esm.js?eaf6:3891
dispatch @ emitter.js?49b0:29
set @ element-ui.common.js?bea0:5588
_c.on.change @ element-ui.common.js?bea0:5456
invokeWithErrorHandling @ vue.esm.js?eaf6:1863
invoker @ vue.esm.js?eaf6:2184
original._wrapper @ vue.esm.js?eaf6:7559
vue.esm.js?eaf6:1897 TypeError: Cannot read property 'props' of undefined
    at eval (form-create.elm.js?4cbb:5419)
    at Array.forEach (<anonymous>)
    at Object.hidden (form-create.elm.js?4cbb:5416)
    at radioRule.event.change (HelloWorld.vue?140d:1662)
    at invokeWithErrorHandling (vue.esm.js?eaf6:1863)
    at VueComponent.invoker (vue.esm.js?eaf6:2188)
    at invokeWithErrorHandling (vue.esm.js?eaf6:1863)
    at VueComponent.Vue.$emit (vue.esm.js?eaf6:3891)
    at VueComponent.eval (element-ui.common.js?bea0:5729)
    at invokeWithErrorHandling (vue.esm.js?eaf6:1863)

**Comment by guojs** [comment]
控制自定义组件隐藏时报错了：
   
![image](https://user-images.githubusercontent.com/13706435/58455847-45841c80-8155-11e9-80d3-8cc93262d9e4.png)

**Comment by xaboy** [comment]
是不是没有定义 props,能否发一下生成规则

**Comment by guojs** [comment]
![微信截图_20190528153003](https://user-images.githubusercontent.com/13706435/58459599-571df200-815e-11e9-8708-67d7eb485735.png)

**Comment by xaboy** [comment]
props是个对象,不需要的配置项可以不传,但是不要定义为 null

**Comment by guojs** [comment]
我的表单是这样的，radio切换选择的时候有不同的表单项，要控制表单项的显示与隐藏，其中有一个是自定义的组件，就报错了。 props不传也会报错
![微信截图_20190528154323](https://user-images.githubusercontent.com/13706435/58460047-5a65ad80-815f-11e9-8eee-910401ee2376.png)

**Comment by xaboy** [comment]
传个空对象试试,看看报的什么错误

**Comment by guojs** [comment]
还是这个错误
![微信截图_20190528141946](https://user-images.githubusercontent.com/13706435/58460669-b2e97a80-8160-11e9-928d-3689f91cfd63.png)

**Comment by xaboy** [comment]
错误消息提示的是 radio 组件

**Comment by guojs** [comment]
我是在radio的change事件里面去做的显隐控制，报错肯定是在radio 里面。
代码是这样的：
  radioRule.event.change = (v) => {
          let fields = radioRule.clist[radioRule.value];   //当前选中项要显示的所有组件的field
          _this.fApi.hidden(radioRule.allfields, true);    // 隐藏所有的field
          if (fields) {
            _this.fApi.hidden(fields, false);
          }
   }
当没有自定义组件的时候是没问题的

**Comment by xaboy** [comment]
发一下你 radio 组件的规则

**Comment by guojs** [comment]
let rl3 = [
      {
        "type": "radio",
        "title": "分类",
        "field": "is_postage",
        "value": "0",
        "actionurl": null,
        "props": null,
        "validate": null,
        "options": [
          {
            "value": "0",
            "label": "图文版",
            "disabled": false,
            "extend": null
          },
          {
            "value": "1",
            "label": "大图版",
            "disabled": false,
            "extend": [
              {
                "type": "input",
                "title": "大图跳转地址",
                "field": "briefab_name",
                "value": null,
                "actionurl": null,
                "props": {
                  "data": null,
                  "renderFormat": null,
                  "disabled": false,
                  "clearable": false,
                  "placeholder": "请输入大图跳转地址，最多20字",
                  "trigger": null,
                  "changeOnSelect": false,
                  "size": "32",
                  "loadData": null,
                  "filterable": false,
                  "notFoundText": null,
                  "transfer": false,
                  "required": false,
                  "type": "text",
                  "readonly": false,
                  "rows": "4",
                  "autosize": false,
                  "number": false,
                  "autofocus": false,
                  "autocomplete": "off",
                  "spellcheck": false,
                  "vertical": false,
                  "trueValue": null,
                  "falseValue": null,
                  "multiple": false,
                  "not_found_text": null,
                  "placement": null,
                  "format": null,
                  "confirm": null,
                  "editable": false,
                  "steps": null,
                  "max": null,
                  "min": null,
                  "step": null,
                  "precision": null,
                  "alpha": false,
                  "hue": null,
                  "recommend": false,
                  "count": null,
                  "allowHalf": false,
                  "showText": false,
                  "range": false,
                  "showInput": false,
                  "showStops": false,
                  "showTip": null,
                  "tipFormat": null,
                  "inputSize": null,
                  "uploadType": null,
                  "action": null,
                  "headers": null,
                  "name": null,
                  "withCredentials": false,
                  "accept": null,
                  "maxSize": null,
                  "maxLength": null,
                  "beforeUpload": null,
                  "onProgress": null,
                  "onSuccess": null,
                  "onError": null,
                  "onPreview": null,
                  "onRemove": null,
                  "onFormatError": null,
                  "onExceededSize": null,
                  "handleIcon": null,
                  "allowRemove": false,
                  "src": null,
                  "icon": null,
                  "height": null,
                  "width": null,
                  "spin": false,
                  "title": null,
                  "onHandle": null
                },
                "validate": [
                  {
                    "required": true,
                    "message": "请输入跳转地址",
                    "trigger": "blur",
                    "type": null,
                    "min": null
                  }
                ],
                "options": null,
                "slot": null,
                "col": null,
                "template": null,
                "vm": null
              }
            ]
          },
          {
            "value": "2",
            "label": "音频版",
            "disabled": false,
            "extend": null
          },
          {
            "value": "3",
            "label": "视频版",
            "disabled": false,
            "extend": [
              {
                "type": "input",
                "title": "视频名称",
                "field": "spname",
                "value": null,
                "actionurl": null,
                "props": {
                  "data": null,
                  "renderFormat": null,
                  "disabled": false,
                  "clearable": false,
                  "placeholder": "请输入视频名称，最多20字",
                  "trigger": null,
                  "changeOnSelect": false,
                  "size": "32",
                  "loadData": null,
                  "filterable": false,
                  "notFoundText": null,
                  "transfer": false,
                  "required": false,
                  "type": "text",
                  "readonly": false,
                  "rows": "4",
                  "autosize": false,
                  "number": false,
                  "autofocus": false,
                  "autocomplete": "off",
                  "spellcheck": false,
                  "vertical": false,
                  "trueValue": null,
                  "falseValue": null,
                  "multiple": false,
                  "not_found_text": null,
                  "placement": null,
                  "format": null,
                  "confirm": null,
                  "editable": false,
                  "steps": null,
                  "max": null,
                  "min": null,
                  "step": null,
                  "precision": null,
                  "alpha": false,
                  "hue": null,
                  "recommend": false,
                  "count": null,
                  "allowHalf": false,
                  "showText": false,
                  "range": false,
                  "showInput": false,
                  "showStops": false,
                  "showTip": null,
                  "tipFormat": null,
                  "inputSize": null,
                  "uploadType": null,
                  "action": null,
                  "headers": null,
                  "name": null,
                  "withCredentials": false,
                  "accept": null,
                  "maxSize": null,
                  "maxLength": null,
                  "beforeUpload": null,
                  "onProgress": null,
                  "onSuccess": null,
                  "onError": null,
                  "onPreview": null,
                  "onRemove": null,
                  "onFormatError": null,
                  "onExceededSize": null,
                  "handleIcon": null,
                  "allowRemove": false,
                  "src": null,
                  "icon": null,
                  "height": null,
                  "width": null,
                  "spin": false,
                  "title": null,
                  "onHandle": null
                },
                "validate": [
                  {
                    "required": true,
                    "message": "请输入是视频",
                    "trigger": "blur",
                    "type": null,
                    "min": null
                  }
                ],
                "options": null,
                "slot": null,
                "col": null,
                "template": null,
                "vm": null
              },
              {
                "type": "Upload",
                "title": "视频缩略图",
                "field": "pic2",
                "value": "",
                "actionurl": null,
                "props": {
                  "data": {},
                  "renderFormat": null,
                  "disabled": false,
                  "clearable": false,
                  "placeholder": null,
                  "trigger": null,
                  "changeOnSelect": false,
                  "size": null,
                  "loadData": null,
                  "filterable": false,
                  "notFoundText": null,
                  "transfer": false,
                  "required": false,
                  "type": "select",
                  "readonly": false,
                  "rows": null,
                  "autosize": false,
                  "number": false,
                  "autofocus": false,
                  "autocomplete": null,
                  "spellcheck": false,
                  "vertical": false,
                  "trueValue": null,
                  "falseValue": null,
                  "multiple": false,
                  "not_found_text": null,
                  "placement": null,
                  "format": "[]",
                  "confirm": null,
                  "editable": false,
                  "steps": null,
                  "max": null,
                  "min": null,
                  "step": null,
                  "precision": null,
                  "alpha": false,
                  "hue": null,
                  "recommend": false,
                  "count": null,
                  "allowHalf": false,
                  "showText": false,
                  "range": false,
                  "showInput": false,
                  "showStops": false,
                  "showTip": null,
                  "tipFormat": null,
                  "inputSize": null,
                  "uploadType": "image",
                  "action": "",
                  "headers": {},
                  "name": "",
                  "withCredentials": false,
                  "accept": "",
                  "maxSize": "5M",
                  "maxLength": "1",
                  "beforeUpload": () => { },
                  "onProgress": () => { },
                  "onSuccess": null,
                  "onError": (error, file, fileList) => { },
                  "onPreview": () => { },
                  "onRemove": () => { },
                  "onFormatError": () => { },
                  "onExceededSize": () => { },
                  "handleIcon": "ios-eye-outline",
                  "allowRemove": true,
                  "src": null,
                  "icon": null,
                  "height": null,
                  "width": null,
                  "spin": false,
                  "title": null,
                  "onHandle": null
                },
                "validate": [
                  {
                    "required": true,
                    "message": "请上传1张图片",
                    "trigger": "change",
                    "type": "array",
                    "min": "1"
                  }
                ],
                "options": null,
                "slot": null,
                "col": {
                  "span": 8,
                  "labelwidth": 0,
                  "xs": 24
                },
                "template": null,
                "vm": null
              },
              {
                "type": "Upload",
                "title": "上传视频",
                "field": "pic3",
                "value": "",
                "actionurl": null,
                "props": {
                  "data": {},
                  "renderFormat": null,
                  "disabled": false,
                  "clearable": false,
                  "placeholder": null,
                  "trigger": null,
                  "changeOnSelect": false,
                  "size": null,
                  "loadData": null,
                  "filterable": false,
                  "notFoundText": null,
                  "transfer": false,
                  "required": false,
                  "type": "select",
                  "readonly": false,
                  "rows": null,
                  "autosize": false,
                  "number": false,
                  "autofocus": false,
                  "autocomplete": null,
                  "spellcheck": false,
                  "vertical": false,
                  "trueValue": null,
                  "falseValue": null,
                  "multiple": false,
                  "not_found_text": null,
                  "placement": null,
                  "format": "[]",
                  "confirm": null,
                  "editable": false,
                  "steps": null,
                  "max": null,
                  "min": null,
                  "step": null,
                  "precision": null,
                  "alpha": false,
                  "hue": null,
                  "recommend": false,
                  "count": null,
                  "allowHalf": false,
                  "showText": false,
                  "range": false,
                  "showInput": false,
                  "showStops": false,
                  "showTip": null,
                  "tipFormat": null,
                  "inputSize": null,
                  "uploadType": "image",
                  "action": "",
                  "headers": {},
                  "name": "",
                  "withCredentials": false,
                  "accept": "",
                  "maxSize": "5M",
                  "maxLength": "1",
                  "beforeUpload": () => { },
                  "onProgress": () => { },
                  "onSuccess": null,
                  "onError": (error, file, fileList) => { },
                  "onPreview": () => { },
                  "onRemove": () => { },
                  "onFormatError": () => { },
                  "onExceededSize": () => { },
                  "handleIcon": "ios-eye-outline",
                  "allowRemove": true,
                  "src": null,
                  "icon": null,
                  "height": null,
                  "width": null,
                  "spin": false,
                  "title": null,
                  "onHandle": null
                },
                "validate": [
                  {
                    "required": true,
                    "message": "请上传1张图片",
                    "trigger": "change",
                    "type": "array",
                    "min": "1"
                  }
                ],
                "options": null,
                "slot": null,
                "col": {
                  "span": 8,
                  "labelwidth": 0,
                  "xs": 24
                },
                "template": null,
                "vm": null
              }

            ]
          },
          {
            "value": "4",
            "label": "直播或回放",
            "disabled": false,
            "extend": null
          },
          {
            "value": "5",
            "label": "列表跳转",
            "disabled": false,
            "extend": [
              {
                "type": "input",
                "title": "跳转地址",
                "field": "briefa_name",
                "value": null,
                "actionurl": null,
                "props": {
                  "data": null,
                  "renderFormat": null,
                  "disabled": false,
                  "clearable": false,
                  "placeholder": "请输入跳转地址，最多20字",
                  "trigger": null,
                  "changeOnSelect": false,
                  "size": "32",
                  "loadData": null,
                  "filterable": false,
                  "notFoundText": null,
                  "transfer": false,
                  "required": false,
                  "type": "text",
                  "readonly": false,
                  "rows": "4",
                  "autosize": false,
                  "number": false,
                  "autofocus": false,
                  "autocomplete": "off",
                  "spellcheck": false,
                  "vertical": false,
                  "trueValue": null,
                  "falseValue": null,
                  "multiple": false,
                  "not_found_text": null,
                  "placement": null,
                  "format": null,
                  "confirm": null,
                  "editable": false,
                  "steps": null,
                  "max": null,
                  "min": null,
                  "step": null,
                  "precision": null,
                  "alpha": false,
                  "hue": null,
                  "recommend": false,
                  "count": null,
                  "allowHalf": false,
                  "showText": false,
                  "range": false,
                  "showInput": false,
                  "showStops": false,
                  "showTip": null,
                  "tipFormat": null,
                  "inputSize": null,
                  "uploadType": null,
                  "action": null,
                  "headers": null,
                  "name": null,
                  "withCredentials": false,
                  "accept": null,
                  "maxSize": null,
                  "maxLength": null,
                  "beforeUpload": null,
                  "onProgress": null,
                  "onSuccess": null,
                  "onError": null,
                  "onPreview": null,
                  "onRemove": null,
                  "onFormatError": null,
                  "onExceededSize": null,
                  "handleIcon": null,
                  "allowRemove": false,
                  "src": null,
                  "icon": null,
                  "height": null,
                  "width": null,
                  "spin": false,
                  "title": null,
                  "onHandle": null
                },
                "validate": [
                  {
                    "required": true,
                    "message": "请输入跳转地址",
                    "trigger": "blur",
                    "type": null,
                    "min": null
                  }
                ],
                "options": null,
                "slot": null,
                "col": null,
                "template": null,
                "vm": null
              },
              {
                type: 'template',
                title: '视频传送',
                field: 'test111',
                "props":{},
                template: '<input  type="text" ></input>'
              },
              {
                "type": "template",
                "title": "上传视频",
                "field": "richdata2",
                 "props":{},
                "value": null,
                "actionurl": null,
                "validate": null,
                "options": null,
                "slot": null,
                "col": {
                  "span": 24,
                  "labelwidth": 0,
                  "xs": 24
                },
                "template": "<quill-editor v-model='richdata2'></quill-editor>",
                "vm": new Vue({                
                 data() {
                     return {
                          richdata2: '测试数据'
                        }
                   },
                  methods: {
                    onInput: function(cb, $f) {
                      cb(this.richdata2);
                    }               
                  },
                  created: function(cb) {
                    this.$on('fc:input', this.onInput);
                  }
                })
              }
            ]
          }
        ],
        "slot": null,
        "col": null,
        "template": null,
        "vm": null
      }
    ];

//对以上从后台拿到的规则进行处理
    rl3.forEach(item => {
      if (item.type == 'radio') {
        let clist = {};
        let childrens = [];
        let allfields = [];
        item.options.forEach(a => {
          if (a.extend) {
            clist[a.value] = [];
            a.extend.forEach(b => {
              clist[a.value].push(b.field);
              allfields.push(b.field);
              b.props = b.props || {};
              b.props.hidden = false;
              if (item.value != a.value) {
                b.props.hidden = true;
              }
              childrens.push(maker.parse(b));
            })
            delete a.extend;
          }

        })
        item.clist = clist;
        item.allfields = allfields;
        var radioRule = maker.parse(item);
        radioRule.event.change = (v) => {
          let fields = radioRule.clist[radioRule.value];
          _this.fApi.hidden(radioRule.allfields, true);
          if (fields) {
            _this.fApi.hidden(fields, false);
          }
        }
        trules.push(radioRule);
        trules = trules.concat(childrens);

      }
      else {
        trules.push(maker.parse(item));
      }
    })

**Comment by xaboy** [comment]
props 不能为空,你第一个规则的 props 就是空的

**Comment by guojs** [comment]
这个和props 是否为空关系不大，设置了值还是报错了；加了自定义组件就报错了
[
      {
        "type": "radio",
        "title": "分类",
        "field": "is_postage",
        "value": "0",
        "actionurl": null,
        "props": {},
        "validate": null,
        "options": [
          {
            "value": "2",
            "label": "音频版",
            "disabled": false,
            "extend": null
          },
          {
            "value": "3",
            "label": "视频版",
            "disabled": false,
            "extend": [
              {
                "type": "input",
                "title": "视频名称",
                "field": "spname",
                "value": null,
                "actionurl": null,
                "props": {
                  "data": null,
                  "placeholder": "请输入视频名称，最多20字"
                },
                "validate": [
                  {
                    "required": true,
                    "message": "请输入是视频",
                    "trigger": "blur",
                    "type": null,
                    "min": null
                  }
                ],
                "options": null,
                "slot": null,
                "col": null,
                "template": null,
                "vm": null
              }
            ]
          },
          {
            "value": "5",
            "label": "列表跳转",
            "disabled": false,
            "extend": [
              {
                "type": 'template',
                "title": '视频传送',
                "field": 'test111',
                "props":{},
                "template": '<input type="text" ></input>'
              }
            ]
          }
        ],
        "slot": null,
        "col": null,
        "template": null,
        "vm": null
      }
    ];

**Comment by xaboy** [comment]
我这边测试没问题

**Comment by guojs** [comment]
测试代码有发你邮箱，大佬能帮我看下么，谢谢！

**Comment by xaboy** [comment]
我刚刚看了一下好像是 bug,隐藏自定义组件的时候报的错

**Comment by guojs** [comment]
啥时候会修复了

**Comment by xaboy** [comment]
最近会发布一个版本

**Comment by xaboy** [comment]
@guojs `1.6.6`版本已修复
