### ISSUE TITLE
挂在在vue全局下的组件数据怎么处理

### ISSUE THREAD

**Issue by byte9527** [xaboy/form-create#87]
##  问题描述
我使用了一个vue全局下的组件，然后从formCreate里面的trueData来看，对于没有在componentList里面的组件，trueData是不会加入相应的field的，这样就没办法获取这种自定义组件的value，这个问题怎么解

**Comment by xaboy** [comment]
在规则里面增加`field`配置项即可

**Comment by byte9527** [comment]
规则里面已经加了field，从实际的效果来看是不行的。不知道是我哪里漏掉了什么，有没有demo看看。
`export function getComponent(vm, rule, createOptions) {
  const componentList = drive.componentList;
  const name = toString(rule.type).toLowerCase();
  const component = isComponent(name) ? componentList[name] : getUdfComponent();

  return new component.handler(
    vm,
    rule,
    component.render,
    createOptions,
    component.noValue
  );
}

export function isComponent(type) {
  return drive.componentList[type] !== undefined;
}

export function getUdfComponent() {
  return {
    handler: Handler,
    render: Render,
    noValue: true
  };
}`
这段代码好像是对于没有在componentList里面的组件的值有影响

**Comment by xaboy** [comment]
可以参考这里[http://form-create.com/guide/custom-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E4%BA%8B%E4%BB%B6](http://form-create.com/guide/custom-component.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E4%BA%8B%E4%BB%B6)

2.0这块应该会重构,不用现在这么麻烦

**Comment by byte9527** [comment]
期待大牛的2.0，这种自定义组件用起来确实麻烦，校验起来也有问题。

**Comment by xaboy** [comment]
iview 版这周末应该就发布了.
**2.0自定义组件只要定义好`value`属性和` input`事件就能和现在的内置组件效果一样.而且默认支持验证**

**Comment by byte9527** [comment]
2.0的版本希望也能支持除了提交和重置之外的按钮，提交按钮的宽度似乎有些问题

**Comment by xaboy** [comment]
有什么问题? 可以通过自定义组件生成按钮

**Comment by byte9527** [comment]
宽度的问题，在element/form.js下有这段代码，如果自定义了submitBtn的宽度了，会不起作用
![image](https://user-images.githubusercontent.com/30108509/58926757-dc1c9300-877e-11e9-908c-e4553c00af87.png)

按钮是希望和submitBtn在同一行的按钮，比如在某些业务里面，表单有提交、撤回、重置、取消等多个按钮

**Comment by byte9527** [comment]
目前版本自定义组件的校验该怎么做

**Comment by byte9527** [comment]
> 目前版本自定义组件的校验该怎么做

看到其他的issue了，目前不支持。element的form的校验，form的model里面没有自定义组件的value

**Comment by xaboy** [comment]
1.x 目前不支持
2.0版本自定义组件验证方式和内置组件相同
