### ISSUE TITLE
表单验证函数$f.validate验证条件好像只是对初始表单数据验证？

### ISSUE THREAD

**Issue by tiger54910** [xaboy/form-create#93]
而使用表单提供的submit对表单验证是正确的，想要隐藏表单提交按钮，使用自定义的表单提交，validate似乎只对表单创建的初始数据状态有效，如果初始表单数据通过验证，即使对字段数据修改了，验证还是按照初始数据验证似的。

**Comment by xaboy** [comment]
我这边测试没有这个问题, 可以发下复现的代码吗?

**Comment by tiger54910** [comment]
save: function(){
                var $f = vm.fApi;
                $f.validate(()=>{
                    console.log('validate success')
                },()=>{
                    console.log('validate fail')
                })
            },

**Comment by xaboy** [comment]
我这边测试没有问题,复现不了..

**Comment by tiger54910** [comment]
发现是formdata数据没有更新的原因，直接调用$f.submit也是一样，验证的formdata还是初始的值，而不是从界面上已经填写的值。但是用提供的提交按钮获取的是与界面同步的数据，很奇怪。

**Comment by xaboy** [comment]
你用的是哪个版本?什么环境?

**Comment by tiger54910** [comment]
1.x版本，我找到问题了，是我代码的问题，谢谢你
