### ISSUE TITLE
是否可以支持嵌套表单？

### ISSUE THREAD

**Issue by mengpro** [xaboy/form-create#94]
2.0

iview

3.4

**Comment by xaboy** [comment]
支持的,可以通过自定义组件实现.

**Comment by mengpro** [comment]
> 支持的,可以通过自定义组件实现.

谢谢。我今天在实现嵌套表单时遇到field不能重复的问题。数据结构如下：
list: [
  { count: 1, text: 'aaa' },
  { count: 2, text: 'bbb' }
]
在生成嵌套表单的第二组时，错误信息为count字段已存在和text字段已存在，请问如何解决？

**Comment by xaboy** [comment]
字段不能重复是必须的,这个变不了.你可以生成两个表单,或者在 form-create 里面再嵌套一个 form-create
