### ISSUE TITLE
safari  TypeError: undefined is not an object (evaluating 'string.replace')

### ISSUE THREAD

**Issue by jy1989** [xaboy/form-create#95]
version  1.6.5

ui框架  element-ui 

在safari下，给date控件set一个格式为"yyyy-MM-dd HH:mm:ss"的日期会导致日期控件无法选择日期。

chrome下一切正常。

例：
```js
this.fApi.setValue({
            deliveryDate: '2019-12-12 00:12:12'})
```

```js
maker
          .date("交货日期", "deliveryDate", new Date())
          .props({
            type: "date",
            placeholder: "请选择交货日期"
          })
          .col({
            span: 12
          }),

```

![image](https://user-images.githubusercontent.com/1291756/60232371-03263a80-98cf-11e9-9a3f-01a81e24b608.png)

**Comment by xaboy** [comment]
感觉你的反馈.我刚刚检查了下是兼容性的问题,下个版本会修复

**Comment by xaboy** [comment]
我刚刚测试了一下,发现是 elementUI 没有显示,`setValue('2019-12-12')`就可以正常显示

**Comment by jy1989** [comment]
@xaboy  是的， 但在chrome上两种格式setvalue也是没问题的

**Comment by xaboy** [comment]
@jy1989  这个我这边处理不了,只能自己处理或者等 elementUI 更新
