### ISSUE TITLE
2.0版本，npm run dev:ele出错，找不到@form-create模块？是哪里设置不对吗？

### ISSUE THREAD

**Issue by tiger54910** [xaboy/form-create#96]

**Comment by xaboy** [comment]
直接从 github 上clone 的报错? 有没有执行 npm install

**Comment by tiger54910** [comment]
直接clone，执行了npm install，还是报错。
![image](https://user-images.githubusercontent.com/14190457/60377384-06453600-9a49-11e9-916e-5d831278939c.png)

**Comment by tiger54910** [comment]
npm版本用的是5.5.1

**Comment by xaboy** [comment]
`npm install`之后,需要执行一下
`npm install -g lerna`
`lerna bootstrap`

**Comment by tiger54910** [comment]
谢谢你，按照您说的运行成功了
