### ISSUE TITLE
希望值和form，可以分开。因为希望可以从服务器请求动态生成

### ISSUE THREAD

**Issue by longa30** [xaboy/form-create#97]
希望值和form，可以分开。因为希望可以从服务器请求动态生成

**Comment by xaboy** [comment]
明看明白...你可以生成的时候让 `value:''`,等表单生成后通过`$f` 修改表单的值

**Comment by longa30** [comment]
表单的value 和from的json是分开请求的。生成from的json只须请求一次。而value会因为表格点击不同的行，值不一样。

**Comment by longa30** [comment]
谢谢。
