### ISSUE TITLE
文本框 的 placeholder  无效

### ISSUE THREAD

**Issue by seekwe** [xaboy/form-create#98]
最新

element-ui

最新

设置了 placeholder  但是无效

![666](https://user-images.githubusercontent.com/5528581/60334448-1d930d80-99ce-11e9-820f-1d3ea0d0c4b3.png)

(配置直接复制 https://github.com/xaboy/form-create/blob/eda6b3042e98c40852eb26e88c895b358bc97257/packages/element-ui/demo/json.js )

代码示例: https://code.73zls.com/gist/e1195ba5ea1650860d7932f3519f8ab8

**Comment by xaboy** [comment]
这个是 bug,下个版本修复

**Comment by xaboy** [comment]
0.0.4版本已修复
